meteor/meteor

- tools/commands-packages-query.js
- tools/tests/package-tests.js
- tools/tests/packages/package-for-show/package-with-implies.js
In 'meteor show', display the list of packages implied by a package/version.
Implied exports are part of the package's exports, especially for an umbrealla
package like 'meteor-platform' or 'cfs:standard-packages'. However, we can't
tell you the exact exports (ex: "Mongo") without running the constraint solver
(because we don't know what version of the implied package you will end up with).
Showing implies also makes umbrella packages like 'meteor-platform' and
'cfs:standard-packages' more obvious -- the user can tell what is going on with the
package much better.
> show implied packages

- tools/console.js
This explains how to use the Console printing functions. It also moves
some of the documentation around to more public functions where it will be
easier for users to find. (ex: moves Console.options documentation
to Console.options, rather than the internal Console.wrapText)
> more, cleaner comments in Console.js

- packages/templating/templating.js
Instead of a collection of top-level views, which it was before
Basically, now Template.body has a single render function that is composed out of all of the <body> tags.
> Make Template.body be a normal template

- packages/blaze/builtins.js
- packages/blaze/materializer.js
- packages/blaze/view.js
- packages/spacebars-compiler/codegen.js
- packages/tracker/tracker.js
WIP.
- Expose references to computations in Tracker.
- Introduce a package called `tracker-profiler` that counts recomputations of every computation.
- Give Blaze autoruns descriptive names in the [`displayName`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName) field.
- Spacebars generator should give more descriptive names to the views generated for helpers and other symbols (or identifier paths).
@avital
> Tracker profiler package

- packages/observe-sequence/observe_sequence.js
- packages/observe-sequence/observe_sequence_tests.js
We had a bug in `observe-sequence`, a translation layer between the array diff and the DOM operations.
Can someone from the Blaze team review it for me? @avital @stubailo @dgreensp
> Fix the broken logic of moving elements forward in a sequence (Blaze)

- docs/client/search.js
- examples/localmarket/client/templates/app-body.js
- examples/localmarket/lib/bookmarks.js
- examples/unfinished/coffeeless/model.coffee
- packages/autoupdate/autoupdate_cordova.js
Addresses issue #3906 and swaps 
```new Meteor.Collection``` 
to 
```new Mongo.Collection```
where found in project.
> Issue #3906 fix

- docs/client/api-box.js
- docs/client/data.js
- docs/client/names.json
- packages/blaze/template.js
- packages/minimongo/minimongo.js
- packages/tracker/tracker.js
- scripts/admin/jsdoc/docdata-jsdoc-template/publish.js
This PR makes it possible to use JSDoc's `@callback` directives to declare a specific type of callbacks with specific arguments types.
So far, we still hide the extra arguments in the docs app, but it should be easier to implement with this PR.
(+ it contains some improvements to internal docs)
cc @stubailo
> Better documentation for callbacks taking arguments

- packages/package-version-parser/package-version-parser-tests.js
- packages/package-version-parser/package-version-parser.js
- tools/commands.js
Instead of in the general package version parser
> Validate number of colons in package name on create

- scripts/admin/copy-bootstrap-tarballs-from-jenkins.sh
- scripts/admin/copy-dev-bundle-from-jenkins.sh
- scripts/admin/copy-windows-installer-from-jenkins.sh
Port from s3cfg to awscli.
This serves 3 purposes
1) aws cli can do a lot more things, so this is fewer tools we have to use
2) this uses the same key format as we're already using for everything else
3) because of key format, we can easily switch to everyone using their own keys
Note that after this is committed you will have to set up aws cli to use this script.
See: https://mdg.hackpad.com/Operational-Suggestions-and-tips-EZFrKK81iHf#:h=AWS-management
> Mbrewer dev bundle

- packages/html-tools/parse.js
- packages/html-tools/parse_tests.js
Fix/Workaround for issue:
https://github.com/meteor/meteor/issues/3797
It will still not be able to parse end script tags inside quoted strings, but at least it will work in most scenarios
> Issue 3797 fix

- docs/client/docs.less
enable momentum scrolling on the documentation page for iOS devices
> Add momentum scrolling to documentation

- docs/client/api-box.js
- docs/client/data.js
- packages/blaze/template.js
- packages/blaze/view.js
- packages/spacebars-tests/template_tests.js
Add a `connection` options to `template.subscribe`, based on @jamgold's pull request.
> Template subs connection

- packages/blaze-tools/token_tests.js
- packages/blaze-tools/tokens.js
- packages/blaze/builtins.js
- packages/blaze/lookup.js
- packages/blaze/view.js
- packages/spacebars-compiler/codegen.js
- packages/spacebars-tests/template_tests.html
- packages/spacebars-tests/template_tests.js
- packages/spacebars/README.md
```handlebars
<ul>
{{#each person in people}}
<li>{{person.name}} from {{people.groupName}}</li>
{{/each}}
</ul>
```
```handlebars
{{#each people}}
{{@index}}
{{/each}}
```
```handlebars
{{#let x=y.z f=w.s}}
{{x}} {{f}} {{w}}
{{/let}}
```
> Implement #each .. in ..

- packages/spacebars-compiler/codegen.js
- packages/spacebars-compiler/compiler_output_tests.coffee
- packages/spacebars-compiler/spacebars_tests.js
- packages/spacebars-compiler/templatetag.js
- packages/spacebars-tests/template_tests.html
- packages/spacebars-tests/template_tests.js
```handlebars
<div> {{add (add 1 2) 3}} </div>
```
Implements nested expressions in Spacebars tags.
cc: @stubailo @avital @dgreensp
> Spacebars nested exprs

- tools/package-source.js
We should be doing a lexicographical comparison of path components, rather than including the `/` characters in the comparison, to match the order given by the Unix `find` or `ls` commands.
Fixes #4300.
> Split on path separator before comparing files alphabetically.

- packages/minimongo/minimongo_tests.js
- packages/minimongo/modify.js
Issue meteor/meteor#4158.
Adds the `$position` modifier to `$push` in minimongo. Also adds tests.
Behavior of `$push` with multiple modifiers is documented [here](http://docs.mongodb.org/manual/reference/operator/update/push/#modifiers) as
> 1. Update array to add elements in the correct position.
> 2. Apply sort, if specified.
> 3. Slice the array, if specified.
> 4. Store the array.
**Details:**
As described in the last paragraph [here](http://docs.mongodb.org/manual/reference/operator/update/position/#up._S_position), if value of `$position` exceeds the size of the array to be modified, then the operation is the same as not using the `$position` at all.
The minimongo code I added still runs through the [`$position` code path](https://github.com/meteor/meteor/blob/d383e479b3ea5354583e7c1 …
> add modifier $position to $push in minimongo

- examples/todos/client/head.html
Todos is spelled wrong in one of the meta tags. 
It doesn't make a meaningful difference but I thought I'd make the change just in case anyone hosts this.
> Fix typo in todos example

- scripts/dev-bundle-tool-package.js
- scripts/generate-dev-bundle.ps1
- scripts/generate-dev-bundle.sh
- tools/files.js
Only uses npm 3 for generating the bundles, we'll keep using npm 1.x for everything else for now.
> Upgrades generate_dev_bundle scripts on both Unix and Windows to use npm 3

- packages/blaze/lookup.js
See discussion in slack #blaze channel: this change makes sure `@index` is only accessible within the `{{#each}}` block, but not from a template nested inside the `{{#each}}` block.
> fix @index lexical scoping

- packages/mongo/collection.js
- packages/mongo/mongo_livedata_tests.js
An array is not a valid selector in Mongo, so we should fail fast in that case. Also, before this fix, if you passed an empty array as a selector, it would select everything just like `{}`.
> Fix #4804 and throw error when Mongo selector is array

- packages/ddp-client/livedata_connection.js
Hey @glasser, can you give this a look? It seems like a brittle solution but I don't know of another way to pass the error object because e.stack is lost once we leave the exception. Then, in debug.js, we use `arguments` and so I did some hairy stuff to get it to still be of the form that it was before. I don't know if it's necessary to do console.log.apply instead of just doing a console.log (do we do this so that it applies all indices of the arguments object) and in that case I can change it to console.log in my check case.
I ran all of test-packages, and it passes fine (unlike the earlier solution that broke bindEnvironment tests).
I think this is important because it doesn't currently print the stack and I spent a lot of time identifying where I didn't have something defined since …
> Improving error code output in tool code.

- packages/mongo/mongo_driver.js
Based on the log message in e38cefbc0466167e4bf5a19010f8ba1a1e4aca62 the original intent of passing `{safe:true}` in the `_ensureIndex()` options was to emulate MongoDB's [`createIndex()`](http://docs.mongodb.org/manual/reference/method/db.collection.createIndex/) (neé [`ensureIndex()`](http://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/)) setting `{unique:true}`. Unfortunately, `{safe:true}` does not throw an error if duplicate data is found. That's what `{unique:true}` is for. `{safe:true}` simply adds the key `safe` with the value `true` to the index document.
Here's an illustration. Create a new collection:
mongo> db.people.drop()
mongo> db.people.insert({name:'Samus'})
mongo> db.people.insert({name:'Samus'})
mongo> db.people.find()
{"_id": …
> don't add {safe:true} to MongoDB indexes

- packages/ddp-client/livedata_connection.js
- packages/ddp-client/livedata_connection_tests.js
- packages/mongo/collection.js
User could enter irrecoverable broken state after doing any action while
reconnecting (specifically between stream reset and quiescence).
In this state some or all documents in collections would be missing,
because the loop processing buffered messages is interrupted with an
exception in _process_added.
This commonly happened on slow/bad networks, such as mobile.
> Fix method calls during reconnect

- tools/cli/commands.js
- tools/isobuild/bundler.js
- tools/isobuild/compiler-plugin.js
- tools/isobuild/compiler.js
- tools/isobuild/isopack.js
- tools/meteor-services/deploy.js
If $METEOR_BINARY_DEP_WORKAROUND is set, then when bundling for a
non-host platform (build/bundle/deploy commands only), if a package has
no server unibuild for the target architecture, use the host
architecture and replace the npm modules with a package.json and
npm-shrinkwrap.json.  Also write out a top-level setup.sh script (inside
programs/server) which runs npm install in all such directories.
To support this, we make sure to save the package.json and
npm-shrinkwrap.json files in various intermediate directories in case we
need them later.  (We put them inside node_modules because that is what
gets copied from source tree to isopack.)
> One way of cross-compiling local binary packages

- History.md
- packages/ddp-common/random_stream.js
- packages/mongo/collection.js
- packages/random/package.js
- packages/random/random.js
This change harmonizes server document ID generation regardless of whether
it happens inside of a method or not, by using Alea in both cases.
This cuts time of inserting small documents outside of methods
on the server by over 30%, and more importantly makes it easier to be
confident in benchmarking numbers.
---
BACKGROUND
When calling `coll.insert()` on the server within methods, we use the Alea PRNG
(which is fast, can be seeded, and not cryptographically secure) to generate
the `_id` field for the newly created document (unless an `_id` field was
explicitly passed).
The reason we use Alea is so that we can seed the PRNG from the client, as to
ensure consistently chosen IDs for methods that create multiple documents and
run on both client and server.
Prior to this change, when calling …
> Use fast PRNG to generate `_id` for documents created outside methods

- packages/minimongo/minimongo_tests.js
- packages/minimongo/modify.js
Originally created because of [angular-meteor issue #689](https://github.com/Urigo/angular-meteor/issues/689). From now on the $pull modifier would except null values.
> (minimongo) Fix pull modifier not excepting null values

- tools/isobuild/package-source.js
The link to the github documentation on Meteor's cordova integration pointed to an outdated page that redirects to the new page, which means the anchor link was totally broken.
In addition, the example using a github tarball URL used the short form of the sha, which Meteor doesn't accept -- trying to use that example would throw `must declare exact version of dependency: org.apache.cordova.camera@https://github.com/apache/cordova-plugin-camera/tarball/d84b875c`
> Fix documentation for Cordova.depends

- packages/mongo/allow_tests.js
- packages/mongo/collection.js
This minor change will help prevent potential security issues.
Currently, the following snippet gets silently ignored:
```js
Articles.allow({
insert: false
});
```
Instead, the above snippet should throw an error.
The code currently does check truthy values, but doesn't check falsey values. Instead, it should check all defined values. This pull request fixes the check for truthy values with defined values.
I decided to use `Object#hasOwnProperty` instead of e.g. `options[name] !== undefined` because in some situation `undefined` might also be passed to one of the keys.
This issue came to light after a team member wrote the following piece of code:
```js
var isAdmin = function() {
return Roles.userIsInRole(Meteor.userId(), ['admin']);
};
Articles.deny({
insert: !isAdmin
});
```
Luckily …
> Falsey in Collection#deny and Collection#allow

- packages/spiderable/spiderable_server.js
According to Facebook
(https://developers.facebook.com/docs/sharing/webmasters/crawler), they
have a new (May 2014) crawler named Facebot. Spiderable doesn't
currently work for Facebot. It ought to.  
PS. I shed a tear along with @stuabilo that this is even a thing.
> Adding new Facebook user-agent to spiderable

- packages/check/match.js
- packages/check/match_test.js
Currently, when `value` is null, the error message is (for example) `Expected string, got object`. This changes the error message to `Expected string, got null`, which aids debugging.
> Improve error message when value is null.

- docs/canonically_diff_docs.sh
- examples/unfinished/benchmark/run-local.sh
- examples/unfinished/chat-benchmark/run-local.sh
- meteor
- packages/spiderable/spiderable_server.js
- packages/test-in-console/run.sh
- scripts/admin/copy-bootstrap-tarballs-from-jenkins.sh
- scripts/admin/copy-dev-bundle-from-jenkins.sh
- scripts/admin/copy-windows-installer-from-jenkins.sh
- scripts/admin/eslint/eslint.sh
- scripts/admin/find-author-github.sh
- scripts/admin/find-new-npm-versions.sh
- scripts/admin/install-from-bootstrap.sh
- scripts/admin/jsdoc/jsdoc.sh
- scripts/admin/launch-meteor
- scripts/admin/publish-meteor-tool-on-all-platforms.sh
- scripts/admin/publish-meteor-tool-on-arch.sh
- scripts/generate-dev-bundle.sh
- scripts/node.sh
- tools/isobuild/bundler.js
- tools/runners/run-velocity.js
- tools/tests/fake-mongod/fake-mongod
- tools/tests/old/cli-test.sh
- tools/tool-testing/selftest.js
To make the scripts more compatible on different linux environments, shebang should be changed in general to `#!/usr/bin/env bash` instead `#!/bin/bash`
> Make Script More Portable With #!/usr/bin/env

- packages/blaze/template.js
Reproduction: https://github.com/dburles/undefined-object-bug
This patch fixes an issue related to the `lastParamOptionsPattern` which is used to check for an options object, however it also matches on empty objects. See https://github.com/meteor/meteor/blob/devel/packages/blaze/template.js#L367
```js
if (Meteor.isClient) {
// Server logs 'undefined'
Template.body.onCreated(function() {
this.subscribe('test', {});
});
// Works as expected, server logs an empty object {}
// Meteor.subscribe('test', {});
}
if (Meteor.isServer) {
Meteor.publish('test', function(options) {
console.log(options);
});
}
```
> Fix issue with template subscribe

- packages/check/match.js
Hi @stubailo I found the problem on `check` package related to issue:  https://github.com/meteor/meteor/issues/5630
Please review this PR it
> fix Match.Where function called twice bug

- tools/shell-client.js
- tools/static-assets/server/shell-server.js
These changes make it possible to use `meteor shell` for single-command evaluation, with only the command output echoing to `stdout`. Errors are printed to `stderr`, and the `meteor shell` process returns a non-zero error code.
Example:
```js
> meteor create asdf
> cd asdf
> meteor &
> echo Meteor.isServer | meteor shell
true
```
cc @avital @glasser
> Allow piping commands to `meteor shell` via STDIN

- packages/ddp-client/livedata_connection.js
- This is to avoid any confusion of passing in any argument when it is checking for an EJSONable value
- Fixes #5657
> Fix docs to reflect EJSON format instead of Any

- packages/mongo/polling_observe_driver.js
Allow users to change polling default interval per cursor, Important when using polling instead of oplog.
For example: Collection.find({}, {_disableOplog:true, _pollingInterval:4000}) so the pooling will happen at least once in  4 sec.
> Polling observer driver - Allow to customize polling Interval

- docs/client/data.js
- packages/allow-deny/allow-deny-tests.js
- packages/allow-deny/allow-deny.js
- packages/allow-deny/package.js
- packages/mongo/collection.js
- packages/mongo/mongo_livedata_tests.js
- packages/mongo/package.js
As a first start to making it possible to use collections without allow/deny, I'm working on splitting out the code. This is a first step to solving #5096, and in general will be good for reducing the size of the `mongo` package. Consider that all of the code I'm moving was in _one file_, called `collection.js`.
In order to enable this, I needed to refactor `insert`/`update`/`remove` so that I could actually understand the control flow of those functions, which I think is a benefit in itself.
This should result in zero user-facing changes; the next PR will have some of the changes related to making it possible to not use allow/deny at all, or enable it per-collection.
@avital to review.
> WIP: Move allow/deny entirely into a separate package and refactor insert/update/remove

- tools/cli/commands-packages.js
- tools/isobuild/meteor-npm.js
- tools/isobuild/package-source.js
- tools/tests/cordova-plugins.js
- tools/utils/utils.js
See for instance #844 for people running into the
fact that our lack of support for git protocols means
dealing with private npm packages is a pain.
> Allow the other types of URLs that npm supports.

- packages/webapp/webapp_server.js
Otherwise it is stored into the `staticFiles` as `manifest.json` (instead of `/manifest.json`) which is then never matched.
> Serve manifest.json file correctly for the main architecture

- packages/tinytest/README.md
@tmeasday : PR as requested. Note I have retained the guide style (it's nice and friendly), but removed references that suggest this is a part of the guide.
Also, I've removed the "how do I test ..." sections. I no longer think they are appropriate in the context of a README, and especially as the official guide position will not be recommending Tinytest. There are resources around which go into this in some detail and links to those should probably be added.
I've added a reference to smithy:describe as you asked.
> Tinytest README - first draft

- packages/oauth/end_of_popup_response.html
- packages/oauth/end_of_popup_response.js
- packages/oauth/end_of_redirect_response.html
- packages/oauth/end_of_redirect_response.js
- packages/oauth/package.js
When `browser-policy` [1] is loaded _before_ the `oauth` package, the popup & redirect pages would fail due to policy violations. ([1] - With inline scripts disabled.)
However, when `browser-policy` loads after `oauth`, the header isn't injected when requesting the `/_oauth/xx` route, and they work fine.
It might be worth updating `browser-policy` to inject the header before all other handlers.
---
As for this PR - I wasn't sure whether to conditionally put the script into separate files, akin to `meteor_runtime_config.js`.
However, this is the simpilest solution considering the scripts are not dynamic.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/meteor/pull/5628%23issuecomment-157544127%22%2C%20%22https%3A//github.com/meteor/meteor …
> OAuth - remove inline javascript from popup/redirect logins

- tools/cli/commands.js
- tools/cli/main.js
- tools/console/console.js
- tools/fs/files.js
- tools/isobuild/bundler.js
- tools/isobuild/meteor-npm.js
- tools/meteor-services/auth.js
- tools/meteor-services/service-connection.js
- tools/packaging/catalog/catalog-remote.js
- tools/packaging/package-client.js
- tools/packaging/warehouse.js
- tools/runners/run-all.js
- tools/runners/run-app.js
- tools/runners/run-mongo.js
- tools/runners/run-proxy.js
- tools/runners/run-selenium.js
- tools/runners/run-updater.js
- tools/tool-testing/selftest.js
- tools/utils/buildmessage.js
- tools/utils/fiber-helpers.js
- tools/utils/func-utils.js
- tools/utils/http-helpers.js
- tools/utils/utils.js
This branch has been sitting around since May 2015. After rebasing it against https://github.com/meteor/meteor/pull/4619, I decided I'd rather not rebase it again if I can help it.
Note that many of these commits use `Promise.prototype.await` to yield the current `Fiber` until the `Promise` is resolved, which (like `Future.prototype.wait`) allows the code creating the `Promise` to avoid returning the `Promise` to the caller. This works great in an environment with `Fiber`s, but it might be better, if this code was being written from scratch, to stick to `Promise.prototype.then` or `async` functions and `await` expressions, so that the calling code can decide how to orchestrate the asynchronous operations.
> Replace all uses of Future in tools/ code with equivalent Promise-based code

- docs/client/full-api/commandline.html
- docs/client/full-api/tableOfContents.js
Here is my first (small) contribution to Meteor. Tell me if it's ok. I just cloned the devel branch, and copied the output from "meteor help shell" in the docs application. I also added it to the table of contents and a link appears in the left part of the application.
> Fix #5416 Include `meteor shell` reference in docs

- tools/isobuild/compiler.js
Helps to profile apps, like wekan.
https://github.com/meteor/meteor/issues/5269
> Add profiling information to clearly outline slow legacy-style compilers

- packages/webapp/webapp_server.js
This change will allow routers and other middleware to set the HTTP status code to something other than 200, for example returning a 404 if the route does not exist on the client or server. It retains the default 200 response if `res.statusCode` has not been set.
My first PR here, couldn't see an obvious way to add tests for this functionality as it's inside an anonymous function but happy to be enlightened.
In the case of Iron Router, there is already some commented-out code that this will allow to work as long as routes are defined on client & server (https://github.com/iron-meteor/iron-router/blob/devel/lib/router_server.js#L80-L89). There may be other SEO considerations (for the JS-rendering search engines) - if I click a client-side route from a 404 (where Iron Router NotFound …
> Allow middleware to set http status code (fixes #5820)

- tools/cordova/project.js
While processing a clean build (ie: meteor reset) this error occurs, because the platform directory exists but it empty.  The order should be reversed, per documentation: https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration#advanced-build-customization 
Others have issues too: https://github.com/meteor/meteor/issues/5373
Create a cordova-build-override/platforms/android/build-extras.gradle
Then run:
$ meteor reset
$ meteor build <dir> --server <server> --verbose
....
Processing mobile-config.js
Writing new config.xml
Creating Cordova project
% Creating a new cordova project.
Preparing Cordova project from app bundle
Processing mobile-config.js
Copying resources for mobile apps
Writing new config.xml
Copying over the cordova-build-override directory
Adding platform iOS to …
> Override should come after Platform Synchronize

- packages/reload/reload.js
- packages/webapp/.npm/package/npm-shrinkwrap.json
- packages/webapp/package.js
- packages/webapp/webapp_server.js
This is a more comprehensive version of https://github.com/meteor/meteor/pull/5900.
As discussed on that PR, using `location.replace()` instead of `location.reload()` can significantly improve reloading performance because it avoids unnecessary cache validations.
One problem noted there is that we currently serve non-cacheable assets with a `max-age` of a day, which means that changes to assets (such as an image in `/public`) would not be detected if we switch to `location.replace()`. 
Setting the `max-age` to this value was supposedly done to avoid image flickering during reloads (see #773). I'm not sure about the original reasoning, but thinking about it some more I don't see how this would help. With `location.reload()`, the browser basically ignores `max-age` anyway and it therefore …
> Webapp caching improvements

- tools/isobuild/compiler-plugin.js
Otherwise it is really hard to know where the errors are coming from. Now the error is like:
```
While processing files with peerlibrary:blaze-components (for target os.osx.x86_64):
/tools/isobuild/compiler-plugin.js:432:13: Document sections can only be emitted to web targets: test-templating.html
```
> Better error messages

- docs/client/full-api/commandline.html
- docs/client/full-api/tableOfContents.js
I recently came across the issue of how to handle Galaxy deployments with third-party continiuous integration providers. Unfortunately I couldn't find any infos in the documentation on how to handle `meteor login` without sharing my main credentials. Luckily I came across [this post](https://medium.com/@natestrauser/migrating-meteor-apps-from-modulus-to-galaxy-with-continuous-deployment-from-codeship-aed2044cabd9#.j4a68a16v) and the usage of `METEOR_SESSION_FILE` to generate a session token. To promote good security practices we should add this to the docs.
> Add meteor login / logout info to docs

- docs/client/full-api/api/passwords.md
Found a spelling mistake -
`responsiblity` > `responsibility`
> Fix typo in docs

- meteor
- packages/logic-solver/logic_tests.js
Note that `export default` no longer modifies `module.exports`, but simply defines `exports.default`, so these two import styles will work:
```js
import DefaultExport from "./export-default-module.js"; // preferred
var DefaultExport = require("./export-default-module.js").default;
```
but this style will no longer work:
```js
var DefaultExport = require("./export-default-module.js");
```
At least some of the test failures will be fixed with this Babel PR is resolved: https://github.com/babel/babel/pull/3310
> Use Babel 6 to implement ECMAScript 2015+ in tool code.

- packages/webapp/webapp_server.js
Otherwise CORS preflight does not work for `manifest.json` file. CORS preflight can happen if you are having some extra headers in your request for `manifest.json` (so if the request is classified as [non-simple](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests)).
> Allow HTTP OPTIONS method to correctly support CORS preflight

- packages/webapp/webapp_server.js
This made URL paths with `\` which then did not correctly resolve. There is no need to be OS specific here, it breaks things.
> Fixed manifest.json path on Windows

- tools/cli/commands-cordova.js
- tools/cordova/index.js
- tools/cordova/project.js
When adding custom platforms it is a bit misleading to name available platforms. But the main issue is that `checkPlatformRequirements` is called for all platforms, despite calling `filterPlatforms` earlier. This fixes it so that only for Cordova platforms check is called.
> Make clear those are Cordova platforms

- docs/client/search.js
Avoid opening search on function (FN) keys press (`String.fromCharCode()` returns letters with them).
> [Docs] Proper detection of key codes for search

- tools/cli/help.txt
This functionality was changed by @multilinear. Change the cli help to match this.
> mongo url is good for an hour now

- History.md
- packages/mongo/collection.js
- packages/mongo/oplog_observe_driver.js
- packages/mongo/polling_observe_driver.js
These can be useful to tune performance for application specific data patterns.
Parameters exposed and documented:
- disableOplog
- pollingInterval
- pollingThrottle
Tested with:
```
m = new Mongo.Collection("foo");
if (Meteor.isServer) {
Meteor.publish("foo", function () { return m.find({_id: '7'}, {disableOplog: true}); });
Facts.setUserIdFilter(function (userId) { return true; });
} else if (Meteor.isClient) {
Meteor.subscribe("foo");
}
```
in a new app with `facts` and not `autopublish`
> Expose options for performance tuning `observe` on the server

- packages/blaze/template.js
Hello guys!
I use Сoffeescript and faced unpleasant trouble recently, when a small bug made me feel nerveous since I couldn't figure out its reason and Meteor didn't suggest anything. 
I wrote a code, where passed function instead of object  Event Map:
```js
Template.myJobsInfo.events ->
'click [data-action="check_status"]': -> console.log 'OK'
```
I did not receive mssage about error, but my code still did not work. As appeared Meteor does not check parameters, which are passed to methods events and helpers.
My minipatch allows to discard this undefined behavior.
> Added check of params for template's methods events and helpers

- packages/ddp-client/livedata_connection.js
When making change into a pull request (#5845) I missed this file change.
This now provides a way to access collections from stores on the client.
> Missed filter to pass _getCollection through

- tools/cli/commands.js
This isn't quite the complete solution we are planning, but it is enough to allow others to test alternate runners. 
I've tested this with https://github.com/tmeasday/meteor-mocha/tree/1.3-reporter, and it works against Todos (you need to `meteor remove avital:mocha; meteor add tmeasday:mocha`)
> Take a test runner as commandline argument

- packages/accounts-password/password_server.js
If a user has email verified and `Accounts.sendVerificationEmail()` is called with that userId - server logs error ` No such email address for user.`.
Whereas it should log `This email is already verified`.
> Accounts.sendVerificationEmail() - incorrect error text

- packages/browser-policy-content/browser-policy-content.js
This PR is for adding methods of the form BrowserPolicy.content.allow<ContentType>BlobUrl() to BrowserPolicy, to support the "blob:" CSP directive.
> Add methods of the form BrowserPolicy.content.allow<ContentType>BlobUrl() to BrowserPolicy

- packages/boilerplate-generator/boilerplate_web.browser.html
- packages/webapp/webapp_server.js
This PR represents the minimum changes to `webapp` that would enable other connect handlers to inject content into the `HEAD` and `BODY` of the boilerplate, effectively enabling packages to implement a loading page or server side rendering. I'm not expecting this PR to be merged as is, rather to form a starting point for a discussion on how we can get something like this into core. Happy to do the work, would just like MDG's guidance and blessing on best to move forward.
A clear example of how this is used is here: https://github.com/percolatestudio/react-leaderboard/blob/master/react-leaderboard.jsx#L162-L168 .
Currently Meteor provides no way for user code to modify the contents of the boilerplate html. This makes it difficult/hacky to serve a loading page or content rendered from the …
> POC for adding hooks to boilerplate generation for loading page and/or SSR

- docs/client/full-api/api/packagejs.md
I wasted ~30 minutes discovering this behavior while trying to test a modification to the TypeScript build plugin, which is registered by the meteortypescript:compiler package but depends on the barbatus:ts-compilers package for the bulk of the implementation (including the code I needed to modify).
Here's a reproduction based on what I was originally trying to do.  It includes a local version of barbatus:ts-compilers that compiles all TypeScript files in "bare" mode, but this local version is only used when meteortypescript:compiler is also local.  I'm using Linux (Fedora 23), but I doubt it matters.
```
$ git clone https://github.com/mattmccutchen/meteor-build-plugin-deps-repro
$ cd meteor-build-plugin-deps-repro
$ meteor
$ grep bare .meteor/local/build/programs/server/app/repro.js
$ ls …
```
> Document how to use local dependencies for build plugins.

- examples/simple-todos-react/.meteor/versions
- examples/simple-todos-react/AccountsUIWrapper.jsx
- examples/simple-todos-react/App.jsx
The current example code for React does not work. There was a change in 5773b7e3b0a that moved to use ReactDOM but the `.meteor/versions` file was not updated.
Besides fixing this, also made changes to remove warnings and removed the use of `findDOMNode` to access the input. This is no longer needed in 0.14, reference: [Starting with this release, this.refs.giraffe is the actual DOM node](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#dom-node-refs).
> Update react example to React 0.14

- packages/boilerplate-generator/boilerplate_web.browser.html
Rather than include our bundle from <head>, include it at the end of <body> . This way, code can make use of the new `dynamicHead` feature to add loading html into the boilerplate. (as requested by #3860)
> Moves <script> tags to end of <body>

- packages/meteor/test_environment.js
***1 Upvote*** @zol do you think this is satisfactory syntax?
A driver package can now define `.runTests()` on the client, which kicks off the test process, and `.start()` on the server which can be used for various purposes as discussed on #6436
> For #6436 -- allow test drivers to `.start()` on the server

- tools/cli/commands.js
@benjamn I just wanted to sanity check this with you, I'm pretty confident it should happen.
I think we hadn't done this for back-compat reasons, however it doesn't make sense as it means that test-drivers and test utilities can't be `testOnly` if they want to be usable for `meteor test-packages`. Which kind of makes it pointless to have `testOnly`.
I don't anticipate it will cause problems, but I'm not entirely sure.
> `buildMode === "test"` for both `test` and `test-packages`

- packages/meteor/test_environment.js
Previously the "No --driver-package specified for `meteor test`" error would never actually show because the logic was wrong. Now it will.
cc @tmeasday
> Fix logic for showing --driver-package error

- History.md
An unescaped `<script>` tag prevented viewing the full History.md file. Added backticks to restore visibility.
Before the fix:
> Escape script tag in History.md

- packages/twitter/twitter_server.js
Overview
---
Meteor can get user email from twitter api, If your app is whitelisted on twitter. So I add `include_email=true` parameter by default for convenience. This change will make twitter api response to return email address if your site is whitelisted otherwise return null.
reference: https://dev.twitter.com/rest/reference/get/account/verify_credentials
> Opt-in user email address request for twitter sign up

- tools/isobuild/import-scanner.js
As discussed in #6489 the build process crashes when a module js file contains BOM mark. This change fixes stripping the BOM in import-scanner.js.
> Fix for stripping BOM in import scanner. Fixes #6489

- tools/isobuild/bundler.js
It seems that `program.json` file in some packages has different `node_modules` format than bundler script expects. One example is `angular-templates`, where you can find:
```
{
"node_modules": "npm/babel-compiler/node_modules",
"sourceMap": "packages/babel-compiler.js.map",
"path": "packages/babel-compiler.js"
},
```
It leads `NodeModulesDirectory.readDirsFromJSON` method to return `undefined` for `packageName`.
This pull requests adds parsing code for this path format so package name is extracted properly.
> Get proper packageName in bundler.js. Fixes #6555

- History.md
Unescaped HTML tags cause rendering errors in History.md when viewed on Github. This patch escapes them all.
> Escape HTML tags in History.md

- packages/blaze/view.js
It's helpful to know that this also destroys the template instance associated with the view being removed. Could possibly be worded better.
> Update Blaze.remove docs.

- docs/client/full-api/api/templates.md
Per my conversation with @stubailo - converted examples to use ES6 conventions.
> Converted example to use ES6 conventions (Method shorthand and arrow functions)

- docs/client/full-api/api/core.md
Hi guys - just a small change; `Meteor.isDevelopment` was missing in the docs. I've added it in below `Meteor.isCordova`. Thanks!
> Added in missing Meteor.isDevelopment.

- docs/client/full-api/packages/modules.md
Link should be to Meteor Guide, not non-existent documenation.
> Fix bad link in modules package documentation

- packages/email/email.js
***1 Upvote*** Fix #4323
Using _.once gives you no option for "clearing the cache" of the ran function.
Using _.memoize, we can pass in the value of process.env.MAIL_URL, so once 
it changes, the function is allowed to be run again, caching the return value
for the current value of process.env.MAIL_URL.
> Remove _.once and add cache to getPool

- scripts/npm.cmd
The current implementation of the npm wrapper on Windows does not work properly if the username contains a whitespace, because your AppData-path will then contain a whitespace.
Steps to reproduce:
1. Create a user account with a whitespace in it's name, such that your user directory path will be something like `C:\Users\John Doe\`
2. If you run, e.g., `meteor npm version` you end up with Windows' command not found error.
The same issue exists for the script path/first parameter. I encountered this when using npm-shrinkwrap: You will not trigger Windows' command not found error but module-not-found errors:
```
error: couldn't install npm packages from npm-shrinkwrap: Command failed:
module.js:340
throw err;
^
Error: Cannot find module 'C:\Users\Daniel'
at Function.Module._resolveFilename …
```
> Fix whitespace and command-output handling of npm.cmd

- packages/check/match.js
- packages/check/match_test.js
`Match.Optional` is still only supposed to "pass" if the value is `null`
or the specified type.  The new `Match.Maybe` allows `undefined` or
`null` in addition to the specified types. `Match.Optional` is on the
track toward deprecation, however to not break existing code it was
*supposed* to stay working the same as before. (per #3876).
There weren't tests in place to make sure that `Match.Optional` kept
working the same, and the code didn't actually make it keep working the
same.  Hopefully extra tests will make this better.
`.Maybe` has some additional bugs, but should be addressed separately
(see #6712)
Fixes #6735
> Fix `Match.Optional` to work as it did previously in Meteor 1.2

- packages/autoupdate/autoupdate_cordova.js
Removed handle.stop() so that live query continues to run after the first code push, and newer versions continue to download.
Important when delaying reload until after a resume, otherwise it takes multiple resumes to get to the latest bundle.
> Remove handle.stop() after update

- docs/source/api/check.md
- docs/source/api/session.md
Same thing I did in fd2bc2a8b31bb35ca65cf946e8f1d9171cd8d2f2 except for the (previously unware-of) hexo docs.
Fixes #6932
> [docs-hexo] Clarify that "session" and "check" must be installed

- tools/README.md
- tools/tool-testing/selftest.js
This pull request fixes the issue #5776.
I did not write tests for the pull request but if the MDG considers they are needed for this modifications, I will work on them.
> Fixes #5776: Test app debugger listens TOOL_NODE_FLAGS debug port + 1

- tools/cli/commands.js
- tools/tests/run.js
The `test` mode wasn't passing the proper proxyHost and proxyPort values to runAll.  This changes the behaviour to work the same as the regular `run` mode and also adds tests for both modes to test the bindaddr (localAddress) is taking effect properly.
Fixes #6961
> Allow --port in "test" to support a bindaddr, same as non-test

- History.md
I think it is somehow important to convey that batching until 500 ms happens only if changes are coming under 5 ms in. If they are not, they things get flushed.
> Slight improvements

- packages/jquery/README.md
Documentation fix to remove references to jquery-history and jquery-layout packages, which Meteor no longer provides.
> Meteor no longer provides jquery history or layout

- packages/standard-minifier-js/plugin/minify-js.js
#5378 Old PR
#5363 Issue
Resubmitted but I'm not ready with writing tests. Personally think that shouldn't have any problems. Pinging the member dealing with the old PR @stubailo
> Don't reminify *.min.js

- scripts/ci.sh
- tools/cli/commands.js
- tools/console/console.js
I've already increased the number of containers from 4 back to 8, but the `scripts/ci.sh` script needs to be updated to take advantage of the new resources.
Submitting this as a pull request not only because we just turned on branch protection for `devel` but also because it seems like a good idea to re-run the test suite after making significant changes to the test infrastructure.
cc @tmeasday @zol @stubailo
> Bump Circle CI parallelism to 8x

- packages/facebook/facebook_client.js
Allow using authType in Facebook login (https://developers.facebook.com/docs/facebook-login/reauthentication) :balloon:
> Handle authentication type in Facebook

- packages/google/google_configure.html
The Google API Manager has changed it's interface since this was last updated. I've corrected the instructions with as little change as possible to accurately describe the current workflow.
This issue was reported for another project, here, and I figured this was a simple fix to provide: https://github.com/sandstorm-io/sandstorm/issues/1756
> Update Google Client ID instructions

- packages/tracker/tracker.js
- packages/tracker/tracker_tests.js
For, #4514, this is my first pass at a core package PR, so feedback welcome!
> Implements Tracker.Computation#flush and #run (fixes #4514)

- packages/http/httpcall_tests.js
- packages/http/package.js
Previously 0.0.0.0 was used, but that _can_ refer to the local machine and was causing problems when the test was run on a machine that had something (e.g. Apache, etc.) listening on 0.0.0.0:80.
Fixes #7038
> [tests] Change destination IP for http error test to something more invalid

- circle.yml
- scripts/ci.sh
Trying to see if re-enabling the `--headless` spinner that Ben put in place will work if combined with a longer timeout for CircleCI.
...about to find out.
> Increase circleci timeout and disable spinner for CI tests

- packages/allow-deny/allow-deny.js
- packages/mongo/collection.js
- packages/mongo/collection_tests.js
- No error is thrown when constructing a `Mongo.Collection` twice for the same name
- If mutation methods were already created for a named collection, we skip them and do not throw an error
- `Mongo.Collection` constructor takes a new option, `defineMutationMethods`, which can be set to false to skip creating the default mutation methods
- `_defineMutationMethods` function performance is slightly improved by returning earlier if there is no need to loop through method types
This could obviously have some edge cases effects I'm sure, but I can't think of any and all tests still pass. Maybe something weird would happen if defining it twice with different types of _id?
There is of course the chance that two packages, or a package and app, unknowingly use the same collection name and don't …
> Allow new Mongo.Collection to be called multiple times for the same collection name

- History.md
- tools/packaging/warehouse.js
Discussed about it at #6944. This PR gives you ability to override the default warehouse urlbase (`warehouse.meteor.com`) by setting `METEOR_WAREHOUSE_URLBASE`.
> Ability to override the default warehouse url base

- packages/minimongo/minimongo_tests.js
- packages/minimongo/modify.js
Mongo now allows specifying an `_id` in upserts using the `$setOnInsert` operator, but MiniMongo throws an error. This makes simulations for latency compensation very cumbersome.
However MiniMongo does support setting _id s with `$setOnInsert` as it stands now. Only the exception was thrown incorrectly.
So I have added the tests to the relevant test case and fixed the condition on throwing the exception.
Steps to reproduce: 
```JavaScript
let collection = new LocalCollection;
collection.upsert({foo: 'bar'}, {$setOnInsert: {_id: 'test'}});
```
Expected result:
```JavaScript
isEqual(collection.findOne(), {
_id: 'test',
foo: 'bar'
});
```
Actual result:
> Error: MinimongoError: Mod on _id not allowed [409]
> Minimongo: Allow `_id` in `$setOnInsert`.

- packages/email/email.js
- packages/email/email_tests.js
This will insert a default date header into all emails, if you do not
specify such a header by your self. This way it will work for the emails
send by accounts-password and all emails from user code. So this will
fix #3940.
> Insert default date header into emails

- History.md
The log entry about `Match.*` bugs in 1.3.2 is actually opposite of what was changed.  This clarifies it and adds an entry for the original addition of `Match.Maybe` to the 1.3 log.
This was my mistake for not submitting a `History.md` entry with my fix in #6736 and leaving it (a confusing situation) to be interpreted by the person who wrote the History.  I didn't even notice it was wrong the second time I read it!
Fixes #7083
> Fix incorrect History entry about Match.Maybe and Match.Optional

- History.md
Adds changelog for PR #6964, (`--port IP:ADDR` support on `meteor test`), which is included in 1.3.3.
> Adds changelog for PR #6964

- packages/ddp-server/package.js
This exposes additional headers: https://github.com/sockjs/sockjs-node/blob/master/Changelog
This is useful when working with [Sandstorm](http://sandstorm.io/) which uses some of those headers to convey current host, which can then be used for dynamic `Meteor.absoluteUrl`.
> Bump the sockjs package

- packages/ddp-common/method_invocation.js
Not sure if this is the best language. But I have been bitten too many times with this. Not all server-side called methods have connection null. Only when it is started by the server-side. But if you recurse in one client-side started call into other methods connection stays the same.
> Explain that connection is provided when call recurse into other methods

- packages/email/email.js
When using a password that contains a percent sign, meteor fails to send e-mail, throwing a `URIError: URI malformed`.
Parsing a SMTP URL with encoded auth credentials will get **unencoded** auth.
In the example below, the password is `pass%123`.
If MAIL_URL is set to `smtp://username%40hostname.tld:pass%25123@hostname.tld:25`, the parsed `mailUrl` will be
```
{ protocol: 'smtp:',
slashes: true,
auth: 'username@hostname.tld:pass%123',
host: 'hostname.tld:25',
port: '25',
hostname: 'hostname.tld',
hash: null,
search: null,
query: null,
pathname: null,
path: null,
href: 'smtp://username%40hostname.tld:pass%25123@hostname.tld:25' }
```
which means that `mailUrl.auth` has already been decoded by the parser and must **not** be re-decoded.
> Don't decode username and password from auth

- packages/email/email_tests.js
* Added `smokeEmailTest` function which sets up test stream
* Splits the previously combined tests into multiple tests
* Created test that catches error in PR #6916, caught in #7123
* Confirmed regression without 6e071838af0c9594cdbf9b23ded7ef5806510a86
Per @tmeasday in https://github.com/meteor/meteor/pull/6916#issuecomment-221953805
> Improve Tests for the `email` package

- packages/modules/install-packages.js
- tools/isobuild/compiler-plugin.js
- tools/tests/apps/package-tests/packages/with-add-files/package.js
- tools/tests/apps/package-tests/packages/with-add-files/with-add-files.js
- tools/tests/apps/package-tests/packages/with-main-module/package.js
- tools/tests/apps/package-tests/packages/with-main-module/with-main-module.js
- tools/tests/modules.js
Addresses #6907.
@benjamn, this is what I had in mind and solves the issue for me.  Pending any comments from you I'll play with it for a few more days then add some tests to the PR and rebase.
> Proper import chain for Meteor packages to app

- packages/babel-compiler/babel-compiler.js
Addresses point 1 in https://github.com/meteor/meteor/issues/6351#issuecomment-220944251, cc: @benjamn.
I don't have too much time this weekend but this code has been in my head the whole week and it wants out :D  As usual, completely open to change style / variable names / approach per your guidance, or for you to use just as inspiration if you'd like to go a different route.
Requires my [PRs for meteor/babel](https://github.com/meteor/babel/pulls) (I slipped in the `sourceHash` for the same trouble).  I should probably update my use of `deps` there to `cacheDeps`.  `cacheHashDeps` is even clearer but a little excessive.
Ultimately `Babel.compile(source, babelOptions, cacheDeps)` gets a `cacheDeps` like:
```js
{
'sourceHash': '2c9f7e231af1a62db195875ca62df7edc253c3c4', …
```
> Use babel preset/plugin versions/hash for cache invalidation

- packages/spacebars/README.md
One of several PRs to correct references to the new location of the Spacebars docs.
> Correct Spacebars readme link

- tools/static-assets/skel-pack/~fs-name~-tests.js
The package skeleton test example was importing the module as if it was outside the package.  This changes it to reference the local package source, relative to itself, so that this sequence of commands will work properly:
```
meteor create my-app1
cd my-app1
meteor create --package my-app1:my-package123
meteor add my-app1:my-package123
meteor test-packages my-app1:my-package123
```
Fixes #6653
> Change package creation skeleton to import properly

- packages/reactive-dict/reactive-dict-tests.js
- packages/reactive-dict/reactive-dict.js
Make the behavior of ReactiveDict.setDefault match that of ReactiveDict.set when it comes to the Object argument form.  Copied implementation strategy from set method.  Closes #6992.
> Make setDefault compatible with object type argument

- tools/cli/commands.js
- tools/cordova/builder.js
- tools/runners/run-all.js
- tools/tests/cordova-run.js
- tools/tests/test-modes.js
- tools/tests/utils-tests.js
- tools/utils/utils.js
This is my take on fixing IPv6 handling in meteor.
What's changed:
- Format URLs using url.format instead of string concatenation
- Renamed host to hostname. (host is ip+port and hostname is just ip, seems to be mixed up here)
IPv6 is working perfectly with these changes. However, I still may have missed other parts of the code where URLs are constructed using string concatenation.
Please review this PR and I will fix what is needed.
> IPv6 Support. closes #7155 

- packages/ddp-server/.npm/package/npm-shrinkwrap.json
- packages/mongo/mongo_driver.js
- packages/mongo/mongo_livedata_tests.js
- Add tests for the previous behaviour (returning nMatched)
- I verified they pass on devel too before adding to this branch.
- Fix a bug with upserting when it did not cause any change.
> Mongo 3.2 update/upsert returns nMatched as numberAffected

- packages/random/random.js
Documents functions in the _random_ package with JSDoc so they can be referenced with `apibox` in the docs. Descriptions are taken from the current (badly formatted) docs: https://github.com/meteor/docs/blob/017792770e4354810eef8e9cf2e8b6f089f3747d/source/packages/random.md @guide
PR for the docs: https://github.com/meteor/docs/pull/51
> Add documentation for Random functions

- packages/email/email.js
This backwards compatible patch allows smtps protocol, and secureConnection on port 587.  Port 465 is non-standard and assigned to something else.  See #7042 for details.
> Allow smtps:// in MAIL_URL to enable secureConnection

- packages/reload/package.js
- packages/reload/reload.js
Make sure URLs ending with `#` get properly picked up by `Reload` package and the app refreshes.
Fixes #7239 .
> Reload: detect href ending with `#`.

- packages/facebook/facebook_client.js
Adds truthness check b4 accessing property in facebook package. Fixes #7255:
Trying to login using `facebook@1.2.7` (newest version) in Meteor 1.3.3.1 yields the following type check error:
```
facebook_client.js:40 Uncaught TypeError: Cannot read property 'authType' of null
```
Please do let me know if you need more info to reproduce.
I'm attaching a one-line PR that fixes this.
> Adds truthiness check b4 accessing property in facebook package. Fixes #7255

- tools/utils/http-helpers.js
While debugging #7090 I discovered that there is no timeout specified for many HTTP requests Meteor is making. This means that when packaging server (or CDN) is badly behaving, client is waiting indefinitely instead of throwing an error.
> Set timeout for HTTP requests

- scripts/generate-dev-bundle.sh
With release 1.3.4 there was a new variable `$NPM_VERSION` defined in `build-dev-bundle-common.sh`.
Instead checking the right version inside the `generate-dev-bundle.sh` this var is better to use.
In addition, the message is not correct anymore because no special node is delivered anymore. The npm is not build via PORTABLE=1 in the binaries of nodejs.
In case that the NPM is replaced during the bulid this content should be deleted.
Hope that fits to you
Tom
> Finalize replacement NPM@3 at generate-dev-bundle.sh script

- tools/cli/commands-packages.js
When running meteor from checkout (as we do for the ARM fork) and use `meteor update` or `meteor update --packages-only` you will get following error:
<pre>
packages/promise/.npm/package/node_modules/meteor-promise/promise_server.js:165
throw error;
^
TypeError: Cannot read property 'packages' of null
at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:1721:12)
at /tools/cli/main.js:1402:23
</pre>
```bash
cd /tmp
git clone -b release/METEOR@1.3.4 https://github.com/meteor/meteor.git meteor-checkout
meteor-checkout/meteor create hello-world
cd hello-world
../meteor-checkout/meteor update
```
When running `meteor update` from checkout the var `releaseRecordForConstraints` ist set to `null` in case of `if (!files.inCheckout())` - [see source …
> Minor Bug: Fix error on accessing empty releaseRecordForConstraints var

- packages/twitter/twitter_client.js
Trying to login with Twitter package give an error:
`Uncaught TypeError: Cannot read property 'force_login' of null`
Make the same thing than #7256 but for twitter package.
This issue was introduced by commit https://github.com/meteor/meteor/commit/001a3f3128d1eaebdea431bf35707748b5dc185e
> Check options exist in twitter package

- packages/mongo/connection_options.js
- packages/mongo/mongo_driver.js
- packages/mongo/package.js
For #6958
I noticed the API has changed for a bunch of the existing options used in `mongo_driver.js` such as `{ safe: true }` now replaced by: https://docs.mongodb.com/manual/core/replica-set-write-concern/ but that is a bit out of scope for this PR. Maybe something to be looked at though.
> User defined mongo connection options API for #6958

- packages/autoupdate/autoupdate_client.js
- packages/webapp/webapp_server.js
A fix for #7149 
Previously we did not take the JsCssRewriteHook (i.e. CDN host)
into account when doing CSS-only "version-refreshable" HCP.
It is not possible on the client to rewrite CSS urls to take the
hook into account (as it is a function), so instead, we just
publish those CSS URLs post-transform.
> Publish CSS documents for autoupdate after rewriting for #7149

- tools/project-context.js
Issue #7292 
Use `path.resolve` to resolve the relative path to project. May need to take this down to `History.md`.
> Relative path resolves to project directory when use METEOR_LOCAL_DIR.

- packages/minifier-css/minifier.js
See https://github.com/meteor/meteor/pull/5841 -- I used a version of `path.relative` that should work on all platforms.
> Mquandalle fix path minifiers css

- scripts/admin/launch-meteor
For #7266. This is code copied from install.meteor.com. The script seems to work, as far as I can test it.
> Add retrying to installer

- History.md
- meteor
- packages/accounts-password/package.js
- packages/meteor-tool/package.js
- packages/non-core/npm-bcrypt/.versions
- packages/non-core/npm-bcrypt/package.js
- packages/non-core/npm-node-aes-gcm/.versions
- packages/non-core/npm-node-aes-gcm/package.js
- packages/oauth-encryption/package.js
- scripts/admin/meteor-release-experimental.json
- scripts/admin/meteor-release-official.json
- scripts/build-dev-bundle-common.sh
- scripts/dev-bundle-tool-package.js
- scripts/generate-dev-bundle.ps1
- tools/cli/commands-packages.js
- tools/packaging/updater.js
- tools/project-context.js
- tools/static-assets/skel/.meteor/.gitignore
Unfortunately, the following claim in the [release notes](https://github.com/meteor/meteor/blob/devel/History.md#v1342) for the [1.3.4.2 release](https://github.com/meteor/meteor/pull/7340) was not entirely true:
* The `meteor node` and `meteor npm` commands now respect `.meteor/release` when resolving which versions of `node` and `npm` to invoke. Note that you must `meteor update` to 1.3.4.2 before this logic will take effect, but it will work in all app directories after updating, even those pinned to older versions. [#7338](https://github.com/meteor/meteor/issue/7338)
Specifically, running `meteor update` to update to 1.3.4.2 was not actually enough to modify the `~/.meteor/meteor` symlink (or `AppData\Local\.meteor\meteor.bat` on Windows), which prevented the new behavior of `meteor …
> Release 1.3.4.3

- packages/babel-compiler/babel-compiler.js
Side PR for #7356.
`.min.js`es don't need to be compiled by babel.
> Exclude .min.js from babel compiling.

- packages/promise/.npm/package/npm-shrinkwrap.json
- packages/tracker/tracker.js
Fix for issues https://github.com/meteor/meteor/issues/7326 and https://github.com/meteor/blaze/issues/44
This change in Tracker speeds up the removal of Blaze templates with many sub-templates by approximately 5-10x.
It replaces the `delete` of a stopped computation by setting it to `null`. Read more [here](http://bertanguven.com/preventing-memory-leaks-in-javascript-null-vs-delete)
Reproduction of the issue used as a benchmark (and a test to verify the effect): https://github.com/arggh/blaze-tmpl-destroy/tree/nosubs
Without the fix in Tracker, the first time hiding the table with 550 rows took about **1.5 seconds**. On the second go it took about **2.6 seconds**. Then **3.5 seconds**. Then **~5 seconds** and so on, which is really strange - as if things just got incremented instead of …
> Set stopped computation to null instead of delete (#7326)

- tools/cli/commands.js
- tools/cli/help.txt
Fixes #7396 by adding an option to output directly to stdout, without adding a timestamp or parsing.
> Add --raw-logs option for meteor test

- packages/ddp-server/livedata_server.js
- packages/ddp-server/livedata_server_tests.js
Hi,
I'm happy to publish my first PR on the meteor project, hope that you will enjoy it.
This is an answer for the issue #6649.
It allows this three syntaxes for publications
```
Meteor.publish({
something() {
//something
}
});
```
```
Meteor.publish({
"something": function() {
//something
}
});
```
```
Meteor.publish("something", function() {
//something
});
```
> Allow `Meteor.publish` to take an object

- meteor
- scripts/dev-bundle-tool-package.js
- tools/packaging/tropohouse.js
- tools/tests/utils-tests.js
- tools/utils/http-helpers.js
For #7267 
I wanted to get your thoughts on this approach @benjamn.
Todo:
> Package download request resuming

- History.md
- packages/minifier-css/minifier.js
- packages/minifier-css/urlrewriting-tests.js
Fixes regression caused in 1.3.4.1 which caused network path reference URLs
(i.e. //img.domain.com/path/font.eot) used in CSS `url()`'s' to be stripped
of their leading slashes causing them to become relative URL paths.
Closes meteor/meteor#7416
> Don't rewrite network path references in CSS URLs.

- tools/cli/example-repositories.js
I added a new base application example, it includes Meteor 1.3 application with Angular2 and Angular2-Meteor applications, along with basic "Hello World" example with unit tests and all the required dependencies for Angular2-Meteor applications.
The idea is to get an easy start for new Angular2-Meteor developers, by providing the command:
`meteor create angular2`.
Thanks.
> Added Angular2 to the example repositories

- tools/isobuild/bundler.js
After running `meteor build` in created archive `Readme` file currently has next content:
```text
This is a Meteor application bundle. It has only one external dependency:
Node.js 0.10.40 or newer. To run the application:
$ (cd programs/server && npm install)
$ export MONGO_URL='mongodb://user:password@host:port/databasename'
$ export ROOT_URL='http://example.com'
$ export MAIL_URL='smtp://user:password@mailhost:port/'
$ node main.js
Use the PORT environment variable to set the port where the
application will listen. The default is 80, but that will require
root on most systems.
Find out more about Meteor at meteor.com.
```
Since `Meteor@1.4` requires `nodejs@4.4.7` and fails on `nodejs@0.10.*`, generated `Readme` must be updated
> Update generated Readme file in builded app

- .travis.yml
This is a simple quick fix for the travis yml config file.
run.sh already runs ./meteor --self-test
so the install section defined in travis config can be remove.
> Improve the meteor build speed on Travis CI

- meteor
- scripts/generate-dev-bundle.ps1
- tools/cli/commands-packages.js
- tools/fs/files.js
- tools/packaging/tropohouse.js
- tools/packaging/warehouse.js
For the sake of portability, the `files.extractTarGz` method is currently implemented in terms of a pure-JavaScript library: https://www.npmjs.com/package/tar
Portability is nice, but speed is also nice. On my machine, it takes 25 seconds to extract the `fourseven:scss` package using the npm `tar` package, whereas it takes only *3.5 seconds* to extract it using the native `tar` command. On Windows, the time drops from 36 seconds to 8 seconds.
The time savings for even larger packages like `meteor-tool` are even more dramatic: 45 seconds vs. 4 seconds on my Mac.
This pull request uses the native commands when possible, but falls back to the npm `tar` library if the native commands don't work for any reason.
For Windows, we now include a standalone `7z.exe` binary in the dev bundle (i.e., …
> Extract .tar.gz files using native tar or 7z.exe when possible

- meteor
- scripts/dev-bundle-tool-package.js
- tools/tests/utils-tests.js
- tools/utils/http-helpers.js
Use `concat-stream` instead of `stream-buffers`
`concat-stream` is efficient and uses `Buffer.concat` once, rather than a continuous re-allocation and strcpy into new buffers.
> Switch to concat stream

- packages/facebook/facebook_server.js
It's possible to get an access token directly, for instance with mobile application. To make it easier to handle those access tokens on the backend, I split the function that handles the token from the larger function that starts with the code.
This enables things like handling fb login directly from an access token:
```js
let fbAppId = null;
export const loginWithFacebook = (params, req, res) => {
const fbAccessToken = req.body.token;
// make sure the access token is for our app
const fbAppIdForToken = JSON.parse(HTTP.get(
"https://graph.facebook.com/app", {
params: { access_token: fbAccessToken }
}).content).id;
// get our app id
if (!fbAppId) {
const config = ServiceConfiguration.configurations.findOne({service: 'facebook'});
fbAppId = config.appId;
}
if (fbAppId !== fbAppIdForToken) { …
```
> Expose the function that gets fb data from an access token

- History.md
- packages/google/google_client.js
This is a re-submission of https://github.com/meteor/meteor/pull/5699.
The `email` scope is enough for getting the required data, including the user ID, so no need for the `profile` scope, which may deter users.
The discussion started at https://github.com/meteor/meteor/issues/5650
Our team anticipates Google to be a major choice for users during signup, so we would like to alleviate some of the concerns that requesting the `profile` scope may bring.
We would also like developers to have more control over more aspects, such as the way the popup window behaves (e.g, forcing it upon login for situations where there is more than one logged-in Google account).
I would really like to hear your opinions in the discussion thread.
> Remove the google `profile` scope.

- tools/tool-env/install-promise.js
- tools/tool-testing/selftest.js
The `phantomjs-prebuilt` package (typically installed [here](https://github.com/meteor/meteor/blob/46b9f128ce113d16e304415600dbbb22b0989c59/scripts/ci.sh#L10)) now depends on a `Promise` polyfill package called `es6-promise`, which misbehaves by overwriting the `global.Promise` constructor. This becomes a problem when Meteor tools code attempts to call `Promise.prototype.await` that are [added](https://github.com/meteor/meteor/blob/46b9f128ce113d16e304415600dbbb22b0989c59/tools/tool-env/install-promise.js#L7-L10) by our (well-behaved) runtime setup code, because `global.Promise` is no longer the same as the version of `Promise` that we augmented.
> Fix misbehaving promise polyfill

- packages/minifier-js/.npm/package/npm-shrinkwrap.json
- packages/minifier-js/package.js
- packages/standard-minifier-css/package.js
- packages/standard-minifier-css/plugin/minify-css.js
- packages/standard-minifier-js/package.js
- packages/standard-minifier-js/plugin/minify-js.js
Though UglifyJS unfortunately does not support many new ES2015+ features, and its `harmony` branch is [not quite stable yet](https://github.com/meteor/meteor/pull/7517), we can mitigate part of the problem by avoiding using the `uglify-js` package for server files.
> Stop minifying server files

- packages/accounts-base/accounts_common.js
- packages/accounts-base/accounts_server.js
- packages/accounts-password/password_server.js
- packages/accounts-password/password_tests.js
This PR is based on #6833 
I have added some tests for the new functionality and increased the default password expiration time to 3 days.
> Expire Password reset tokens

- tools/isobuild/bundler.js
The previous code did not accommodate the possibility that `meteorNpm.getProdPackageNames` might return a package name that contained one or more `/` characters.
Fixes #7579.
> Fix accidental stripping of @scoped npm packages.

- tools/packaging/updater.js
Just because the background updater manages to download a new release, we should not necessarily update the `~/.meteor/meteor` symlink (or `AppData\Local\.meteor\meteor.bat` on Windows) to refer to the new release. That should happen only when the user explicitly runs `meteor update`, i.e. [here](https://github.com/meteor/meteor/blob/eebf538ee00434edeae60ed2ad053e3f76d1b6a6/tools/cli/commands-packages.js#L1346).
> Don't touch ~/.meteor/meteor after background updates.

- tools/cli/commands.js
- tools/cli/help.txt
- tools/runners/run-all.js
In issue #7026, the release updater is not a part of the catalog update, therefore it still runs the updater even if `METEOR_OFFLINE_CATALOG` is specified.
The reason that we really really need this option is, meteor runs way too slow on travis-ci, it spents almost 7 minutes to just *prepare* the application.
A `--no-release-check` option is added to the run command in this PR.
> Add option to skip release check

- History.md
This is just a small fix for the version number of Node MongoDB driver in History.md.
The correct version in Meteor 1.4.1.1 is 2.2.8, not 2.2.7.
> fix version number of Node MongoDB driver in History.md (v1.4.1.1)

- History.md
The change was added in the v.NEXT, but later v.NEXT was changed into v1.3.3 for the 1.3.3 release. Now it was in 1.3.3, which is wrong and misleading. This PR move it to v.NEXT since it was not released till now.
> Move #7117 entry to v.NEXT in History.md

- packages/accounts-base/accounts_client.js
Fixes #7385 
For consistency with the server methods, this passes an object to the onLoginFailure hooks, but unlike on the server it contains only the error associated with the failed login attempt.
> Pass object with error to onLoginFailure hooks

- packages/boilerplate-generator/boilerplate_web.cordova.html
This PR should fix #7772 by adding ws: and wss: to the default CSP for Cordova.
> Add ws: and wss: sources to default CSP for Cordova

- packages/stylus/package.js
Meteor's fork of Stylus was updated: https://github.com/meteor/stylus/pull/1
This updated a reference to it.
Fixes: #7725
> Updating stylus dependency

- packages/npm-mongo/package.js
This release of the node-mongodb driver finally fixed performance issues we were having on our Compose MongoDB 3.2 deployment.
> Update node-mongodb driver to 2.2.10

- tools/cli/commands.js
This functionality for the `test` command was overlooked when meteor/meteor#7445 was implemented.
Closes meteor/meteor#7026
> Add support for `--no-release-check` to `meteor test` command

- tools/isobuild/meteor-npm.js
This subtle change appears to be the fix for the (recent) CI server timeouts.  Previously, the `await` was only on the `Promise` from `getEnv` and this adds it to the `Promise` for the `npm install` as well.
It's entirely possible that the `await()` would be better suited to be [in the `getEnv` method](https://github.com/meteor/meteor/blob/942221d07f7197e449855a70e526f454ee46887b/tools/cli/dev-bundle-bin-helpers.js#L16) but I'm not certain that would be desired.
There is still a completely separate failure which is still occurring (_far_ less often) which produces the error:
```
Can't install npm dependencies. Are you connected to the internet?
```
...but that appears that it might actually be a _legitimate_ problem with the connection.  More on that later, maybe.
> Await `Promise` when running `npm install`

- packages/mongo/collection.js
This change changes units to be consistent and more clearly indicates when these parameters come into play.
Addresses concerns in meteor/meteor#7538
Fixes meteor/meteor#7538
> [docs] Clarify JSDoc for pollingIntervalMs and pollingThrottleMs options

- tools/isobuild/meteor-npm-userconfig
- tools/isobuild/meteor-npm.js
Fixes https://github.com/meteor/meteor/issues/7636
Now it just doesn't check the connection if we need to authenticate for get requests (according to the `always-auth` npm setting). This is because there are multiple ways to authenticate to NPM servers (http auth, certs, bearer tokens?) and it'd be hard to make all of them work.
> Do not check connection with protected npm registries

- tools/cli/main.js
Hi,
This is a solution for #7631
```
$ sudo meteor
It seems that you are running meteor as root, if you really know what you are
doing, add the unsafe-perm flag.
meteor --unsafe-perm <command>
```
```
$ sudo meteor --unsafe-perm
You are running meteor as root, don't forget to chown your .meteor directory
back to yourself.
chown -Rh <username> ~/.meteor
...
```
> Meteor should check if is running as root and prevent it on Unix

- packages/coffeescript/.npm/plugin/compileCoffeescript/npm-shrinkwrap.json
- packages/coffeescript/package.js
- packages/coffeescript/plugin/compile-coffeescript.js
- packages/coffeescript/tests/coffeescript_module.coffee
- packages/coffeescript/tests/coffeescript_tests.coffee
- packages/coffeescript/tests/es2015_module.js
CoffeeScript 1.11.0 is out, and this release adds [native support for `import` and `export` statements](http://coffeescript.org/#modules). There’s no need to wrap such statements in backticks anymore.
This pull request updates Meteor’s `coffeescript` package as follows:
- The version of CoffeeScript is bumped to 1.11.0.
- Previously, any CoffeeScript file that contained at least one backtick was passed to the `ecmascript` package for further compilation by Babel. Now CoffeeScript files that contain backticks or the substrings `import`, `export` or `function*` are passed to `ecmascript`.
- New tests are added to check that the native `import` and `export` statements work.
Regarding when to pass to `ecmascript`, technically CoffeeScript currently has two features that are output as ES2015 …
> CoffeeScript now supports ES2015 modules

- Contributing.md
Link to Meteor website was broken and there were 2 links which looked
like one. Replaced with a link to the list of packages in the Meteor
repository to give the best currently available overview of the parts
of Meteor.
> Fix #7827 - Fix link in Contributing.md

- packages/coffeescript/plugin/compile-coffeescript.js
This commit improves the performance of the regex used to check if the coffeescript source should be passed to babel, by using `Regex#test` instead of `String#match` (see http://stackoverflow.com/a/10940138/3142952)
> coffeescript: improve es6 regex performance

- packages/coffeescript/package.js
By doing a version bump of this package, anyone who wants to can update to version `1.2.6` and enjoy coffeescript `1.11.0`.
As discussed here: https://forums.meteor.com/t/coffeescript-1-11-0-now-supports-es6-modules/29750/8
> Bump the coffeescript package version

- tools/isobuild/bundler.js
- tools/tests/bundle-ignore-files.js
This is a continuation of @c9s work (https://github.com/meteor/meteor/pull/7483) to fix (https://github.com/meteor/meteor/issues/7482)
Merging the different regex to one is quite a bit faster than executing them one-by-one (see: https://github.com/meteor/meteor/pull/7483#issuecomment-249938794 for a rough estimate).
> Optimize ignoreFiles patterns

- tools/fs/safe-pathwatcher.js
- tools/isobuild/package-api.js
- tools/isobuild/package-cordova.js
- tools/isobuild/package-namespace.js
- tools/isobuild/package-npm.js
- tools/isobuild/package-source.js
Similar to the treatment given to `PackageAPI` in my commit af50b4cc5b55a958607b427a8f35e33cb8967f30.
This clearer separation of concerns will be helpful for optimizing `PackageSource#initFromPackageDir`.
> Decompose PackageNamespace, PackageNpm, and PackageCordova classes.

- tools/console/console.js
`Console.failInfo` and `Console.failWarn` functions were both using the `Console._fail` function which is passed a severity of failure as a string (e.g. "warn", "error", etc.) which corresponds to the appropriate `Console` function.  Previously, the string was just being called as if it was a function.
Fixes meteor/meteor#7882
> Fix for `Console.failInfo` and `Console.failWarn` when `pretty` is false

- tools/console/console.js
- tools/cordova/project.js
`Console.success` is currently called in only one place but it relies on the fact that `pretty` console mode is enabled for it to make any sense.  This adds the ability to pass an "ugly" (less pretty?) message to `Console.success` (default: "success") and changes the Cordova dependency checker to use "installed" when showing a met-dependency.
Fixes meteor/meteor#7883
> `Console.success` should provide an indicator when pretty is disabled

- tools/cli/commands.js
Building logs files on Travis-CI are getting over 4mb and 80% are spinners.
There's no point in spinning the spinner when we're running automated builds.
> Add --headless option to the build command

- packages/standard-minifier-css/plugin/minify-css.js
The previous implementation had a run time quadratic in the number of CSS files with an associated source map. This new implementation has a linear run time because it iterates only once through all mappings of each CSS file.
Fixes the performance problems discussed in #7673.
> Rewrite source map composition for CSS files

- tools/tests/cordova-platforms.js
* Adds test which would have caught #7884 (fails without it, passes with it)
* Adds (Unix-only) test which checks for message when platform is already added (previously no test)
* Fix incorrectly redeclared `var` + s/`var`/`let`/
> Add Cordova Platform Dependency Tests

- packages/mongo/mongo_driver.js
- packages/mongo/package.js
I'm not sure if we want to do a point release for this one, or just release a new version of the `mongo` package and sweep it up in the next release.
AFAICT, fixes #7822, and possibly various other mongo-related bugs I've been hearing about.
> Reconnect to mongo indefinitely.

- packages/mongo/.npm/package/npm-shrinkwrap.json
- packages/mongo/mongo_driver.js
- packages/mongo/package.js
- packages/npm-mongo/.versions
- packages/npm-mongo/package.js
Travis CI builds have been failing intermittently [since around the time #7880 was merged](https://travis-ci.org/meteor/meteor/builds).
I'm going to use this pull request to try to fix those tests. As a start, I've merely bumped the `npm-mongo` and `mongo` package versions. I don't expect that to solve the problem, but it's a start.
> Fix Travis CI tests by setting mongoOptions.server.reconnectTries = Infinity.

- History.md
Just a proposal, but happy to be rejected.
Currently the history entry for meteor/meteor#7821 states that it prints a warning but is actually a breaking change for anyone running the `meteor` tool as `root` right now (for example, CI environments with auto-deploy, etc.).  This moves that history entry higher (a bit more prominent) and explains why.
> Move History entry about #7821 higher explain further

- packages/facebook/facebook_client.js
According to the Facebook docs:
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
The parameter should be `auth_type`, not `authType`.  A cursory look through their API history didn't show anything about it being changed, but I can confirm that using this feature does not work with `authType` in the current implementation.
I don't think this has ever worked.
Related meteor/docs#94
Related meteor/meteor#7584
Closes meteor/meteor#7078
> Change Facebook oAuth param from `authType` to `auth_type`

- tools/cli/help.txt
- tools/packaging/warehouse.js
- tools/project-context.js
This is a refactor/finishing-move of @c9s's original PR meteor/meteor#7586.
This maintains backward compatibility with `PACKAGE_DIRS` using the original separator that it expected (':').  Users of the new `METEOR_PACKAGE_DIRS` variable should use the correct path separator for their platform (`:` on BSD/Linux and `;` on Windows).
Fixes meteor/meteor#7585
Fixes meteor/meteor#4204
***
Suggested for `History.md`:
```
For compatibility, the `PACKAGE_DIRS` environment variable has been deprecated.
Developers should use `METEOR_PACKAGE_DIRS` and Windows projects should
now use a semi-colon (;) instead of a colon to separate paths. #4204 #7585
```
> Add METEOR_PACKAGE_DIRS support and deprecate PACKAGE_DIRS

- README.md
The README explained how to run Meteor from a checkout: 
https://github.com/meteor/meteor#slow-start-for-developers
The example used is the Meteor docs app, which is available in the Meteor repository itself. However it did not mention how you can run the local Meteor checkout from a local app.
That is the most basic use case, for example to reproduce or even fix a bug. 
That’s why this example is based on creating a new clean app with meteor create so we focus on creating a clean reproduction. That way we can point to it when people want to debug their own issue.
This change makes it easier for beginners to use while it does not negatively impact expert users in my opinion.
**Edit:** Another thing which I am not sure of mentioning: The process described does not work actually. You first …
> Readme: Make clear how to run your app with a local checkout of Meteor

- packages/mongo/collection.js
- packages/mongo/connection_options.js
The JSDoc linked to older versions (1.4 and 2.1) of the MongoDB driver docs.
Related PR: https://github.com/meteor/docs/pull/98
> Update links to MongoDB driver docs

- packages/boilerplate-generator/boilerplate_web.cordova.html
In UIWebView on iOS10 we get CSP failure to load gap://ready, this resolves it on both simulator and device. This is an urgent fix.
> Adding gap: into CSP

- meteor
This makes a couple changes to the `ulimit` calls of the Meteor launch script.
This will hopefully be less necessary with future changes to the watcher, but as long as polling mechanisms are in place for the files (e.g. `file.watchFile`), this seems helpful as changes to `ulimit -n` could be necessary.  This POSIX-compatible PR does two things:
* Don't lower `ulimit` max open files if it's already higher than desired  …
* Previously, if the default ulimit was set to a value higher than 16384, it was lowering it.  While this doesn't do much for users with default OS settings, those that have modified their ulimit settings will have their settings maintained.
* Increase the value of the first `ulimit` max open files change attempt  …
* Make the first attempt 32768 instead of 16384 since …
> Change "max open files" logic in launcher

- packages/oauth1/oauth1_server.js
- packages/twitter/package.js
- packages/twitter/twitter_client.js
- packages/twitter/twitter_common.js
- packages/twitter/twitter_server.js
Ok, please bear with this description...
This PR is meant to fix a previous broken implementation of the `force_login` parameter for Twitter (link below) which was reported in #6987.   This appears to be first attempted by very-old PR #1566 as a two-in-one-PR but turned into abandonware and never got merged.
#5693 (another attempt) also never landed but was resurrected into #6987 which did land but unfortunately, there is no way that it could work as the `force_login` parameter would be lost when passed to the Meteor oAuth server before the redirect to the actual service (e.g. Twitter, other oAuth1 implementations) which needs to see this param.
So, with a little help from code from #2404 and using the previously-supported ability to pass a function (versus a string) for an oAuth1 URL, …
> Support additional params on oAuth1 authorize URL

- tools/packaging/catalog/catalog-local.js
Presently, `buildmessage.forkJoin` is being used to loop over the packages and initialize them. I believe the original intent was to run the package initializations in parallel, but apparently this was causing issues and was disabled. So it is logically equivalent to just iterating over each package and initializing them in serial. However, using `forkJoin` causes each package initialization to run in its own fiber, which can cause serious performance problems. This PR replaces the `forkJoin` with a plain loop, and decreased the runtime of `LocalCatalog#_loadLocalPackages` from around 5s to about .1s on [Qualia](http://qualia.com)'s very large application. 
I'm not entirely certain (I should probably test this), but this PR may only be effective in conjunction with …
> Replace forkJoin with enterJob to avoid fiber issues

- tools/cli/dev-bundle-bin-helpers.js
- tools/cli/main.js
Propagating environment variables to child processes is easier than (re)passing explicit command-line flags, so `--unsafe-perm` is now a shorthand for setting `process.env.METEOR_UNSAFE_PERM = "true"`.
Allowing the use of an environment variable is important for `meteor npm`, since we don't parse or pass through Meteor-specific command-line arguments when running `meteor npm`.
When `$METEOR_UNSAFE_PERM` is set, its value should be propagated to any npm commands via the `$NPM_CONFIG_UNSAFE_PERM` variable.
Helps with #7959.
Follow-up to #7821.
> Respect $METEOR_UNSAFE_PERM in addition to --unsafe-perm.

- tools/cli/commands.js
I accidentally a line when I committed/submitted meteor/meteor#7799, as reported in this comment:
https://github.com/meteor/meteor/issues/7026#issuecomment-256728729
The `METEOR_NO_RELEASE_CHECK` environment variable did/does work properly, but both were meant to work.
> Fully implement `--no-release-check` for `meteor test`

- packages/accounts-password/email_templates.js
As I see, current realization of `Accounts.emailTemplates.verifyEmail.text` are equal to result of already defined `greet` function with `"To reset your password"` param. So I suggest to use it instead.
> Refactor template of `resetPassword` email

- packages/stylus/README.md
Make it clear that all files with the `.styl` extension are processed and not just `.main.styl` files based on the comment from meteor/meteor#6337.
I believe this `main.styl` syntax might be residue from some ancient version but Meteor definitely processes all `styl` extensions, as seen [here](https://github.com/meteor/meteor/blob/7858fb2431321a11d22cc87bbf1ea591d7594d77/packages/stylus/plugin/compile-stylus.js#L7-L10).
Fixes meteor/meteor#6337
> Clarify mis-leading wording in the `stylus` README

- Contributing.md
The style guide link pointed to content that was moved to the meteor guide, where you needed to click again. This links directly to that target.
> Link directly to style guide

- packages/minimongo/minimongo_tests.js
- packages/minimongo/modify.js
Related issue: https://github.com/meteor/meteor/issues/7857
This implements $min, $max and partially $currentDate + tests
I didn't implement $mul, since there can be [numeric type conversions](https://docs.mongodb.com/v2.6/faq/developers/#faq-developers-multiplication-type-conversion) which I don't know how to deal with in JS. There's also no support for `timestamp` type in $currentDate, since from what I understand of [the docs](https://docs.mongodb.com/manual/reference/bson-types/#document-bson-type-timestamp), this is an internal type I can't generate myself.
> Implement $min, $max, $currentDate modifiers

- packages/accounts-password/password_client.js
- packages/accounts-password/password_tests.js
This PR is intended to address #5676. Preventing an `undefined` callback from being passed into the `forgotPassword` Method helps avoid issues with the `audit-argument-checks` package (more details in issue). Thanks!
> Preventing undefined callback from being passed into the forgotPassword Method

- packages/minifier-css/minifier.js
- packages/minifier-css/urlrewriting-tests.js
For certain use cases, like SVG filters, the url needs to have a # symbol. For example, the following css property : 
```filter:url("filters.svg#lightGreen")```
In the current version of the codebase, gets rewritten to : 
```filter:url("http://myapp.com/filters.svg")```
Whereas the proper behaviour should be: 
```filter:url("http://myapp.com/filters.svg#lightGreen")```
This simple change will fix the issue.
> Keep Hashes in URL when rewriting relative URLs

- tools/static-assets/skel-full/imports/api/links/links.js
- tools/static-assets/skel-full/imports/api/links/links.tests.js
- tools/static-assets/skel-full/imports/api/links/methods.js
- tools/static-assets/skel-full/imports/api/links/methods.tests.js
- tools/static-assets/skel-full/imports/api/links/server/publications.js
- tools/static-assets/skel-full/imports/api/links/server/publications.tests.js
- tools/static-assets/skel-full/imports/startup/both/index.js
- tools/static-assets/skel-full/imports/startup/server/fixtures.js
- tools/static-assets/skel-full/imports/ui/components/info/info.html
- tools/static-assets/skel-full/imports/ui/components/info/info.js
- tools/static-assets/skel-full/imports/ui/pages/not-found/not-found.html
- tools/static-assets/skel-full/imports/ui/stylesheets/not-found.less
- tools/static-assets/skel-full/package.json
Updated the code style (and dependencies) for the full scaffold to match (as best as seems reasonable) the Meteor guide.
There is some discrepancy with the recommended eslint configuration. For example there are a number of rules that make sense within the context of a Meteor project, which is exactly why [these have been added](https://github.com/meteor/todos/blob/master/package.json#L41-L61) in the todos example. So to address that I've added a few `eslint-disable` comments where it makes sense, though it's not ideal.
In [some cases like this](https://github.com/meteor/meteor/blob/devel/tools/static-assets/skel-full/imports/ui/components/hello/hello.js#L3) it is pretty much standard practise (in Meteor) to not bother with naming function expressions (`func-names`). So we should probably …
> code style changes for skel-full

- tools/console/console.js
See https://github.com/meteor/meteor/issues/6785
Basically, 
```
new Array(249).join('\b')
```
is not a good idea for a carriage return. Code has been tested with CMD, PowerShell and PowerShell in Legacy Mode and seems to solve the issue.
> Fix for console output in PowerShell on Win10

- tools/cli/commands.js
- tools/cli/default-npm-deps.js
Although I have said I do not think Meteor should run `npm install` automatically to update application `node_modules`, my real concern is that Meteor should not interfere with your preferred `node_modules`-related workflow, be it `npm`, `npm-shinkwrap.json`, `shrinkpack`, `yarn` + `yarn.lock`, checking your `node_modules` into git/mercurial/cvs, or whatever other scheme you currently have (or might adopt in the future).
Automatically installing `node_modules` from the default `package.json` file when a new app is created will eliminate real confusion, and should not interfere with any workflows, because there is no opportunity to establish another workflow before Meteor runs `npm install` the very first time.
Addresses https://github.com/meteor/meteor/issues/6848.
May make …
> Install npm dependencies automatically when creating apps.

- tools/isobuild/compiler-plugin.js
While not a Meteor bug, this makes the error message more helpful when a build plugin tries adding an asset (`ResourceSlot.addAsset`) without data.  For example, [this file](https://raw.githubusercontent.com/Urigo/meteor-rxjs/28ac86a29b957b705b78425b49285eb7d90db324/examples/angular2/client/imports/app/app.component.scss) when run through `angular2-compiler` (which has since had the bug fixed, but it was harder to find because this error was not verbose enough).  This was as demonstrated in meteor/meteor#8034.
With this change, `ResourceSlot.addAsset` behaves the same as [`ResourceSlot.addHtml`](https://github.com/meteor/meteor/blob/b1df3ed0ed2b686e96d89ee66252f447b3c3b87e/tools/isobuild/compiler-plugin.js#L756-L760) which provides the `path` (of the file attempting to be compiled) in the …
> Improve build plugin error when asset is added with empty contents

- packages/browser-policy-content/browser-policy-content.js
- packages/browser-policy-content/package.js
- packages/browser-policy/README.md
- packages/browser-policy/browser-policy-test.js
- packages/browser-policy/package.js
This Pull Request adds support for for the frame-ancestors CSP option in the browser-policy package. Right now, there is no easy way to allow and/or restrict specific domains from framing your app. Using the X-Frame-Options header has the following problems:
- You are only allowed to restrict all domains, only allow same domain, or only allow one other domain. So, if you need to allow multiple domains to frame your app, you can't.
- The X-Frame-Options header does not work in Chrome or Safari. So even if you want to allow another domain to frame your app, you can't guarantee that it will work in those browsers.
As a result of the above, to allow other domains to frame your app, you have to allow _all_ domains to frame your app. 
However, there is a [frame-ancestors …
> Add support for frame-ancestors CSP option in browser-policy

- packages/ddp-server/livedata_server.js
- packages/ddp-server/stream_server.js
In general, we try to avoid allowing TCP connections to be open with no
traffic on it indefinitely.  We place timeouts on incoming HTTP
connections in webapp_server.js (which we adjust to longer values when
there's an HTTP request pending), and once a DDP connection is fully
established we require heartbeats.
However, if the incoming connection is a websocket, the faye-websocket
package used by SockJS calls setTimeout(0) on the underlying socket when
it initializes the WebSocket object:
https://github.com/faye/faye-websocket-node/blob/3148348a3/lib/faye/websocket/api.js#L111
So if a client does the WebSocket handshake with the server but never
sends a valid DDP connect message, the socket can be held open
indefinitely. (To add insult to injury, a 1MB Buffer object is retained
on such …
> Don't allow websockets to indefinitely wait for DDP handshake

- History.md
As a correction to 8e22818 which inadvertently removed 1.4 from existence.
Good catch by @mitar.  https://github.com/meteor/meteor/commit/8e228180e66a9808f268f1de1b9ead2ec21a8751?diff=unified#commitcomment-20013960
/cc @zol – I think this is what you wanted.
> Fix history and add history for #7970

- History.md
- meteor
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/babel-compiler/package.js
- packages/modules/.npm/package/npm-shrinkwrap.json
- packages/modules/package.js
- scripts/dev-bundle-tool-package.js
- scripts/generate-dev-bundle.ps1
- tools/isobuild/js-analyze.js
Currently, we run Reify to transpile all `import` and `export` declarations at the end of the `meteor-babel` compiler pipeline, as explained in [this comment](https://github.com/meteor/meteor/issues/8021#issuecomment-258888771).
That needs to change if we want Reify to be able to generate block-scoped `let` declarations for imported symbols (#8021) or to have a chance of handling `import` declarations before generator functions get transpiled (#7662).
I was hoping these changes might make it into Meteor 1.4.2.1, but (even though tests were passing) they introduced too much risk, as outlined in [this comment](https://github.com/meteor/meteor/issues/8021#issuecomment-259202160).
> Run Reify before Babel to fix #8021 and #7662

- tools/console/console.js
This is a followup to https://github.com/meteor/meteor/pull/7814. There are simply many reasons why would various commands be run inside CI and other automatic environments. Spinner is not needed there. Instead of adding `--headless` arguments to various commands, let's have a global environment variable and this is it.
BTW, this also seems to improve speed of whole Meteor tool experience. I would even say that probably this should be the default. No need for a spinner at all. It slows down things too much.
> Allow global headless setting

- scripts/ci.sh
General improvements to the CI script:
* Changes the CI script to make sure it runs all tests, regardless of the environment configuration while still allowing flexibility in the size of the container parallelism.
While not having any effect on the Meteor configuration this will now run all 8 test groups across a fewer number of containers, if necessary.
This fixes issues where false-positives are achieved on contributor PRs, like seen on meteor/meteor#7963 and for the reason I explained here: https://github.com/meteor/meteor/pull/7963#issuecomment-264188162
* Permits changing `TIMEOUT_SCALE_FACTOR` using a variable instead of hard-coding it in the script and adds `ADDL_SELF_TEST_EXCLUDE` to define environment specific tests which must be skipped.  For example:
```sh
$ …
```
> Make CI test runner more defensive and a bit more flexible

- packages/meteor/timers.js
Thanks to @CdavM for pointing out this JSdoc discrepancy in #7778.
The value passed into from `Meteor.clearTimeout` or `Meteor.clearInterval` is an opaque handle returned by `Meteor.setTimeout` and `Meteor.setInterval` accordingly.
That is to say, on some engines it will be a `Number` and on others an `Object` but you need not worry about the actual type.
Closes meteor/meteor#7778
> [docs] Clarify docs for handle returned by Meteor.setTimeout/setInterval

- packages/stylus/.npm/plugin/compileStylusBatch/npm-shrinkwrap.json
- packages/stylus/package.js
- packages/stylus/plugin/compile-stylus.js
Nib is very outdated. I was mostly using it to add vendor prefixes. But now people use autoprefixer for that. So I added it to the package.
One can configure which browsers to support using file options:
``` javascript
api.addFiles([
'file.styl'
], 'client', {
autoprefixer: {
browsers: ['last 3 Chrome versions', 'Firefox >= 7', 'Explorer >= 8', 'last 2 versions', '> 1%', 'Firefox ESR', 'Safari >= 4']
}
});
```
[See defaults here](https://github.com/ai/browserslist#queries).
> Added autoprefixer to stylus

- scripts/ci.sh
As a follow-up to cleaning up `ci.sh` yesterday in #8122, I found some tests that don't exist anymore but were still "excluded" from running.  This removes the exceptions for these non-existent tests:
* ^mongo - logged (in|out)
* ^logs - logged (in|out)
* ^can't publish package with colons
> Remove skipped CI tests which don't exist anymore

- packages/coffeescript/.npm/plugin/compileCoffeescript/npm-shrinkwrap.json
- packages/coffeescript/package.js
- packages/coffeescript/plugin/compile-coffeescript.js
[CoffeeScript 1.12.0 is out](http://coffeescript.org/#changelog). This updates Meteor’s package to use the new version.
I removed the `if` check that passed through the CoffeeScript compiler’s output to `ecmascript` only if certain ES2015+ features were recognized in the original source. Now all coffee output is parsed by `ecmascript`. With the addition of tagged template literals and `for…of` in CoffeeScript 1.12.0, I don’t think it’s possible anymore to reliably detect when ES2015+ features are being used. We should just always assume there could be ES2015+ syntax in the CoffeeScript compiler output, unfortunate though that is from a performance perspective.
> Use CoffeeScript 1.12.0

- packages/shell-server/shell-server.js
- tools/shell-client.js
This is a partial alleviation of the issue explained/reproduced in #5346.
Previously, the width (or "columns") for the readline shell was being obtained on the server.  This causes problems for clients which are connecting to the server which are sized differently (like WebStorm)
The client will still have problems if they resize AFTER they are connected to the REPL, but at least they have the option of being a different size.
A more complete solution would be to have the client listen on process.stdout "resize" and pass that to the server when it occurs, but I'm not sure of an easy way to do that with the current communication (perhaps pause-reconfigure-unpause?)
Addresses meteor/meteor#5346
> `meteor shell` should pass its TTY width to the server on connect

- tools/cli/commands-packages.js
Tiny fix for an old issue where the console output would get corrupted when running `meteor admin set-unmigrated` or `meteor admin change-homepage` due to missing newline on `rawInfo` command.
Fixes meteor/meteor#4054
> Fix console glitch when using some admin package functions

- tools/cli/commands.js
This fixes a regression caused by 88d43a0f16a484a5716050cb7de8066b126c7b28 which is demonstrated in meteor/meteor#7849.
Essentially, with the current implementation some Cordova build elements are "stale" when the build is copied.  For example, if you execute a `meteor run ios` and then `meteor build . --server=http://example.com/` (note: `example.com`) the `config.xml` (`<access origin />`), the boilerplate HTML (`__meteor_runtime_config__`) and other elements of the bundle (`Info.plist` on iOS) will still contain the previously used `http://<local_ip>:3000` address instead of `http://example.com` as they should.
Additionally, it would appear that it's impossible to actually checkout a project and immediately run `meteor build` without running `meteor run (android|ios)` first.
Various …
> Cordova project preparation must occur before copying to the build

- packages/ddp-server/livedata_server.js
- packages/ddp-server/livedata_server_tests.js
- packages/ddp-server/server_convenience.js
Like the `onConnection` hook, this is called for every DDP message received. We have a large meteor app and would like to centralise authorisation for publications and methods in the least error-prone way possible. Without any documented way to hook into the server core, the best we can do is monkey-patch `Session`. This PR provides a better way.
> add onMessage hook

- packages/observe-sequence/observe_sequence.js
Fix for #8160.
Simple fix to enable arrays created in foreign windows to be valid for Blaze `{{#each}}` loops.
Just changed `instanceof` check to use `_.isArray()`.
> fix for #8160

- packages/minimongo/minimongo.js
- packages/minimongo/minimongo_tests.js
- packages/minimongo/modify.js
- packages/minimongo/package.js
Hi all - this PR is intended to help address issue #3786. Right now Minimongo allows inserts with dot (".") containing field names, which is against [Mongo's field name restrictions](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names). The changes in this PR will cause a new exception to be thrown if dot containing field inserts are attempted by Minimongo, with the exception thrown matching the exception thrown by Mongo on the server side. Thanks!
> Adjusted Minimongo to prohibit dot based field name inserts, to fix issue #3786

- packages/npm-mongo/.npm/package/npm-shrinkwrap.json
- packages/npm-mongo/package.js
- tools/runners/run-mongo.js
This fixes an issue where the driver fails to recover from unresponsive primary in a replica set.
Relevant commit in `mongodb-core`:
https://github.com/christkv/mongodb-core/commit/6611ea48e2a9e195fdef1572d3f94db5924b3ee9
> Update node-mongodb driver to 2.2.16

- tools/static-assets/skel-bare/.meteor/packages
Fixes #8145
As described in the issue, `meteor create --bare` should not add the autopublish and insecure packages because it's for developers who want the bare minimum start.
> Remove autopublish and insecure from the bare skeleton app

- Contributing.md
Hi all - this small PR is intended to help address issue #3255. The [Contributing](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/Contributing.md) guide already outlines how to test internal Meteor packages, but it doesn't provide any details concerning Meteor Tool "self tests". I've added a small section that mentions the "self tests" and refers people to the testing section of the Meteor Tool README for more details. Thanks!
> Small content change to point to the Meteor Tool README for "self test" info

- packages/fastclick/README.md
See here:
https://github.com/ftlabs/fastclick/issues/497
And here:
https://productforums.google.com/forum/#!topic/chrome/Q4Rt6d0C4Qo
I just spent hours trying to figure out why selects haven't been working on my site, and finally found out it was fastclick.
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.
Always follow the [contribution guidelines](https://github.com/meteor/meteor/blob/devel/Contributing.md) when submitting a pull …
> Fastclick will break selects on Chrome mobile

- tools/static-assets/skel-bare/package.json
- tools/static-assets/skel-full/package.json
- tools/static-assets/skel/package.json
The `bare` skeleton didn't include the `babel-runtime` in `package.json`, thus making the instructions for starting the project (`meteor npm install` & `meteor`) inaccurate.
This change makes the `bare` skeleton the same as the `full` and "default" versions.
As an unnecessary liberty, since the latest version would be installed anyway, I bumped `meteor-node-stubs` and `babel-runtime` to the latest published version numbers and standardized the format of all three `package.json` files.
Closes meteor/meteor#8202
> Ensure `babel-runtime` is included in "skeleton" variations

- History.md
- packages/modules-runtime/.npm/package/npm-shrinkwrap.json
- packages/modules-runtime/modules-runtime.js
- packages/modules-runtime/package.js
- tools/isobuild/import-scanner.js
- tools/isobuild/resolver.js
Previously, when building a JavaScript bundle for the client, if a `package.json` file had a string-valued `"browser"` field, we would replace the value of the `"main"` field of the bundled `package.json` module with the value of the `"browser"` field. This trick was important because it allowed an npm package to have a different entry point on the client than it had on the server.
However, that approach became inconsistent if the `package.json` file was also explicitly imported as a module, because the `package.json` stub used for module resolution prevented the real contents of `package.json` from getting bundled, and disagreed with the original `package.json` module about the value of the `"main"` field.
To resolve that inconsistency, it seems better to avoid modifying the `"main"` …
> Preserve true "main" and "browser" fields of package.json modules.

- packages/tracker/tracker_tests.js
While working on an alternative implementation of Tracker, I added some more checks to assure correct behavior of `hasDependents`.
> Extended tests for Tracker for hasDependents

- tools/isobuild/import-scanner.js
Make the error message displayed to the developer more helpful in a situation like meteor/meteor#7859 where the `package.js` inadvertently referred to an imProPeRly-CaSeD version of the file it was importing.
No functionality change, just developer experience.
Fixes #7859
> Improve helpfulness of error message when combining different files

- packages/webapp/webapp_server.js
Previously we used the Node default behavior of just closing the
socket. This made it difficult for load balancers to understand if the
backend is buggy or the client request was bad (if Node is validating
something more strictly than the load balancer).
This only takes effect on Node 6; in older versions the socket is
already destroyed before the event is invoked. See
https://github.com/nodejs/node/pull/4557/ for details.
> In Node 6, send a 400 on HTTP parse failure

- packages/reload-safetybelt/safetybelt.js
- packages/test-in-console/driver.js
Hi all - this small PR is intended to help address issue #2380. There are only 2 core files remaining in the current codebase that reference `document.location`:
- `packages/reload-safetybelt/safetybelt.js`
- `packages/test-in-console/drivers.js`
This PR switches these over to `window.location`. All existing tests are passing, but I haven't included any new tests to verify these changes (as this is a difficult change to test for, and other than the issue outlined in http://stackoverflow.com/a/12098898/1756909, these are really just semantic changes). Let me know if you feel this should be handled differently - thanks!
> Replaced core references to document.location with window.location.

- packages/accounts-password/password_server.js
An example of a slow query that was slowing down my entire database that this PR should fix:
```
query wc_draft.users query: { $or: [ { services.password.reset.when: { $lt: new Date(1481501706951) } }, { services.password.reset.when: { $lt: 1481501706951.0 } } ] } plan
Summary: COLLSCAN ntoreturn:1000 ntoskip:0 nscanned:64642 nscannedObjects:64642 keyUpdates:0 numYields:208 locks(micros) r:1782624 nreturned:0 reslen:20 1028ms
```
See the discussion here:
https://github.com/meteor/meteor/issues/8158#issuecomment-267456752
> Added an index for the users collection

- tools/cli/help.txt
Hi guys - this small PR is intended to help address issue #8241, by adding the missing `os.windows.x86_32` option to the `meteor help build` architecture section. This brings the help listed architecture options inline with the supported architectures defined in https://github.com/meteor/meteor/blob/90f7efd98b87da080955398688fd0d82e3f62fe0/tools/cli/commands.js#L34-L39. Thanks!
> Updated meteor build CLI help to include os.windows.x86_32 --architecture option.

- packages/ddp-client/livedata_connection.js
- packages/ddp-client/livedata_connection_tests.js
So it seems we introduced a bug with #5680.
The issue is the following scenario:
* you have a publish sending changes to a field `a`
* they get buffered
* at the same time a client runs a method with a stub which changes field `b`
* method is simulated and ends
* buffered changes are applied
* server-side confirms a method
* client-side switches to a state after a simulated method call using `replace` message with the old `a` value, without that published change being present
Or something like this. It is really tricky race condition when this happens. But the solution is simple. Methods should always run on the latest state of data, without any pending buffered state. So this pull requests applies pending buffered state. In retrospective this looks obvious.
I am unsure how to make a test …
> Fix bad interaction between methods and buffering

- packages/force-ssl/README.md
- Drop reference to *.meteor.com apps (no longer exist)
- Clarify that this is a separate feature from Galaxy's "Force HTTPS" setting,
and that MDG recommends the latter for apps on Galaxy.
If this PR is merged, I'd appreciate publishing a new version quickly to update Atmosphere, as this is a constant source of confusion.
> force-ssl: update README

- packages/coffeescript/.npm/plugin/compileCoffeescript/npm-shrinkwrap.json
- packages/coffeescript/package.js
- packages/coffeescript/plugin/compile-coffeescript.js
Bumps the `coffeescript` package to use CoffeeScript [1.12.3](http://coffeescript.org/#changelog), and includes #8285 (which worked when I tested it).
> CoffeeScript 1.12.3

- packages/coffeescript/plugin/compile-coffeescript.js
This change, suggested by @abernix, fixes an issue (see #8281) where CoffeeScript source maps were not being generated (they appeared as blank files in the browser sources panel).
It's worth noting that these source files move from `top -> 💻app -> packages` to `top -> localhost:XXXX -> packages` in the sources list when this patch is applied (presumably because CoffeeScript files are now also passed through Babel).
> Fix typo in coffeescript compiler options. Fixes #8281

- packages/browser-policy-content/browser-policy-content.js
- packages/browser-policy-content/package.js
- packages/browser-policy-framing/browser-policy-framing.js
- packages/browser-policy-framing/package.js
- packages/browser-policy/browser-policy.js
- packages/browser-policy/package.js
This PR is intended to help close issue #6766. Developers expect to be able to use the following import:
```
import { BrowserPolicy } from 'meteor/browser-policy';
```
but due to the way the `browser-policy*` family of packages are setup, actually have to use the following import:
```
import { BrowserPolicy } from 'meteor/browser-policy-common';
```
This PR re-exports the `BrowserPolicy` variable within each of the `browser-policy*` packages that can be used on their own:
- `browser-policy-content`
- `browser-policy-framing`
- `browser-policy`
This way each one of the following imports will work:
```js
import { BrowserPolicy } from 'meteor/browser-policy';
import { BrowserPolicy } from 'meteor/browser-policy-content';
import { BrowserPolicy } from 'meteor/browser-policy-framing';
``` …
> Added additional BrowserPolicy exports to help with ES2015 import support.

- packages/http/httpcall_tests.js
- packages/url/package.js
- packages/url/url_common.js
- packages/url/url_tests.js
Hi all - this PR is intended to help address issue #5065. I've extracted @aldeed's proposed code from the [dispatch:url-encode-params](https://github.com/DispatchMe/meteor-url-encode-params) package, adding it to the `url` package. As mentioned in the original issue, this isn't a perfect solution since Node handles this differently, but it's definitely better than the current behaviour (and can always be extended later if/as needed). Anyways, it's a start - let the discussions begin! :-)
> Adjusted the url package to encode nested objects and arrays (to help address #5065).

- History.md
Now we have `twitter` and `google` splitted too. Thank you @abernix @pradel for reviewing and submitting PRs!
We should update the History.md accordingly. Maybe we should rephrase a bit since this version is not clear enough now. Discussions welcomed.
> Accounts splitting History.md update.

- packages/google-config-ui/google_configure.html
- packages/google-config-ui/google_configure.js
Issue https://github.com/meteor/meteor/issues/8309 is about a trailing / not being allowed by Google's OAuth registration form. This patch makes a quick change so the Meteor package google-config-ui shows a value for the OAuth origin that is copy-pasteable directly to Google.
> Fix for issue 8309

- packages/facebook-oauth/facebook_server.js
In testing for #7715, I discovered that the v2.2 Graph API endpoint was still in use in the `facebook` package which was due to sunset on 2017-03-25.
See Facebook Graph API Changelog here:
https://developers.facebook.com/docs/apps/changelog
When a Graph API endpoint is sunset, it (is claimed) to automatically turn over to the next more recent version, in this case v2.3.
v2.3 has a breaking-change over v2.2, notably listed in "Changes from v2.2 to v2.3":
> [Oauth Access Token] Format - The response format of https://www.facebook.com/v2.3/oauth/access_token returned when you exchange a code for an access_token now return valid JSON instead of being URL encoded. The new format of this response is {"access_token": {TOKEN}, "token_type":{TYPE}, "expires_in":{TIME}}. We made this update to be …
> Upgrade Facebook Graph API to use v2.8

- packages/url/package.js
- packages/url/url_common.js
- packages/url/url_tests.js
Hi guys - after some discussion about the implementation provided in PR #8261, it looks like we should adjust the implemented array handling a bit. Right now arrays are encoded with indices like:
```
some_array[0]=value1&some_array[1]=value2&some_array[2]=value3
```
While this implementation is somewhat supported by external languages and frameworks, it's not as well supported (by default) as the following query string representation for arrays:
```
some_array[]=value1&some_array[]=value2&some_array[]=value3
```
For example, PHP and Rails both expect **no indices** for arrays.
This PR adjusts the `url` package to make sure query string encoded arrays do not include indices. Thanks!
> Adjusted query string array representation to remove indices.

- packages/coffeescript/plugin/compile-coffeescript.js
Fixes missing CoffeeScript source maps (#8281/#8285).
* CoffeeScript has an `inlineMap` option that sets the `sourcesContent` property. However, it also includes the source map at the end of the compiled code. Since we have to process the compiled code afterwards, we can't use this option and have to set the `sourcesContent` manually. There is an issue in the CoffeeScript repo for more flexible source map options: https://github.com/jashkenas/coffeescript/issues/4342.
* The `SourceMapGenerator` was created incorrectly (its constructor doesn't accept a `SourceMapConsumer`), causing the generated source map to be empty.
A note on source map size: the produced source maps are correct but larger than necessary because of the way `applySourceMap` works. If there is no mapping from compiled …
> Fix CoffeeScript source map composition

- History.md
- meteor
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/babel-compiler/package.js
- packages/ecmascript/package.js
- packages/meteor-tool/package.js
- packages/modules/.npm/package/npm-shrinkwrap.json
- packages/modules/package.js
- scripts/admin/meteor-release-experimental.json
- scripts/admin/meteor-release-official.json
- scripts/dev-bundle-tool-package.js
- tools/isobuild/meteor-npm.js
Whereas [Meteor 1.4.2.7](https://github.com/meteor/meteor/pull/8361) fixed #8349 by reverting `npm` from version 4.1.2 to version 3.10.9, this release fixes the same bug by keeping `npm@4.1.2` but dealing with the consequences of [this breaking change](https://github.com/npm/npm/blob/latest/CHANGELOG.md#no-more-partial-shrinkwraps-breaking).
This release will also fix #8312, which could have been fixed independently (since it involves only packages), but was easier to fix after fixing the problem described above.
Note that Meteor 1.4.3 has been published, but we have not (and will not) "recommend" it, because of the problem with upgrading npm dependencies of Meteor packages.
> Release 1.4.3.1

- tools/isobuild/package-api.js
Delete a misleading comment as discussed in https://github.com/meteor/meteor/issues/5279#issuecomment-146018275
Resolves #5279
> Fix comment about unordered imports

- packages/accounts-base/accounts_client.js
- packages/accounts-base/accounts_client_tests.js
- packages/accounts-base/accounts_tests_setup.js
- packages/accounts-base/client_tests.js
- packages/accounts-base/package.js
- packages/accounts-ui-unstyled/login_buttons.html
Hi all - this PR is intended to help address issues #769 and #1331. It's essentially a re-working of the very old PR #826 (submitted by @raix - thanks!). I've modified it to work with the current codebase and added some tests. Let me know if you have any questions / need anything changed. Thanks!
> Added in Meteor.loggingOut() and related Blaze helpers.

- LICENSES/MIT.txt
- packages/check/isPlainObject.js
- packages/check/match_test.js
Update `isPlainObject` function used in `check` package to newer version. This new function is extracted from [JQuery v3.1.1 isPlainObject](https://github.com/jquery/jquery/blob/3.1.1/src/core.js#L238-L257).
I also add some tests to make sure it solve this issue #7354.
> Extract new isPlainObject function from JQuery v3.1.1

- History.md
Cordova was updated to 6.2.0 in Meteor 1.4.2 and Cordova (itself) changed the way the `buildNumber` was generated.  Some users experienced problems with the various app stores having version number clashes due to this change but Cordova insists it was mandatory.
This was brought up in a discussion on https://github.com/meteor/meteor/issues/7205.
Resolves https://github.com/meteor/meteor/issues/7205
Not sure if I should `git cherry-pick` this into `release-1.4.2` for prosperities sake or not, but happy to do so (if it won't break any of our versioning history).
Resolves #7205
> Update the 1.4.2 release notes to clarify Cordova `buildNumber` changes.

- packages/mongo/collection.js
- packages/mongo/mongo_livedata_tests.js
Hi guys - this PR is intended to help address issue #8329. Objects that contain a `length` property are causing issues when passed into the [`Mongo.Collection._rewriteSelector`](https://github.com/meteor/meteor/blob/907e1d91833eace7e40cc1d796cc7f9d171ceab1/packages/mongo/collection.js#L365) function. This is because the `_rewriteSelector` function is making a `_.each` call that is inappropriately treating the incoming selector object as an array. This PR replaces the `_.each` call with a `Object.keys(selector).forEach` call, which properly handles objects that have `length` properties.
I've updated the issue with the full troubleshooting details. Standing by for feedback - thanks!
> Replaced _.each with Object.keys().forEach to fix objects with length properties being used as Mongo selectors

- packages/http/package.js
This is to remove jQuery as a default dependency from `http` package, as a part of removing jQuery altogether as a default dependency from Meteor. See #8388 for more details.
> Remove jQuery dependency from http package

- tools/cli/commands.js
As of #8108, `meteor create` runs `meteor npm install`, so it doesn't need to tell you do to do so.
> Remove `meteor npm install` instruction

- History.md
- packages/minifier-js/package.js
- packages/standard-minifier-js/package.js
- packages/standard-minifier-js/plugin/minify-js.js
This is a stop-gap until #8378 is complete.
The error messages which come from UglifyJS tend to be quite cryptic, as
seen in issues like meteor/meteor#8370 or meteor/meteor#8020.  The file,
line, and column are provided, however the message is garbled and the
stacktrace long and acutely harrowing.  Since these errors are occurring
on automatically concatenated files, even the line number is sometimes
not helpful.  Additionally, sourceMaps are not available in production
builds, intentionally.  (I wasn't able to access them from
`file.getSourceMap()` or `file.sourceMap` at all.)
In addition to actually providing the name of the encapsulating file,
which provides _some_visibility, this commit implements a parser around
the UglifyJS error which detects the error and location information of …
> Improve minifiers to capture error from UglifyJS.

- packages/standard-minifier-js/package.js
This was only intended to be there during the publishing of
`standard-minifier-js` as part of meteor/meteor#8414 and is normally
not necessary as part of the `meteor publish-release` process.
> Remove version constraint from `standard-minifier-js`.

- packages/standard-minifier-css/package.js
It appears that an older version constraint was left in place during the publishing of `standard-minifier-css` which prevented it from getting the fixes included in https://github.com/meteor/meteor/pull/8048.
Since packages which depend on compiler plugins have their compiler built into them, this has prevented the new version from being released as was planned in ~#7523~ #8048.
This was mentioned in https://github.com/meteor/meteor/issues/7523#issuecomment-280930819
/cc @jeanfredrik
> Remove version constraint from minifier-css in standard-minifier-css.

- packages/ddp-rate-limiter/ddp-rate-limiter-test-service.js
- packages/ddp-rate-limiter/ddp-rate-limiter-tests.js
- packages/ddp-rate-limiter/ddp-rate-limiter.js
- packages/rate-limit/rate-limit.js
> Add callback to DDPRateLimiter.addRule, run after a rule is executed

- packages/accounts-facebook/notice.js
- packages/accounts-github/notice.js
- packages/accounts-google/notice.js
- packages/accounts-meetup/notice.js
- packages/accounts-meteor-developer/notice.js
- packages/accounts-twitter/notice.js
- packages/accounts-weibo/notice.js
Hi guys - this PR is intended to help address issue #8366. We shouldn't be showing the "you didn't install the accounts configuration UI" warning if an app is already using `service-configuration`. Thanks!
> Prevent accounts configuration UI warning from showing when using service-configuration.

- packages/ddp-client/livedata_connection.js
Hi all - this PR is intended to help resolve #8435, by adding in the missing `options.throwStubExceptions` jsdoc line. Thanks!
> Added missing docs for Meteor.apply's options.throwStubExceptions.

- tools/runners/run-app.js
This is a developer experience (DX) change.
In production, the `METEOR_SETTINGS` environment variable is used to
pass parameters which will be available in the `Meteor.settings` within
the app.  However, `METEOR_SETTINGS` is ignored when using the
`meteor-tool` itself as in development, environment variables are
often less desirable.  Additionally, there would be no reactivity when
changing settings was necessary, instead requiring that the `meteor`
tool be restarted entirely.
On more than one occasion, developers have been confused as to why the
`METEOR_SETTINGS` are not respected in development.  To make it more
clear when this is attempted (and clarify that they will _not_ be used),
provide the a clear warning before ignoring the `METEOR_SETTINGS`
variable.
Aims to avoid …
> [dx] Provide warning when `METEOR_SETTINGS` are used in development.

- packages/webapp/webapp_server.js
As per the comment on line 653, this appears to be the best (only?) way to let users do things like set up a custom error page to catch app-rendering-time exceptions.
This purports to solve [#8402](https://github.com/meteor/meteor/issues/8402)
> Export "app"

- tools/isobuild/meteor-npm.js
We now check `package.json` (thanks to bcffe53d14463322109baa4eb2632ed15a4cd3e8) in order to help make an educated decision as to whether or not a package has binary dependencies which need to be rebuilt.  In some cases, such as the `npmconf` npm which is included as a dependency of `flow-router`, a [`package.json` used as a test fixture](https://github.com/npm/npmconf/blob/master/test/fixtures/package.json) exists but is empty.  We should silently permit this.
Fixes meteor/meteor#8427
> Allow incorrect `package.json` when determining binary dependencies.

- packages/shell-server/package.js
- packages/shell-server/shell-server.js
Fixes #8290.
Do we need a test for this?  I think it's pretty unlikely that someone will regress this unintentionally.
> Shell: Don't be confused by SyntaxErrors thrown by command execution.

- Contributing.md
- Development.md
- README.md
The current edition of [Contributing.md](https://github.com/meteor/meteor/blob/devel/Contributing.md) is great in that it's beginning to offer a lot of information on the various ways to contribute to Meteor aside from just code contributions including Issue Triaging, PR help, etc.
It falls a bit short when it comes to actual development though as there is also quite a bit that is undocumented in that aspect.  There's a bit of a section on [running Meteor tests](https://github.com/meteor/meteor/blob/devel/Contributing.md#running-tests-on-meteor-core), but aside from the "[Slow start for developers](https://github.com/meteor/meteor/#slow-start-for-developers)" section of the `README.md` there isn't much breaking down the nitty gritty – what a dev bundle is, how you run specific tests, …
> `Development.md`: How to Develop Meteor Itself

- packages/mongo/mongo_driver.js
- packages/mongo/package.js
- packages/npm-mongo/.npm/package/npm-shrinkwrap.json
- packages/npm-mongo/package.js
> Bump mongodb driver to 2.2.24

- packages/force-ssl-common/.npm/package/.gitignore
- packages/force-ssl-common/.npm/package/README
- packages/force-ssl-common/.npm/package/npm-shrinkwrap.json
- packages/force-ssl-common/README.md
- packages/force-ssl-common/force_ssl_common.js
- packages/force-ssl-common/force_ssl_tests.js
- packages/force-ssl-common/package.js
- packages/force-ssl/README.md
- packages/force-ssl/force_ssl_both.js
- packages/force-ssl/force_ssl_common.js
- packages/force-ssl/force_ssl_server.js
- packages/force-ssl/package.js
Hi all - this PR is intended to help address issue #6120 (updating `force-ssl` to work with the `forwarded` header (see [RFC 7239](https://tools.ietf.org/html/rfc7239)), falling back on `x-forwarded-for` and `x-forwarded-proto`). I know there has been some discussion lately about whether or not it makes sense to use `force-ssl`, but for now it's still supported / included in core (hence these updates).
A few quick notes about these changes:
- To wire this up, I've leveraged the [`forwarded-http`](https://www.npmjs.com/package/forwarded-http) npm package. This package will look for any `*forwarded*` headers, then combine them all into a nice and clean forwarded object. This simplifies the `force-ssl` code a fair bit.
- I've included tests for the new `isLocalConnection` and …
> Adjusted force-ssl to work with the forwarded header (RFC 7239).

- tools/fs/files.js
#Windows has no concept of the executable bit so it is not applied by the `fstream` `Reader` when building the tarball which is used in both `meteor build` and `meteor deploy`.  For Windows users, this causes important scripts (such as `node-pre-gyp`) to not be executable when the bundles are deployed to Unix platforms (such as Galaxy).
To avoid giving every file executable bits, this applies an executable bit to the file only if it has read permission (something Windows _is_ aware of) and if it is in a location that Node bin links are typically placed, the `/node_modules/.bin/` directories.
Additionally, to apply a slightly more conservative approach to the existing logic (which applied executable bits to all directories), this changes that logic to only apply the executable bit to …
> Ensure that `.bin` files maintain executable bits in Windows bundles.

- packages/email/.npm/package/npm-shrinkwrap.json
- packages/email/email.js
- packages/email/email_tests.js
- packages/email/package.js
I wrote this patch to fix #8425, namely, to fix how long header lines get encoded.  Main discussion is there.
* Switch from mailcomposer 0.1.15 -> 4.0.1 (latest, still MIT license).
* Switch from simplesmtp (which only supports mailcomposer 0.1) to smtp-connection (which supports any mail composer).
* Use smtp-connection@2 (instead of latest) which shares nodemailer-shared codebase with mailcomposer 4.0.1.
* Add test for long header lines (the original bug being fixed here)
* Add extra test for HTML + text messages
* Document some extra options arguments supported by new mailcomposer.  (I didn't add [them all](https://github.com/nodemailer/mailcomposer/blob/v4.0.1/README.md#e-mail-message-fields) -- let me know if I should, or link to that in some way...)
> Upgrade to mailcomposer@4 and smtp-connection@2

- tools/meteor-services/deploy.js
This simple fix prevents the disappointment of trying to deploy your app
but failing because there's a space on the end of the `DEPLOY_HOSTNAME`
environment variable.
`process.env` always contains string values and assigning a property on
`process.env` implicitly converts the value to a string so it should not
be necessary to check if `typeof` is a `string`.
Fixes Dev Experience.
> Automatically trim `DEPLOY_HOSTNAME` of leading/trailing spaces.

- meteor
- scripts/dev-bundle-tool-package.js
- tools/fs/files.js
This PR addresses the following `EXDEV` error (#7852) that consistently happens for me when running `meteor build` inside a Docker container.  (see https://github.com/meteor/meteor/issues/7852#issuecomment-284925574 for my reproduction steps)
```sh
Error: EXDEV: cross-device link not permitted, rename '/opt/meteor/dist/bundle' -> '/opt/meteor/dist/bundle-garbage-1vn2pov'
at Error (native)
at Object.fs.renameSync (fs.js:681:18)
at Object.wrapper [as rename] (/tools/fs/files.js:1535:35)
at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:965:11)
at Builder.complete (/tools/isobuild/builder.js:690:13)
at /tools/isobuild/bundler.js:2529:13
at /tools/isobuild/bundler.js:2436:7
at /tools/isobuild/bundler.js:2837:22
at /tools/utils/buildmessage.js:271:13
at [object …
```
> use fs.move() from fs-extra to fix EXDEV cross device error in docker builds (issue 7852)

- circle.yml
- tools/fs/files.js
- tools/static-assets/server/mini-files.js
Presently, the renaming of directories that are in-use will fail on Windows.  This is already compensated for when `process.platform` is
set to `win32`.  However, within [BashOnWindows](https://github.com/Microsoft/BashOnWindows)/WSL (Windows Subsystem for Linux), `process.platform` is equal to `linux`, though the underlying filesystem is still the same and subject to similar limitations.
Microsoft has stated that it is [unlikely that they will remove "`Microsoft`"](https://github.com/Microsoft/BashOnWindows/issues/423#issuecomment-221627364) from the `os.release()` value so this checks for that in a similar fashion to how we used to check for `process.platform === "win32"`.  Also, this change causes `EACCES` to be tolerated in the same was as `EPERM` was already.  (`EACCES` is another …
> Be more understanding of Windows' filesystem limitations.

- packages/minifier-js/.npm/package/.gitignore
- packages/minifier-js/.npm/package/README
- packages/minifier-js/.npm/package/npm-shrinkwrap.json
- packages/minifier-js/minifier.js
- packages/minifier-js/package.js
- packages/standard-minifier-js/plugin/minify-js.js
This gives us all the benefits of @sethmurphy18's great work without the additional performance hit of using Babili for everything.
With this commit:
```sh
% meteor create min-test
% cd min-test
% time meteor build ../min-build
meteor build ../min-build  39.26s user 5.49s system 112% cpu 39.647 total
```
Without this commit:
```sh
meteor build ../min-build  59.28s user 5.23s system 107% cpu 1:00.08 total
```
Keep in mind this is the best-case scenario for Babili (a very small app). Larger apps take much longer for Babili to minify.
cc @abernix @glasser @sethmurphy18
> Use UglifyJS when possible, but fall back to Babel.minify.

- packages/accounts-base/accounts_server.js
- packages/accounts-password/password_tests.js
The issue was with _.extend overriding two documents (a token filter by reason and a time filter) with the same key ($or). Put the two filters in an ($add) to solve the issue, and added two tests to ensure no interference between those two.
Fixes #8218
> [fix #8218] cleaning up reset tokens also cleans up enroll tokens

- meteor.bat
In Unix we support adding `TOOL_NODE_FLAGS` when debugging the Meteor
tool itself, however Windows did not currently support it.  This should
add that support.  As this is a .bat file, I have every reason to
believe that this syntax should work on older versions of Windows as the
syntax of .bat files hasn't changed much, but I only tested on Windows 10.
Helps with meteor/meteor#8513.
> Add TOOL_NODE_FLAGS support for Windows in the same way as Unix.

- packages/accounts-base/accounts_common.js
- packages/accounts-password/password_server.js
User account enumeration is a security concern for *some* people. In our bug bounty program @LegalRobot, we've had 17 different reports on user enumeration. It got annoying, so we started using this code in local forks of accounts-core and accounts-password but are now happy to share this with the community. This PR addresses some of the simpler attack vectors: different error messages returned from the server upon various login failures or pw reset failures. 
By default, we leave the existing behavior alone but provide a simple mechanism to enable this by setting the ```ambiguousErrorMessages``` key to ```true``` in Accounts.config on the server, like this:
```
Accounts.config({
ambiguousErrorMessages: true
})
```
Enabling this option sends the same, rather ambiguous, error message to …
> Add ambiguous error messages option to Accounts config

- meteor.bat
- scripts/windows/download-dev-bundle.ps1
This resolves a rare situation which could occur when the extraction of the `dev_bundle.tar` (the latter half of the [7-zip extraction pipe in `download-dev-bundle.ps1`](https://github.com/meteor/meteor/blob/devel/scripts/windows/download-dev-bundle.ps1#L44)) fails with an unexpected end-of-file (EOF) error, but the publish tool continued as if the file was fine.  Ultimately, (from what I understand) the error preference (`$ErrorActionPreference = "Stop"`) set in the PS1 script is only observed in the case of PowerShell ErrorLevel (on PowerShell cmdlets) and not just an error condition encountered on an arbitrary command.
This error condition occurred to me during the publishing of Meteor `1.4.4-rc.4`.  Since the error was not caught, it resulted in the publishing of an `rc.4` for Windows …
> Detect dev_bundle download errors and fail appropriately on Windows.

- packages/accounts-google/google.js
- packages/accounts-google/package.js
- packages/google-oauth/google_client.js
- packages/google-oauth/google_server.js
- packages/google-oauth/google_sign-in.js
- packages/google-oauth/namespace.js
- packages/google-oauth/package.js
- tools/cordova/README.md
Addresses #8253.
This implementation makes heavy use of https://www.npmjs.com/package/cordova-plugin-googleplus and takes loose inspiration from https://github.com/sujith3g/meteor-cordova-google-plus.
I have not yet figured out exactly how we should bump the version numbers, or whether a new `google-sign-in` package should be created (instead of modifying `google-oauth`).
cc @ramezrafla @realyze @stubailo
> [Work in Progress] Support Google Sign-In in google-oauth package.

- scripts/dev-bundle-tool-package.js
- tools/fs/files.js
This is a follow-up to meteor/meteor#8491 which worked properly on Unix platforms, but failed in a variety of ways on Windows due to its lack of Fiber-awareness and desire to create symlinks as unprivileged users (something not always possible on Windows).
The Fiber issue was observed when trying to remove "src" directories within the `move` function (which tries a variety of OS/OS/arch-specific techniques to accomplish its goal) after they had been copied to "dest".  On Windows, this resulted in `EDIRNOTEMPTY` errors since Windows appears to temporarily cache the file-handle or doesn't release the file-handle until the next tick.
The symlink issue will hopefully improve in an upcoming release of Windows (Creator Edition) when Microsoft makes it possible to create symlinks as an …
> Improve `fs-extra`s `move` calls for Windows platform.

- packages/mongo/collection.js
- packages/mongo/mongo_livedata_tests.js
Hi all - this PR is intended to help resolve #6599. Currently when a `{ _id: falsey }` selector is passed into the `Mongo.Collection._rewriteSelector` function, a new selector is returned with an auto-generated string `_id`. This causes a problem if a Collection has been configured to use a `options.idGeneration` value of `MONGO`, meaning `Mongo.ObjectID`'s should be used for `_id`'s. These changes allow a fallback ID of any type (string or ObjectID) to be passed into `Mongo.Collection._rewriteSelector`, that will be used instead of the auto-generated string `_id`, if present. I've then updated the main source of this problem, `Mongo.Collection.prototype.update` (when upserting), to make sure a proper fallback ID of either string or `ObjectID` type is passed into …
> Adjust Mongo.Collection._rewriteSelector to allow a custom fallback _id.

- packages/accounts-password/email_tests.js
- packages/accounts-password/email_tests_setup.js
Hello,
In order to reproduce the following issue https://github.com/meteor/meteor/issues/8532 I updated the tests but I couldn’t reproduce the bug.
Unless I am mistaken, it seems there is no issue when calling the `Accounts.verifyEmail` for the same mail in upper case because the verification token is correctly removed and the email is marked as _verified_.
Regards
> [TEST] Updating tests for accounts-password

- tools/isobuild/meteor-npm.js
- tools/tests/npm.js
Previously, we captured and displayed shorter error messages for the
more complicated and unnecessarily verbose messages which npm produced.
While updating npm to 4.4.4, I observed the changelog for 4.4.0
indicated it would now produce less verbose messages.  In searching for
possible Meteor conflicts with this, I discovered that
`installNpmModule` had already regressed on providing pretty messages.
This fixes those messages to be parsed properly and adds tests which
ensure if npm changes again that we can capture them.
Follows-up on: https://github.com/meteor/meteor/pull/8562
> Update `installNpmModule` to properly capture newer `npm` error formats.

- packages/tracker/tracker.js
`inFlush` indicates wether a flush is active or not. Slightly the same like `Tracker.active` with one big difference. `Tracker.active` gets unset inside `Tracker.nonreactive`.
I want to savely call `Tracker.flush()` without getting the `Can't call Tracker.flush while flushing` error.
`Tracker.active` doesn't work for me, since I don't know if the flush was called inside `Tracker.nonreactive`. I think I need to access the `inFlush` variable to get the global flushing state.
Background:
I'm writing a package to connect reactive data to react components. In direct comparison with `react-meteor-data`, I want to reduce the reruns of the reactive function if the props of the component change. To avoid unnecessary renders, I'm calling `Tracker.flush()` inside of `componentWillReceiveProps` to …
> add function to expose tracker inFlush variable

- scripts/dev-bundle-tool-package.js
- tools/fs/files.js
- tools/isobuild/builder.js
This proposes reverting/replacing #8491, which has been problematic in the 1.4.4 series of RCs, specifically on Windows.  More so, I believe that `fs-extra` could be overboard and we could go with a much more simple implementation to accomplish the goal of fixing cross-device copies.
Unfortunately, `fs-extra` is still not as perfect at handling various file system conditions as would be ideal.  It seemed sensical to try and use a library like this, however it turns out that the Meteor suite of file system functions performs better on Windows.  For example, `fs-extra` still tries to create symlinks as an unprivileged user – a forbidden task on Windows unless running as Administrator.
In addition, I ran into a constant stream of other errors: `ENOTEMPTY`, `EBUSY`, `EEXIST` and `EPERM` (on …
> Recommendation to switch `fs-extra` for an alternate implementation.

- History.md
The previously documented `vNEXT` changes are now on the 1.4.4 release.
This change reflects that!
:tada:
> Update `History.md` for Meteor 1.4.4 release.

- History.md
- packages/babel-compiler/babel-compiler.js
- packages/babel-compiler/package.js
- packages/ecmascript/package.js
- packages/meteor-tool/package.js
- scripts/admin/meteor-release-experimental.json
- scripts/admin/meteor-release-official.json
- tools/fs/files.js
Removing garbage directories asynchronously in `files.renameDirAlmostAtomically` (my idea, mea culpa) would have been a nice optimization if it had worked, but (in addition to leaving garbage directories lying around sometimes if the process was killed), it appears to have some unintended consequences for `meteorNpm.rebuildIfNonPortable` and related functions, since the garbage directories are easily confused for npm package directories.
Example stack trace:
```
Error: ENOENT: no such file or directory, open '/home/travis/build/meteor/galaxy-server/node_modules/heapdump-garbage-1c2jqib/package.json'
at Error (native)
=> awaited here:
at Promise.await (/home/travis/.meteor/packages/less/.2.7.9.9fh5c1++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node …
```
> Release 1.4.4.1

- packages/minimongo/minimongo.js
- packages/minimongo/minimongo_tests.js
- packages/minimongo/modify.js
- packages/minimongo/package.js
When Minimongo throws an error, most of the times, the field names are not present, making it a bit difficult to debug. Updated the error messages to include the field name for which it threw the error.
I did not create an issue for this as I think it was too trivial a change. If its not, please let me know and I will create one for discussion.
Thank you.
> Add the name of the field in the error

- History.md
- meteor
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/babel-compiler/package.js
- packages/modules/.npm/package/npm-shrinkwrap.json
- packages/modules/package.js
- scripts/dev-bundle-tool-package.js
Fixes #8595.
As long as the tests pass for this PR, we can re-release the `babel-compiler`, `ecmascript`, and `modules` packages without needing to publish a new Meteor release.
> Upgrade meteor-babel and reify to fix #8595.

- packages/google-oauth/google_server.js
- packages/google-oauth/package.js
Follow-up to https://github.com/meteor/meteor/pull/8588.
While testing #8588, I noticed that `request.serverAuthCode` was sometimes/always an empty string (on iOS, at least), so the `query` that was passed to `getServiceData` didn't have a usable `.code` property.
I then realized that the response from Google Sign-In already contains the tokens that would be returned from `getTokens`, so this PR avoids calling `getTokens` in that case, though it still shares most of the `serviceData` logic.
cc @realyze @ramezrafla @abernix
> Use tokens from Google Sign-In instead of calling getTokens.

- packages/email/.npm/package/npm-shrinkwrap.json
- packages/email/email.js
- packages/email/email_tests.js
- packages/email/package.js
* Most critically, use a pool instead of direct SMTP connection, to handle dropped connections and increase throughput, like mail module 1.1.  (#8591)
* New nodemailer's sendMail wants an options object, not a MailComposer object.  Luckily, a MailComposer object has a "mail" field that remembers the original options, so we can keep original behavior.
* However, we no longer support the mailComposer option set to a compiled MailComposer object (functionality that was briefly added in 1.2.0).
* nodemailer does SMTP URL parsing now automatically for us, simplifying code.
* Tests' outputs now end with additional "\r\n"
* Drop underscore package dependency (no longer needed)
> Switch to modern nodemailer 4, Node 4 version. Fix #8591

- packages/email/.npm/package/npm-shrinkwrap.json
- packages/email/email.js
- packages/email/email_tests.js
- packages/email/package.js
This PR simply cherry-picks the great work from @edemaine in 6d4562656641b3c1f6c4a79e6a3c60c61b0136d5 (PR https://github.com/meteor/meteor/pull/8605) into `master` for the official `email@1.2.1` release.  The changes include those already in the original PR, as outlined below:
* Switch to modern nodemailer 4, Node 4 version. Fix #8591
* Most critically, use a pool instead of direct SMTP connection,
to handle dropped connections and increase throughput,
like mail module 1.1.  (#8591)
* New nodemailer's sendMail wants an options object, not a MailComposer
object.  Luckily, a MailComposer object has a "mail" field that
remembers the original options, so we can keep original behavior.
* However, we no longer support the mailComposer option set to a compiled
MailComposer object (functionality …
> email@1.2.1

- packages/minimongo/helpers.js
- packages/minimongo/minimongo.js
- packages/minimongo/minimongo_tests.js
- packages/minimongo/modify.js
- packages/minimongo/validation.js
#5165 
This fixes issues with minimongo allowing updates with invalid field names. I started out by looking at $addToSet as per ticket, and then expanded to check on other modifiers. I also checked on insert which was handling this issue. 
I ran all the tests on server MongoDB to confirm consistent behavior.
> [Fix #5165] don't allow invalid field names

- tools/isobuild/bundler.js
- tools/tests/cordova-hcp.js
Hey,
quoting commit's message:
CORDOVA_COMPATIBILITY_VERSION_IOS or CORDOVA_COMPATIBILITY_VERSION_ANDROID allows to override compatibility version for a specified platform.
CORDOVA_COMPATIBILITY_VERSION_EXCLUDE provides a way of excluding a certain plugin from compatibility version calculation. You can pass several plugin names with ';'. For example: `CORDOVA_COMPATIBILITY_VERSION_EXCLUDE='cordova-plugin-crosswalk-webview;cordova-plugin-device'`
This addresses:
https://github.com/meteor/meteor/issues/7030
and somehow: https://github.com/meteor/meteor/issues/7183
Why **CORDOVA_COMPATIBILITY_VERSION_EXCLUDE**?
This can be used in many ways but the one crucial is crosswalk. Since it will no longer be developed https://crosswalk-project.org/blog/crosswalk-final-release.html this is crucial to …
> Implement CORDOVA_COMPATIBILITY_VERSION_IOS/ANDROID and EXCLUDE

- packages/babel-compiler/babel-compiler.js
Removes the leading slash from the `filename` and `sourceFileName` Babel options so that Babel plugins can distinguish relative paths from absolute paths.
I couldn't find out if the `filename` property is used somewhere in the Meteor build process but the `sourceFileName` is used in [tools/isobuild/bundler.js](https://github.com/meteor/meteor/blob/6a9f8b904425efce112103f3846d7a153f8988ca/tools/isobuild/bundler.js#L1245) where the removed slash is handled correctly.
Fixes #8566
> Remove leading slash from paths in Babel options

- packages/minimongo/minimongo.js
- packages/minimongo/minimongo_tests.js
- packages/minimongo/selector.js
- packages/minimongo/sort.js
#3599 
The goal was to match the behavior of $near in tests to Mongo as close as possible in tests. As such, all the tests I added or updated have been run on server Mongo before I started fixing the code. Here's the issues I discovered:
1. In Mongo, sort as an option [overrides $near sort completely](https://docs.mongodb.com/manual/reference/operator/query/near/#sort-operation) and does not use $near as a tie-breaker.
2. When using $near to query an array with an update, Mongo always uses the first matching index to update.
3. Mongo and MiniMongo differ in the behavior of observe and applying changes. This seemed out of scope and possibly not an issue for this ticket. 
4. Mongo does not throw an error on find with $near when it's not a top-level operator like "{$and:{$near". Instead, it …
> [#3599] match $near behavior in minimongo to mongo

- packages/reactive-dict/reactive-dict-tests.js
- packages/reactive-dict/reactive-dict.js
```js
var b = new ReactiveDict({b: true});
b.get('b') //throw (Error: EJSON.parse argument should be a string)
```
This is because `dict.set` stringify the value before settings it, which is not done when u initiate the dict with initial data.
> fix bug when initiating dict with non string values

- packages/facebook-oauth/facebook_server.js
This is a security measure that is opt-in but recommended by Facebook for securing access tokens. 
https://developers.facebook.com/docs/graph-api/securing-requests#appsecret_proof
> Added support for making secure graph api requests with appsecret_proof

- Development.md
Hi all - I've updated the `Development.md` doc with a small note explaining why `dev_bundle` PR tests initially fail, and how to request a new `dev_bundle` be built/published. Thanks!
> Added a small note explaining how to get dev_bundle changes published.

- packages/mongo/collection.js
- packages/mongo/mongo_livedata_tests.js
Hi guys - this PR fixes the issue identified in #8666. Mongo upserts are failing when an `undefined` selector is used. This functionality was allowed in previous versions of Meteor, but was changed (indirectly) in https://github.com/meteor/meteor/commit/f4e41cbf1bcb871d1a8e9a63d496bcb57233a8db. This change wasn't previously caught as the Mongo test suite doesn't have any tests for `undefined` selector upserts. I've included a new test to help prevent this from happening in the future. Thanks!
> Fixed broken upserts with undefined selectors (fixes regression in #8666).

- History.md
- packages/reactive-dict/migration.js
- packages/reactive-dict/package.js
- packages/reactive-dict/reactive-dict-tests.js
- packages/reactive-dict/reactive-dict.js
As per the discussion in #8643 I've changed the implementation of `ReactiveDict` to support setting initial data when creating a `ReactiveDict` with a name.
```js
const state = new ReactiveDict('applicationState', { currentRoute: 'home' });
```
This PR also fixes the issue brought up in #8643 by using `_setObject` which uses `set` to set the data and make sure it's stringified.
I also took the liberty to re-write `ReactiveDict` as an es2015 class.
/cc @hwillson, @abernix
> Add support for initial data alongside a name for ReactiveDict

- packages/non-core/bundle-visualizer/style.css
There was an issue where most of the visualizer was visible but the module size details displayed when hovering over a segment were hidden behind some UI elements. Setting a high z-index fixes it.
> Ensure visualizer displays on top of other UI

- packages/localstorage/localstorage.js
@benjamn, here you go. Maybe move the comment also inside the try/catch block?
This fixes #1291 again after it got reverted in the 1.5 branch by accident.
Accessing window.localStorage can immediately throw an error in IE and other/older webkit versions.
See https://github.com/meteor/meteor/pull/8327#issuecomment-302176415
> Move localStorage access back into try statement

- circle.yml
- tools/isobuild/isopack-cache.js
- tools/isobuild/isopack.js
- tools/tool-testing/selftest.js
- tools/utils/http-helpers.js
1a036553 in 1.4.4.2 expanded on the HTTP error checking added by 30aec9f in
1.4.2. Neither of these changes were aware that discoverGalaxy invokes
httpHelpers.request with json:true, resulting in a `body` that is a parsed JSON
object rather than a string or Buffer.  Before 1.4.4.2, this had no consequences
because body.length is undefined and `undefined < 90` is false, but the change
to Buffer.byteLength actually made the condition true.
It's safe to not check length in the JSON case because a truncated JSON object
is not legal JSON (unless the truncation just drops trailing whitespace, in
white case that's OK).
I check for both string and Buffer because some calls to this function pass in
an encoding option.  Buffer.byteLength works with both types.
> tools: fix Galaxy discovery

- History.md
I think it is cleaner in this way. Because now methods do have `this.connection` available.
cc @zimme
> Updating history a bit for #8629

- packages/email/.npm/package/npm-shrinkwrap.json
- packages/email/email.js
- packages/email/package.js
I've made two changes to the Email package:
1. Using a MAIL_URL of the form `smtp://...:465` now warns that there's probably a bug (protocol should be `smtps:`). `email@1` used to automatically force `smtps:` protocol when port was 465, so this warning is useful for upgraders, without getting in the way of people who Know What They're Doing.  In response to #8696 and some later comments on #8591.
2. I tweaked `node4mailer` slightly to work on even older versions of Node 4. In response to https://github.com/chriswessels/meteor-tupperware/issues/32
I tested the warning in both activating and nonactivating cases, and tested that sending multiple messages only causes one warning.  (In fact, if `MAIL_URL` changes multiple times, each one may cause a warning.  But this seems good.)
> Email package improvements

- History.md
- tools/isobuild/builder.js
- tools/tests/assets.js
The root of the problem was that the `es5-ext` npm package contains directories called `#`, e.g.
https://github.com/medikoo/es5-ext/tree/master/array/%23
These directory names were being sanitized to `''` and thus ignored when reserving paths in the `Builder`, which led to reservation conflicts later.
This commit fixes the problem in three different and independently sufficient ways:
* Use `files.mkdir_p` instead of `files.mkdir` when creating parent directories of written files.
* Replace illegal characters in sanitized paths with `_` instead of `''`.
* Allow `#` in sanitized paths (only needs to be escaped in the shell, not actually forbidden in paths).
Fixes #8761.
> Fix #8761 in three different ways.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Contributing.md
- IssueTriage.md
Hi guys - I've updated the repo templates and supporting docs to reference [meteor/meteor-feature-requests](https://github.com/meteor/meteor-feature-requests). Once we flip that repo to be public, we should be all set to merge these in. Let me know if you notice anything that should be changed. Thanks!
> Adjusted to add references to the new meteor/meteor-feature-requests repo

- tools/static-assets/server/boot.js
`vm`'s `runInThisContext` used to have an undocumented parameter to display error messages in executed code but this was actually changed to an `options`-style argument ages ago, in Node.js 0.11, via https://github.com/nodejs/node/commit/fd3657610e49005dfc778c3f060dbba0a34f286a.  Due to this change, and our lack of notice this "descriptive error message" was not displayed and the actual location of the error was quietly swallowed.
This reimplements the descriptive error message, which was also brought up by @d-schiffner in https://github.com/meteor/meteor/issues/3200#issuecomment-289685677.
> Change `runInThisContext` to `Script.prototype.runInThisContext`.

- packages/non-core/bundle-visualizer/package.js
- packages/non-core/bundle-visualizer/server.js
While this was helpful in one of the incarnations of the `bundle-visualizer` during development it isn't relevant anymore since the `.stats.json` will not be present in the bundle unless it was created by a recent version of `standard-minifier-js` which passed in `stats` (no older versions did this).
Removing this check will also make it possible for other minifiers to be used with `bundle-visualizer` without them also needing to fork make their own version.
Thusly, this makes the `bundle-visualizer` work with Meteor 1.6, which comes with `standard-minifier-js@2.2.x`.
> Remove check for standard-minifier-js@2.1.x from `bundle-visualizer`.

- packages/minimongo/minimongo_tests.js
- packages/minimongo/selector.js
This may not be a complete fix for issue #8775, but I noticed while debugging the issue that `LocalCollection._removeDollarOperators` isn't removing nested `$`-operators (as it seems like it should be): https://github.com/meteor/meteor/blob/d6c4281eebe8fffcdeb415ccc361784f854126f4/packages/minimongo/minimongo.js#L790
> Partial fix for #8775.

- meteor
- scripts/dev-bundle-tool-package.js
There have been a number of commits in [the history for `rimraf`](https://github.com/isaacs/rimraf/commits/master) which indicate other projects have also been struggling with ENOTEMPTY, specifically on Windows.
[This commit on `rimraf`](https://github.com/isaacs/rimraf/commit/d53235de863cfb00f691456288fcf3abbced7f6c), included in 2.6.1, takes a relatively aggressive approach but the absence of follow-up commits in a while leads me to believe that approach may have helped.
Of course, if Windows wants to cache a file handle after a process has stopped using it, that is its prerogative but the result is that tools (like Meteor) need to guess when it's safe to delete directories, which may still have cached file handles open on the OS, or try excessively (in the way this update to `rimraf` …
> Attempt to fix "ENOTEMPTY" by updating rimraf dependency.

- tools/isobuild/meteor-npm.js
If the comment just above the changed code is to be taken seriously, it was definitely a mistake to skip reinstalling any packages, even if their required versions have not changed, since we're populating a brand-new `node_modules` directory whose contents will dictate the new `npm-shrinkwrap.json` file.
Fixes #8732.
Should also fix #8747.
> Don't skip reinstalling unchanged Npm.depends-style dependencies.

- History.md
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/babel-compiler/babel.js
- packages/babel-compiler/package.js
- packages/minifier-js/.npm/package/npm-shrinkwrap.json
- packages/minifier-js/minifier.js
- packages/minifier-js/package.js
- scripts/dev-bundle-tool-package.js
Despite [my previous concerns](https://github.com/meteor/meteor/issues/6402#issuecomment-221042378), having `minifier-js` replace `process.env.NODE_ENV` with its string value seems to be the most direct way to guarantee production versions of React modules do not access `process.env.NODE_ENV` at runtime, and that any resulting dead code is removed.
Relevant [background](https://forums.meteor.com/t/new-react-devtools-check-if-your-production-build-is-really-in-production-mode/36199).
Fixes meteor/meteor#6402.
Fixes meteor/meteor-feature-requests#94.
> Inline process.env.NODE_ENV when minifying.

- History.md
- packages/accounts-password/email_templates.js
- packages/accounts-password/package.js
Currently, the default "from" address for `meteor-accounts` is
"no-reply@meteor.com".  While this works for many users, and granted it
is a "no reply" address and there should be no expectation of the
address working, it contributes to a negative spam rating for the
"meteor.com" domain and a surplus of extra e-mail.
The correct way to set the default "from" address is by setting:
```js
Accounts.emailTemplates.from = "Name <email@domain.com>";
```
As per the documentation here:
* https://docs.meteor.com/api/passwords.html#Accounts-emailTemplates
By changing it to "example.com", and making a more obvious "example"
out of the name ("Accounts Example"), it should encourage users to
actually change the address to something more reasonable especially
since many e-mail providers will also reject …
> Change default `from` email for `accounts-password` to an "example".

- History.md
- packages/mongo/mongo_driver.js
- packages/mongo/observe_changes_tests.js
This will use `bindEnvironment` on `observe` and `observeChanges` callbacks.
This will allow `Meteor.userId()` to be used within these callbacks.
See this conversation for background.
https://github.com/meteor/meteor/pull/8629#issuecomment-300084704
/cc @mitar
> Bind environment of observeChanges callbacks

- packages/accounts-password/package.js
- packages/npm-bcrypt/package.js
The `modules` package should not be pinned to the `0.7.5` release any longer.
These are published, but this PR will allow me to merge it to `master`.
/cc @benjamn
> Unpin `modules` from `npm-bcrypt`

- History.md
- packages/non-core/coffeescript/.npm/plugin/compileCoffeescript/npm-shrinkwrap.json
- packages/non-core/coffeescript/package.js
- packages/non-core/coffeescript/plugin/compile-coffeescript.js
Bumps the CoffeeScript version, and uses the new primary repo, `coffeescript`.
> Update CoffeeScript to 1.12.6

- tools/cli/commands.js
The CLI still printed out of date URLs, pointing towards the old Github wiki. I've replaced them with the new Meteor Guide URLs.
> Updated doc URLs

- packages/ddp-server/livedata_server.js
- packages/ddp-server/livedata_server_tests.js
- packages/meteor/errors.js
- packages/meteor/package.js
This is a possible implementation of something we discussed about a year ago here: https://forums.meteor.com/t/meteor-guide-methods/19662/34?u=aldeed
If any thrown error has `isClientSafe` set to `true`, it is cast into a `Meteor.Error` to be sent back to the client. I think an ideal implementation would not even reference `Meteor.Error` anywhere in the DDP code, but this is a simple, safe, backwards compatible solution for now.
The goal here is for NPM packages like [simpl-schema](https://github.com/aldeed/node-simple-schema) to be able to throw validation or other errors and have them sent back to the client call.
One question: Should it do the same thing for any sanitizedError that has `isClientSafe` set?
Closes https://github.com/meteor/meteor/issues/7305
> isClientSafe DDP errors

- packages/minimongo/minimongo_tests.js
- packages/minimongo/selector.js
Hi all - this PR is intended to fix https://github.com/meteor/meteor/issues/8794. The `LocalCollection._removeDollarOperators` changes introduced in PR https://github.com/meteor/meteor/pull/8776 have an unintended side effect of not allowing `MongoID.ObjectID`'s through intact. The `JSON.stringify` / `JSON.parse` combo isn't restoring the full `MongoID.ObjectID` object (since it's not JSON compatible).
This PR adjusts things a bit so we're working with the EJSON representation of `MongoID.ObjectID` (and other objects), when running through `LocalCollection._removeDollarOperators`.
> Adjust mongo upserts so MongoID.ObjectID's aren't filtered from queries.

- packages/jshint/plugin/lint-jshint.js
Hi all - sorry, there isn't an associated issue # with this PR, but I thought I'd fire it in regardless. This PR fixes the `jshint` linting errors that show up in the logs on every Travis run (or when running `./packages/test-in-console/run.sh` locally). For example, see the output of https://travis-ci.org/meteor/meteor/builds/244730834 starting on line 562:
These errors are coming from linting the `jshint` wrapper package itself. This PR adjusts the wrapper package to meet the configured linter requirements. Thanks!
> Adjusted the jshint package to meet its own linting requirements.

- History.md
- meteor
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/jshint/plugin/lint-jshint.js
- packages/modules-runtime/.npm/package/npm-shrinkwrap.json
- packages/modules/.npm/package/npm-shrinkwrap.json
- packages/test-in-console/run.sh
- scripts/admin/eslint/npm-shrinkwrap.json
- scripts/build-dev-bundle-common.sh
- scripts/ci.sh
- scripts/dev-bundle-tool-package.js
- scripts/generate-dev-bundle.ps1
- tools/isobuild/meteor-npm.js
This is a major update from npm 4.6.1, and should bring significant benefits in terms of speed and reproducibility of `npm install`s. Read the [blog post](http://blog.npmjs.org/post/161081169345/v500) for an introduction to those benefits.
To understand npm's new `package-lock.json` file format, I would highly recommend reading [this documentation](https://docs.npmjs.com/files/package-lock.json). Note especially that `npm-shrinkwrap.json` files are exactly the same as `package-lock.json` files, except that `package-lock.json` files cannot be published to npm.
For backwards compatibility, Meteor still works with `npm-shrinkwrap.json` files internally (for example, to manage `Npm.depends`-style dependencies), but that's perfectly fine because `npm-shrinkwrap.json` files have the same …
> Upgrade npm to version 5.0.3

- packages/boilerplate-generator/boilerplate-generator.js
- packages/server-render/.npm/package/.gitignore
- packages/server-render/.npm/package/README
- packages/server-render/.npm/package/npm-shrinkwrap.json
- packages/server-render/README.md
- packages/server-render/package.js
- packages/server-render/server-render-tests.js
- packages/server-render/server-render.js
- packages/webapp/package.js
- packages/webapp/webapp_client.js
- packages/webapp/webapp_server.js
- packages/webapp/webapp_tests.js
To support server-side rendering of any kind, it would be ideal if there was a way for server code to inject rendered HTML into the boilerplate HTML generated by packages like `static-html`. Until now, that hasn't been possible, since the only mechanism for adding dynamic HTML to the initial HTTP response was to modify `request.dynamicHead` and/or `request.dynamicBody`.
With this new API, it should now be possible to register callbacks that (for example) parse `boilerplate.baseData.body`, find DOM nodes by `id`, render HTML fragments, inject the fragments into the DOM, and set `boilerplate.baseData.body` to the resulting HTML string.
I previously thought this would require changes to the `boilerplate-generator` package, and thus we had to wait for #8820 to be finished, but it turns out we …
> Server-side rendering revamp

- History.md
- meteor
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/http/.npm/package/npm-shrinkwrap.json
- packages/jshint/plugin/lint-jshint.js
- packages/less/.npm/plugin/compileLessBatch/npm-shrinkwrap.json
- packages/less/package.js
- packages/modules-runtime/.npm/package/npm-shrinkwrap.json
- packages/modules/.npm/package/npm-shrinkwrap.json
- packages/stylus/.npm/plugin/compileStylusBatch/npm-shrinkwrap.json
- packages/stylus/package.js
- packages/test-in-console/run.sh
- scripts/admin/eslint/npm-shrinkwrap.json
- scripts/build-dev-bundle-common.sh
- scripts/ci.sh
- scripts/dev-bundle-tool-package.js
- scripts/generate-dev-bundle.ps1
- tools/isobuild/meteor-npm.js
- tools/tests/apps/modules/node_modules/repl/index.js
- tools/tests/apps/modules/package-lock.json
- tools/tests/apps/modules/packages/modules-test-package/.npm/package/npm-shrinkwrap.json
- tools/tests/apps/modules/packages/modules-test-package/client.js
- tools/tests/apps/modules/packages/modules-test-plugin/.npm/package/npm-shrinkwrap.json
- tools/tests/apps/modules/packages/modules-test-plugin/.npm/plugin/compile-arson/npm-shrinkwrap.json
- tools/tests/apps/modules/tests.js
- tools/tests/compiler-plugins.js
- tools/tests/hot-code-push.js
- tools/tool-testing/selftest.js
This PR takes the place of https://github.com/meteor/meteor/pull/8831, which was prematurely merged and closed by @benjamn.
This is a major update from npm 4.6.1, and should bring significant benefits in terms of speed and reproducibility of `npm install`s. Read the [blog post](http://blog.npmjs.org/post/161081169345/v500) for an introduction to those benefits.
To understand npm's new `package-lock.json` file format, I would highly recommend reading [this documentation](https://docs.npmjs.com/files/package-lock.json). Note especially that `npm-shrinkwrap.json` files are exactly the same as `package-lock.json` files, except that `package-lock.json` files cannot be published to npm.
For backwards compatibility, Meteor still works with `npm-shrinkwrap.json` files internally (for example, to …
> Upgrade npm to version 5.0.3 (take 2)

- packages/accounts-facebook/package.js
- packages/facebook-oauth/facebook_client.js
- packages/facebook-oauth/package.js
The most recent version of the API is Version 2.9, which was introduced on April 18th, 2017 https://developers.facebook.com/docs/apps/changelog
The url parameters are not changed with the new version https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
Fixes https://github.com/meteor/meteor/issues/8856
> Update Facebook api version in loginUrl

- Development.md
Hi all - just a small housekeeping PR; In the `Development.md` doc we mention how to filter `self-tests`'s to control which tests are run, but don't mention how fine-grained test filtering can be handled with `meteor test-packages`. This PR adds in a quick mention of `TINYTEST_FILTER`, along with a small example. Thanks!
> Added mention of how to use TINYTEST_FILTER to filter which tests are run.

- tools/fs/safe-watcher.js
- tools/tests/compiler-plugins.js
- tools/tests/cordova-plugins.js
- tools/tests/hot-code-push.js
- tools/tests/package-tests.js
- tools/tests/run.js
This restores the behavior of 8c70716954f8fcdd02fc0c673a39da2b7186ce2b by default, with the option of disabling the prioritized file watching system by setting `METEOR_WATCH_PRIORITIZE_CHANGED` explicitly to `"false"`.
The self-tests where the environment variable is explicitly set form a nice to-do list of tests that should be improved to be more robust to cope with differences in file watcher timing.
Helps with #8648 and similar issues.
> Make METEOR_WATCH_PRIORITIZE_CHANGED opt-out instead of opt-in.

- tools/cli/commands.js
If I have a directory `test-app` with `packages` subdirectory, and I run outside `test-app` directory `meteor create --bare test-app` it fails on `files.stat` because `files.stat('packages')` is run outside `test-app`, and it does not exist there.
> filePath is relative to appPath

- History.md
- scripts/build-dev-bundle-common.sh
https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
> Upgrade Node to 8.1.4, fixes CVE-2017-1000381

- meteor
- tools/utils/gc.js
Tests have been [failing](https://circleci.com/gh/meteor/meteor/4536#tests/containers/2) recently on the `master` branch because the `./meteor self-test create` test runs out of memory.
The `release-1.6` branch contains a few commits that successfully limit memory usage by forcing garbage collection periodically (throttled to once every 500ms).
This PR back-ports those commits to `master`, which I hope will fix the failing tests.
> Enable throttled garbage collection (borrowed from release-1.6).

- packages/accounts-password/password_server.js
- tools/tests/apps/dynamic-import/.meteor/packages
- tools/tests/apps/dynamic-import/.meteor/release
- tools/tests/apps/modules/.meteor/packages
- tools/tests/apps/modules/.meteor/release
To allow easier customization email sending of tokens.
More or less just moving code around.
A new version of #8065 and #8038.
> Refactored reset password and enroll account methods

- tools/cli/commands.js
- tools/tests/command-line.js
Hi all - this PR is intended to fix https://github.com/meteor/meteor/issues/8897. The `test-packages` command `--test-app-path` parameter expects the specified directory to already exist. If it doesn't, an error is thrown. The changes in this PR create the specified directory if it doesn't already exist (and adds a few extra safeguards, like handling user permission errors, cases where the `test-app-path` already exists as a file instead of a directory, etc.). It also adds `self-test`'s for `--test-app-path` functionality. Thanks!
cc @mitar
> Adjust test-packages --test-app-path to create the directory if missing

- History.md
- packages/accounts-base/accounts_common.js
- packages/accounts-base/accounts_tests.js
- packages/accounts-base/package.js
This pull request fixes #5121.
I also add a test for this fix, and a few other tests for related functionality. These tests didn't already exist because it was difficult to test Accounts configuration as the `Accounts.config` method modified global state.
> Fix disabling of token expiration

- packages/npm-mongo/.npm/package/npm-shrinkwrap.json
- packages/npm-mongo/package.js
Meteor 1.4.3.2 upgraded npm mongo to 2.2.24 in order to fix an issue
with MongoDB arbiter login attempts, see Meteor issue 8449 and Meteor
1.4.3.2 changelog.
But the MongoDB upstream fix was incomplete.
This commits upgrades npm mongo further to 2.2.29 in order to get the
fix for the related arbiter login issue NODE-981 on the MongoDB Jira,
which requires `mongo-core@>=2.1.10`, which requires `mongodb@>=2.2.26`;
see references below.
References:
- Meteor issue 8449: <https://github.com/meteor/meteor/issues/8449>.
- Meteor 1.4.3.2: <https://github.com/meteor/meteor/blob/devel/History.md#v1432-2017-03-14>
- NODE-981 in MongoDB Jira: <https://jira.mongodb.org/browse/NODE-981>
- mongodb-core 2.1.10 changelog: <https://github.com/christkv/mongodb-core/blob/2.0/HISTORY.md#2110-2017-04-18>,
- …
> npm-mongo: Upgrade to npm mongo@2.2.30 to fix arbiter login attempts

- tools/tests/colon-converter-tests.js
- tools/tests/linter-plugins.js
- tools/tests/package-tests.js
These changes should help with the recent (common) increase in the number of Circle build failures. With these adjustments I'm now seeing successful builds (with Ubuntu 14.04) in my own Circle environment, and very few failure retries. I'm sure we'll need to tweak further, but these changes should help get the tests working for the pending PR's. Thanks!
> Adjust self-test match / timeout settings to help reduce Circle test failures

- packages/ejson/ejson.js
- packages/ejson/ejson_test.js
- packages/minimongo/selector.js
- packages/mongo/collection.js
- packages/mongo/mongo_driver.js
- packages/mongo/mongo_livedata_tests.js
- tools/tests/command-line.js
- tools/tests/releases.js
Fixes: https://github.com/meteor/meteor/issues/5652
Background (kudos to: https://github.com/meteor/meteor/issues/5652#issuecomment-157544912 for pointing in the right direction):
Meteor multiplexes/re-uses duplicate observers. For fast look-up of duplicate observers it creates a hash with some properties of the cursor (e.g. selector, projection, ...).
However, for this hash it simply uses `JSON.stringify` ( https://github.com/meteor/meteor/blob/a4de554a95455e91b5d7e71c4c611c2e78725d5e/packages/mongo/mongo_driver.js#L1221 ) , which can not stringify regular expressions. This leads to a problem where different queries would re-use the same (wrong) observer.
However, this selector has already passed the `Mongo.Collection._rewriteSelector` …
> Handle regular expressions in EJSON

- tools/isobuild/bundler.js
Fixes #8927 
The problem was introduced in 1.5-beta.3 and results in source maps being out by one line for each file containing source maps (e.g. produced by Typescript compiler).
The change keeps the line rather than removing it, but unlike the original change (before 1.5-beta.3) it doesn't add add the slash slash comment (//) as I can't see where that would be needed (other than in a multi-line back tick string - but that case is broken anyway).
It does retain tying the match to the start of a line (introduced in 1.5-beta.3), though I did consider whether the expression would be simpler using multi-line mode:  `/^\/\/# sourceMappingURL=.+/gm`
> Avoid adjusting line counts when removing source map comments.

- scripts/dev-bundle-server-package.js
- scripts/dev-bundle-tool-package.js
The currently used version of semver does have a medium-level security issue. Therefore, the dependencies of `meteor-dev-bundle` had been updated.
|            | Regular Expression Denial of Service   |
| ---------- | -------------------------------------- |
| Name       | semver                                 |
| CVSS       | 5.3 (Medium)                           |
| Installed  | 4.1.0                                  |
| Vulnerable | <4.3.2                                 |
| Patched    | 4.3.2                                  |
| Path       | meteor-dev-bundle@0.0.0 > semver@4.1.0 |
| More Info  | https://nodesecurity.io/advisories/31  |
> updated dependency of semver to the latest version

- tools/fs/safe-watcher.js
Hi all - this PR fixes issue #8942. If the following scenario happens in an app
1. `test1.html` is created.
2. `test1.html` is copied to `test2.html`.
2. `test2.html` is moved/renamed to `test3.html`.
further changes made to `test3.html` will not be picked up by the Meteor Tool, as there is no file watcher created to watch for `test3.html` changes. The reason for this is:
- When `test1.html` is copied into `test2.html`, a new watcher is created and stored in [`entriesByIno`](https://github.com/meteor/meteor/blob/devel/tools/fs/safe-watcher.js#L235) with the inode of `test2.html` serving as the key.
- When `test2.html` is moved/renamed to `test3.html`, the `entriesByIno` Map is first checked ([here](https://github.com/meteor/meteor/blob/devel/tools/fs/safe-watcher.js#L80)) to see if an …
> Adjust the previous watcher check to handle moved files

- tools/tests/modules.js
Circle builds on `devel` are currently failing (and have now many times in a row) because of `modules - test app` self-test failures (outside of the segfaults):
```
modules: modules - test app ... 
... fail!
... retrying (2 tries remaining) ...
... fail!
... retrying (1 try remaining) ...
... fail!
=> match-timeout at ../../../tools/tests/modules.js:28
=> Pattern: App running at
=> Last 100 lines:
2| => Running Meteor from a checkout -- overrides project version (Meteor 1.5.1)
```
I SSH'd into Circle and ran some direct tests, incrementally increasing the `modules - test app` wait time until it passed. 120 seconds seems to work well, so I've added that here. Thanks!
> Increase "modules - test app" self-test wait time to fix Circle

- packages/ejson/ejson.js
Little follow-up PR for https://github.com/meteor/meteor/pull/8821 to avoid the potential DOS-abuse spotted by @abernix https://github.com/meteor/meteor/commit/5e2aa5c6590431e19cabdc33ad312dcfd28f1835#commitcomment-23313310
> Cut of regex flags in ejson parser to avoid abuse

- tools/cli/commands-packages.js
- tools/cli/help.txt
Add 'meteor list --tree' to show a tree of package dependencies.
There's also a --weak command line option which when specified shows weak dependencies.
See feature request: https://github.com/meteor/meteor-feature-requests/issues/143
With the basic `meteor list --tree` it gives output very much like `npm list` (example below).
At the top level are the constraints from the .meteor/packages, and then for each of those it outputs the (strong) dependencies of each, expanding recursively.
Subsequent references of a package do not get expanded again. This avoids infinite recursion and an excessive amount of repetitive output.
Weak references can be show by also specifying the `--weak` option, but this never follows weak references. As any weakly referenced package which is present must also …
> Add 'meteor list --tree' to show a tree of package dependencies.

- tools/cli/commands-packages.js
@klaussner spotted that I'd added more uses of the 'package' reserved word in https://github.com/meteor/meteor/commit/96db56b0bae5168fa852eead7cbf0131a12c0ec8
Whilst it doesn't appear to cause a problem, and there are other uses in the constraint solver, this change removes the new uses.  Thanks @klaussner.
> Avoid new uses of 'package' as it is apparently a reserved keyword.

- tools/meteor-services/auth.js
- tools/tests/login.js
Previously if you have no `.meteorsession` (first time login), and you run `meteor deploy` and you enter an incorrect password, it would spiral into an infinite loop of printing `Login failed` (and re-sending the same failed credential to Galaxy over and over again).
This fixes that by clearing the password before retrying, and adds a test.
> Clear credentials before retry on initial `meteor deploy` password failure.

- packages/minimongo/minimongo_tests.js
- packages/minimongo/selector.js
Fixes #5301 
Currently when functions are (mistakenly?) passed as a part of a selector object in a minimongo query on the client, no results are matched.
However, the same query on the server ignores any part of the selector object which is a function and returns whatever matches the other parts of the selector. This behavior seems to come from the node mongodb driver.
As discussed in #5301, even though the client behavior might be more logical, the proposed solution is to change it to match the server for consistency.
I explored some of the relative behaviors on the server and client when functions are passed in this [repro](https://github.com/jamesmillerburgess/meteor-issue-5301), but I didn't find anything else. I certainly didn't explore every possible way functions could be passed, …
> Adjust minimongo behavior to match server when functions are in selectors

- tools/cli/commands.js
- tools/cli/help.txt
- tools/meteor-services/deploy.js
In the course of looking at another issue I:
* Removed `meteor claim` which is no longer a supported command.
* Removed checks for `protection` of type `password` which @glasser confirmed (verbally) was no longer supported by the Galaxy API.
* Updates to newer ECMAScript language `import` and `export`s.
* ~_Mostly_ r~Removes `underscore` in lieu of native ECMAScript
May be be best reviewed commit by commit and I recommend **not**-squashing for posterity.
> `meteor deploy` cleanup and partial modernization

- History.md
- tools/isobuild/bundler.js
- tools/isobuild/meteor-npm.js
This makes it possible to know exactly which version of Node.js and npm were used by the `meteor` tool which the bundle was built from by making new values available alongside the existing `meteorRelease` value in `star.json`: `nodeVersion` and `npmVersion`.  The version of the `star.json` has remained the same since this is only adding new properties, not removing any existing.  This preserves the existing `.node_version.txt` for compatibility reasons, but it's reasonable to believe that may be deprecated in a future version.
Those using `.node_version.txt` should consider using the `nodeVersion` value in `star.json`, though it should be noted that it does not include the `v`(ersion) prefix as the `.node_version.txt` file did.
> Include the Node.js and npm version in the `star.json` manifest.

- scripts/build-dev-bundle-common.sh
This is a re-open of @skirunman's #8911 which wasn't on a branch and thus I wasn't unable to make changes to the PR at all (to build a dev bundle).
---
Install latest version of MongoDB 3.2.x by default.
> Update to MongoDB  v3.2.15

- Development.md
- History.md
- scripts/ci.sh
- tools/tool-testing/selftest.js
**Note:** Targeted for `release-1.6`, because of the dependency on #8976.
---
This uses the same new facilities which were created for auto-installing Cordova (#8976) to also auto-install PhantomJS and BrowserStack WebDriver npms into their appropriate home in the dev bundle when they're needed for running self-tests.
Gloriously, this means if you're constantly changing between dev bundles, you'll no longer need to take the extra step of doing so each time. 🙌
> Auto-install `meteor self-test` dependencies upon use.

- packages/babel-compiler/babel-compiler.js
- tools/tests/apps/modules/.babelrc
- tools/tests/apps/modules/babel-env.js
- tools/tests/apps/modules/package.json
This PR implements support for the env key in `.babelrc` files.
It looks first for `BABEL_ENV` then `NODE_ENV` then finally defaults to `development` per the Babel documented behavior.
Rationale: be able to add additional babel plugins/presets for testing environment for example (eg. `babel-plugin-istanbul`)
I wasn't sure where to add tests as I did not see any existing tests for the functionality.  Please let me know your feedback.
> support env in babelrc

- tools/runners/run-mongo.js
- tools/tests/modules.js
Hi all - this PR should fix the `modules - test app` self-test timeout issues that were originally uncovered by https://github.com/meteor/meteor/commit/4d37a05fb33576b8f167168f4bc1b12821354615 (and reverted by https://github.com/meteor/meteor/pull/8913/commits/565281e765cb9e5f5c10ac37c8ee03f42ecc1874). With 4d37a05fb33576b8f167168f4bc1b12821354615 in place, the `modules - test app` self-test times out on most runs, due to not being able to connect to Mongo within the [`tools/runners/run-mongo.js`](https://github.com/meteor/meteor/blob/2ebd647e1a16c41344bc13533bd852bfd843620f/tools/runners/run-mongo.js#L596) specified mongo connection timeout of 30 seconds. Increasing this timeout to 60 seconds allows the test to pass properly and shouldn't impact any other parts of the codebase (or normal …
> Increase mongo connection timeout to reduce self-test mongo errors

- History.md
- tools/isobuild/linker.js
Immediately after each Meteor package is evaluated, we synchronously `require` its eager entry point modules (typically those identified by `api.mainModule`), before loading other packages. This behavior makes the load order of packages more important than it should be, leading to bugs like #8969, where one package synchronously imports another package that hasn't loaded yet, and gets weird/`undefined` results.
The natural solution here is to run all eager `require` calls after loading all package code. However, we have avoided making that change because of an obscure feature that allows package files to be `bare`, which means they are not wrapped as modules, and thus may declare variables directly in the package scope. Historically, `bare` code could run in between eager `require` calls, …
> Run all "bare" package files before requiring eager entry point modules.

- packages/constraint-solver/constraint-solver.js
- packages/package-version-parser/package-version-parser.js
- tools/project-context.js
- tools/tests/apps/package-tests/packages/tilde-constraints/package.js
- tools/tests/apps/package-tests/packages/tilde-constraints/tilde-constraints.js
- tools/tests/apps/package-tests/packages/tilde-dependent/package.js
- tools/tests/apps/package-tests/packages/tilde-dependent/tilde-dependent.js
- tools/tests/package-tests.js
As discovered in #8947, creating an app with
```sh
meteor create --release 1.4.4.1 new-app
```
does not actually constrain core packages to have the same minor versions they had when Meteor 1.4.4.1 was published. Rather (as of Meteor 1.4.3), the Meteor release only constrains core packages to have versions at least as recent as the versions they had when the release was published, and to have the same major version. Any later minor version is fair game.
What we need is a new kind of package version constraint, more like [semver's `~` range operator](https://www.npmjs.com/package/semver#tilde-ranges-123-12-1).
This commit implements that functionality, though it stops short of supporting all possible semver range syntax.
> Support @~ version constraints and use them for core packages.

- tools/meteor-services/config.js
- tools/tests/cordova-plugins.js
- tools/tool-testing/selftest.js
I was going to make some other changes to `selftest.js` but the code seemed like it could use a once-over first.  It now uses `import` statements (with import specifiers!), `export`s, more modern ECMAScript and no longer uses Underscore.
I'd advise reviewing commit by commit to review functionality (pro-tip: start [here](https://github.com/meteor/meteor/pull/8995/commits/5f3bb80c0d644bb0f329748be5bf2771013face5) and use `n`(ext)+`p`(revious) shortcuts!).  There are a lot of commits (40!) but each commit was meant to be relatively small and individually functional (exeception: https://github.com/meteor/meteor/commit/23b6c78b2f93c5819cde51f70bd7f6868b459ca1), which might help a future `git bisect` _if_ we don't "squash" (though we can always recover the branch from this PR, if we do).
> Modernize "Self Test" module, remove Underscore.

- History.md
- packages/mongo-dev-server/README.md
- packages/mongo-dev-server/package.js
- packages/mongo-dev-server/server.js
- packages/mongo/package.js
- tools/runners/run-all.js
- tools/tests/static-html.js
Only start the MongoDB server if this package is present in the project.
This reverts commit 565281e765cb9e5f5c10ac37c8ee03f42ecc1874.
In addition to re-instating the `mongo-dev-server` changes, this PR also includes adjustments to the `static-html - throws error` self-test, that are required as part of the `mongo-dev-server` work. These adjustments were orginally included in https://github.com/meteor/meteor/commit/4d37a05fb33576b8f167168f4bc1b12821354615, but when some of these changes were reverted by https://github.com/meteor/meteor/commit/565281e765cb9e5f5c10ac37c8ee03f42ecc1874, the `static-html - throws error` fix was left in 1.5.2. Without the rest of the `mongo-dev-server`  changes in place howerver, this self-test fix had to be changed, which was done in …
> Reinstate the mongo-dev-server package (#8853)

- tools/fs/files.js
- tools/fs/optimistic.js
- tools/tests/compiler-plugins.js
- tools/tests/cordova-plugins.js
- tools/tests/hot-code-push.js
- tools/tests/package-tests.js
- tools/tests/run.js
Should fix #8988 and #8942.
Now that #8866 is the default behavior, it can take up to 5000ms for changes to files modified during the build process to be noticed.
Before #8866, when we called e.g. `files.writeFile(path)`, a native file watcher would notice the change immediately, almost always before the build process read the file again. This was definitely racy, but we were getting away with it consistently... until #8866.
I was able to reproduce the problem in #8988 by running
```sh
echo some-local-package-name >> .meteor/packages
```
in an app with a local package of the given name. After debugging the endless rebuild cycle, I found that `.meteor/versions` was being rewritten by `files.writeFile` during the build process, but the file watching system was not noticing the change in …
> Immediately dirty optimistic functions when relevant paths modified.

- tools/cordova/builder.js
Related issues:
[`App.icons` for iOs are incomplete](https://github.com/meteor/meteor/issues/9006)
[Current set does not include a few key icons](https://github.com/lpender/meteor-assets/issues/10)
*Note*
The notification sizes don't work yet but I suspect this may be an [issue with phonegap](https://github.com/phonegap/phonegap-plugin-push/issues/1218#issuecomment-321882253)
> Add sizes necessary for iOs legacy, notification icon support.

- .circleci/config.yml
- tools/cli/commands.js
- tools/tool-testing/selftest.js
This started as a proof-of-concept, but I think it's worth submitting for consideration.
In an effort to get more fine-grained information out of the `meteor self-test` tool (which is used for testing of Meteor releases during development) and to take advantage of additional features in CircleCI (and other test environments), this introduces a `--junit=output.xml` argument to the `meteor self-test ...` command.
This gains us a couple relatively functionally pleasing features, such as the ability to see [failed tests without scrolling through all the results](https://circleci.com/gh/abernix/meteor/1358) and [CircleCI Insights on test timings](https://circleci.com/build-insights/gh/abernix/meteor/abernix%252Fmore-selftest2).
One of the more important historical pieces of information we will …
> JUnit support for `meteor self-test` test runner.

- tools/cli/dev-bundle-bin-helpers.js
- tools/isobuild/meteor-npm.js
This PR submits two changes for the `release-1.6` branch (Meteor 1.6) which uses `npm@5`.  Without this fix, on Windows 10 Insider Preview, somewhat cryptic errors were encountered when trying to `meteor npm install`, such as:
```
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
```
This appears to be fixed if we no longer set the `NPM_CONFIG_CACHE` variable to our own cache directory.  This should be fine given that `npm@5` has …
> Changes to npm installation methods for npm@5 / Meteor 1.6.

- tools/fs/watch.js
- tools/tests/run.js
This fixes #3854 (where passing a directory via the `meteor --settings` option causes the Meteor Tool to get caught up in an infinite rebuild loop).
Looking over the Meteor codebase, it doesn't look like [`tools/fs/watch.js#readAndWatchFileWithHash`](https://github.com/meteor/meteor/blob/65c8b481e20d02aa06b994c75d83c7db79ce37df/tools/fs/watch.js#L725-L738) needs to ever allow directory watching (since [`tools/fs/watch.js#readAndWatchDirectory`](https://github.com/meteor/meteor/blob/65c8b481e20d02aa06b994c75d83c7db79ce37df/tools/fs/watch.js#L712-L716) exists for this purpose). To this end, I've adjusted `readAndWatchFileWithHash` to skip adding directories to the `watchSet`, which fixes the infinite `--settings` rebuild loop. I'm happy to move this around if anyone thinks this should go …
> Avoid creating a watcher when --settings is set to a directory

- History.md
Oops - looks like we missed this one. Adding it in - thanks!
> Add the missing `meteor list --tree` History.md entry

- tools/cli/help.txt
I just noticed this was missing, so adding it in. Thanks!
> Add missing CLI help for test/test-packages --driver-package

- .circleci/config.yml
- History.md
- meteor
- scripts/build-dev-bundle-common.sh
- scripts/build-node-for-dev-bundle.sh
- scripts/generate-dev-bundle.sh
- tools/cli/dev-bundle-bin-helpers.js
Brings https://github.com/nodejs/node/pull/14829 to the version of Node that ships with Meteor, hopefully preventing segmentation faults like those reported in #8648.
These changes will be officially released in Node 4.8.5, but we didn't want to [wait until September or October](https://github.com/nodejs/node/pull/14829#issuecomment-323350770) for that release.
All credit for these changes belongs to @abernix. I simply adapted his script to run in a separate Jenkins job, so that we don't have to rebuild Node from source every time we publish a new dev bundle.
> Patch Node 4.8.4 to fix segmetation faults.

- packages/test-in-browser/driver.css
- packages/test-in-browser/driver.html
- packages/test-in-browser/driver.js
- packages/test-in-browser/package.js
This PR is intended to help fix #4979. I know external package `Tinytest` use has dwindled since adding `--driver-package` support to `meteor test-packages`, but since we are still supporting it (and it's used by the Meteor core), we might as well improve the `test-in-browser` UI experience a bit (let me know if anyone disagrees!).
These changes add a global `window.onerror` event handler to the `test-in-browser` package, to catch any previously uncaught exceptions. When uncaught exceptions are found, an alert like the following is shown at the top of the `test-in-browser` UI:
This should help notify developers of potential errors behind the scenes, that are preventing the client side tests from running.
(P.S. --> I snuck `ecmascript` in there ... hope that's okay!)
> Visually notify of uncaught exceptions breaking client tests

- History.md
I previously failed to update the `History.md` with the date before landing the `release-1.5.2` PR in `master`.  Since `master` is a protected branch, I can't fix this without a pull request.
> Add date to History.md for official 1.5.2 release.

- packages/babel-compiler/babel-compiler.js
Just a small improvement of the error that is thrown if a `.babelrc` file doesn't contain valid JSON. For example, the error message will be
```
.babelrc is not a valid JSON file: Unexpected token }
```
instead of
```
Unexpected token }
```
for the invalid `.babelrc` file
```
{
"plugins":
}
```
Resolves #8792
> Throw more meaningful error if .babelrc is not a valid JSON file

- .gitignore
While downloading a new `dev_bundle`, thousands of files are created in the temporary `dev_bundle.xxx` directory, which can slow down editors and IDEs that are tracking the Git status in the background.
> Add temporary `dev_bundle.xxx` directory to .gitignore

- packages/ddp-client/stream_tests.js
When running the `ddp-client` package tests with `meteor test-packages`, and accessing the test runner via http://127.0.0.1:3000, the websocket endpoint test fails due to a CORS error. This PR replaces the use of `Meteor.absoluteUrl` with `Meteor._relativeToSiteRootUrl` to make sure test HTTP requests are kept within CORS restrictions.
Fixes #8094.
> Adjust websocket endpoint testing to avoid CORS issues

- .github/PULL_REQUEST_TEMPLATE.md
The GitHub pull request template (i.e. `PULL_REQUEST_TEMPLATE.md`) is displayed to contributors when they are submitting a PR to the project.
In a similar attempt to what I did with the [`ISSUE_TEMPLATE.md`](https://raw.githubusercontent.com/meteor/meteor/devel/.github/ISSUE_TEMPLATE.md) (which is the same template except for filing issues), this change aims to improve the friendliness of the PR template by making it sound less intimidating, manage expectations and a hopefully provide a positive experience for someone filing a pull-request.
Having a pull-request rejected (and rejecting a pull request!) is not a "feel-good" situation and I think it's best to avoid that as much as possible.  I don't claim this will solve the problem, but I hope it helps.
Input (and iteration) appreciated …
> Improve messaging and friendliness of "pull request template".

- packages/webapp/package.js
- packages/webapp/webapp_server.js
The `localIp` constant was never used, so the HTTP server was started with an `undefined` host instead of "0.0.0.0" if `process.env.BIND_IP` was `undefined`.
Related to #9072.
👋  @aliogaili, @hwillson
> Fix host IP fallback for `webapp` server

- packages/force-ssl-common/force_ssl_common.js
- packages/force-ssl-common/force_ssl_tests.js
- packages/force-ssl-common/package.js
- packages/force-ssl/package.js
`force-ssl`'s current `isLocalConnection` regex does not handle IPv4-mapped and/or IPv4-compatible IPv6 addresses, when checking if the connection is local. This means a local address of `::ffff:127.0.0.1` is being marked as non-local. These changes adjust the `isLocalConnection` regex to handle a wider range of localhost address representations.
Fixes #9072.
> Adjust force-ssl localhost regex to handle IPv4 in IPv6 addresses

- tools/static-assets/skel-full/.meteor/packages
The `shell-server` package was missing in the scaffold app skeleton, see https://github.com/meteor/docs/pull/161#issuecomment-328767441.
> Add `shell-server` package to scaffold app skeleton

- packages/minimongo/cursor.js
- packages/minimongo/matcher.js
- packages/minimongo/minimongo_tests_client.js
In #8893 (Minimongo refactoring), [this commit](https://github.com/meteor/meteor/commit/92555c32ba40e969a0bd905975961326d2365f1e) changed how the `_id` property of a selector object is handled, but the new version fails for falsy `_id`s, e.g., empty strings (see #9060).
This pull request fixes the bug by checking if the selector object has an `_id` property instead of looking for a truthy value.
**Regarding falsy selectors and `_id`s:** 
The bug is fixed by the changes to `cursor.js`. Since `matcher.js` contains the same logic, I made the same changes there but I'm not sure if that's correct. Since the refactoring, `_selectorIsIdPerhapsAsObject` is called instead of `_selectorIsId` on the following line:
https://github.com/meteor/meteor/blob/5f13b20e1e4023a23a50b9c4f1c9e1ad9d88136c/package …
> Fix falsy `_id` in selector object not being treated as ID

- Development.md
The _"Dev Bundle" versions_ section in `Development.md` currently gives the impression that `dev_bundle` caching is enabled by default. This PR adds a short paragraph about the `SAVE_DEV_BUNDLE_TARBALL` environment variable, which is used to enable caching. :slightly_smiling_face:
> Explain how to enable `dev_bundle` caching

- meteor
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/babel-compiler/package.js
- packages/babel-runtime/babel-runtime.js
- packages/babel-runtime/package.js
- packages/ecmascript/runtime-tests.js
- packages/ecmascript/transpilation-tests.js
- packages/non-core/coffeescript-compiler/.npm/package/npm-shrinkwrap.json
- packages/non-core/coffeescript-compiler/package.js
- packages/non-core/coffeescript/package.js
- scripts/dev-bundle-tool-package.js
- tools/static-assets/skel-bare/package.json
- tools/static-assets/skel-full/package.json
- tools/static-assets/skel/package.json
- tools/tests/apps/dev-bundle-bin-commands/package.json
- tools/tests/apps/dynamic-import/package.json
- tools/tests/apps/modules/package-lock.json
- tools/tests/apps/modules/package.json
- tools/tests/apps/shell/package.json
Specifically, [Babel 7.0.0-beta.0](https://github.com/babel/babel/releases/tag/v7.0.0-beta.0).
Notable changes: https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7
Apologies for the terse PR description; more information (and commits) to come!
> Upgrade to Babel 7

- packages/modules-runtime/server.js
- tools/fs/files.js
- tools/isobuild/bundler.js
- tools/static-assets/server/boot.js
Ever since Meteor 1.3 first introduced a module system based on something other than `Npm.require`, we've continued throwing missing module exceptions that refer to `Npm.depends` and/or `Npm.require`, even if the developer called `require` or used an `import` declaration. This commit fixes that, so that all missing module exceptions look like `Cannot find module "module/name"`.
I also noticed recently that `Npm.require` is capable of returning modules installed in `node_modules` directories completely outside the app, which is bad news for development/production reproducibility. Fixed that too.
CC @hwillson who has spoken of deprecating `Npm.require` entirely, and
just using `require` everywhere, instead.
> Standardize Npm.require exceptions and limit lookup paths.

- packages/dynamic-import/client.js
A fix to the dynamic-import code to correctly detect modules version.
Without this fix dynamic-import can't detect correctly modules versions
which breaks the dynamic-import cache functionality.
[I prepared a video that demonstrates the issue and the fix.](https://drive.google.com/open?id=0B3MQ_v8orqd_QURnUVZOaDBFWms)
-Daniel
> dynamic-import: fix modules version recognition to fix caching

- packages/accounts-base/accounts_common.js
- packages/accounts-base/accounts_tests.js
Hi all - as mentioned in https://github.com/meteor/meteor/issues/9066, the changes made in https://github.com/meteor/meteor/pull/8917 use `Infinity` to represent an unexpiring login token millisecond lifetime. The problem with this approach is that Accounts is attempting to perform `Date` based operations on the value returned from [`_getTokenLifetimeMs`](https://github.com/meteor/meteor/blob/4f43008aa0b02db79eb791d9103d696288a5bfb9/packages/accounts-base/accounts_common.js#L217), in several locations:
- https://github.com/meteor/meteor/blob/4f43008aa0b02db79eb791d9103d696288a5bfb9/packages/accounts-base/accounts_common.js#L240
- https://github.com/meteor/meteor/blob/4f43008aa0b02db79eb791d9103d696288a5bfb9/packages/accounts-base/accounts_common.js#L248
- …
> Fix issues with Infinity based login token lifetimes

- tools/runners/run-mongo.js
> Prologue: A heartbeat is used amongst members of a MongoDB replica set
to poll the status of said members.
When we are initiating a new replicaset for the test Mongo server, the replicaset is not fully prepared to accept writes until the voting members have negotiated and propagated their decision about who is the "primary" to all members involved.  This seems to be delayed by almost _exactly_ the default heartbeat interval, which is 2000ms.
The heartbeat interval is marked as an "internal only" property in Mongo so I was hesitant to lower it.  It's also a new property in Mongo 3.2 which might explain why this cropped up a while ago.
I believe this heartbeat delay is the only explanation for why the `rs.status()` (i.e. `replSetGetStatus`) believes it is ready before the `mongod` has …
> When starting mongod, yield until the heartbeat has pulsed after election.

- tools/cordova/builder.js
Hi,
this PR fix some typo in App.icons that prevent to display some Ios new values in docs
https://docs.meteor.com/api/mobile-config.html#App-icons
regards
> Fix App.icons documentation typo

- packages/minimongo/common.js
- packages/minimongo/minimongo_tests_client.js
The `subMatcher` function `let` statment was missing (dropped during the latest minimongo refactoring - see https://github.com/meteor/meteor/commit/fe576f60ce019212699af53660d2afbcb3a721e6). This turned `subMatcher` into a global function, which caused several minimongo issues.
Fixes #9111.
> Add missing let statment to the $elemMatch subMatcher function

- History.md
- meteor
- tools/cordova/index.js
Meteor's iOS 11 emulation is currently broken when using the latest version of Xcode (9.x). This PR updates the `cordova-ios` dependency to 4.5.1, which includes an iOS 11 fix (https://github.com/apache/cordova-ios/commit/a20aeddbc25dca293f412cce80f6e0ef90f09b9d).
These changes will require a new `dev_bundle`.
Fixes #9098.
Fixes #9126.
> Update cordova-ios to 4.5.1, to add in iOS 11 / Xcode 9 support

- packages/accounts-base/accounts_client.js
- packages/accounts-base/accounts_reconnect_tests.js
The changes added in https://github.com/meteor/meteor/commit/d854a4b9ba97a230d9d57b4a23f358edd2a36702 fixed a long standing issue where the Accounts system was overwriting other DDP `connection.onReconnect` callbacks, that were potentially set by developers (and vice-versa - developers could overwrite the `onReconnect` callback registered by the Accounts system, which impacted logging back in after reconnecting). Unfortunately these changes are also registering a new duplicate `onReconnect` callback to be called, after every login. These duplicate callbacks pile up and are all called when reconnecting, which eventually breaks user logins.
The changes in this commit make sure that any previously set Accounts login `onReconnect` callback is first removed, before adding a new callback. This …
> Make sure Accounts login only sets 1 onReconnect callback

- tools/cli/commands-packages-query.js
- tools/cordova/builder.js
- tools/cordova/run-targets.js
- tools/isobuild/bundler.js
- tools/isobuild/isopack.js
- tools/meteor-services/auth.js
- tools/meteor-services/service-connection.js
- tools/project-context.js
- tools/runners/run-log.js
- tools/runners/run-mongo.js
- tools/tool-env/isopackets.js
- tools/tool-testing/selftest.js
- tools/tool-testing/test-utils.js
By my calculations, the sum of the sizes of the individual "isopackets" was 152MB, and the size of the combined isopacket is now just 36MB. That remarkable difference goes to show how much duplication of transitive dependencies was happening before this change.
That's a savings of 116MB for the (uncompressed) size of the `meteor-tool` package. In Meteor 1.5.x, the `meteor-tool` package is about 544MB, but in Meteor 1.6 it's considerably smaller: 373MB. In other words, this change should reduce those sizes to 428MB (-21%) and 257MB (-31%), respectively.
> Combine all isopackets to share transitive dependencies.

- tools/runners/run-app.js
- tools/static-assets/server/boot.js
- tools/static-assets/server/debug.js
The `meteor debug` command behaves like Node's `--inspect-brk` flag, in that it attempts to pause the server before executing any server code.
However, simply passing the `--inspect-brk` flag to Node causes execution to pause on the very first line of code, which is not good for setting any breakpoints, because no server code has actually loaded yet.
Instead, the `meteor debug` command uses Node's `--inspect` flag to enable debugging without an initial pause, then manually pauses at an appropriate moment during server startup. Ideally, the pause should last until an inspector client has been attached to the process, at which point the developer has a chance to set any desired breakpoints, then clicks the continue button to proceed with server startup.
The most difficult part of this …
> Detect inspector client attachment by timing debugger keyword.

- packages/npm-mongo/.npm/package/npm-shrinkwrap.json
- packages/npm-mongo/package.js
- packages/npm-mongo/wrapper.js
This fixes the occurrences of #8598 that I've been able to personally reproduce.
Doing this on the release-1.6 branch, though a backport to 1.5.x-land would probably be a good idea if this works.
Unfortunately the Node Mongo maintainers (see @mbroadst in https://jira.mongodb.org/browse/NODE-1153) haven't indicated when they think they'll be able to review this PR so we'll probably have to push it out to Meteor users without any real review by the folks who know this code best, as this issue has been a major source of pain for many Meteor users.
> npm-mongo: use fork of mongodb-core for #8598

- History.md
- tools/cli/commands.js
- tools/cli/help.txt
- tools/cli/main.js
- tools/runners/run-app.js
This PR replaces the `meteor debug` command with the more flexible `--inspect` and `--inspect-brk` command-line flags, which work for any `run`, `test`, or `test-packages` command.
The syntax of these flags is the same as the equivalent Node.js [options](https://nodejs.org/en/docs/inspector/#command-line-options). When no port value is provided, the default is 9229.
Two notable differences:
* The flags affect the server process spawned by the parent build process, rather than affecting the build process itself. The build process can be debugged (as before) by setting the `TOOL_NODE_FLAGS` environment variable to `--inspect` or `--inspect-brk`.
* The `--inspect-brk` flag causes the server process to pause just after server code has loaded but before it begins to execute. This timing is …
> Support --inspect and --inspect-brk for all Meteor test/run commands.

- packages/minimongo/common.js
- packages/minimongo/minimongo_tests_client.js
As @janowsiany noticed in https://github.com/meteor/meteor/issues/9167 , there was an error in the function that checks for ambiguous field definitions during an upsert. While this should only work for nested fields, it also threw errors in case some field name starts with some other field name. (e.g. a document with both 'foo' and 'fooBar')
This should fix this and add tests.
> Fix for 9167

- packages/logging/logging.js
- packages/logging/package.js
Fixes #9118
Uses [bright variant](https://www.npmjs.com/package/cli-color#bright-variants) of colors from cli-color.
CMD and windows Powershell, need bright colors for propercontrast difference for comfortable reading.
> Switch to bright colors on Windows Powershell

- packages/server-render/README.md
As of React 16, using `ReactDOM.render` in the manner demonstrated in the `server-render` README will cause a React deprecation warning. Switching to `ReactDOM.hydrate` will avoid this. From the React docs:
> Using ReactDOM.render() to hydrate a server-rendered
> container is deprecated and will be removed in React 17.
> Use hydrate() instead.
Source: https://reactjs.org/docs/react-dom.html#render
(I'll create a similar PR for the [`server-render` docs](http://docs.meteor.com/packages/server-render.html).)
> Replace ReactDOM.render with ReactDOM.hydrate

- tools/cli/main.js
- tools/packaging/catalog/catalog-remote.js
- tools/packaging/updater.js
- tools/utils/archinfo.js
This PR is a follow-up to https://github.com/meteor/meteor/pull/9218, which introduced support for 64-bit builds of Meteor for Windows.
I've attempted to solve two problems with this PR:
- 64-bit builds of Meteor 1.6 on Windows may be used to run older apps with 32-bit versions of Meteor, which requires downloading a 32-bit build of `meteor-tool` and springboarding to it: https://github.com/meteor/meteor/commit/e9db660d03bc58418b2601dd2f67d9256dfc49ce
- Running `meteor update` from a 32-bit Meteor installation can only download other 32-bit builds of Meteor, which means you may want to reinstall Meteor from scratch to get a 64-bit build. While reinstalling will work, I think it may be possible to catch the 32/64-bit discrepancy after springboarding, and perform a second springboard to the …
> [WIP] Automatically switch between 64- and 32-bit Windows builds.

- History.md
- packages/minimongo/cursor.js
- packages/minimongo/minimongo_tests_client.js
This PR changes the default behaviour of `cursor.count()` on the client. Previously, `.count()` on the client would return the number of matching documents taking into account `skip` and `limit`. Now, it will ignore those options unless it is passed `true` when invoked. (i.e. `cursor.count(true)`). This is consistent with the way it works on the server.
Issue: #1201 
Introduction of feature on server-side: 258b14a & bce4df9
Previous PR (incomplete): #5023
Test app: [meteor-issue-1201](https://github.com/carlevans719/meteor-issue-1201)
> Make behaviour of cursor.count() on client reflect server

- History.md
Meteor 1.5.3 is [now released](https://github.com/meteor/meteor/pull/9266) and the 1.5.x-series of Meteor now has its [own branch](https://github.com/meteor/meteor/commits/release-1.5.x) (which will remain forever as its own limb and not merge back to `master` now that Meteor 1.6 is out), however it remains important that the `History.md` changes from the 1.5.x-series make their way back to `master` and thus `devel` to maintain a complete `History.md` on the main trunk.
> Update History.md with miscellaneous changes in Meteor 1.5.3.

- packages/meteor/define-package.js
- packages/meteor/global.js
- packages/meteor/package.js
- tools/isobuild/bundler.js
- tools/isobuild/compiler-plugin.js
- tools/isobuild/isopack.js
- tools/isobuild/linker.js
- tools/static-assets/server/boot.js
This removes the need for
```js
if (typeof Package === 'undefined') Package = {};
```
at the bottom of every package, and replaces
```js
(function (pkg, symbols) {
for (var s in symbols)
(s in pkg) || (pkg[s] = symbols[s]);
})(Package.minimongo = exports, {
LocalCollection: LocalCollection,
Minimongo: Minimongo,
MinimongoTest: MinimongoTest,
MinimongoError: MinimongoError
});
```
with
```js
Package._define("minimongo", exports, {
LocalCollection: LocalCollection,
Minimongo: Minimongo,
MinimongoTest: MinimongoTest,
MinimongoError: MinimongoError
});
```
It's not a huge savings, but it opens the door for us to do more interesting things with the `Package` namespace, by adding other methods to it.
> Use Package._define to reduce package boilerplate.

- tools/isobuild/isopack.js
- tools/isobuild/unibuild.js
This is routine refactoring to move the `Unibuild` class to its own module, with relatively isolated `toJSON` and `fromJSON` methods. It's too bad that these methods still have side-effects like writing files, but it's much easier to see how `Unibuild` objects relate to `Isopack` and bundler logic, and I think it will be easier to add `Unibuild`-specific methods in the future, thanks to this refactoring.
> Extract Unibuild class.

- History.md
As mentioned in https://github.com/meteor/meteor/issues/9308#issuecomment-342447058, it would be great if we highlight the fact that it's possible to publish backwards incompatible packages using Meteor 1.6. I've updated the `History.md` with some plagiarism from @benjamn's comments in https://github.com/meteor/meteor/issues/9308#issuecomment-342295413.
Fixes https://github.com/meteor/meteor/issues/9308.
> Add note about possible package incompatibilty with 1.5

- tools/isobuild/compiler-plugin.js
- tools/isobuild/compiler.js
- tools/isobuild/isopack-cache.js
- tools/isobuild/linker.js
Several years ago, before all major browsers supported source maps, we felt it was important to provide line number information in generated files using end-of-line comments like `// 123\n`.
Adding all these comments was always slower than leaving the code unmodified, and recently they have begun interacting badly with certain newer ECMAScript syntax, such as multi-line template strings (#9160).
Since source maps are well supported in most browsers that developers are likely to be using for development, and the line number comments are now causing substantive problems beyond the performance cost, I think it's time we stopped using them once and for all.
Fixes #9160.
> Stop adding line number comments to linked JavaScript files.

- packages/ddp-server/package.js
New version has just been released which passes some useful headers on to the server from client. (Personally, I need DNT header.)
Also, I noticed that this file has been forked in the past and a relatively old version is being used. Probably it should be updated at some point as well: https://github.com/meteor/meteor/blob/devel/packages/ddp-client/sockjs-0.3.4.js
> Bumping sockjs-node to 0.3.19

- History.md
- meteor
- packages/meteor-tool/package.js
- scripts/admin/meteor-release-experimental.json
- scripts/admin/meteor-release-official.json
- scripts/build-dev-bundle-common.sh
- scripts/generate-dev-bundle.sh
This is a small but important update to the Meteor 1.5.x series, which follows up on the recent [Meteor 1.5.3](https://github.com/meteor/meteor/pull/9266) by updating Node.js to 4.8.6, released today (Nov 7, 2017) as part of the Node.js v4 "Maintenance" LTS updates.
The Node.js "notable changes" are below, but subtly and most notably for Meteor, the [detailed commits](https://nodejs.org/en/blog/release/v4.8.6/#commits) includes our fix to an improperly applied V8 garbage collection patch on Node.js core which was causing segmentation faults, as found in our test-suite, https://github.com/meteor/meteor/issues/8648 and https://github.com/nodejs/node/issues/14228 and fixed with https://github.com/nodejs/node/pull/14829, which had previously applied to Meteor releases 1.5.3, 1.5.2.2, 1.5.2.1 …
> Release 1.5.4

- packages/mongo/collection.js
- packages/mongo/collection_tests.js
- packages/mongo/local_collection_driver.js
- packages/mongo/mongo_livedata_tests.js
- packages/mongo/package.js
When we talk about removing `underscore` from core packages, we're primarily concerned about removing it from the client JS bundle. In other words, we only need to remove `underscore` from modules within a given package that are used on the client. The `mongo` package is a good example of a package where this insight matters: since `mongo` contains mostly server-side code, client-only removal of `underscore` should be relatively easy.
> Convert Mongo.Collection to class and remove underscore on client.

- .circleci/config.yml
- scripts/windows/appveyor/install.ps1
While this was necessary in previous versions of Meteor, as of 1.6 the
`self-test` tooling will automatically install the dependencies it needs
at runtime. (Thanks to https://github.com/meteor/meteor/pull/8981)
Not only does this allow the installation to be avoided when tests using
those facilities aren't invoked, it also allows us to reliably install
the same version of these npms, rather than falling back to the
`latest` npm tag on each CI run.
Note that this doesn't change the behavior of the [`test-packages` `run.sh`](https://github.com/meteor/meteor/blob/abernix/stop-installing-self-test-npms/packages/test-in-console/run.sh#L8)
script (used by Travis) which still installs the `latest` version of these npms.
> Stop pre-installing phantomjs-prebuilt and browserstack-webdriver.

- History.md
- packages/minifier-js/.npm/package/npm-shrinkwrap.json
- packages/minifier-js/package.js
- packages/standard-minifier-js/package.js
There have been quite a few `uglify-es` bug fixes made since 3.0.28, some of which fix outstanding Meteor issues. This PR updates `minifier-js` to use the latest version (3.1.9). Unfortunately `uglify-es` doesn't maintain a changelog so it's a bit difficult to run through all of the changes, but I've stepped through the commit history and haven't found anything that jumps out as being problematic. I've also minified a few apps using 3.1.9, and everything looks good.
Fixes https://github.com/meteor/meteor/issues/9138 (and likely others).
> Update minifier-js uglify-es dependency to latest version

- History.md
Somehow the comment for https://github.com/meteor/meteor/pull/9198 did not make it into Meteor 1.6 section. This fixes this minor issue with the Meteor history file.
> Fix history file

- packages/minimongo/cursor.js
- packages/minimongo/package.js
The `Cursor.observeChanges` function throws an error when there is an attempt to use an unordered observe with skip/limit. This error can also be thrown when attempting the same thing with `Cursor.observe`. This is because `Cursor.observe` ends up calling back to `Cursor.observeChanges`. When using `Cursor.observe` however, the shared error message is a bit misleading, as `addedAt` should be used instead of `addedBefore`. This commit adjusts the shared error message to cover both `observeChanges` and `observe` scenarios.
Fixes #4996.
> Adjust observeChanges skip/limit ordered observe error message

- History.md
- packages/dynamic-import/client.js
- packages/dynamic-import/package.js
- packages/dynamic-import/security.js
- packages/dynamic-import/server.js
- packages/ecmascript/package.js
- packages/http/.npm/package/npm-shrinkwrap.json
- packages/http/deprecated.js
- packages/http/httpcall_client.js
- packages/http/httpcall_common.js
- packages/http/httpcall_server.js
- packages/http/package.js
- packages/meteor-base/package.js
- packages/meteor/package.js
- packages/meteor/startup_server.js
- packages/modules-runtime/.npm/package/npm-shrinkwrap.json
- packages/modules-runtime/package.js
- packages/non-core/bundle-visualizer/client.js
- packages/non-core/bundle-visualizer/package.js
- packages/non-core/bundle-visualizer/server.js
- packages/url/package.js
- packages/url/url_client.js
- packages/url/url_common.js
- packages/url/url_server.js
Ever since Meteor 1.5 first shipped, dynamic modules have been fetched over a WebSocket, which is appealing because sockets have very little latency and metadata overhead per round-trip.
However, using a WebSocket requires first establishing a socket connection to the server, which takes time and may require a WebSocket polyfill.
An even more subtle problem is that we cannot use dynamic imports in any of the code that implements the `ddp-client` package, as long as the `dynamic-import` package depends on `ddp-client`.
By switching from WebSockets to HTTP POST requests, this commit radically reduces the dependencies of the `dynamic-import` package, while preserving (or even exceeding) the benefits of socket-based dynamic module fetching:
* The client makes a single HTTP POST request for …
> Support fetching dynamic modules via HTTP POST requests.

- tools/isobuild/meteor-npm.js
Attempt to fix: https://github.com/meteor/meteor/issues/9381
Short story: Meteor updates a package's npm dependencies on every change to any of the package files when one of the npm dependencies was scoped or when using a private npm server.
Root causes explained here: https://github.com/meteor/meteor/issues/9381#issuecomment-345709113
and here: https://github.com/meteor/meteor/issues/9381#issuecomment-345746220
Basically the shrinkwrap meteor created didn't include scoped packages (weird this hasn't resulted in more bugs before) and the comparison between requested and installed modules couldn't deal with private npm servers. 
Don't know if this will fix every situation (e.g. what is the resolved URL if the private NPM server sends redirects to another url). But I don't know of any such …
> Don't update npm dependencies when it's not needed

- History.md
- packages/tinytest/README.md
- packages/tinytest/model.js
- packages/tinytest/package.js
- packages/tinytest/tinytest.js
- packages/tinytest/tinytest_client.js
- packages/tinytest/tinytest_server.js
This is fairly standard stuff by now, though I'd also like to support returning `Promise`s from test functions.
> Modernize tinytest by using ecmascript.

- packages/boilerplate-generator-tests/.npm/package/npm-shrinkwrap.json
- packages/boilerplate-generator-tests/package.js
- packages/boilerplate-generator-tests/test-lib.js
- packages/boilerplate-generator-tests/web.browser-tests.js
- packages/boilerplate-generator-tests/web.cordova-tests.js
- packages/boilerplate-generator/.npm/package/.gitignore
- packages/boilerplate-generator/.npm/package/README
- packages/boilerplate-generator/.npm/package/npm-shrinkwrap.json
- packages/boilerplate-generator/generator.js
- packages/boilerplate-generator/package.js
- packages/boilerplate-generator/template-web.browser.js
- packages/boilerplate-generator/template-web.cordova.js
- packages/server-render/.npm/package/npm-shrinkwrap.json
- packages/server-render/README.md
- packages/server-render/client-sink.js
- packages/server-render/package.js
- packages/server-render/server-register.js
- packages/server-render/server-render-tests.js
- packages/server-render/server-sink.js
- packages/webapp/.npm/package/npm-shrinkwrap.json
- packages/webapp/package.js
- packages/webapp/webapp_server.js
- packages/webapp/webapp_tests.js
👋 With the release of React 16, a new way to render on the server is [streaming](https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67) the rendering of the react portion of your app to the client. This PR adjusts Meteor's internal markup generation for the server to move to a stream first API. With this change, you can use a string (renderToString) or a stream (renderToNodeStream) when adding content into an id.
In initial testing, it results in a 40% reduction of TTFB 🌮 (Time To First Byte [of taco]).
**Todo**
Wanted to get this up early enough for review though!
This PR address [setting status codes](https://github.com/meteor/meteor-feature-requests/issues/210) including for [SEO](https://github.com/meteor/meteor-feature-requests/issues/198), improved …
> Improved server rendering

- tools/cli/commands.js
- tools/cli/help.txt
The `meteor build --architecture` help was missing `os.windows.x86_64`. This commit adds it in and also updates an out of date comment in the source that referred to there only being 3 allowed architectures.
> Add os.windows.x86_64 to meteor build --architecture help

- packages/ddp-client/test/livedata_connection_tests.js
For a while the livedata `reconnect to a different server` test was failing since the `reverse.meteor.com` host and application were taken down, but nobody noticed. This is because even though the test was still enabled, it was configured to swallow the failure if the connection failed. `reverse.meteor.com` has been brought back up, so this commit adjusts the test to make sure it will properly fail if `reverse.meteor.com` goes down again.
Fixes https://github.com/meteor/meteor/issues/8092.
> Fail test when reverse.meteor.com cannot be connected to

- History.md
- packages/webapp/webapp_server.js
As discussed in #6674, Meteor currently serves its own manifest file from `/manifest.json`. This location is not application configurable, and can conflict with other non-Meteor defined manifest files, that are already being served from this location. For example, [Google's progressive web app documentation](https://developers.google.com/web/fundamentals/web-app-manifest/) suggests using the `/manifest.json` location for its manifest. The newest version of the [web app manifest spec](https://developer.mozilla.org/en-US/docs/Web/Manifest) recommends using a different location for the web app manifest, like
```html
<link rel="manifest" href="/manifest.webmanifest">
```
but the `/manifest.json` location was recommended at one point. Regardless, there isn't really any reason why Meteor needs …
> Stop serving the application manifest from /manifest.json

- packages/minimongo/common.js
- packages/minimongo/minimongo_tests_client.js
Fix: https://github.com/meteor/meteor/issues/9401
Note: I added some extra code that checks the operand values which is not strictly necessary, but now the errors are exactly the same as when using mongo shell.
> Add support for $type aliasses.

- tools/isobuild/compiler.js
When sources in the `node_modules` directory are being watched by a build plugin, if that build plugin is removed while the Tool is running, the Tool can crash. This is because the Tool currently see's this situation as an improbable edge case, and purposely errors out instead of allowing the Tool to continue. This commit adjusts the Tool to swallow this exception thereby allowing the rebuild process to continue normally (and avoiding a Tool crash). Given that the liklihood of this situation happening is quite low, and the impact of allowing the rebuild to continue is neglibile (if source files are no longer handled by a build plugin, app developers will notice quickly), this seems like an acceptable way forward.
Fixes #8644.
> Prevent Tool crash when node_modules source watcher is removed

- packages/shell-server/shell-server.js
- tools/tests/apps/shell/server/main.js
- tools/tests/shell-tests.js
_(PR body is the commit message body from https://github.com/meteor/meteor/commit/15b24ff6d1242dc80f52c94a053c5b1c8742efa5.)_
A truthy `useGlobal` option when calling Node's `repl.start()` will use the `global` context, which will allow global Meteor variables (such as the global `_` provided by the `underscore`) to be available in the context of the REPL shell.  This sounds desirable, and in fact, the original
implementation set it as such, only to be later changed to `false` in 7c7e52f, specifically to avoid the undesirable behavior of Node REPL stomping on the global `_` variable with its own special-meaning `_` variable which is set to the value of the most recently eval'd expression.
This `useGlobal ` was once again changed to `true` to fix the lost tab-completion functionality, …
> Correct global _ destruction via `meteor shell`.

- packages/google-oauth/google_server.js
- packages/google-oauth/package.js
Google's OAuth2 token endpoint (https://accounts.google.com/o/oauth2/token) returns an `expires_in` property in its response, which was being stored internally as `expiresIn`. The `getServiceDataFromTokens` function would only attempt to work with the `expiresIn` value if the `tokens` object had a set `expiresAt` property, meaning the `expiresIn` property was never used. This PR switches the `expiresAt` check to `expiresIn`.
Fixes #9435.
> Fix check for Google OAuth2 expiresIn property in tokens

- packages/appcache/appcache-server.js
As described in issue #9407, dynamic-imports does not load modules from the appcache, and since we don't want the browser to download these assets twice, this patch avoids adding those files to app.manifest.
This patch does pass the appcache unit test, but I'm not sure how to create a test for this, as I'm not sure how to set gt it to load dynamic imports to test with.
> remove dynamic js and map files from appcache (app.manifest)

- History.md
- meteor
- packages/babel-compiler/.npm/package/npm-shrinkwrap.json
- packages/babel-compiler/package.js
- packages/babel-runtime/babel-runtime.js
- packages/ecmascript/transpilation-tests.js
- packages/modules/.npm/package/npm-shrinkwrap.json
- packages/modules/package.js
- packages/non-core/coffeescript-compiler/package.js
- packages/non-core/coffeescript-test-helper/package.js
- packages/non-core/coffeescript/package.js
- packages/tinytest/tinytest.js
- scripts/dev-bundle-tool-package.js
- tools/static-assets/skel-bare/package.json
- tools/static-assets/skel-full/package.json
- tools/static-assets/skel/package.json
- tools/tests/apps/dev-bundle-bin-commands/package.json
- tools/tests/apps/dynamic-import/package.json
- tools/tests/apps/meteor-ignore/package.json
- tools/tests/apps/modules/package.json
- tools/tests/apps/shell/package.json
- tools/tests/create.js
- tools/tests/old/app-with-private/package.json
Since Meteor 1.6, we've been quietly beta-testing Babel 7 by using it to compile [the `meteor` command-line tool codebase](https://github.com/meteor/meteor/tree/devel/tools). This [dog-fooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) was vital when we first introduced Babel compilation in Meteor 1.2, and it later helped us gain confidence in the upgrade from Babel 5 to Babel 6. Now it's time to make the leap to Babel 7!
There are a number of important changes hidden behind the abstraction of [`meteor-babel`](https://github.com/meteor/babel/commits/master), but the most disruptive change that will be visible to application developers is that the [`babel-runtime`](https://www.npmjs.com/package/babel-runtime) package is now called …
> Update the babel-compiler package use to Babel 7, like the command-line tool.

- History.md
- tools/cordova/builder.js
- tools/cordova/index.js
Update to Cordova iOS v4.5.4 to fix iPhone X splash screen issue.
Fixes https://github.com/meteor/meteor/issues/9447
> Update to Cordova iOS v4.5.4

- packages/dynamic-import/server.js
- packages/non-core/bundle-visualizer/server.js
- packages/webapp/webapp_server.js
This should fix #9428.
Specifically, I've added an additional set of `connect` handlers that run before `WebApp.connectHandlers`, and that are meant for Meteor-internal HTTP endpoints, such as these:
```
/__meteor__/dynamic-import/fetch
/__meteor__/bundle-visualizer/stats
```
I'm not particularly worried about malicious use of this "private" feature by packages trying to register their handlers earlier. If that really seems like the best way to solve a problem, I just hope those packages take precautions to call `next()` as appropriate, and realize that we might change the way this feature works without notice (because it's supposed to be a private API).
> Fix #9428 by registering dynamic-import HTTP endpoint earlier.

- tools/tests/hot-code-push.js
Since this test utilizes the `testWithAllClients` technique, which runs
the tests in various clients/browsers, it's necessary for the tests
`Sandbox` to define `clients`, otherwise the function within
`testWithAllClients` will not be executed at all.  This was causing this
particular test to always return success (it was running without failure
on exactly zero clients).
Also the technique of setting `this.baseTimeout` appeared to cause
problems, likely because it overrides various other values instead of
using `waitSecs` (we don't use the `baseTimeout` technique in other
places within self-tests either).
Discovered during testing, as mentioned in
https://github.com/meteor/meteor/pull/9439#pullrequestreview-83139232.
> Define Sandbox `clients` when running `versioning hot code push test`.

- History.md
- packages/accounts-ui-unstyled/login_buttons.import.less
- packages/accounts-ui-unstyled/login_buttons_dropdown.html
- packages/accounts-ui-unstyled/login_buttons_dropdown.js
- packages/accounts-ui-unstyled/package.js
- packages/accounts-ui/package.js
`accounts-ui-unstyled` currently uses `<div />`'s to hold its login/signup forms, as well as `<div />`'s to represent the login/signup buttons in the form. By not using proper `<form />` and `<button />` elements, certain browser's do not notice incoming login/signup requests, and therefore do not trigger their built in "would you like to save your user/password" functionality. This commit adjusts the `accounts-ui-unstyled` login/signup form to use proper `<form />` and `<button />` elements, allowing most browsers (Chrome, Firefox, IE - Safari will recognize the request when a user attempts to leave the page) to recognize incoming login/signup requests.
Fixes #1746.
> Help browser account saving with accounts-ui login/signup forms

- packages/email/email.js
Recent versions of `mailcomposer` (which Meteor is now using) no longer (automatically) `JSON.stringify` added header objects. This commit updates the `Email.send` `options.headers` docs to show how to properly associate objects with custom headers.
Fixes #8660.
> Update Email.send docs to show how to add header objects

- tools/fs/safe-watcher.js
The URL for the file watcher warning is out of date. Here it directly links to the new location.
> Update URL for information about file watchers

- .circleci/config.yml
- History.md
- tools/cli/main.js
- tools/console/console.js
- tools/shell-client.js
- tools/tool-env/cleanup.js
- tools/utils/utils.js
I think this was originally designed for Emacs shell but at some point Emacs or
Node improved so that Node finds columns for Emacs shell and switches to the
full display.
Switching to the status-only display leads to massive speedups when doing builds
in my Emacs shell.
> tools: allow explicitly opting in to low-fi status display

- tools/cli/main.js
- tools/static-assets/server/boot.js
Clearly we haven't remembered to bump this version for some time now, which is too bad, because it could have provided a more helpful error for developers using an older version of Node in their non-Galaxy deployment environments: https://github.com/meteor/meteor/issues/9470
As a reminder, you can always find the exact version of Node that Meteor expects by examining the `.node_version.txt` file in the generated build archive.
> Bump MIN_NODE_VERSION to enforce Node >= 8 in production.

- tools/cordova/index.js
`cordova-lib@7.1.0` should use `cordova-common@2.1.1 ` as per https://github.com/apache/cordova-lib/blob/7.1.x/package.json and [this blog post](https://cordova.apache.org/news/2017/10/10/tools-release.html) . I missed this change in this PR https://github.com/meteor/meteor/pull/9213
> Fix cordova lib dependency

- packages/oauth/end_of_redirect_response.js
- packages/oauth/package.js
When using the `oauth` package "redirect" `loginStyle`, the redirect URL is escaped before it is embedded in the HTML page that is used to finalize the oauth process. This escaped redirect URL is then assigned directly to `window.location` to finalize the redirect. Browsers can properly handle most of the escaped URL components, with the exception of HTML entity based ampersands: `&amp;`. The `&amp;`'s are left in the redirect URL after the redirect has completed, leading to broken redirects in some cases.
This PR makes sure `&amp;`'s are converted back to `&`'s before the redirect URL is assigned to
`window.location`.
Fixes #9279.
> Unescape ampersands in oauth redirect URLs

- tools/cli/commands.js
- tools/cli/default-npm-deps.js
- tools/static-assets/skel-full/.meteor/packages
- tools/static-assets/skel-full/imports/api/links/links.tests.js
- tools/static-assets/skel-full/imports/api/links/methods.tests.js
- tools/static-assets/skel-full/imports/api/links/server/publications.tests.js
- tools/static-assets/skel-full/package.json
While looking into issue #9480 I noticed that running `meteor create --full` (`devel` branch) returns errors caused by the `--full` app skeleton using the deprecated `practicalmeteor:mocha` package. This PR replaces `practicalmeteor:mocha` with the more up to date and maintained `meteortesting:mocha` package, in the `--full` app skeleton, along with using `chai` from npm instead of `practicalmeteor:chai`.
> Update meteor create --full to use meteortesting:mocha

- packages/accounts-facebook/package.js
- packages/accounts-github/package.js
- packages/accounts-google/package.js
- packages/accounts-meetup/package.js
- packages/accounts-meteor-developer/package.js
- packages/accounts-twitter/package.js
- packages/accounts-weibo/package.js
All external service `accounts-*` packages (`accounts-facebook`, `accounts-github`, etc.) are currently using ES2015 syntax ([example](https://github.com/meteor/meteor/blob/3f8c90a29f26ec6dc8ff55f736c36a68fa40398f/packages/accounts-facebook/facebook.js#L4)), but do not explicitly declare a dependency on the `ecmascript` package. This means the ES2015 syntax being used is not transpiled by Meteor, and can lead to issues like #9506. Since `accounts-base` and `accounts-password` both already have `ecmascript` as a dependency, this PR adds an `ecmascript` dependency to all external service `accounts-*` packages.
Fixes #9506.
> Add missing ecmascript dependency to accounts-* packages

- tools/static-assets/server/boot.js
These changes are needed to get the plugin meteor-coverage working. IstanbulJS (shipped with meteor-coverage), can only generate the coverage-report for the code loaded after it's initialization. This is why the code, the plugin meteor-coverage contains, must be executed before the code is loaded, which should be tracked in the code-coverage. A suitable check I found was when a debugger isn't used, which makes it impossible to use code-coverage and the debugger at the same time. It's the only feasible condition I could come up with.
The package meteor-coverage also registers a hook of IstanbulJS which overwrites `vm.runInThisContext()` in order to start the coverage. As of now, IstanbulJS does not support overwriting `vm.Script.runInThisContext()`.
In order to get code-coverage fully …
> Add back the possibility to use IstanbulJS as plugin

- scripts/windows/appveyor/install.ps1
We seem to get misleading AppVeyor failures a lot from EPERM errors on `meteor --get-ready`, so this PR modifies the script `install.ps1` to attempt three times before failing.
> Avoid AppVeyor failures from EPERM errors

- History.md
- packages/accounts-base/accounts_client.js
- packages/accounts-base/accounts_client_tests.js
- packages/accounts-base/accounts_common.js
- packages/accounts-base/accounts_server.js
- packages/accounts-base/package.js
Client side `Accounts.onLogin` callbacks are triggered after a successful login, but they're also triggered after a successful DDP reconnect (if already logged in). As discussed in #5127, some people think this is the correct behaviour, while others feel that `onLogin` callbacks should really only fire after a user has actually logged in (e.g. after using something like `Meteor.loginWithPassword`). Since people are split on the proper approach here, an alternative solution would be to provide client side `Accounts.onLogin` callbacks with a way to tell if they're being called after a login or after a reconnect, then let them decide what to do.
Server side `Accounts.onLogin` callbacks receive an object that contains various login details. One of those items is a login `type`, that can hold …
> Pass login type to client side Accounts.onLogin callbacks

- scripts/dev-bundle-server-package.js
- scripts/dev-bundle-tool-package.js
Since these packages aren't published to the npm registry, they can be made private to avoid unnecessary warnings about missing description, repository, and license fields when installing server dependencies and generating dev bundles.
Example output of `npm install` in the `programs/server` directory of a production bundle:
Before:
```
...
"node": "8.4.0",
"openssl": "1.0.2l",
"tz": "2017b",
"unicode": "9.0",
"uv": "1.13.1",
"v8": "6.0.286.52",
"zlib": "1.2.11"
}
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
added 136 packages in 11.314s
```
After:
```
...
"node": "8.4.0",
"openssl": "1.0.2l",
"tz": "2017b",
"unicode": "9.0",
"uv": "1.13.1",
"v8": "6.0.286.52",
"zlib": "1.2.11"
} …
```
> Make "meteor-dev-bundle" and "meteor-dev-bundle-tool" packages private

- packages/caching-compiler/multi-file-caching-compiler.js
- packages/caching-compiler/package.js
Previously, `.cache` filenames were simply a hash of the absolute path of the `inputFile`, which allowed for cache collisions (on disk) between the same file compiled for different architectures (`web.browser`, `os.*`, ...). Now, the `.cache` filenames are generated based on whatever information the compiler plugin deems uniquely identifying about the input file: whatever is returned from `getCacheKey`, plus the absolute path of the file.
> Generate MultiFileCachingCompiler .cache filenames based on getCacheKey.

- packages/es5-shim/package.js
Since Cordova renders boilerplate HTML at build time, and doesn't use the server-render system through the webapp package, it's important that we include `es5-shim` (and sham) statically for Cordova clients.
This logic will go away once we have the `web.browser.legacy` system to control differential bundling (#9439), but for now it's necessary for any Cordova clients that still don't have full ECMAScript 5 support.
> Always include es5-shim in Cordova JS bundles.

- History.md
- packages/npm-mongo/.npm/package/npm-shrinkwrap.json
- packages/npm-mongo/package.js
- scripts/admin/test-packages-with-mongo-versions.rb
- scripts/build-dev-bundle-common.sh
- scripts/generate-dev-bundle.ps1
- scripts/generate-dev-bundle.sh
- tools/runners/run-mongo.js
This PR updates the Meteor Tool to use Mongo 3.6.2 for 64-bit OS' and Mongo 3.2.18 for 32-bit OS' (I've left the garbage `BUNDLE_VERSION` in place intentionally, since these changes will require a new `dev_bundle` publish from MDG). 
A few important mentions:
- As of Mongo 3.6, all Mongo binary downloads include SSL - there is no longer a non-SSL based download bundle (so it's a bit bigger, but that shouldn't be an issue).
- Using the `--nojournal` option with WiredTiger based replica sets is no longer supported (see https://jira.mongodb.org/browse/SERVER-30760). The `--nojournal` flag was added in https://github.com/meteor/meteor/commit/bcfe072d5233be5892f715d27ca9dce69089242d to help reduce the amount of disk space used by Mongo, but since this option is no longer supported, we'll have …
> Upgrade to Mongo 3.6

- .circleci/config.yml
- History.md
- appveyor.yml
- tools/tests/command-line.js
- tools/tests/compiler-plugins.js
- tools/tests/minifier-bad-plugins.js
- tools/tests/old.js
- tools/tool-testing/selftest.js
While doing some test work on another PR, I accidentally ran a `meteor self-test` without my usual `--exclude` list. When that happened, I noticed that  https://github.com/meteor/meteor/commit/cc472785641edc8d5d6c5da152ff00166c3d6e72 broke one of the `command-line: old cli tests (converted)` self-test's, that is no longer usually called (it's currently excluded by the CI configs).  Looking into fixing this has sent me on a complete tangent (it must be Friday 🙂), leading to this PR ...
Meteor's CI infrastructure is configured to exclude certain `self-test`'s on each run. These excludes are specified in each CI environment's config file, and included when running `meteor self-test`. Developers running `meteor self-test` locally however are not using these excludes by default, so developer's …
> Add a self-test skip option

- packages/ecmascript-runtime-client/package.js
- packages/ecmascript-runtime-client/runtime.js
- packages/ecmascript-runtime/runtime-tests.js
I think this should also fix the failing tests for https://github.com/meteor/meteor/pull/9636
> Add support for string padLeft/padRight

- .circleci/config.yml
- tools/tests/hot-code-push.js
This PR aims to reduce the TTGC (time to green check?) on the CircleCI workflow. The last build on `devel` clocked in at [45:48](https://circleci.com/workflow-run/1f129dbc-2189-4ad2-99d0-804205cb038c). I'd like to get this to sub 20:00.
Here are some techniques/ideas for improving the speed:
Currently Group 2 is taking roughly twice as long as the others
`javascript hot code push` in particular tends to have to retry at least once each run.
- ~~Add a time-limited polling-match function to self-test 
I don't know if this is feasible, but right now we wait a fixed number of seconds before running `match`, so there is dead time we could cut down by trying a `match` every second or two and only failing if it exceeds the time limit. This could also have a start-from time so we don't poll if we …
> Faster CircleCI workflow

- tools/cli/commands.js
- tools/cli/help.txt
- tools/meteor-services/deploy.js
- tools/tests/galaxy.js
- This changes meteor deploy to poll the /version-status/ REST endpoint that Galaxy now exposes for the build and deploy status of the version being deployed
- Allows users to set a flag to change the polling timeout or to not wait at all
- Also fixes up some typos and outdated references
> Make `meteor deploy` synchronous

- tools/runners/run-mongo.js
Introduces an environment variable (MONGO_BIND_IP) for overriding of meteor's mongod's `bind_ip` option to allow docker containers to bind on `0.0.0.0` to be able to expose mongod processs via docker's `-p 3001:3001` port bindings.
Related issue: https://serverfault.com/questions/758225/cannot-connect-to-mongodb-in-docker
Partially Related PR: https://github.com/meteor/meteor/pull/469
> Introduce MONGO_BIND_IP override

- packages/minifier-css/minifier.js
- packages/minifier-css/package.js
- packages/standard-minifier-css/package.js
This PR disables [unsafe `cssnano` minification optimizations](https://github.com/ben-eb/cssnano/blob/6bef71fb165a364ab97c6aad66d69e122d585b7a/src/index.js#L102-L122), which change semantics and make assumptions about CSS that aren't valid for all Meteor apps. For example, the [`discardUnused`](http://cssnano.co/optimisations/discardunused/), [`mergeIdents`](http://cssnano.co/optimisations/mergeidents/), and [`zindex`](http://cssnano.co/optimisations/zindex/) optimizations assume that all CSS files of an app are concatenated before minification. However, CSS files that are imported as modules are processed separately from eagerly loaded CSS.
Fixes #9616, fixes #9633
> Disable unsafe `cssnano` minification optimizations

- packages/test-in-console/package.js
- packages/test-in-console/runner.js
During the Meteor 1.6.1 beta period, we introduced logic to render a `<script>` tag to load the SockJS library in older browsers (#9353), and so it seemed important to run test-packages both with and without the `<script>` tag, using a special query parameter appended to the app URL.
The #9353 changes were ultimately reverted before Meteor 1.6.1 was released (see 365804218fc1c7d5a0d9c99a1f5635b4730e2356), and Meteor 1.6.2 will take a very different approach to bundling dependencies like SockJS for legacy browsers (#9439).
As part of this approach, PhantomJS is always considered a legacy browser, and as such provides valuable feedback on the behavior of `web.browser.legacy` bundles. However, since there's nothing to
configure with regard to SockJS anymore, there's no point in running the …
> Stop running test-packages twice in PhantomJS.

- packages/non-core/coffeescript-compiler/.npm/package/npm-shrinkwrap.json
- packages/non-core/coffeescript-compiler/package.js
- packages/non-core/coffeescript-test-helper/package.js
- packages/non-core/coffeescript/package.js
I also bumped the versions of its dependencies, and changed `ecmascript-runtime` to be implied on both client and server. @benjamn, was there a reason we were implying `ecmascript-runtime` only on the server? Don’t we want polyfills on the client as well?
> Bump CoffeeScript to 2.2.1

- History.md
- packages/promise/common.js
- packages/promise/package.js
- packages/promise/promise-tests.js
Adds `Promise.prototype.finally` support to Meteor's `promise` package. Let me know if I missed anything. Thanks!
Fixes #9639.
> Add Promise.prototype.finally support

- packages/meteor/dynamics_browser.js
There is no way how to read errors thrown in functions that is wrapped in bindEnvironment.
If your function throws only what you get is eg:
"Exception in delivering result of invoking 'someMethod': call stack here", but there is no way how to get message or reason of Error that caused exception, you get only the call stack.
My pull request makes error reporting more consistent, making it same behaviour as Meteor.apply [livedata_connection.js#L731](https://github.com/pravdomil/meteor/blob/fb1fd254b0f938a8efa5662499cfe77b92105127/packages/ddp-client/common/livedata_connection.js#L731) or [livedata_connection.js#L712](https://github.com/pravdomil/meteor/blob/fb1fd254b0f938a8efa5662499cfe77b92105127/packages/ddp-client/common/livedata_connection.js#L712)
> Report errors that is thrown in functions wrapped in bindEnvironment

- packages/accounts-password/package.js
- packages/accounts-password/password_server.js
- packages/accounts-password/password_tests.js
This PR fixes #9651 by dynamically evaluating `Accounts._bcryptRounds`.
> fix setting bcryptRounds using Accounts.config()

- CONTRIBUTING.md
- ISSUE_TRIAGE.md
Issue triage documentation changes outlining the new bug lifespan timelines we've discussed previously. Thanks!
> Document new bug triage timelines

- History.md
- packages/mongo/collection.js
- packages/mongo/collection_tests.js
Reverts meteor/meteor#9671. 
As discussed in https://github.com/meteor/meteor/pull/9671#issuecomment-369462985, we're going to handle this a bit differently (we'll throw an error when an `undefined` field is found instead of automatically stripping it).
> Revert " Update Mongo.Collection to strip undefined fields"

- History.md
- tools/cli/help.txt
- tools/isobuild/compiler-plugin.js
- tools/isobuild/package-source.js
- tools/project-context.js
- tools/tests/app-config.js
- tools/tests/apps/app-config/.meteor/versions
- tools/tests/apps/app-config/package.json
- tools/tests/apps/app-config/tests.js
- tools/tests/apps/modules/package.json
- tools/tests/apps/modules/tests.js
Similar to #9690, this PR adds support for a `meteor.testModule` configuration in application `package.json` files, allowing application developers complete control over what test files should load when running `meteor test` to test their applications.
Setting `meteor.testModule` is a great way to specify test entry points explicitly, rather than relying on Meteor's `isTestFilePath` [heuristics](https://github.com/meteor/meteor/blob/devel/tools/isobuild/test-files.js). However, this feature is entirely opt-in, so the old behavior is preserved if you do not configure `meteor.testModule`.
The syntax is identical to `meteor.mainModule`, so you can set a different `meteor.testModule.{client,server,...}` for each platform. If a `testModule` is not specified for a platform, then Meteor's …
> Support a meteor.testModule section in application package.json files.

- History.md
- packages/meteor-base/package.js
- tools/tests/apps/custom-minifier/.meteor/packages
- tools/tests/apps/custom-minifier/code.js
- tools/tests/apps/ddp-heartbeat/.meteor/packages
- tools/tests/apps/ddp-heartbeat/server/heartbeat_test.js
- tools/tests/apps/failover-test/.meteor/packages
- tools/tests/apps/failover-test/server/failover-test.js
- tools/tests/apps/modules/.meteor/packages
- tools/tests/apps/modules/tests.js
- tools/upgraders.js
This should shave down bundle sizes by 14.4 kb for many non-blaze projects.
The other core meteor packages have not depended on `underscore` since #9362. However, we are only able to remove this last dependency now due to the the first commit in this PR, which eliminates usages of `underscore` from apps that did not have the package listed in their `packages` files. This was causing CI test failures that now should be corrected.
Any meteor apps currently using `_` without `underscore` listed in their `packages` file will need to add the package explicitly.
`meteor-base` version number bumped from 1.3.0 to 1.3.1.
There are only a few uses of `underscore` in these apps, and two of them actually used `underscore` without having it explicitly listed in their `packages` file.
This is a …
> Remove underscore from meteor-base

- packages/check/isPlainObject.js
- packages/check/match.js
- packages/check/match_test.js
- packages/check/package.js
The next package in the list, alphabetically. I considered switching the `Match` export to an instance of a class, but ended up leaving it alone. If there is a good reason to switch it, then I can go back and do that!
> Modernize check package

- .circleci/config.yml
- scripts/test-balancer/.gitignore
- scripts/test-balancer/index.js
- scripts/test-balancer/package-lock.json
- scripts/test-balancer/package.json
This PR builds on the work done to improve TTGC (time to green check) in #9627. In that PR, file-matching regular expressions were manually adjusted to try to balance the test groups. In this PR we optimize at the test level instead of the file level, and automate the process, readjusting after every build. Thanks for the suggestions @abernix!
This PR still has some gaps, but the stats look like they are going in the right direction:
* Automated balancing standard deviation: [123 seconds](https://circleci.com/workflow-run/440f8e4f-8b60-4306-986b-142f42671e3a)
* Manual balancing standard deviation: [182 seconds](https://circleci.com/workflow-run/f64f6df7-0820-4164-977f-68f243aa05ac)
Some notes:
- A new job now runs after all test groups finish. It runs a node app that reads the persisted …
> Automate rebalancing of CircleCI test groups

- packages/deprecated/stylus/README.md
- packages/deprecated/stylus/deprecation_notice.js
- packages/deprecated/stylus/package.js
The `stylus` deprecation notice is pointing to the wrong last non-deprecated version. It should refer to `2.513.13`. I've updated the references accordingly (and we'll need to publish a new version so I've bumped the patch version). Thanks!
> Update stylus deprecation notice to use proper last version

- packages/ddp-client/common/livedata_connection.js
- packages/ddp-client/package.js
This is an addition for #9654 and also solves the issue in #9684.
The error object (and with it the stack trace) is lost when calling a method without a callback.
> preserve error object in method callback

- tools/static-assets/skel/package.json
- tools/static-assets/skel/test/main.js
In order for Meteor to maintain its commitment to being a zero-configuration tool, any configuration options that we add must come pre-configured in the best way possible for newly created apps.
> **Important note:** Meteor is still, and always will be, to its core, a zero-configuration tool. Though it may be tempting to slide down the slippery slope towards even more configuration options in the `meteor` section of `package.json`, we are not interested in allowing configuration complexity to explode, and we intend to maintain an extremely strict standard of necessity for any future options. Please don't think of the `meteor` section as a place to solve one-off problems with ad-hoc options.
In particular, the default new Meteor app must contain a reasonable testing story, or else we are …
> Use meteor.{mainModule,testModule} for `meteor create` starter apps.

- packages/webapp/webapp_server.js
This is a small fix that allows users to customize how WebApp listens for TCP connections.
> webapp: allow overriding httpServer.listen

- tools/cordova/run-targets.js
Hi,
by using a pod-based cordova plugin (like phonegap-push-plugin) in a project, opening the configuration file instead of the folder prevents these pods from being included.
This PR change the way Xcode is opened.
Regards,
> open Xcode project folder instead of project file

- packages/meteor/dynamics_nodejs.js
- packages/meteor/package.js
This reverts commit 573f14f171251d475be0d590a72b0f2ce94a35b2.
As discussed with @glasser, this change may have been more disruptive than helpful (e.g. #9730) and could also have negative performance consequences. Since we don't actually rely on `withValue` awaiting the result of the callback (yet), it seems safest to revert this change, and possibly add a different method called something like `withAwaitedValue` at some later time, if necessary.
Fixes #9730.
> Revert "Allow EnvironmentVariable#withValue callbacks to return Promises."

- .circleci/config.yml
While working on #9656, I noticed that we are using a single immutable cache on all builds, rather than updating the cache as dependencies change. This means that the 'Get Ready' job on CircleCI ends up downloading the dev bundle every single time and updating a lot of dependencies that probably haven't changed for months.
This PR implements a caching strategy using [templates](https://circleci.com/docs/2.0/caching/#using-keys-and-templates) that will only download a new dev bundle when the `meteor` file is changed (this is where the dev bundle version number is maintained), and which re-caches `.babel-cache` and `.meteor` on every run, but is loaded based on the branch.
This isn't an ideal strategy, but it saves roughly 2-3 minutes on the 'Get Ready' job compared to what we have …
> Improve CircleCI caching strategy

- packages/oauth/oauth_server.js
- packages/oauth/package.js
With commit 3b18863, connect handlers are guaranteed to run in a fiber, making the fiber wrapper in the OAuth middleware superfluous. Additionally, because it manually wraps the middleware in a Fiber directly, it is losing access to the properties stored in the existing fiber (meteor/meteor-feature-requests#156).
> Removed fiber wrapper around OAuth middleware.

- packages/oauth/oauth_server.js
- packages/oauth/package.js
Fiber no longer needs to be imported because its only usage was removed. See https://github.com/meteor/meteor/pull/9740.
> Remove oauth fiber import
