packages/blaze/template.js, packages/spacebars-tests/template_tests.js
Fixes the bug introduced in previous PR: #3171 
@stubailo, can you please review it?
=> Fix the bug of firing a rendered callback when it was added too late

tools/package-client.js
=> fixed some typos that caused error message to end abruptly

docs/.meteor/packages, docs/.meteor/versions, docs/client/lib/navigate.js
Helps address the issue of accessing https://docs.meteor.com and being redirected to http://docs.meteor.com.
=> Adjusted Meteor.absoluteUrl() to use the secure setting.

tools/commands-cordova.js
Fixes typos in cordova commands
=> Fixes typos in cordova commands

packages/twitter/twitter_configure.html
=> updating the twitter configure message

docs/client/basic/introduction.html
Add missing space between words.
=> Fixes #4149.

packages/coffeescript/.npm/plugin/compileCoffeescript/npm-shrinkwrap.json, packages/coffeescript/package.js
=> Upgrade coffeescript core package to v1.9.2.

packages/reactive-dict/reactive-dict.js
=> ReactiveDict should hold onto dictName?

tools/isobuild/README.md
Also, "marketing material" doesn't seem like an accurate description of the page on the Meteor site as it's more of a high level description of the component.
=> Fix grammar

tools/cli/commands.js
=> Support creating new meteor app in current directory

tools/cli/commands-aliases.js
=> Remove stray comments from command aliases.

packages/reactive-dict/reactive-dict-tests.js, packages/reactive-dict/reactive-dict.js
Fixes #5530
From @sprohaska's comment: https://github.com/meteor/meteor/issues/5530#issuecomment-151186970
=> Check for the existence of a keyValueDep in ReactiveDict clear

packages/http/httpcall_common.js, packages/http/package.js
=> Fix HTTP.call to not explode on undefined content

History.md, docs/client/data.js, packages/ddp-rate-limiter/ddp-rate-limiter.js, packages/ddp-rate-limiter/package.js
Technically, this is a "breaking change" since code that is loaded
on client and server will now throw an error when calling DDPRateLimiter,
but the API didn't do anything on the client anyway so it's probably
more like a bug fix.
=> Make sure it's clear that DDPRateLimiter is on the server

packages/mongo/collection.js
=> return the observeHandle in Mongo.Collection._publishCursor

packages/spacebars-tests/template_tests.html, packages/spacebars-tests/template_tests.js, packages/spacebars/spacebars-runtime.js
I've verified that the new tests pass. Two of the new test cases were broken prior to this change. I've also verified that this change fixes the example program from the issue page, in a really hacky way - I manually patched the fix into the build directory. What's the better way to verify a package fix?
=> Fix https://github.com/meteor/meteor/issues/5441

tools/isobuild/bundler.js
Probably makes things a bit faster.
=> Unnecessary variable

scripts/generate-dev-bundle.sh
Reproducible builds and stuff.
=> Make sure no user configuration is used

packages/mongo/collection.js
I needed this so many times I lost the count.
=> Allow to find the corresponding collection from the store

tools/utils/utils.js
=> Remove duplicate exports.hasScheme

packages/webapp/webapp_server.js
=> Wrap connect middleware function into a Fiber

Contributing.md
For @stubailo, per sharing via https://forums.meteor.com/t/how-open-source-meteor-really-is-if-pull-requests-are-not-getting-in/16483/63.
A small start for a Friday afternoon :)
Sign offs to merge this PR:
=> First draft for sharing new ownership of code sections in Meteor.

tools/cordova/project.js
This is the issue: https://github.com/meteor/meteor/issues/6178
=> Add default value for cordova run argument - extraPaths (Fixes #6178)

packages/blaze/template.js
=> Cleaner code

Contributing.md
=> Contributing.md: improve grammar

tools/tool-env/profile.js
I took inspiration from the Unix [`tree`](https://en.wikipedia.org/wiki/Tree_%28Unix%29) command to modify the profile output to emphasize the hierarchal relations between the tree items.
A gist containing both the old and the new proposed formating is available [here](https://gist.github.com/mquandalle/ae441310cdd466eddf8b), though GitHub formating isn’t as good as the one on a terminal because Github insert some vertical space in between the text lines.
cc @dgreensp
=> Emphasize the tree structure in the profile output

tools/cli/help.txt
First pass at this. TBH I'm not totally sure what goes in here. Am I right to call out to the guide? Should we do this in other spots of the help?
=> Added some help text for meteor test-app

tools/cli/commands-packages.js
#6264 
The old error may confuse some beginners, and this PR should breaks nothing.
Also want to see the change in 1.3 :)
=> Accurate error in removing a non-direct dependency.

tools/cli/commands.js, tools/cli/help.txt
=> Require that you specify a driver package for app tests

packages/minimongo/minimongo_tests.js, packages/minimongo/selector.js
=> Fixed $elemMatch with logical operators in Minimongo

packages/ddp-server/livedata_server.js
=> Show name of missgin method or subscription.

History.md, packages/check/jquery.js, packages/check/match.js, packages/check/match_test.js, packages/check/package.js
=> Require plain objects for Match.ObjectIncluding

packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/meteor-env-dev/server.js, packages/meteor-env-prod/server.js, packages/meteor/package.js, packages/meteor/test_environment.js, tools/cli/commands.js, tools/isobuild/linker.js, tools/runners/run-app.js
=> Fix meteor istest for packages 6331

tools/cli/commands.js, tools/cli/help.txt, tools/runners/run-all.js
See the commit note and issue #6454
=> Ensure that runAll always sets NODE_ENV+buildMode sensibly.

tools/cli/commands-packages.js
=> Correct the info of update when on latest recommended release.

packages/underscore/package.js
Maintains documentation of code
=> Fix spelling mistake in underscore package

Contributing.md, Roadmap.md
Hey @benjamn and @tmeasday . Could you please review the proposed updated Roadmap. This format is inspired by [Docker's roadmap](https://github.com/docker/docker/blob/master/ROADMAP.md). Am I missing something obvious?
=> First pass at an updated roadmap

packages/ddp-client/livedata_connection.js, packages/ddp-client/livedata_connection_tests.js, packages/minimongo/minimongo.js
=> Process DDP updates in batches

tools/cli/commands-packages.js
#5384
Give a hint when user try to update packages outside an app.
=> Fixing #5384

meteor, packages/stylus/package.js, packages/stylus/plugin/compile-stylus.js, scripts/dev-bundle-tool-package.js, tools/tests/autoupdate.js, tools/tests/compiler-plugins.js, tools/tests/package-tests.js, tools/tests/parse-stack-test.js, tools/tool-testing/selftest.js, tools/utils/parse-stack.js
@benjamn can you please check that I did the right thing in adding this to the dev bundle
=> Use longjohn to repair stacktraces on self-test

Contributing.md
maintability => maintainability
un-ambigous => unambiguous
likelyhood => likelihood
=> [docs] Spelling corrections on Contributing.md

README.md
=> Added circle token

tools/isobuild/package-source.js
=> Ensure that test files for both kinds of tests.

packages/twitter/twitter_client.js
Adding support for force_login:
https://dev.twitter.com/oauth/reference/get/oauth/authenticate :sparkle:
/cc #5693 @tmeasday
=> Handle force_login parameter in Twitter package

Contributing.md
I was reading the `Contributing.md` guide in order to make my first contribution to Meteor and found those two typos.
=> Fix typo in Contributing.md

README.md
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.
Always follow the [contribution guidelines](https://github.com/meteor/meteor/blob/devel/Contributing.md) when submitting a pull request. In particular, make sure existing tests still pass, and add tests for all new behavior. When fixing a bug, you may want to add a test to verify the fix.
=> Correct the format of CircleCI badge.

packages/minimongo/minimongo_server_tests.js, packages/minimongo/minimongo_tests.js, packages/minimongo/selector.js, packages/minimongo/selector_modifier.js
=> Merge 4235

tools/tool-testing/selftest.js
Use symlinking to speed up selftest init times
=> Speed up selftest

scripts/windows/installer/WiXInstaller/Resources/Theme_Meteor.xml
#6684 
I replaced "free service" with "publishing Atmosphere packages", because it might be more useful for developers instead of just advertising Galaxy.
=> Update text in Windows installer (Fixing #6684)

tools/cli/commands.js
#1469 , an issue long long ago.
=> Warn users when they meteor reset with MONGO_URL.

.eslintignore, .travis.yml, packages/logging/logging.js, packages/logging/package.js, packages/mongo/mongo_livedata_tests.js, scripts/admin/eslint/package.json, scripts/ci.sh, tools/cli/commands.js, tools/runners/run-log.js, tools/tests/autoupdate.js, tools/tests/package-tests.js, tools/tests/releases.js, tools/tests/run.js, tools/tests/source-maps.js, tools/tests/test-modes.js, tools/tests/wipe-all-packages.js, tools/tool-testing/selftest.js
20 minute, consistent selftest anyone?
See #7087
=> Fix flaky tests

tools/isobuild/meteor-npm.js
=> Use NPM_CONFIG_REGISTRY.

packages/ddp-server/livedata_server.js
This is a rebased version of https://github.com/meteor/meteor/pull/6658
=> Awwx simplify connected msg code

packages/check/match.js, packages/check/match_test.js
Fix for `check` max-recursion when called on circular references. This is a stop-gap fix for a bigger issue with `EJSON.stringify` working on circular objects.  #4778 *apparently* fixes most *other* `EJSON` methods but it's not even clear it if it would fix the `.stringify` problem properly (after all, `JSON.stringify` doesn't either).  Also, that PR is over a year old.
This fix takes the approach of trying to fix the calling of `EJSON.stringify` with an object that it can't work with.  It's doing this by trying the native `JSON.stringify` to see if it would work.  If that returns a `TypeError`, then it just dumbs-down the object to the `typeof`.
Also added a lot of tests
I can't say it's the absolute best, but it *will* take care of:
* Fix #6712
* Fix #4587
Depends on #6736 …
=> Fix for `check` max-recursion when called on circular references

packages/google/google_configure.html
Google changed them. Again. I also decided "Click" is a better verb than
"Press", so I changed that as well.
=> Update Google client ID instructions again

packages/ddp-rate-limiter/README.md
Refer to correct usage: http://docs.meteor.com/api/methods.html#ddpratelimiter
=> DDPRateLimiter, change method to name

packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, tools/cli/dev-bundle-links.js, tools/cli/dev-bundle.js, tools/isobuild/meteor-npm-userconfig, tools/project-context.js
New bug(s):
You can update to this release by running
```sh
meteor update --release 1.3.4.4
```
in any application directory.
=> Release 1.3.4.4

packages/email/.npm/package/npm-shrinkwrap.json, packages/email/email_tests.js, packages/email/package.js
Basic version upgrade.  Just seeing if tests run.
Fixes #7347
Also removes incorrectly copy-pasted comment left over from #7128
=> Update simplesmtp to 0.3.34

packages/mongo/collection.js
Fixes https://github.com/meteor/docs/issues/63
=> Note in docs that findOne can return undefined

tools/cli/commands.js
#7393 
May need further discussions on this problem.
=> Add a warning when use --production.

tools/isobuild/package-source.js
For https://github.com/meteor/meteor/issues/7494
=> More subtle logic for deciding when test files should be lazily loaded

meteor, scripts/dev-bundle-tool-package.js, tools/utils/http-helpers.js
This implements my suggestion in [this comment](https://github.com/meteor/meteor/pull/7539#issuecomment-236598133).
=> Implement a simple ConcatStream class instead of using the concat-stream npm package

tools/isobuild/linker.js
I've described the issue here #7484, please take a look, see if this fix makes sense.
=> Fix source map header for the prelinked files

meteor, scripts/dev-bundle-server-package.js
This will help with running `npm rebuild` in `bundle/programs/server`, fixing problems like #7568.
=> Add node-gyp and node-pre-gyp to dev_bundle/server-lib/node_modules

History.md
* Broken: https://github.com/meteor/meteor/issue/7397
* Working: https://github.com/meteor/meteor/issues/7397
=> Fix broken links in the changelog

History.md
=> Make commits links in changelog

History.md, packages/accounts-password/password_client.js, packages/accounts-password/password_tests.js
See https://github.com/meteor/meteor/pull/7117
Squashed and fixed up a little.
=> Laosb rebase 5681 fixed

History.md
Fix URL to issue fixed in 1.4.1.1 in History.md
=> Fix URL issue in History.md

tools/cli/commands.js, tools/cli/help.txt
=> Use -s as short form of --settings flag

tools/cli/dev-bundle.js
=> Protect against null return values from getDevBundleForRelease

packages/observe-sequence/observe_sequence.js, packages/observe-sequence/observe_sequence_tests.js
=> observer-sequence: Bug, array with null values. fixes #7850

packages/accounts-base/accounts_common.js, packages/accounts-base/accounts_server.js, packages/accounts-password/password_server.js, packages/accounts-password/password_tests.js
=> Separate timeouts for expiration of password reset and enrollment

packages/ddp-common/method_invocation.js, packages/ddp-server/livedata_server.js, tools/isobuild/package-api.js, tools/isobuild/package-cordova.js, tools/isobuild/package-namespace.js, tools/isobuild/package-npm.js
Some changes in order to get the `package.js` section working again.
@benjamn I'm not sure if it's breaking process but it'd be good to merge into `master`.
cc @abernix
=> JSdoc refactoring to make API boxes work again.

scripts/windows/download-dev-bundle.ps1
I recently had the pleasure of running Meteor from a `git` checkout on Windows while debugging an issue.  This helps, a bit.  From my commit message:
The `SAVE_DEV_BUNDLE_TARBALL` environment variable is already supported in the Unix version and this mimics that functionality in the Windows script.  Use of this flag makes debugging much less painful, especially when switching branches (for example, during a `git bisect`) as the `dev_bundle` can be cached locally.
I also replaced a couple un-related uses of `echo` with `Write-Host` which is the preferred way to output messages in PowerShell as it supports more options (i.e. `-NoNewLine`) and allowed some longer lines to get wrapped.
=> Support SAVE_DEV_BUNDLE_TARBALL caching on Windows dev_bundle install

packages/twitter/twitter_configure.html
=> Twitter changed this

packages/minifier-js/package.js
=> update min js

packages/oauth/end_of_popup_response.html, packages/oauth/end_of_redirect_response.html, packages/oauth/oauth_server.js, packages/oauth/oauth_tests.js
=> Fix oauth ROOT_URL_PATH_PREFIX

packages/ddp/DDP.md
Hi guys - this small PR is intended to help address the DDP error doc inconsistencies outlined in issue #7240. Thanks!
=> Adjusted DDP error docs to reflect proper error object properties

packages/twitter/twitter_configure.html
In reference to https://github.com/meteor/meteor/issues/8190.
=> Fixed twitter_configure.html URL

tools/isobuild/bundler.js, tools/isobuild/linker.js
Hi all - this PR relates to issues #5706 and #6222. It's really just a resurrection of PR #6201 (which looks like would have been approved if further changes were made), and is a pre-requisite to make it further on #5706 and #6222 (which have quite a bit of interest in the community).
Short story short - I've made the changes requested in PR #6201, as well as adjusted the `bundler` to also use the `colon-converter` util, to line things up a little more. 
Let me know if you need anything changed - thanks!
=> Added extra colon-converter calls to the bundler and linker.

History.md
Hi all - this small housekeeping PR is intended to help address issue #8193 (by adding release dates beside release version numbers in the `History.md`. Thanks!
=> Added release dates beside release version numbers (to address #8193).

History.md, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, tools/isobuild/bundler.js
Quick follow-up to 1.4.2.4 and 1.4.2.5 to fix the following critical issue:
=> Release 1.4.2.6

tools/isobuild/bundler.js
- Update node version in generated README file by bundler, according to version from `.node_version.txt` file
=> Update generated README

tools/cli/help.txt
Hi guys - this small PR is intended to help address issue #8154, by adding in missing CLI `meteor update --all-packages` help text. Thanks!
=> Added CLI help text for meteor update --all-packages.

packages/webapp/webapp_server.js
Fixes https://github.com/meteor/meteor/issues/8479
=> Make sure manifest.json contains AUTOUPDATE_VERSION (if specified)

meteor, packages/rate-limit/package.js
=> Adds package rate-limit dependence on ecmascript

History.md, scripts/build-dev-bundle-common.sh, scripts/dev-bundle-tool-package.js, tools/cli/dev-bundle-bin-helpers.js, tools/isobuild/bundler.js
**Update Node.js to v4.8.1.**
Notable changes:
https://nodejs.org/en/blog/release/v4.8.1/
**Update `npm` package to v4.4.4.**
Notable changes:
https://github.com/npm/npm/releases/tag/v4.4.4
I'll highlight this part:
```
LESS VERBOSE ERROR MESSAGES
With this change the output is cut down substantially, centering the error message.
```
This means that users should expect a lot of the extra (generally repetitive and unhelpful) details to go away with this update.  For example, the following verbiage is no longer always present:
```
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the error-prone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo …
```
=> [1.4.3.x-series] Update Node.js, npm, node-gyp, node-pre-gyp.

packages/google-oauth/google_client.js, packages/google-oauth/google_server.js, packages/google-oauth/google_sign-in.js, packages/google-oauth/package.js
This PR fixes the user data fetching issues in new `google-oauth` package, see https://github.com/meteor/meteor/issues/8586 (and the parent ticket https://github.com/meteor/meteor/issues/8253) for details.
The problem was that the new login handler did not fetch the right data (was not using the right endpoint).
Not sure who to notify so I'll just mention @abernix and @benjamn (sorry guys :-) ).
=> Fixed Google OAuth user data fetching.

packages/accounts-base/accounts_server.js, packages/accounts-password/password_server.js
Fix for #8448 
The changes have been made according to the comment- 
> [index should be added in the same package that does the query](https://github.com/meteor/meteor/pull/8163#issuecomment-283767598)
=> Index creation in the file using the query

packages/minimongo/minimongo_tests.js, packages/minimongo/modify.js
#5167 (remade after I messed up #8603)
Allowed $slice on $push to work with positive numbers, like MongoDB.
=> [#5167] $push $slice with positive numbers

packages/minimongo/minimongo.js, packages/minimongo/minimongo_tests.js
Fixes https://github.com/meteor/meteor/issues/8631
=> Remove nested properties from upsert selector document

History.md, circle.yml, meteor, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, scripts/build-dev-bundle-common.sh, tools/isobuild/isopack-cache.js, tools/isobuild/isopack.js, tools/tool-testing/selftest.js, tools/utils/http-helpers.js
This is a very small patch release that includes a routine Node upgrade and a fix for #8709.
=> Release 1.4.4.3

packages/ddp-rate-limiter/README.md
Example was out of date; link was broken 😊
=> Link ddp-rate-limiter README to the docs

README.md
=> Add a Meteor Logo to the top of the README.

History.md
See https://github.com/meteor/meteor/issues/8804
=> Fix documentation on MAIL_URL value

packages/constraint-solver/solver.js, tools/cordova/run-targets.js, tools/isobuild/README.md, tools/isobuild/compiler.js, tools/isobuild/isopack.js, tools/isobuild/package-cordova.js
Updated another bunch of old references to the deprecated Github wiki.
=> Updated old github wiki references to Meteor Guide/API docs

tools/console/console.js
In working on another issue, I did some ninja-modernization of the various classes related to `Console` output.  Probably best to review this commit by commit, as I've grouped them by repetitive actions, particularly if they mainly involved whitespace changes.
=> "Console" ECMAScript Modernization

packages/mongo/package.js
This reverts commit 6820d401c3b2fdb403fa5d3132b6b7ee9847accc.
=> Revert "Un-pin version of `npm-mongo` used in `mongo` package."

packages/mongo/package.js, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js
This includes the changes from #8870 except as a PR against `master` to signify the official release of those packages.
=> `npm-mongo` and `mongo` updates.

meteor, scripts/dev-bundle-tool-package.js
While debugging a continuous segmentation fault issue on our continuous integration server, I was able to obtain a core dump from [this build](https://circleci.com/gh/abernix/meteor/581#artifacts/containers/0) on my own CircleCI 2.0 configuration (PR for that configuration upgrade coming soon).  Using that core dump along with the (awesome!) [`autopsy`](https://github.com/nearform/autopsy) npm package, and the Node.js binary from [that dev bundle](https://github.com/abernix/meteor/blob/3b2355f0432dd32a8f30e0dd3a8247c479dfe95d/meteor#L3), I now have reason to believe (see stacktrace output below) that the `longjohn` npm could be somewhat responsible for the segmentation fault.  This jives with a tidbit of information that I've read before which also linked `longjohn` to a segfault, but I'm …
=> Update `longjohn` to latest version to maybe fix SIGSEGV CI errors.

Roadmap.md
=> Miscellaneous updates to Roadmap.md

Roadmap.md
Describe how and why we can make Meteor better for React devs.
=> Add React section to Roadmap.md.

README.md
These are some quick, starter tweaks which might help present a slightly more accurate image of the project on this relatively important landing page for the project.  For example: I think "modern" JavaScript might be more accurate than pure JavaScript given all the latest and greatest ECMAScript features Meteor supports with zero-configuration, right out of the box.
I think we can improve on this though, so commentary welcome.  What is this README page missing?
=> Tweaks to project README.md.

packages/ddp-rate-limiter/ddp-rate-limiter-tests.js, tools/isobuild/import-scanner.js
Further explanation / discussion: https://github.com/meteor/meteor/issues/9176#issuecomment-335913296
Another (complementary) solution to the same problem: #9190
=> Use module.watch live bindings to solve #9176.

History.md
Removed this change from https://github.com/meteor/meteor/pull/9213 as it goes with https://github.com/meteor/meteor/pull/9198
=> Update History.md for PR #9198

packages/non-core/coffeescript-compiler/.npm/package/npm-shrinkwrap.json, packages/non-core/coffeescript-compiler/coffeescript-compiler.js, packages/non-core/coffeescript-compiler/package.js, packages/non-core/coffeescript-test-helper/exporting.coffee, packages/non-core/coffeescript-test-helper/package.js, packages/non-core/coffeescript/package.js, packages/non-core/coffeescript/tests/coffeescript_tests.coffee, tools/tests/command-line.js, tools/tests/test-modes.js
Surely it can’t be this easy. I bumped the version numbers and the tests all still pass. Should probably get some more tests.
See also https://github.com/meteor/meteor/pull/8728#issuecomment-330431601 @benjamn
=> CoffeeScript 2.0.2

History.md
This cherry-picks the commit from the `History.md` entry on the 1.5.4 release pull-request (#9320) (on the `release-1.5.x` branch) to the `master` branch, in order to form a complete history. :smile: 
📖 ✏️ 📖 🔁
=> Update History.md with changes in Meteor 1.5.4.

packages/webapp/.npm/package/npm-shrinkwrap.json, packages/webapp/package.js, packages/webapp/webapp_client.js, packages/webapp/webapp_server.js, packages/webapp/webapp_tests.js
@benjamn @abernix this is a first step towards upgrading webapp. I think the work around the server render package upgrades and the http2 should be new PR's
The formatting changes are from prettier but they seem to align with some other packages. Happy to change it back!
=> Upgrade webapp to latest connect + middleware packages.

packages/ddp-client/client/client_convenience.js, packages/ddp-client/client/stream_client_sockjs.js, packages/ddp-client/common/id_map.js, packages/ddp-client/common/livedata_connection.js, packages/ddp-client/common/namespace.js, packages/ddp-client/common/stream_client_common.js, packages/ddp-client/common/urlHelpers.js, packages/ddp-client/package.js, packages/ddp-client/server/stream_client_nodejs.js, packages/ddp-client/test/livedata_connection_tests.js, packages/ddp-client/test/livedata_test_service.js, packages/ddp-client/test/livedata_tests.js, packages/ddp-client/test/random_stream_tests.js, packages/ddp-client/test/stream_client_tests.js, packages/ddp-client/test/stream_tests.js, packages/ddp-client/test/stub_stream.js
- single quotes
- 80 char line width
=> Make ddp-client more aligned with code style

packages/check/match.js, packages/check/package.js, packages/dynamic-import/package.js
=> Remove underscore from check package.

tools/cli/commands-cordova.js, tools/cli/commands-packages.js, tools/cli/commands.js, tools/runners/run-app.js, tools/upgraders.js
In the same spirit as the changes made in https://github.com/meteor/meteor/pull/8976.
Fixes: https://github.com/meteor/meteor/issues/9257.
=> Ensure that Cordova is installed for `meteor [add | remove] cordova:*`.

packages/reactive-dict/README.md
The link to the ```tracker``` api was broken.
=> Fix broken link

packages/non-core/coffeescript-compiler/package.js, packages/non-core/coffeescript-test-helper/package.js, packages/non-core/coffeescript/package.js
=> Bump CoffeeScript to 2.0.3

packages/modules/README.md
=> Edit http link in README.md

packages/meteor/url_server.js, tools/cli/main.js, tools/tests/run.js
Fix error message for invalid ROOT_URL #8026
=> Fix error message for invalid ROOT_URL #8026

History.md, meteor, packages/meteor-tool/package.js, packages/mongo/collection.js, packages/mongo/mongo_livedata_tests.js, packages/mongo/package.js, scripts/admin/copy-dev-bundle-from-jenkins.sh, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, scripts/build-dev-bundle-common.sh
A small point release for these upcoming Node security updates: https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/
=> Release 1.5.4.1

History.md, meteor, packages/meteor-tool/package.js, packages/mongo/collection.js, packages/mongo/mongo_livedata_tests.js, packages/mongo/package.js, scripts/admin/copy-dev-bundle-from-jenkins.sh, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, scripts/build-dev-bundle-common.sh
A small point release for these upcoming Node security updates: https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/
=> Release 1.4.4.5

History.md, packages/mongo/collection.js, packages/mongo/mongo_livedata_tests.js, scripts/admin/meteor-release-experimental.json, scripts/build-dev-bundle-common.sh, scripts/generate-dev-bundle.sh
After merging `release-1.5.4.1` into `release-1.5.x` and `release-1.4.4.5` into `release-1.4.x`, this PR serves to merge both `release-1.5.x` and `release-1.4.x` into `master`. I would do this from the command-line, but `master` is a protected branch, and I don't feel like turning off the protection just to avoid jumping through a (worthwhile) hoop.
=> Merge 1.5.x and 1.4.x into master.

packages/ddp/README.md
-change two link
1. from "http://docs.meteor.com/#ddp_connect" to "https://docs.meteor.com/api/connections.html#DDP-connect"
2. from "http://docs.meteor.com/" to "https://docs.meteor.com/"
=> Change http link to https in README.md file

LICENSE
With what stillness at last
you appear in the valley
your first sunlight reaching down
to touch the tips of a few
high leaves that do not stir
as though they had not noticed
and did not know you at all
then the voice of a dove calls
from far away in itself
to the hush of the morning
so this is the sound of you
here and now whether or not
anyone hears it this is
where we have come with our age
our knowledge such as it is
and our hopes such as they are
invisible before us
untouched and still possible
[W. S. Merwin]: https://www.poetryfoundation.org/poets/w-s-merwin
=> Update license range for 2018 🎉

packages/mongo/collection.js
=> Fixes #9531 - removing unnecessary check for Mongo.Collection

packages/ddp-client/common/livedata_connection.js
=> add docs for Meteor.apply options.returnStubValue

tools/packaging/catalog/catalog-remote.js
https://github.com/meteor/meteor-feature-requests/issues/154
meteor works on WSL.  But when multiple instances of Meteor are started at the same time an error is produced
```bash
Error: SQLITE_IOERR: disk I/O error
```
This issue is documented in WSL:
https://github.com/Microsoft/WSL/issues/1927
https://github.com/Microsoft/WSL/issues/2395
And they propose to not use the  `WAL` journaling mode.  For meteor I changed 
https://github.com/meteor/meteor/blob/devel/tools/packaging/catalog/catalog-remote.js#L142-L145
```javascript
// WAL mode copes much better with (multi-process) concurrency
self._retry(function () {
self._execute('PRAGMA journal_mode=WAL');
});
```
To:
https://github.com/brucejo75/meteor/blob/WSL_SQLITE_TRUNCATE/tools/packaging/catalog/catalog-remote.js#L142-L153 …
=> TRUNCATE journal mode for packaging DB on Windows like file systems

packages/base64/base64.js, packages/base64/base64_test.js, packages/base64/package.js
In continuing with the modernization process, I've updated the syntax for the next package in the list, alphabetically.
=> Modernize base64 package

packages/appcache/appcache-client.js, packages/appcache/appcache-server.js, packages/appcache/appcache_tests-client.js, packages/appcache/appcache_tests-server.js, packages/appcache/package.js
In continuing with the modernization process, I've removed the `underscore` dependency and updated the syntax for the next package in the list, alphabetically.
=> Modernize appcache package

packages/ddp-rate-limiter/ddp-rate-limiter-test-service.js, packages/ddp-rate-limiter/ddp-rate-limiter-tests-common.js, packages/ddp-rate-limiter/ddp-rate-limiter-tests.js, packages/ddp-rate-limiter/ddp-rate-limiter.js, packages/ddp-rate-limiter/package.js, packages/rate-limit/package.js, packages/rate-limit/rate-limit-tests.js, packages/rate-limit/rate-limit.js
The usual + another underscore user gone.
Btw, I made the order of the logic operators more clear here: https://github.com/meteor/meteor/compare/devel...sebakerckhof:refactor/modernize-ddp-rate-limit?expand=1#diff-014a5bef05a6deaa5941718de150fde0R401 , but is that really what was meant?
=> Modernize rate limiter

History.md, packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/package.js, packages/standard-minifier-js/package.js
=> Update `uglify-es` to 3.3.10

History.md
=> Fixes link.

packages/non-core/bundle-visualizer/README.md
=> Fix a typo in bundle-visualizer README

packages/mongo/mongo_driver.js, packages/mongo/mongo_livedata_tests.js, packages/mongo/package.js
=> Mongo driver: Fix replaceNames to not replace null with {}.

packages/mongo-id/id.js, packages/mongo-id/package.js
Wanted to join in on the modernizing fun.
It was using a mixture of single and double quotes. Did them all single now, since that's what the airbnb rules prefer.
=> Modernize mongo-id package

History.md, meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/babel-compiler.js, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/ecmascript/transpilation-tests.js, scripts/dev-bundle-tool-package.js, tools/isobuild/isopack.js, tools/static-assets/skel-bare/package.json, tools/static-assets/skel-full/package.json, tools/static-assets/skel/package.json, tools/tests/apps/app-config/package-lock.json, tools/tests/apps/app-config/package.json, tools/tests/apps/dynamic-import/package-lock.json, tools/tests/apps/dynamic-import/package.json, tools/tests/apps/meteor-ignore/package-lock.json, tools/tests/apps/meteor-ignore/package.json, tools/tests/apps/modules/package-lock.json, tools/tests/apps/modules/package.json
https://github.com/babel/babel/releases/tag/v7.0.0-beta.41
https://github.com/babel/babel/releases/tag/v7.0.0-beta.42
=> Update meteor-babel to 7.0.0-beta.42.

packages/modules-runtime/client.js, packages/modules-runtime/server.js, tools/static-assets/server/boot.js
This PR is improved version of #9346 with all suggestions applied (see discussion).
=> Print nicer error message for missing Meteor package

History.md, meteor, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, scripts/build-dev-bundle-common.sh
https://nodejs.org/en/blog/release/v4.9.0/
=> Release 1.5.4.2

History.md, meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/modules/.npm/package/npm-shrinkwrap.json, packages/modules/package.js, scripts/dev-bundle-tool-package.js
https://github.com/babel/babel/releases/tag/v7.0.0-beta.43
https://github.com/babel/babel/releases/tag/v7.0.0-beta.44
=> Update meteor-babel to 7.0.0-beta.44 and reify to 0.15.1.

tools/cli/commands.js
Before this change,
meteor create -- list
would produce output containing the following line:
todos-react: https://github.com/meteor/todos#react
and "meteor create todos-react" would create the blaze version of the todos example.
This is beacause for some reason the code is using a # to append the name of the branch, instead of /tree/ .
=> Correctly append branch locations in create example command

tools/isobuild/package-source.js
Although there was a comment in this code about not applying `.meteorignore` files to the contents of `node_modules` directories, I'm pretty sure that was the wrong decision, because `.meteorignore` merely limits what Meteor tries to compile as application code, and does not actually modify or hide `node_modules` files from other parts of Meteor (or Node).
In other words, there's no harm in letting `.meteorignore` apply to `node_modules`, and there may be a LOT of benefit, because it allows the developer to fight back when compilation descends unexpectedly into an npm package that contains non-.js[on] files for which a compiler plugin has been registered, an obscure but not uncommon behavior originally intended to allow importing CSS assets from npm packages:
* …
=> Apply .meteorignore to node_modules in PackageSource#_findSources.

packages/facebook-oauth/facebook_client.js, packages/facebook-oauth/facebook_server.js
Updates calls to Facebook API to use the newest 2.12 version which is set as the only option for newly created apps on the Facebook Developer interface.
=> [facebook-oauth] Update Facebook API to v2.12

packages/http/httpcall_client.js
Found this while reading up on HTTP.
=> HTTP.call docs typo

History.md
1.6.2 → 1.7 in the "v1.7" section. 🙂
=> Fix Meteor version number in History.md

History.md, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, tools/isobuild/package-source.js
Fixing #9991, introduced in [Meteor 1.7.0.2](https://github.com/meteor/meteor/pull/9990) by https://github.com/meteor/meteor/pull/9977.
=> Release 1.7.0.3

packages/non-core/bundle-visualizer/package.js, packages/non-core/bundle-visualizer/style.css, packages/non-core/bundle-visualizer/sunburst.js
Posting as WIP because I would like to get some feedback on the design. Please let me know what you think could be better!
The pills along the top are clickable and switch the sunburst between the two bundles, like so:
=> Split bundles into separate sunbursts in bundle-visualizer

packages/webapp/webapp_server.js
Thanks to @Zodiase for doing most of the investigation here:
https://github.com/meteor/meteor/issues/10019#issuecomment-401225148
Fixes #10019.
=> Fix ROOT_URL path prefix stripping.

packages/binary-heap/binary-heap-tests.js, packages/binary-heap/binary-heap.js, packages/binary-heap/max-heap.js, packages/binary-heap/min-heap.js, packages/binary-heap/min-max-heap.js, packages/binary-heap/package.js
Modernizing the next one in the list, alphabetically.
In this PR I converted the three heap functions into ES6 classes and learned about the Fisher-Yates shuffle.
=> Modernize binary-heap package

tools/isobuild/linker.js, tools/tests/linker.js
Fixes https://github.com/meteor/meteor/issues/9878
The place I did include it in the linker algorithm is my best guess. Let me know if this should be placed somewhere else 🙂
=> Remove non deterministic fields from included package.json files.

packages/oauth1/oauth1_binding.js
Also fix whitespace
Fixes #10094 
Thanks to @nick-gudumac for testing the 1.7.1 beta and finding this!
=> Fix map and reduce functions in oauth1 package

History.md, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js
=> Update mongodb npm package to version 3.0.11.

packages/oauth1/oauth1_binding.js, packages/oauth1/oauth1_tests.js
Fixes #10094 again.
I've made this fix but have not yet had the time to review all of the accounts modernization changes for similar errors. It will probably be another day or two before I will get some time to do that. 
I figured that pushing this fix will at least allow us to publish another 1.7.1 beta version and see if other errors are discovered by our excellent testers like @nick-gudumac!
=> Fix another map function in oauth1

packages/mongo/mongo_livedata_tests.js, packages/mongo/oplog_tailing.js
=> Implement MongoDB 4.0 transaction handling in oplog_tailing.js

packages/minimongo/common.js, packages/minimongo/minimongo_tests_client.js, packages/minimongo/sorter.js
Fixes https://github.com/meteor/meteor/issues/10192 + added extra tests
=> Fix minimongo nested array sorting

packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/minifier.js, packages/minifier-js/package.js
While debugging our build time, I checked if the terser update might solve some performance issues we are facing - it doesn't :D. Anyhow in a micro benchmark of 5runs the new terser version performed sligthly better so he're the pr to update it in 1.8.
=> Update terser to 3.9.1

packages/accounts-oauth/package.js, packages/oauth1/package.js
I've added `ecmascript` to `accounts-oauth` and `oauth1` client.
=> Add ecmascript to modernized packages

scripts/admin/bump-all-version-numbers.js, tools/cli/commands-cordova.js, tools/cli/commands.js, tools/cordova/run-targets.js, tools/isobuild/package-source.js
As described in issue 10240, I've fixed the LGTM errors in the relevant files (excluding JS files in packages).
=> Fix LGTM testing errors (issue 10240)

packages/mongo/collection.js
Fixes #10223 
What do you think on adding tests with `sinon`?
=> Restore wrapCallback behaviour in mongo package

packages/oauth/oauth_server.js, packages/oauth/package.js
As reported by @tjaisson in #10265 it looks like that somewhere we have included and at the same time also reverted #9740.
=> Fix duplicate WebApp.connectHandlers.use -  fix #10265

tools/utils/buildmessage.js, tools/utils/fiber-helpers.js
Whenever you're looking at a stack trace generated by the command-line tool, you see tons and tons of useless stack frames for `withValue`, `enterJob`, and/or `capture`.
Each of these function calls has its own `try`-`finally` block, which is probably the real reason this pattern is slow, though the excess of unnecessary stack frames is subjectively gross as well.
Initial build times for the `meteor create --full` app on my machine are about 4.4 seconds with Meteor 1.8, and just 2.8 seconds after this change, which is a nice 36% improvement. Rebuild times are not noticeably different, however.
Looking to the future, flattening this function call pyramid should make it easier to introduce non-`Fiber`-based `async`/`await` into the `buildmessage` system, so that we can start properly …
=> Flatten buildmessage.{enterJob,capture} stacks by not using withValue.

packages/oauth/oauth_common.js, packages/oauth/oauth_server.js, packages/oauth/package.js
A quick fix based on @jamesmillerburgess suggestion for #10290
=> Fix  #10290

tools/isobuild/compiler-plugin.js
If [this theory](https://github.com/meteor/meteor/issues/10337#issuecomment-439089361) is correct, then this PR should fix #10337.
=> Implement ResourceSlot#_addDirectlyToJsOutputResources to fix #10337.

packages/oauth/end_of_popup_response.js, packages/oauth/package.js
=> Fix #10347

History.md, meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/meteor-tool/package.js, packages/promise/.npm/package/npm-shrinkwrap.json, packages/promise/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js, tools/isobuild/package-source.js, tools/tests/apps/modules/imports/imported.tests.js, tools/tests/apps/modules/tests.js, tools/tests/test-modes.js
Small point release including #10402, which fixes a bug affecting step 11 of the Meteor React tutorial: https://www.meteor.com/tutorials/react/testing
=> Release 1.8.0.2

packages/appcache/appcache-server.js
Reword the message that appcache puts into the console when the resources add up to more than 5MB to clean up the confusing double output, caused by the addition of the modern bundle.
Fixes #10321
Old output:
```
I20181124-00:08:50.958(-5)? ** You are using the appcache package but the total size of the
I20181124-00:08:51.071(-5)? ** cached resources is 5.3MB.
I20181124-00:08:51.072(-5)? **
I20181124-00:08:51.072(-5)? ** This is over the recommended maximum of 5MB and may break your
I20181124-00:08:51.073(-5)? ** app in some browsers! See http://docs.meteor.com/#appcache
I20181124-00:08:51.073(-5)? ** for more information and fixes.
I20181124-00:08:51.074(-5)? ** You are using the appcache package but the total size of the
I20181124-00:08:51.074(-5)? ** cached resources is 5.9MB. …
```
=> Rewrite appcache resources exceed recommended cache size debug message.

packages/ddp-client/client/client_convenience.js, packages/ddp-client/common/livedata_connection.js, packages/ddp-client/common/namespace.js, packages/ddp-client/test/livedata_connection_tests.js, packages/ddp-client/test/livedata_test_service.js, packages/ddp-client/test/livedata_tests.js, packages/ddp-client/test/random_stream_tests.js, packages/ddp-client/test/stub_stream.js
=> Improve `ddp-client` package

packages/facebook-oauth/facebook_server.js, tools/upgraders.js
Fixes #10428 by removing old fields and fields that will trigger app review by Facebook.
=> Fix #10428 facebook permissions

tools/isobuild/linker.js
This reverts commit 95a1f54ccef068327c37dc5aba97b8b25189dcb7.
Although at first this commit seemed like a nice optimization, after digging into #10496 I was reminded that the main bundle includes the paths and hashes of available dynamic modules, so rebuilding the main bundle is important even when only dynamic modules have changed.
@zodern I should have caught this in my review, sorry! Remembering how all the pieces fit together is a challenge, to say the least.
Many thanks to @arggh for testing `1.8.1-beta.20` and putting together the https://github.com/arggh/meteor-bundler-issue reproduction.
Should fix #10496 and #10494.
=> Revert "Skip regenerating main bundle when only a dynamic file changed."

tools/fs/files.js
Should help prevent `noYieldsAllowed` errors due to the `Promise#await` call in the removed `copyFileHelper` function, which is what caused Meteor 1.8.2-beta.0 to fail to publish on Linux (reported in #10540).
=> Wrap fs.copyFile[Sync] rather than reimplementing it.

tools/isobuild/bundler.js
Fixes #10471. This should also have a small build performance improvement for apps with many assets.
=> Do not remove source map url comments in public files

tools/isobuild/compiler.js
Fixes #10558 
Watching was accidentally removed in #10452.
=> Fix watching assets

tools/fs/optimistic.ts
The `shouldWatch` function determines whether the optimistic caching system should subscribe to file change notifications for a given path.
Note that Meteor has other ways of watching for file changes (e.g. the `WatchSet` abstraction), as well as other mechanisms for invalidating cached results, so time and resources can often be saved by returning false here, if we know that the path will be watched in other ways.
Improvements:
1. Add `METEOR_PROFILE` instrumentation to the `shouldWatch` implementation.
2. Stop exporting `shouldWatch`, since it is no longer used anywhere else in the codebase.
3. Return `false` early to avoid watching files inside the `.meteor` directory, a significant shortcut.
4. Allow watching files in application `node_modules` directories that are not located …
=> Improve the shouldWatch function in tools/fs/optimistic.ts.

tools/fs/files.js
Fix [alert found](https://lgtm.com/projects/g/meteor/meteor/snapshot/10a004e1c3dd923b9902c2a50e7b36109ff23d36/files/tools/fs/files.js?sort=name&dir=ASC&mode=heatmap#L1445) in LGTM platform
=> Better code quality

packages/webapp/.npm/package/npm-shrinkwrap.json, packages/webapp/package.js, packages/webapp/webapp_server.js
=> remove qs-middleware to resolve license issues

tools/fs/optimistic.ts
We call the optimistically-cached `optimisticStatOrNull` function many times during the build process, and the underlying function is not particularly expensive, so it's important to make sure we're not wasting more time than we're saving.
=> Attempt to make optimisticStatOrNull less expensive.

LICENSE
Better late than never, right?
=> Update license range for year 2019

README.md
=> Chore: Use https in readme

packages/accounts-base/accounts_server.js
Found this quite unreadable way of extracting a property from an object.
=> Small improvement to hashStampedToken

packages/http/httpcall_tests.js, packages/test-helpers/domutils.js, packages/test-helpers/event_simulation.js, packages/test-helpers/package.js
Step towards getting https://github.com/meteor/meteor/pull/10498 merged.
=> Remove jquery dependency from test-helpers

packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/package.js, packages/standard-minifier-js/package.js
Includes a couple of fixes, and 4.3.5 should include a fix for a performance regression from 4.2.0
=> Update terser to 4.4.0

Roadmap.md
Related to switching to NPM, it would be a good occasion to open up to a broader tooling ecosystem.
A big missing piece from the developer standpoint is Storybook. It's not just some nice tool, it literally changed the way we develop frontend in my company and all the companies where I've managed to introduce this magical tool.
Sadly it doesn't work correctly with Meteor, because it is based on a Webpack build. This issue haven't really been solved. We've added Storybook to Vulcan, but that's more a hack than an actual solution (basically we scrap Meteor imports + rely on Vulcan's naming convention to find package root...) so I am not personaly knowledgeable enough to help :/
Another great tool is Jest, it's way more efficient than Mocha thanks to its powerful CLI, but needs some webpack …
=> Add Storybook to the roadmap

packages/ejson/ejson.js, packages/ejson/ejson_tests.js, packages/ejson/package.js, packages/ejson/utils.js
=> Improve `EJSON` package

packages/browser-policy/README.md
Fixes https://github.com/meteor/meteor/issues/10705
=> Warn about dynamic-imports and eval

Roadmap.md
Add Jan Küster and Harry Adel to take on the Blaze tutorials.
We would love to update the Blaze Tutorials to work with >=1.9 and to reflect latest best practices. We use Blaze for a long time and still have projects going, where Blaze plays an important role.
A follow-up question would be, if the TODOs App would have to be updated as well?
=> Roadmap - Update Blaze Tutorial

packages/accounts-base/accounts_server.js, packages/accounts-oauth/oauth_common.js, packages/accounts-password/password_server.js, packages/oauth/pending_credentials.js, packages/oauth1/oauth1_pending_request_tokens.js
=> change sparse and unique index options values from 1 to true

packages/facts-base/facts_base.tests.js, packages/facts-base/facts_base_server.js
=> Fix race condition in the facts-base package tests as the Facts list may not be reset between tests

Roadmap.md
I am nominating myself to be the lead in the effort to make Vue a first class citizen in the Meteor ecosystem. My plan is to emulate what has already been done for React and build the skeleton, a full tutorial and documentation. I will also reach out to great contributors to the Meteor+Vue integration such as [Guillaume Chau aka Akryum](https://github.com/Akryum) to ensure we get the best possible resources on Meteor + Vue.
=> Update Roadmap to nominate lead for Vue.js

README.md
Added Vue with link to meteor tutorials.  Making Vue a 1st class citizen on Meteor 👍
=> Added Vue to list of tutorials

packages/non-core/less/package.js, packages/non-core/less/plugin/compile-less.js
https://github.com/meteor/meteor/pull/10995#issuecomment-606757614
@DavidSichau Seem ok to you?
=> Tweaks after updating less to version 3.11.1

DEVELOPMENT.md, packages/autoupdate/README.md, packages/autoupdate/autoupdate_client.js
I was reading the CONTRIBUTING and DEVELOPMENT docs and thought that I could improve the second one a little.
=> making the docs a little clearer

Roadmap.md
I can work on updating the minimongo package, there is a good overview of future work in the NOTES.txt file inside the package itself. I can start with some smaller changes and work my way up to adding support for indexes
=> Update to the RoadMap (Minimongo)

packages/npm-mongo/package.js
This PR is intended to fix #11026
=> MongoDB update to 3.5.5

packages/google-oauth/README.md
Fix wrong links and add link to Google's docs.
=> Fix #11012

tools/static-assets/skel-full/.meteor/packages, tools/static-assets/skel-full/imports/startup/client/routes.js, tools/static-assets/skel-full/imports/ui/layouts/body/body.html
see issue https://github.com/meteor/meteor/issues/11014
=> Replace kadira:flow-router with ostrio:flow-router-extra in meteor create --full

tools/cordova/project.js
=> Fix: Install scoped cordova plugins

packages/ddp-client/package.js, packages/ddp-server/package.js
Updated ddp-server dependencies to the latest patch releases and did a patch update on the package. While at it also updated lolex dependency in ddp-client to be the same as in the rest of the code base. Since that is test dependency I did not bump the version.
=> Fix #11076 by updating ddp dependencies

packages/socket-stream-client/package.js, packages/socket-stream-client/sockjs-0.3.4.js
=> Fixes #10555 Invalid State Error (INVALID_STATE_ERR)

History.md, meteor, scripts/build-dev-bundle-common.sh, scripts/dev-bundle-tool-package.js
* Update History file
* Update MongoDB to 4.2.7
* Update Node to [12.18.1](https://nodejs.org/en/blog/release/v12.18.1/), which covers the [12.18.0 security release](https://nodejs.org/en/blog/release/v12.18.0/)
* Update npm to 6.14.5
First time updating these dependencies, so not sure if I got everything.
=> Update MongoDB & Node

packages/email/email.js
Improve comment docs about newly accessible email hook. I believe this will fix the issue with docs generation.
https://github.com/meteor/docs/pull/682
=> Improve comments about new email hook

packages/npm-mongo/package.js
see https://github.com/mongodb/node-mongodb-native/releases/tag/v3.6.2
edpecially: https://github.com/advisories/GHSA-pp7h-53gx-mx7r
=> bump mongodb package

packages/reload/reload.js, packages/reload/reload_tests.js
There are no functional changes or breaking changes.
Just updating code style and old patterns.
=> Modernize reload package

meteor, packages/accounts-password/package.js, packages/accounts-ui-unstyled/package.js, packages/accounts-ui/package.js, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, packages/browser-policy-content/package.js, packages/dynamic-import/package.js, packages/ecmascript/package.js, packages/minimongo/package.js, packages/mongo/package.js, packages/reload/package.js, packages/standard-minifier-css/package.js, packages/typescript/package.js, scripts/admin/meteor-release-experimental.json, scripts/dev-bundle-tool-package.js, tools/cli/help.txt, tools/fs/files.ts
=> Bump typescript package version

tools/tests/apps/app-config/package-lock.json, tools/tests/apps/app-config/package.json, tools/tests/apps/css-injection-test/package.json, tools/tests/apps/custom-minifier/package.json, tools/tests/apps/dynamic-import/package-lock.json, tools/tests/apps/dynamic-import/package.json, tools/tests/apps/git-commit-hash/package-lock.json, tools/tests/apps/git-commit-hash/package.json, tools/tests/apps/modules/package-lock.json, tools/tests/apps/modules/package.json
Upgrading puppeteer and jquery to fix dependabot alerts
=> Fixes dependabot alerts

packages/meteor/helpers.js
This PR addresses the issue raised in https://github.com/meteor/meteor/issues/11120 by adding a note to the documentation of `Meteor.wrapAsync`.
=> wrapAsync doc fix

History.md, meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, packages/dynamic-import/package.js, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/dev-bundle-tool-package.js, scripts/windows/download-dev-bundle.ps1
- Bumps bundle version to 12.20.1.1
- Uses meteor-babel-7.10.6
=> Uses meteor-babel-7.10.6

packages/meteor-developer-oauth/meteor_developer_client.js, packages/meteor-developer-oauth/package.js
We are changing the components in the accounts login and for that, we need more space.
=> Adding new size to Meteor Login popup window

packages/logging/.npm/package/npm-shrinkwrap.json, packages/logging/logging.js, packages/logging/logging_cordova.js, packages/logging/package.js
Update dependencies and make debug available for use in non production environments.
=> Update logging package

History.md, packages/accounts-base/accounts_server.js, packages/accounts-base/accounts_tests.js, packages/accounts-base/package.js, packages/accounts-password/package.js, packages/accounts-password/password_server.js, packages/accounts-password/password_tests.js
=> Add ability to add extra params to emailed urls

History.md, Roadmap.md
Requires https://github.com/meteor/guide/pull/1068
=> Update HMR docs link

packages/accounts-password/password_server.js
Enhancing comments to serve the documentation that will be created here https://github.com/meteor/docs/issues/698
=> Enhancing Accounts.createUserVerifyingEmail comments

tools/cli/commands.js, tools/cli/help.txt, tools/meteor-services/deploy.js
A new flag will be allowed when deploying an app called `plan`.
=> New flag accepted in the deploy command line

scripts/admin/jsdoc/docdata-jsdoc-template/publish.js
=> Fix typo in publish.js

packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/typescript/package.js, scripts/dev-bundle-tool-package.js
Blocked by https://github.com/meteor/babel/pull/40
=> Update TypeScript to 4.2.2

packages/minifier-css/.npm/package/npm-shrinkwrap.json, packages/minifier-css/package.js
=> Update postcss from 7.0.32 to 8.2.10

packages/accounts-password/package.js, packages/accounts-password/password_server.js
Improve password validator and add option to settings to override the maximum length of password.
=> Improve password validator

tools/static-assets/skel-apollo/package.json, tools/static-assets/skel-bare/package.json, tools/static-assets/skel-blaze/package.json, tools/static-assets/skel-full/package.json, tools/static-assets/skel-minimal/package.json, tools/static-assets/skel-react/package.json, tools/static-assets/skel-typescript/package.json, tools/static-assets/skel-vue/package.json, tools/tests/apps/app-config/package.json, tools/tests/apps/client-refresh/package.json, tools/tests/apps/custom-minifier/package.json, tools/tests/apps/dynamic-import/package.json, tools/tests/apps/git-commit-hash/package.json, tools/tests/apps/link-config-npm-package/package.json, tools/tests/apps/linked-external-npm-package/package.json, tools/tests/apps/meteor-ignore/package.json, tools/tests/apps/package-tests/package.json, tools/tests/apps/shell/package.json, tools/tests/apps/standard-app/package.json
While working on other issue I have updated the dependencies for the skeletons.
=> Skelets dependencies updates

packages/mongo-id/package.js
https://github.com/meteor/meteor/issues/11404
=> Remove id-map dependency from mongo-id

History.md, Roadmap.md, packages/accounts-base/accounts_server.js, packages/accounts-password/password_server.js, packages/accounts-password/password_tests.js, packages/babel-compiler/README.md, packages/ddp/DDP.md, packages/es5-shim/README.md, packages/logic-solver/README.md, packages/minifier-css/minifier.js, packages/rate-limit/README.md, packages/url/legacy.js, packages/url/modern.js, packages/url/server.js, packages/url/tests/main.js, packages/webapp/connect.js, packages/webapp/webapp_tests.js, scripts/doctool.md, tools/README.md
Fixes several typos. No functional changes.
=> fix typos in several files

History.md, packages/socket-stream-client/.npm/package/npm-shrinkwrap.json, packages/socket-stream-client/package.js
Update `faye-websocket` dependency to v0.3.3 in socket-stream-client
=> Update faye-websocket dependency in socket-stream-client

History.md, tools/cli/commands.js, tools/cli/help.txt, tools/meteor-services/deploy.js, tools/tool-testing/galaxy-utils.js
Some clients want to have the ability to build first and after some validations proceeding with the upload and deploy.
=> New deploy option: build-only

packages/observe-sequence/observe_sequence.js
=> when #each argument is unsupported, show it for better debug experience

packages/browser-policy/browser-policy-test.js
=> Fix typo in browser-policy-test.js

tools/cli/commands-packages.js
Add additional description for package updates so that people are not confused why they can't update.
=> Add description about package upgrades for non-recommended releases

History.md, packages/meteor-tool/package.js, scripts/admin/meteor-release-official.json, tools/cordova/project.js
=> Fix issue when running android cordova projects due to aab format change

History.md, packages/callback-hook/hook.js, packages/callback-hook/hook_tests.js, packages/callback-hook/package.js
- Modernized the code
- Fixed a variable assignment bug in `dontBindEnvironment` function
=> Callback-hook var assingment fix & modernization

packages/ddp-server/livedata_server_async_tests.js, packages/ddp-server/package.js
This PR adds unit testing for the new feature developed here: https://github.com/meteor/meteor/pull/11444
=> Async publications unit testing

tools/cli/commands.js, tools/meteor-services/deploy.js
- We should have a user able to deploy to any account using a token
=> Accept a token to authenticate deploys

History.md, meteor, packages/modules/package.js, scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js
Upgrading to benefit of this PR https://github.com/benjamn/reify/pull/291
=> Reify upgrade 0.22.1

History.md, packages/webapp/package.js, packages/webapp/webapp_server.js
In response to https://github.com/meteor/meteor/pull/11607#issuecomment-907904575
For the 2 callbacks I introduced I have updated to use the meteor `callback-hook` package.
=> use callback-hook package

tools/isobuild/package-source.js
=> Fix typo in package-source.js

tools/cli/commands.js, tools/meteor-services/deploy.js
We are adding an option to inform the container size in the deploy command.
=> Container size in the command line

guide/source/accounts.md
Added missing commas to Accounts.config example in accounts.md
=> Added missing commas to Accounts.config example in accounts.md

docs/source/install.md
Added note for fish shell users
=> Update install docs

docs/scripts/api-box.js, docs/source/packages/accounts-passwordless.md
For example, to override the module that is importing a function.
=> Adding option to override data from api using args from api-box.

packages/minifier-js/minifier.js, packages/minifier-js/package.js, packages/standard-minifier-js/package.js
=> Reverting terser evaluate false

packages/react-fast-refresh/client.js
Partial fix for #11772 (fixes production build/bundle)
=> Make code compatible with IE11 - #11772

npm-packages/meteor-installer/README.md, npm-packages/meteor-installer/config.js, npm-packages/meteor-installer/package.json, packages/react-fast-refresh/package.js, packages/react-fast-refresh/server.js
- Fixes #11744
- Updates react-refresh. This fixes some bugs with high order components and typescript namespaces.
=> Fix react refresh bugs

guide/source/security.md
See https://github.com/helmetjs/csp/issues/97
=> Remove `browserSniff` Option

packages/oauth/end_of_redirect_response.js
Fixes #11817 by adding try/catch around sessionStorage in end of redirect response.
=> Fix #11817 add try/catch to end of redirect response

packages/mongo/mongo_driver.js
Fix Oplog Tailing high cpu usage with new Mongodb driver. As the old way of passing the "tailable" option to find cursors is now removed, the cursor was dying and making calls all the time.
Fix it by using addCursorFlag
=> Fix MongoDB Node Driver 4 high cpu usage

packages/static-html/package.js
The static-html package is in the meteor/meteor repo.
=> correct git link in static-html package

packages/mongo/mongo_driver.js
Fix sync return for insert methods inside _collection private method
=> Fix sync return for insert methods inside _collection private method

docs/history.md, packages/google-oauth/google_server.js, packages/google-oauth/package.js
* `google-oauth@1.4.2`
- Migrate from `http` to `fetch`
Tested with account creation and login. No problems. Like last time, the missing piece were callbacks.
=> Replace http for fetch in Google login

docs/history.md, packages/test-helpers/callback_logger.js
=> Fix typo in callback_logger.js

guide/source/deployment.md
Updates the link to galaxy deployment guide from the Meteor Guide.
=> fix url to galaxy deployment guide

tools/console/console.js
=> Fix typo in console.js

guide/source/build-tool.md
Added online version of Autoprefixer . So users can instantly use it without installing it.
=> Added online version of autoprefixer.

guide/source/deployment.md
It took me forever to figure out that the app starts at a "random" port if the `PORT` environment variable is not set.
=> Describe the PORT variable in Custom Deployment

tools/isobuild/bundler.js
=> Fix typo in bundler.js

tools/static-assets/skel-apollo/package.json, tools/static-assets/skel-apollo/server/apollo.js
Update Apollo skeleton dependencies and add cache option on server from addition in v3.9: https://www.apollographql.com/docs/apollo-server/performance/cache-backends/
=> Update Apollo skeleton

README.md
=> Added badge to new guide

docs/history.md
Here we have the changelogs for this new release :)
Made this a separate PR so that we can revise it before the merge
=> Feat changelog 2.8

docs/history.md, guide/source/2.8-migration.md
Relates to [this topic](https://github.com/meteor/meteor/pull/12057#discussion_r956599272])
Also corrected a typo in changelog
=> Feat migration guide for 2.8

guide/source/2.8-migration.md
As discussed in this thread #12168 with @radekmie and @StorytellerCZ 
I've added this new section: How can I start using these new features?
Any opinions, @denihs?
=> chore: added how can I use section to change log

CODE_OF_CONDUCT.md
In the Code of Conduct, the Contributor Covenant URL has been updated as it was previously somehow redirecting to the Italian version of this document. This change also updates the Ubuntu URL for currency and updates from using insecure http://.
=> Update Code of Conduct Attribution URLs

docs/source/packages/fetch.md
`err` instead of `error` in catch statement
=> Update fetch.md typo

CODE_OF_CONDUCT.md, docs/source/commandline.md, docs/source/packages/fetch.md, docs/source/roadmap.md, packages/ddp-client/common/namespace.js
Addressing issue #12060 
Happy Hactoberfest 2022 :)
=> updated the doc with the dependency of --container-size on --plan flag

packages/non-core/less/tests/top-cdn-file.import.less, packages/non-core/less/tests/top.import.less
Updating cdn link in order to make tests pass again
=> chore: updated css cdn link

.eslintignore, npm-packages/eslint-plugin-meteor/.eslintignore, tools/runners/run-all.js, tools/runners/run-updater.js
- convert Updater to es6 class
- remove run-updater.js from .eslintignore
- fix a small bug
=> [Refactoring] modernize `tools/run-updater.js`

packages/accounts-base/accounts_server.js
This is just to always set the limit on this query since there is no reason to ever return more than 2 items. This fixes cases where you may have a large number of users that start with the same few characters.
Referring to this https://github.com/meteor/meteor/issues/12211#issue-1398221726
=> Fix case insensitive lookup resource overuse

packages/test-in-browser/driver.js
Fixing - there isn't much to describe here.
=> Fix "type" is not defined issue on TinyTest after underscore removal.

tools/cli/commands.js, tools/cli/help.txt, tools/static-assets/skel-apollo/.meteor/packages, tools/static-assets/skel-bare/.meteor/packages, tools/static-assets/skel-blaze/.meteor/packages, tools/static-assets/skel-chakra-ui/.meteor/packages, tools/static-assets/skel-full/.meteor/packages, tools/static-assets/skel-minimal/.meteor/packages, tools/static-assets/skel-react/.meteor/packages, tools/static-assets/skel-solid/.meteor/packages, tools/static-assets/skel-svelte/.meteor/packages, tools/static-assets/skel-tailwind/.meteor/packages, tools/static-assets/skel-typescript/.meteor/packages, tools/static-assets/skel-vue/.meteor/packages
Standardized the use of insecure packages in skeletons and made this an opt-in feature. 
It is only possible to pass in this flag when you are not using the package flag( it does have a validation)
=> Feat: not using insecure & autopublish by default

packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js
=> chore: updated mongo driver

guide/source/2.8-migration.md
=> update 2.8-migration.md, fix typo

meteor, scripts/dev-bundle-tool-package.js
upgraded dev bundle because changed babel version
=> Dev bundle 14.21.1.2

packages/babel-compiler/.npm/package/npm-shrinkwrap.json, tools/cli/commands.js, tools/tests/shell-tests.js
Some tests are not passing even though I have reverted some changes. Will do most of the tryout work here
=> Solving 2.9 tests

packages/test-in-console/puppeteerRunner.js
=> Solving issues with the CI

meteor, scripts/dev-bundle-tool-package.js
Upgrading dev bundle to match latest babel package
=> Dev bundle 14.21.1.3

meteor
=> chore: updated bundle version

packages/meteor/package.js
In this pr I revert changes made by mistake in 2.9.1.
closes #12365
=> chore: reverted missing types

docs/_config.yml
=> Adding missing dropdown item for 2.9

meteor
New dev bundle for new babel version
=> New dev bundle for new babel version

meteor
This brings current devel bundle + bumps on node
=> chore: update on dev bundle

docs/history.md
Updating the docs to match more exactly what is going on in the code base
=> docs: update on history.md(breaking changes)

packages/test-in-browser/driver.css
As @zodern commented, the new Tiny Test Ui was not IE compatible in this PR I ensure that it will work properly by passing the same prop but without variable
=> Making new Tinytest UI IE compatible

docs/source/commandline.md
In the community slack there was doubt when it will generate a ts scaffold that was left undocumented, in this PR I document how the scaffolds API check if it should use ts or js
for [context](https://meteor-community.slack.com/archives/CN350MY1G/p1670958266529549?thread_ts=1670948262.173679&cid=CN350MY1G)
=> docs: updating meteor generate docs

meteor
Updated 2.9.1 dev bundle update with devel
=> Chore: update dev-bundle with devel

docs/history.md, packages/accounts-2fa/2fa-server.js, packages/accounts-2fa/server_tests.js
In this PR I focus on making accounts-2fa async, making it possible to have a Fibers-free MeteorJS.
=> Making accounts-2fa async

packages/boilerplate-generator-tests/package.js, packages/boilerplate-generator-tests/test-lib.js
=> Revert "Update boilerplate-generator-tests"

meteor, scripts/dev-bundle-tool-package.js
This relates to typescript bump in #12393
=> New Dev bundle 14.21.2.3 to include typescript bump

meteor, scripts/dev-bundle-tool-package.js
Thanks to @afrokick for catching that I've missed in the dev bundle to bump typescript version
=> Dev bundle 14.21.2.4

tools/static-assets/skel-vue/server/main.js
=> Fix vue tutorial link

packages/minimongo/common.js
I've noticed that the `omitUnnecessaryFields` function pops up more and more often in our profiling traces, sometimes taking even 26% of the CPU time. It's clear that it does the complete opposite of what all JIT languages like - it alters the created structs. I replaced it with a `buildResult` function that creates an object dynamically, only with the properties that should be there.
This improvement made up roughly 70% of the results. But then I made the `arrayIndices` calculation lazy, and while it didn't change anything for Safari, it got me another significant improvement on V8.
<details>
<summary>Benchmarks</summary>
```ts
{
const matcher = MinimongoTest.makeLookupFunction('a');
const doc = { a: 1 };
for (let round = 1; round <= 50; ++round) {
console.time('simple');
for (let _ = 0; …
```
=> Optimized `makeLookupFunction`.

tools/static-assets/skel-chakra-ui/imports/ui/Info.jsx, tools/static-assets/skel-chakra-ui/server/main.js, tools/static-assets/skel-react/imports/ui/Info.jsx, tools/static-assets/skel-react/server/main.js, tools/static-assets/skel-tailwind/imports/ui/Info.jsx, tools/static-assets/skel-tailwind/server/main.js, tools/static-assets/skel-typescript/imports/ui/Info.tsx, tools/static-assets/skel-typescript/server/main.ts
Since Meteor.js 2.9 in this [PR](https://github.com/meteor/meteor/pull/12220) we do not have insecure package by default anymore.
Because of this, our skeletons were a little bit outdated, In this PR, I start solving this issue, starting with the React packages.
=> Updating react skeletons

README.md
=> Small grammar & spelling corrections

packages/tracker/tracker.d.ts
Addressing this comment [here](https://github.com/meteor/meteor/pull/12475#discussion_r1097576196)
=> chore: adressing comments

packages/accounts-base/accounts_server.js
Solves issue reported in https://github.com/meteor/meteor/pull/12480#issuecomment-1422792020
=> making arrow function to normal fn in meteor.loginServiceConfiguration subscription

packages/accounts-base/accounts-base.d.ts, packages/email/.npm/package/npm-shrinkwrap.json, packages/email/email.d.ts, packages/email/package.js, packages/meteor/meteor.d.ts, packages/mongo/mongo.d.ts, packages/npm-mongo/.npm/package/npm-shrinkwrap.json
This PR is the twin of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64368 (which was opened first against DefinitelyTyped to make sure the tests still passed)
=> Improve specificity of types previously declared as "Object"

docs/history.md, guide/_config.yml
Just updating the guide with the missing information + updating history.md to its latest version
=> Updating guide with missing information

docs/generators/changelog/versions/2.11.md
Adding some information about what was changed and removing statement that did not make any sense given the context
=> Updating changelog

docs/history.md
=> Keeping history.md(autogenerated up to date)

docs/source/install.md
Update and clean up the installation process.
Preview: https://deploy-preview-12556--meteor-docs.netlify.app/install.html
=> docs: update and clean installation process

packages/non-core/mongo-decimal/decimal_tests.js
[Task](https://favro.com/organization/929aab32206e9caa0b59b5cf/cef8866673a006c0854ffd64?card=Met-2919).
The only package that needed an adjustment was the mongo-decimal package.
=> [Release 3.0] fix non-core packages tests

scripts/generate-dev-bundle.ps1, scripts/generate-dev-bundle.sh
Nodejs 14 official download source has been discontinued, we are switching to our custom source https://static.meteor.com
=> Using Node 14 from ESM

docs/source/api/core.md, docs/source/install.md, docs/source/packages/webapp.md, packages/meteor/meteor.d.ts, packages/meteor/test_environment.js, packages/webapp/webapp_server.js
Should resolve https://github.com/meteor/meteor/issues/12318
=> Add undocument properties to docs

packages/minifier-css/minifier-async-tests.js, packages/minifier-css/minifier-tests.js, packages/minifier-css/package.js, packages/standard-minifier-css/package.js
Resolves https://github.com/meteor/meteor/issues/12561
=> Bump NPM versions for css minifiers

packages/email/email.d.ts, packages/mongo/mongo.d.ts
Two errors that snuck into my changes in #12520; apologies for the oversights.
=> Two type fixes

docs/generators/changelog/versions/2.12.md, packages/npm-mongo/package.js
Updating MongoDB driver to 4.15
=> chore: updating MongoDB driver to 4.15

packages/minifier-css/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/standard-minifier-css/.npm/plugin/minifyStdCSS/npm-shrinkwrap.json, packages/underscore/.npm/package/.gitignore, packages/underscore/.npm/package/README, packages/underscore/.npm/package/npm-shrinkwrap.json
In this PR I update the .lock files for a few packages
=> Updating .lockfiles

docs/source/api/tracker.md, packages/tracker/tracker.d.ts, packages/tracker/tracker.js
based on this discussion from [slack](https://meteor-community.slack.com/archives/C04USBMR3QW/p1681103928498359?thread_ts=1680553359.945209&cid=C04USBMR3QW) and [this](https://meteor-community.slack.com/archives/C04USBMR3QW/p1681197084625709) I've updated the docs.
If you do not have access to our Slack click [here](https://join.slack.com/t/meteor-community/shared_invite/zt-1ttwisols-x3z~VWxDfHZXavchzUKAPw)
The resulting docs can be checked [here](https://deploy-preview-12598--meteor-docs.netlify.app/api/tracker.html#Tracker-withComputation)
=> Updating tracker docs

README.md
Upping the version number on the readme.
=> Update README.md version number

meteor
As part of generating a release, I'm making a new dev-bundle with the latest changes from the `release-3.0`
=> Merging 3.0 and devel dev-bundles

packages/accounts-base/accounts_server.js
=> regression(meteor-3): Change Accounts’ hooks to support async

packages/mongo/collection.js, packages/mongo/collection_tests.js
This one fixes https://github.com/meteor/meteor/issues/12626
=> Fix upsert logs when using WARN_WHEN_USING_OLD_API flag

packages/ddp-server/livedata_server_async_tests.js, packages/test-in-console/driver.js, packages/test-in-console/puppeteerRunner.js
Trying to make the CI green again
=> Chore/solving 2.13 tests

packages/mongo/mongo_driver.js
fix #12642, #12628 https://jira.mongodb.org/browse/NODE-5316
=> fix #12642, #12628 https://jira.mongodb.org/browse/NODE-5316

tools/cli/commands-cordova.js, tools/cli/commands-packages-query.js, tools/cli/commands-packages.js, tools/cli/commands.js, tools/cordova/builder.js, tools/cordova/index.js, tools/cordova/project.js, tools/cordova/run-targets.js, tools/cordova/runner.js, tools/project-context.js, tools/runners/run-all.js, tools/runners/run-app.js, tools/runners/run-mongo.js, tools/runners/run-proxy.js, tools/tests/old/test-bundler-assets.js, tools/tests/old/test-bundler-options.js, tools/tests/wipe-all-packages.js
This PR focus on adapting the cordova integration of Meteor for the 3.0 release
=> Adapt missing parts to async in cordova commands.

packages/mongo/mongo_driver.js
=> fix(mongo-livedata-test): Add missing fence commit to updateAsync method

packages/mongo/observe_changes_tests.js
=> fix: Failing test `observeChanges - tailable`

packages/deprecated/http/httpcall_client.js, packages/deprecated/http/httpcall_server.js, packages/deprecated/http/httpcall_tests.js, packages/deprecated/http/package.js, packages/deprecated/http/test_responder.js, packages/deprecated/markdown/package.js, packages/deprecated/stylus/plugin/compile-stylus.js
`./meteor test-packages` is failing due to some error on package `markdown`, I could not find the issue and I realized the deprecated packages were not being loaded from locally, but from atmosphere, so using `METEOR_PACKAGE_DIRS="packages/deprecated" ./meteor test-packages` I could include the deprecated packages from local file system and then I found the errors fixed in this PR. The solution for the markdown was the removal of the `lazy: true`.
=> fix: Failing tests of deprecated packages

packages/deprecated/jquery-history/package.js, packages/deprecated/jquery-layout/package.js, packages/deprecated/markdown/package.js, packages/deprecated/spiderable/package.js, packages/non-core/coffeescript-compiler/package.js, packages/non-core/coffeescript/package.js, packages/test-in-console/package.js, packages/test-in-console/reporter.js, packages/test-in-console/run.sh
=> fix: ci failing to run tests

packages/test-in-console/run.sh
=> fix: ci puppeteer

guide/_config.yml, guide/source/flowbite.md
I have added a new section on Meteor Guide called "Integrations" and also added a markdown that's show how to integrate and use Flowbite UI with Tailwind and Meteor.js.
=> docs(flowbite): added flowbite-ui integration docs

README.md
Current React js logo image on the README.md is broken.
This PR fixes it.
=> fix react logo on README.md

guide/_config.yml
Was missing in last migration the change in this line
=> updating from 2.12 to 2.13 in sidebar

tools/cli/commands.js
regards with this comment https://github.com/meteor/meteor/pull/12359#issuecomment-1620593079
Will default to 2.x way of creating projects when user passes --release _or_ --prototype
=> chore: solved issue when passing --release

meteor, scripts/generate-dev-bundle.sh
=> updating CI

docs/_config.yml, docs/source/known-issues.md
Add https://github.com/meteor/meteor/issues/12731 to docs while we are working in a solution to this issue.
=> docs: added known issues section for 2.13

docs/generators/changelog/versions/2.13.md, guide/source/2.13-migration.md
Adds known issues section to migration guide
=> docs: added known issues section to migration guide

docs/source/known-issues.md
updating docs on how to solve https://github.com/meteor/meteor/issues/12731 to be more precise
=> docs: updated known issues to add solution section

packages/accounts-password/README.md
I came, I saw, I came, I saw
I read the docs, then create a PR
It rains, it pours, it rains, it pours
Yours truly,
the greatest Meteor developer alive second only to @zodern the II lord of Monti APM
=> [Docs] Fix broken link in accounts password README

CONTRIBUTING.md
=> Update CONTRIBUTING.md    "Corrected the spelling mistake"

docs/generators/changelog/versions/2.14.md, packages/react-fast-refresh/client-runtime.js, packages/react-fast-refresh/package.js, packages/react-fast-refresh/server.js
Just a quick and straight forward update of a dependency that I came across while doing other things. Also fixes a few lint issues.
=> Update semver in react-fast-refresh

guide/_config.yml, guide/source/prepare-meteor-3.0.md
Hello ;)
This pull request proposes adding a new section to our guide showing tips, articles, and tools to help migrate to Meteor 3.0. The idea is to upgrade your 2.X with the new async methods to make the transition to 3.0 easier.
https://github.com/meteor/meteor/assets/70543018/4a99dd7a-8103-4c14-a3c5-6243d2b041a2
=> docs(guide): how to prepare to meteor 3

packages/allow-deny/allow-deny.js
This error was thrown when calling writing methods (insert/update/remove) from the client in a prototype app (uses the `insecure` package):
That happens because the `insecure` package allows you to call a function like `TasksCollection.insert({text: "New Task"})` from the client then it [calls](https://github.com/meteor/meteor/blob/678506b398473e9aa0287c5c1024022a3a191274/packages/allow-deny/allow-deny.js#L217) that same method in the server to persist the data. But these sync methods no longer exist in the server, hence the error.
So now we are creating this mapper that calls the respective async method on the server side and persists the data.
=> Solve error when trying to use insert/update/remove from the client

tools/static-assets/skel-apollo/server/main.js, tools/static-assets/skel-chakra-ui/server/main.js, tools/static-assets/skel-full/imports/startup/server/fixtures.js, tools/static-assets/skel-react/server/main.js, tools/static-assets/skel-tailwind/server/main.js, tools/static-assets/skel-typescript/server/main.ts
Fix https://github.com/meteor/meteor/issues/12676
Open it again because I deleted the meteor repo from my account 😅
Just replacing old URLs with the newest.
Follow the issue for more details.
Ps: I'm replacing it with `simple-todos/01-creating-app` because the old URL was sent to `react/creating-an-app`.
=> Fix skell react url

tools/static-assets/skel-vue/imports/ui/router.js
=> Updating Vue skeleton to remove build error

packages/accounts-base/accounts_client.js
This is a fix for #12391.
This feature was introduced by https://github.com/meteor/meteor/pull/10543 which fixed https://github.com/meteor/meteor/issues/10157.
=> Fix #12391

packages/tracker/README.md
=> Update Tracker manual link

packages/logging/logging.d.ts, packages/logging/package.js
Extracting the types from #12669 since we have tests failing there, so I'm getting the most important things into this PR.
=> Types for logging

packages/accounts-base/README.md, packages/accounts-facebook/README.md, packages/accounts-github/README.md, packages/accounts-google/README.md, packages/accounts-meetup/README.md, packages/accounts-meteor-developer/README.md, packages/accounts-oauth/README.md, packages/accounts-passwordless/README.md, packages/accounts-twitter/README.md, packages/accounts-ui-unstyled/README.md, packages/accounts-ui/README.md, packages/accounts-weibo/README.md, packages/deprecated/facebook/README.md, packages/deprecated/github/README.md, packages/deprecated/google/README.md, packages/deprecated/meetup/README.md, packages/deprecated/meteor-developer/README.md, packages/deprecated/twitter/README.md, packages/deprecated/weibo/README.md, packages/google-oauth/README.md, packages/oauth/README.md, packages/oauth1/README.md, packages/oauth2/README.md, packages/service-configuration/README.md, packages/tracker/README.md
While reading into the docs, I ran into the same problem I fixed in https://github.com/meteor/meteor/pull/12793/files so I searched the code base and made the change in one go.
=> Update broken accounts link

guide/source/using-node-v14.21.4.md
- Removed "It will be updated soon" because it is already updated.
=> Removed the parentheses where it says Galaxy meteor-base image "it will be updated soon"

docs/generators/changelog/versions/2.14.md, docs/history.md, docs/source/api/passwords.md, packages/accounts-password/package.js, packages/accounts-password/password_client.js
Relates to this [branch](https://github.com/meteor/meteor/pull/12787#issuecomment-1764629821), backporting a method that exists on server in to the client as well
=> backport createUserAsync from  #12787

packages/meteor/meteor.d.ts
It's not much but it's honest work
=> [meteor] Add types for makeErrorType and meteorRelease

packages/tracker/README.md
=> Fix links in tracker README

packages/mongo/mongo.d.ts
=> add: depracated notices added for the old methods that are depracated in version 2.8

packages/service-configuration/service-configuration.d.ts
Add types for configError 
https://github.com/meteor/meteor/blob/72f27da680cfdd3ff6fb20f580a7f468cb5f21ce/packages/service-configuration/service_configuration_common.js#L21
I'm not well versed in TS so a little help is appreciated.
=> [service-configuration] Add types for ConfigError

docs/source/api/tracker.md
Hey Meteorians!
I've read the documentation about Tracker.withComputation and I think that it's not that easy to decipher. To be more clear, I updated the example and removed some parts to make it more concise.
Thanks for the work 😃
=> Documentation update to make Tracker.withComputation more understandable

docs/generators/changelog/versions/3.0.md, scripts/dev-bundle-tool-package.js, tools/isobuild/bundler.js
* Upgraded `node-gyp` to v9.4.0
* Upgraded `node-pre-gyp` to `@mapbox/node-pre-gyp` v1.0.11
This should help in supporting what they do into future Node.js releases.
=> Update node-gyp and node-pre-gyp to their latest versions

guide/source/writing-atmosphere-packages.md
=> Clarifying the language around publishing a package

packages/accounts-base/accounts_server.js, packages/accounts-password/password_server.js, packages/accounts-passwordless/passwordless_server.js, packages/accounts-passwordless/server_utils.js
While migrating an actual project using `accounts-passwordless` I found more places where we need async functions.
I also found server code in the core using MongoDB collection sync API.
=> More async for accounts passwordless, base and password

npm-packages/cordova-plugin-meteor-webapp/package.json, npm-packages/cordova-plugin-meteor-webapp/src/android/AssetBundleManager.java, npm-packages/cordova-plugin-meteor-webapp/src/android/WebAppLocalServer.java
the previous fix #12762 didn't fix the issue #12761
P.S I have tested this changed, in development and production ready build.
following is sample java code to test the constructed url
```
package hello;
import java.io.IOException;
import okhttp3.Call;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.json.JSONObject;
public class App {
public String getUrl() {
String url = "https://test.xyz.com/app";
HttpUrl rootUrl = HttpUrl.parse(url);
HttpUrl baseUrl = rootUrl.newBuilder().addPathSegment("__cordova").build();
HttpUrl manifestUrl = baseUrl.newBuilder().addPathSegment("manifest.json").build();
Request request = new Request.Builder().url(manifestUrl).build();
OkHttpClient httpClient = new OkHttpClient(); …
```
=> fixes #12761  url to pull manifest from correct url if parameter are used in baseurl

guide/package-lock.json, guide/source/2.13-migration.md
Updating migration guide to 2.13 telling people to go directly to 2.13.3
=> Adding note on how to solve 2.13.3 issue

guide/source/writing-atmosphere-packages.md
=> Update Testing section for Tinytest

meteor, scripts/dev-bundle-tool-package.js
Relates to this https://meteor-community.slack.com/archives/C01SWPPE81F/p1700649911747459?thread_ts=1700647464.127249&cid=C01SWPPE81F
cc @filipenevola
=> [Meteor 3] - Revert Sqlite to 5.0.2

packages/webapp/webapp_server.js
##What this PR do?
-> Fixed IncomingMessage and ServerResponse link in api docs.
Fixes https://github.com/meteor/meteor/issues/12878
Changes in
packages > webapp > webapp_server.js
line number :
IncomingMessage link : 1145
ServerResponse link : 1150
=> fix/12878  incomingMessage and serverResponse node js link in api docs

packages/ddp-client/client/client_convenience.js, packages/ddp-client/package.js, packages/ddp-client/test/async_stubs/client.js, packages/ddp-client/test/async_stubs/server_setup.js
Relates to this forum [post](https://forums.meteor.com/t/proposal-to-fix-issues-with-async-method-stubs/60826/21?u=grubba)
Created this PR to test the code against our CI
=> Add zodern solution for Async stubs

guide/source/writing-atmosphere-packages.md
[mtest](https://github.com/zodern/mtest) is a little gem worth mentioning when it comes to testing packages.
=> Add note about mtest

README.md
Meteor would crumble without me. You can [sponsor](https://github.com/sponsors/harryadel) me now to get more awesome contributions like this one.
=> My greatest contribution ever

packages/non-core/less/package.js
Changing the version of dependencies on the less package
=> Changing the version of dependencies on the less package

packages/accounts-oauth/oauth_server.js, packages/meteor-developer-oauth/meteor_developer_server.js, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/webapp/.npm/package/npm-shrinkwrap.json
Some functions were missing async treatment, and logging with Meteor as a provider was failing in some specific cases.
=> Fix Meteor accounts oauth

packages/underscore/package.js, packages/underscore/underscore.js
A quick fix in underscore. Recommend releasing this as a patch asap.
=> Fix #13001

meteor
Updating the dev bundle (we had ci issues)
=> Dev bundle to 20.11.1.1

packages/ddp/ddp.d.ts
In our tests we found out that it was missing this type in ddp
=> Added call async type for ddp

packages/accounts-2fa/.npm/package/npm-shrinkwrap.json, packages/email/.npm/package/npm-shrinkwrap.json, packages/force-ssl-common/.npm/package/npm-shrinkwrap.json, packages/meteor/dynamics_browser.js, packages/meteor/dynamics_nodejs.js, packages/meteor/dynamics_test.js, packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/webapp/.npm/package/npm-shrinkwrap.json
Fix [this](https://forums.meteor.com/t/problem-with-environmentvariable/61135/12?u=denyhs).
```js
import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
const linkContext1 = new Meteor.EnvironmentVariable();
const linkContext2 = new Meteor.EnvironmentVariable();
linkContext1.withValue({ idd: Random.id() }, async () => {
await linkContext2.withValue({ idd: Random.id() }, async () => {
await linkContext2.withValue({ idd: Random.id() }, async () => {
console.log('    Link context 2', linkContext2.get())
})
console.log('  Link context 2', linkContext2.get())
})
console.log('Link context 1', linkContext1.get())
console.log('Link context 2', linkContext2.get())
});
```
The result is:
```js
Link context 2 { idd: 'nai9jtXk7mAdrQq5N' }
Link context 2 { idd: …
```
=> [Meteor 3] Clean Environment Variables upper context when finish executing callback

meteor, npm-packages/meteor-babel/package-lock.json, npm-packages/meteor-babel/package.json, packages/babel-compiler/package.js, packages/typescript/package.js, scripts/dev-bundle-tool-package.js, tools/static-assets/skel-typescript/package.json
=> Dev bundle 20.11.1.2 [ Typescript to 5.4.3 ]

packages/minimongo/cursor.js, packages/mongo/mongo_driver.js, packages/mongo/mongo_livedata_tests.js
OSS-339
Context: https://github.com/meteor/meteor/issues/12918
=> 339 Support observeChangesAsync and observeAsync [Meteor 2.x]

tools/static-assets/skel-solid/package.json
Updated solid skeleton npm dependencies based on [my stream](https://www.youtube.com/watch?v=cyhgvaSEJiY) testing it out today.
=> Update solid skeleton dependencies

packages/email/package.js
Updates `nodemailer` in `email` package to the latest version.
=> Update nodemailer to v6.9.10

packages/accounts-ui-unstyled/login_buttons_single.js, packages/twitter-config-ui/twitter_configure.html
Looked through the new X developer portal (at least new since the UI was last updated) and changed things accordingly. Still need to finish setting things up to do the full test, but this is already a good patch improvement I think.
=> Update X/Twitter setup instructions and button text to: X/Twitter

npm-packages/meteor-installer/config.js, npm-packages/meteor-installer/install.js, npm-packages/meteor-installer/package-lock.json, npm-packages/meteor-installer/package.json, packages/npm-mongo/.npm/package/npm-shrinkwrap.json
=> [3.x] Support Linux ARM with the Meteor installer

packages/test-in-console/puppeteerRunner.js, packages/tinytest/tinytest.js
This is a cherry-pick of https://github.com/meteor/meteor/pull/13078
=>  Making our CI more easy to understand

guide/source/3.0-migration.md, npm-packages/meteor-node-stubs/CHANGELOG.md, npm-packages/meteor-node-stubs/package-lock.json, npm-packages/meteor-node-stubs/package.json, npm-packages/meteor-node-stubs/wrappers/crypto.js, packages/mongo/mongo_driver.js, packages/mongo/oplog_tailing.js
Making CI green in release 3.0
=> Merging devel to 3.0

packages/mongo/mongo.d.ts
Added missing TS types for `observeAsync` and `observeChangesAsync` as pointed out in #12918 by @ebroder
=> Add missing observe async types

docs/generators/changelog/versions/2.16.md, packages/minifier-js/package.js
#13118 for Meteor 2.16 with changelog entry.
=> [Meteor 2.16] Update terser to v5.31.0

README.md, docs/source/index.md, docs/source/install.md, guide/source/3.0-migration.md, guide/source/index.md, npm-packages/babel-preset-meteor/babel-presets-meteor/package-lock.json
OSS-415
As part of the initiative to mantain Meteor secure, we will resolve few security alerts [performed by dependabot scanning](https://github.com/meteor/meteor/security/dependabot) on each release.
=> Security updates RC.2

.envrc, packages/accounts-password/password_server.js
https://github.com/meteor/meteor/issues/13072
=> [2.x] Add Accounts.addEmailAsync

.envrc, docs/source/install.md, v3-docs/v3-migration-docs/.vitepress/config.mts, v3-docs/v3-migration-docs/breaking-changes/upgrading-packages.md, v3-docs/v3-migration-docs/guide/publishing-packages.md, v3-docs/v3-migration-docs/vite-bundler/setup.md
- Add info about publishing packages
- Add info about `sudo` and troubleshooting (Gabs' issue) to main docs
- Add info about vite bundler
=> [3.x] Update Migration Docs

docs/source/roadmap.md
I'm just fixing the link to blog post about scaffold api.
=> fix: broken link into roadmap post

packages/meteor/asl-helpers.js, tools/runners/run-app.js, tools/static-assets/server/boot.js, tools/tool-env/profile.ts, tools/utils/fiber-helpers.js
=> Rename global variable to prevent conflicts

README.md
=> Update README.md to show Meteor 3 tag
