meteor/meteor

packages/webapp/package.js
update to latest version of cordova-plugin-meteor-webapp (1.6.0) which resolve issue about IOS and local web server restart after device sleep :
https://github.com/meteor/cordova-plugin-meteor-webapp/commit/963cef8392d0fdd43700cc2b80e2fc2d4f692baf
Hard to say if issues depend on this.
until it's merged you can update to 1.6.0 manually with
`meteor add cordova:cordova-plugin-meteor-webapp@1.6.0`
=> update cordova-plugin-meteor-webapp dependency to 1.6.0

History.md, packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/package.js, packages/standard-minifier-js/package.js
PR #9652 by @klaussner upgraded `uglify-es` from 3.2.2 to 3.3.10 to fix issue #9647, but 3.3.9 is the latest version published to npm, and 3.3.10 seems to suffer from this bug: https://github.com/mishoo/UglifyJS2/issues/2896
For that reason, I think it might be best to downgrade `uglify-es` to 3.3.9, at least until 3.3.11 is published.
Since this bug causes `uglify-es` to throw during minification, the `meteorJsMinify` function falls back to Babel's minifier, which is known to use massive amounts of memory, and may be contributing to OOM problems such as #9568. In other words, there's a chance that this downgrade will help with #9568.
=> Downgrade uglify-es to version 3.3.9 (latest published version).

History.md, meteor, scripts/build-dev-bundle-common.sh, scripts/dev-bundle-tool-package.js, scripts/generate-dev-bundle.sh
Fairly self-explanatory, though there are a number of notable changes, since it's been a while since `npm` released a new version:
* http://blog.npmjs.org/post/171139955345/v570
* http://blog.npmjs.org/post/171169301000/v571
* http://blog.npmjs.org/post/171813275740/v580-next0
* http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
=> Update npm to version 5.8.0.

History.md
Since these are legacy release branches, we want to make extra sure we resolve any merge conflicts in favor of the current `master` branch (1.6.1), without accidentally reverting to older code. Also, I can't merge these branches into `master` from the command line without overriding GitHub's branch protection, so it seems easiest just to open a PR, wait for the tests to pass, and merge from the web.
=> Merge release-1.4.4.x and release-1.5.x into master.

tools/isobuild/compiler-plugin.js
This PR caches the linker disk cache files in memory. These files are huge and most of them rarely change on a given rebuild. It uses the existing `optimisticReadJsonOrNull` function to replace a call to `files.readJSONOrNull`.
This improved rebuild times in my application by a solid 10-15%.
=> Keep linker cache files in memory

packages/modern-browsers/modern-tests.js, packages/modern-browsers/modern.js
This PR belongs to https://github.com/meteor/meteor/issues/9751 and will consider chrome for mobile as a modern browser. I took up the [idea](https://github.com/meteor/meteor/issues/9751#issuecomment-374955713) of @benjamn and kept it generic in case there are other browsers with the same relation.
=> Define browser aliases for modern browser test

scripts/test-balancer/index.js
Split from #9785.
This PR catches an error in the test load-balancer script that manifests if there is a mismatch between the CircleCI environment variable `NUM_GROUPS` and the actual number jobs in the workflow that are running test groups.
This can happen if you are testing from a checkout and comment out jobs in order to speed up CircleCI turnaround.
=> Protect against missing results files in test load balancer

packages/accounts-base/accounts_server.js, packages/allow-deny/allow-deny.js, packages/mongo/mongo_driver.js, packages/mongo/mongo_livedata_tests.js, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js, tools/runners/run-mongo.js
This PR updates the MongoDB driver from 2.2.34 to 3.0.5 and addresses the breaking changes described in [`CHANGES_3.0.0.md` (`node-mongodb-native`)](
https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md) and https://github.com/meteor/meteor-feature-requests/issues/268#issuecomment-366048866.
**Summary of the changes:**
* Create the `Db` instance manually because `MongoClient` passes a client instance instead of a database to the callback function. I'm using the undocumented `client.s.options.dbName` property to get the database name because I couldn't find better way to access it without parsing the URL in the `MongoConnection` constructor.
* Use `Cursor.prototype.next` instead of `Cursor.prototype.nextObject` (deprecated in version 2 and removed in version 3).
* Use …
=> Update MongoDB driver to 3.0.5

tools/isobuild/isopack-cache.js
https://github.com/meteor/meteor-feature-requests/issues/283
The `ProjectContext#_buildLocalPackages` method calls `IsopackCache#buildLocalPackages` which calls `_ensurePackageLoaded` for each local package, so this commit exposes how long each of those
`_ensurePackageLoaded` calls takes (when `METEOR_PROFILE` is enabled).
=> Provide more detailed profiling of _buildLocalPackages.

packages/http/httpcall_client.js
For example: if we lost connection in middle of http request now we report `Connection lost` instead `network`.
[See diff for complete changelog](9806/files).
=> Fine-tune error messages in HTTP lib

History.md, packages/mongo/mongo_driver.js, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js
Since version 3.0.6 of the MongoDB driver, the internal `client.s` property is no longer necessary to create the database object. If `MongoClient.prototype.db` is called without arguments, it will use the database name from the connection URI (https://jira.mongodb.org/projects/NODE/issues/NODE-1258).
This reverts 567e620a867a5e34188024d3175d4cc9dedaff3b, see https://github.com/meteor/meteor/issues/9827#issuecomment-383107731.
@abernix I had to target `release-1.7` instead of `devel` because the driver update from #9790 was merged into `release-1.6.2` and isn't on `devel` yet. :upside_down_face:
=> Update MongoDB driver to 3.0.7

packages/meteor/server_environment.js
In many production systems logs from the application will be forwarded to various logging systems, sometimes third party ones. Since Meteor logs the value of `METEOR_SETTINGS` when it's not valid JSON, all credentials in your settings will be leaked to any third parties. This will prevent that. 
There was a short discussion on the [feature request](https://github.com/meteor/meteor-feature-requests/issues/293) on whether or not to make this change backwards compatible, but the conclusion was that logging the settings to stdout offers little value anyway, so let's just get rid of it.
=> Stop logging value of METEOR_SETTINGS when it is not valid JSON.

packages/non-core/bundle-visualizer/package.js, packages/non-core/bundle-visualizer/server.js, packages/webapp/webapp_server.js, packages/webapp/webapp_tests.js, tools/isobuild/bundler.js
Inspired by discussion with @CaptainN in #9776, I think we can (and should) stop relying on URL prefixes to determine whether to load static files from the `web.browser` (modern) or `web.browser.legacy` (legacy) architectures. If this works, it will be a major ergonomic simplification for the modern/legacy system coming in Meteor 1.7.
This PR makes `webapp` serve different static files based on `isModern(request.browser)`, which is something we already have to do without the help of URL prefixes [in the `dynamic-import` package](https://github.com/meteor/meteor/blob/8e6f673fd066a69b2b4779526d200a7be0f1fc73/packages/dynamic-import/server.js#L80-L82).
Note that `web.cordova` URLs will still be prefixed with `/__cordova/`, as they always were, even before #9439 split `web.browser` and …
=> Stop prefixing legacy URLs with /__browser.legacy

packages/facebook-oauth/facebook_client.js, packages/facebook-oauth/facebook_server.js, packages/facebook-oauth/package.js
So, Facebook is once again upgrading their API.
They also require all apps which require more fields beyond `public_profile` and `email` permissions, [to go through the review process](https://developers.facebook.com/docs/apps/review/faqs/#faq_2159180284311114).
I have also updated the list of fields that are retrieved and saved, according to [the FB docs](https://developers.facebook.com/docs/facebook-login/permissions/v3.0) to retrieve a few more fields.
I was unable to locate under which permissions the `locale` field is retrievable, so I removed it.
=> facebook-oauth: upgrade api version to v3

packages/boilerplate-generator/generator.js
Got this error with meteor `1.4.2.3`:
```
(webapp_server.js:730) Error running template: ReferenceError: toHTMLAsync is not defined
at Boilerplate.toHTML (packages/boilerplate-generator/generator.js:47:12)
at getBoilerplate (packages/webapp/webapp_server.js:269:62)
at packages/webapp/webapp_server.js:728:23
```
Looked into it and it just was that the method was being called without `this.`.
=> Fix deprecated toHTML method

packages/ecmascript-runtime-client/modern.js
with the split of modern/legacy bundles we no longer polyfill already present standard features. While array.prototype.includes is available in modern browsers flatten and flatMap aren't. This pr readds the polyfills to the modern bundle.
------
If I got this right: https://github.com/meteor/meteor/blob/master/CONTRIBUTING.md#submitting-pull-requests I should base of devel, but this seems kind of impossible as devel doesn't yet include the [modern/legacy](https://github.com/meteor/meteor/tree/devel/packages/ecmascript-runtime-client) split. Just ping me if I should rebase or sth.
=> polyfill es7 array functions

tools/fs/files.js
`symlinkWithOverwrite` currently relies on Windows throwing an error when creating a file symlink with a source that is a folder, to know when the source is a folder and recreate the symlink as a junction. Windows 10 April 2018 Update no longer throws the error and instead creates the symlink despite it having the wrong type. This PR changes it to check if the source is a folder before creating the symlink.
Fixes #9863.
=> Fix creating symlinks on Windows April 2018 Update

packages/mongo/oplog_tailing.js
Whenever there is any update to the oplog, each matched listener gets a cloned version of the oplog update. As the comment in the diff mentioned, this may not be necessary. As best as I can tell by looking through the code it is indeed not necessary.
This is a small change but has significant performance implications, since this clone may be executed many times for each oplog entry. 
For example, suppose you have 1000 publications/observes on the `Widgets` collection. Further suppose that the publications/observes don't include a specific `_id` in the selector. In that case, any update to any document in the `Widgets` collection would clone the oplog entry 1000 times.
=> Remove EJSON.clone from onOplogEntry handler

packages/ddp-server/crossbar.js
I've noticed that almost all of the time spent in `ObserveHandle.stop` (called when publications/observes are stopped) is spent calling the `_.isEmpty` function. This PR manually tracks the number of listeners so that it isn't necessary to call this function.
Here is a profile before the change: https://app.box.com/s/g2uxbqu1kduik9a4sb6kb9aw3jrfinex
Here is a profile after the change: https://app.box.com/s/evqvytvp07pasuobl1c42n1cz82liyv7
I produced these profiles using this reproduction code https://gist.github.com/veered/931624389163916ded3a4f5617b558d1. The time spent in `ObserveHandle.stop` went from 1390ms to 34ms.
I know that this reproduction code is pretty extreme, but I've noticed this performance issue in production. It's possible that this PR could help resolve …
=> Manually track number of crossbar listeners by collection

History.md, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, tools/cli/commands.js, tools/fs/files.js, tools/isobuild/builder.js, tools/tests/old/test-bundler-assets.js, tools/tests/old/test-bundler-npm.js, tools/tests/old/test-bundler-options.js, tools/tool-testing/sandbox.js
This is a very small release intended to fix #9863 by making #9887 available to Windows users without forcing them to update to Meteor 1.7 (yet). Thanks very much to @zodern for identifying a solution to this problem.
In short, after the Windows April 2018 Update, the Windows file system suddenly stopped reporting any error when `fs.symlink` failed, which caused Meteor to continue as if the symlink had been created, when in fact it had not. While I don't understand how this new behavior can be considered anything other than a bug, we don't have any control over the QA of Windows releases, so I suppose we just have to cope with their mistakes.
=> Release 1.6.1.2

tools/fs/watch.js
Allows users to set the `METEOR_FILE_WATCH_COALESCE_MS` environment variable (https://github.com/meteor/meteor/issues/9896#issuecomment-391812382) to control how long Meteor waits before a file change is processed.
Fixes #9896.
=> Use environment variable to control file watcher coalescence delay

tools/cli/dev-bundle-bin-helpers.js
In my local development environment, the `meteor` command resolves to my Meteor checkout, and I use `~/.meteor/meteor` explicitly when I want to run a released version of Meteor.
If I run
```sh
~/.meteor/meteor npm test
```
and the `package.json` file defines an npm `test` script that refers to `meteor`, in my environment this `meteor` won't be the same as the one I used to run `~/.meteor/meteor npm test`, which can introduce weirdness such as pinning the versions of packages in `meteor/packages/non-core`, and all the usual Meteor version inconsistency risks.
This commit fixes that problem by prepending the directory that contains the `meteor` (or `meteor.bat`) executable to the `PATH` before running `meteor npm ...` commands.
=> Ensure npm scripts find correct meteor executable.

packages/dynamic-import/server.js
A tweak to the change introduced in c4b5707747ce3c5bf339b62940da84628680a1d3 to fix #9952.
This will allow clients that don't support the * value in `Access-Control-Allow-Headers`,
but do specify the `Access-Control-Request-Headers` (such as electron 2.0.2) to use dynamic import.
=> Allow dynamic import() requests from any origin on any device.

packages/webapp/legacy_test_asset.js, packages/webapp/modern_test_asset.js, packages/webapp/package.js, packages/webapp/webapp_server.js, packages/webapp/webapp_tests.js
Fixes #9953.
cc @glasser @morloy
=> Let any client request any static resource.

packages/socket-stream-client/browser.js, packages/socket-stream-client/package.js
Not including `SockJS` in the modern JS bundle was a nice bundle size savings (28KB before gzip), but `SockJS` works better than a native `WebSocket` for clients that are stuck in unusual networking situations, and the fallback of using dynamic `import()` to load `SockJS` when the native `WebSocket` failed was much slower than simply including `SockJS` in the bundle and using it from the start.
Moreover, the new `meteor create --minimal` starter app does not use `socket-stream-client` (nor DDP), so going back to including `SockJS` in both the modern and the legacy bundles should have no impact on the minimal modern bundle size.
If you want to continue using a native `WebSocket` instead of `SockJS`, you can always pin the older version of the socket-stream-client package:
```sh
meteor add …
```
=> Statically import SockJS in both modern and legacy bundles.

tools/isobuild/bundler.js, tools/isobuild/compiler-plugin.js
When a CSS (or compiled-to-CSS) module is lazy (e.g., in `imports/` or `node_modules`) and not otherwise imported by another CSS module, Meteor automatically turns it into a JS module so that it can be handled by the `ImportScanner`, and imported dynamically by other JS modules.
Until now, there were two problems with CSS handled in this way: it did not have proper source maps, and the CSS text was not minified in production.
This commit introduces a special minification step for dynamic CSS, which must take place before we create the dynamic JS module. Waiting for the usual minification of CSS would be a mistake, since that happens long after the `ImportScanner` and `Linker` have already processed JavaScript modules. Modifying the contents of JS modules at that point would be impossible …
=> Source maps and minification for dynamic CSS modules.

History.md, meteor, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/build-dev-bundle-common.sh
This will be a quick patch release to update Node to version [8.11.3](https://nodejs.org/en/blog/release/v8.11.3/).
=> Release 1.6.1.3

packages/non-core/bundle-visualizer/package.js, packages/non-core/bundle-visualizer/server.js
Fixes the issue mentioned in the recent [Meteor Night talk on 1.7](https://youtu.be/vpCotlPieIY?t=1525). 
Instead of `bundle (1)` and `bundle (2)`, you should now see `web.browser` and `web.browser.legacy`.
=> Replace generic bundle names with arch names in bundle-visualizer

History.md, tools/isobuild/resolver.js
As reported by @justinanastos via Slack, files with non-`.js` file extensions (e.g. `index.tsx`) cannot be used to make a directory importable in the same way that an `index.js` module can.
Fixing this involves updating both [the runtime module system](https://github.com/meteor/meteor/commit/445fd3714a9e85ffe40975185f550faf4dcde099) and our build-time `Resolver` logic (this PR).
Unfortunately this fix will have to wait for the next Meteor release, since it involves changes to the build tool.
=> Allow resolving index.* modules with non-.js file extensions.

tools/isobuild/compiler-plugin.js, tools/isobuild/import-scanner.js
This is a follow-up to PR #9983, which allowed misbehaving compiler plugins to fail to report errors when returning `null` from a lazy finalizer function (which always implies there was an error).
=> Improve lazy OutputResource error reporting.

packages/non-core/bundle-visualizer/client.js, packages/non-core/bundle-visualizer/package.js
Zapped the one use of `http` here! ⚡
I wasn't really sure which version number to bump the package to due to #10025 not yet being merged.
=> Replace http with fetch in bundle-visualizer

packages/appcache/appcache_tests-client.js, packages/appcache/package.js, packages/autoupdate/package.js, packages/ddp-client/package.js, packages/dynamic-import/client.js, packages/dynamic-import/package.js, packages/fetch/.npm/package/.gitignore, packages/fetch/.npm/package/README, packages/fetch/.npm/package/npm-shrinkwrap.json, packages/fetch/README.md, packages/fetch/fetch-tests.js, packages/fetch/legacy.js, packages/fetch/modern.js, packages/fetch/package.js, packages/fetch/server.js, packages/fetch/tests/asset.json, packages/fetch/tests/main.js, packages/non-core/bundle-visualizer/client.js, packages/non-core/bundle-visualizer/package.js
As described in my [talk](https://youtu.be/vpCotlPieIY?t=29m18s) about Meteor 1.7's modern/legacy bundling system (relevant [slides](https://slides.com/benjamn/meteor-night-may-2018#/46)), the [WHATWG `fetch()` API](https://fetch.spec.whatwg.org/) is a great example of a feature that requires a totally different implementation in modern browsers, legacy browsers, and Node.
The `fetch()` API is already widely used in the JavaScript community, and I suspect it will eventually replace the core Meteor `http` package for most HTTP request needs, especially since it is essentially free in modern browsers.
=> Provide isomorphic implementation of WHATWG fetch() API.

History.md, packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/minifier.js, packages/minifier-js/package.js, packages/standard-minifier-js/package.js
Thanks to @arrgh for suggesting this replacement: #10042 
This may help with lots of issues, most recently #10044 but also #10034, #9976, #9711, and #9568, to name a few. In particular, since we silently fall back to `Babel.minify` when `uglify-es` (now `terser`) fails, there should be fewer problems with `Babel.minify` (parse errors, performance, memory usage) if `terser` succeeds more often.
Note: because we have bumped the minor versions of `minifier-js` and `standard-minifier-js`, and they are core packages, you'll have to be using the next beta version of Meteor 1.7.1 in order to update to these versions, unless you clone those packages into your local `packages/` directory. However, if we can validate that `terser` is fully backwards compatible with `uglify-es`, we might be able to …
=> Replace uglify-es with terser, a more actively maintained fork.

packages/mongo/polling_observe_driver.js
This PR adds two new environment variables to the polling observe driver. Both of these values are already configurable on a cursor-by-cursor level, but it is helpful to be able to configure them globally.
First, it adds `METEOR_POLLING_THROTTLE_MS`. This controls the maximum number of times a poll can be scheduled within a given time span. Increasing this value can greatly help performance when the result set of active publications are experiencing high write velocity.
Second, it adds `METEOR_POLLING_INTERVAL_MS`. Polling observers re-poll every `METEOR_POLLING_INTERVAL_MS` milliseconds even if the Meteor server has made no updates. This can be super expensive. It is also completely unnecessary if there is only one server updating the db (which is often the case).
Although polling …
=> Configure polling throttle and polling interval

packages/mongo/collection.js
When the client receives a "changed" message from the server, it currently always calls an update on Minimongo. However, if the update was initiated on that same client, Minimongo will already be up-to-date. 
In many applications, this is a very common situation. And for applications that are using collection hooks, even a no-op update will trigger all "before" hooks (this includes people using SimpleSchema and https://github.com/matb33/meteor-collection-hooks). So even no-op updates can have a fair amount of overhead.
This PR ensures that no-op updates aren't happening in response to a "changed" message on the client.
Note: I've been running this change in production for almost 2 years, and I've had no issues. Figured it was time to make a PR for it :)
=> Don't update Minimongo if the update will be a no-op

packages/boilerplate-generator-tests/test-lib.js, packages/boilerplate-generator/generator.js, packages/boilerplate-generator/template-web.browser.js, packages/webapp/webapp_server.js, tools/fs/watch.js, tools/isobuild/bundler.js
After moving our Meteor assets out to a CDN, the [Mozilla Observatory](https://observatory.mozilla.org/) kept complaining about missing [Subresouce Integrity](https://infosec.mozilla.org/guidelines/web_security#subresource-integrity) in our JavaScript files.
This PR adds a `sha512` hash to all basic Meteor files served to the client.
Solves meteor/meteor-feature-requests#35.
=> Add Subresource Integrity for JS and CSS files

History.md, tools/fs/watch.js, tools/isobuild/bundler.js
Follow-up to https://github.com/meteor/meteor/pull/9933.
As recommended by @abernix, the sha1 hash of every file is now computed from the file's sha512 hash, so we don't have to hash the entire contents of the file twice with two different algorithms.
Other changes/improvements:
* Invalidate the hashes when/if `File#setContents` is called.
* Ignore `options.hash` and just compute hashes from actual file contents. Disagreement here would be worse than any performance benefits from precomputing the hash.
=> Improve File hashing logic in bundler.js.

packages/github-oauth/package.js, packages/meetup-oauth/package.js
Looking into https://github.com/meteor/meteor/pull/9558#issuecomment-402178859, it seems that `_` is being used in two packages' architectures where it is not specified in `package.js`. I thought that `_` would have been available anyway, because these packages are using oauth, which in turn uses underscore everywhere, but I suppose not.
So this PR makes those two usages of underscore explicit in the respective `package.js` files, hopefully resolving @jancurn's issue without having to wait for #9558 to get merged.
=> Use underscore on both client and server in github-oauth and meetup-oauth

packages/autoupdate/autoupdate_client.js, packages/autoupdate/autoupdate_cordova.js, packages/autoupdate/autoupdate_server.js, packages/autoupdate/package.js, packages/meteor/define-package.js, packages/meteor/message-dispatch.js, packages/meteor/package.js, packages/modern-browsers/modern.js, packages/modern-browsers/package.js, packages/webapp/webapp_server.js, packages/webapp/webapp_tests.js, scripts/dev-bundle-tool-package.js, tools/fs/watch.js, tools/isobuild/bundler.js, tools/project-context.js, tools/runners/run-app.js, tools/static-assets/server/boot.js
Now that Meteor [builds two client bundles](https://blog.meteor.com/meteor-1-7-and-the-evergreen-dream-a8c1270b0901), build times have naturally increased a bit. We are hard at work attacking this problem from multiple angles, such as #9983, and I'm confident that Meteor 1.7.1 build times will be shorter for most apps than they were before Meteor 1.7, despite building both `web.browser` and `web.browser.legacy` bundles.
Nevertheless, since most testing in development happens using one bundle/browser at a time, it has been suggested (#9948) that we could skip the legacy build in development, as a cheap short-cut to faster rebuild times. To be honest, I don't love most of these ideas for disabling the legacy build with some sort of additional configuration, because supporting older browsers …
=> Delay building web.browser.legacy bundle until after development server restarts.

meteor
A recent commit (5c1ba3a85ec17141f02c61cea03044596c9b4a78) added a flag to request 4GB space for
node, which causes an immediate segmentation fault on 32-bit Linux. Fixes #10080 .
=> Request less than 4GB memory on 32-bit platforms

packages/ddp-server/livedata_server.js, packages/diff-sequence/diff.js, packages/id-map/id-map.js, packages/minimongo/cursor.js, packages/mongo-id/id.js
@benjamn  The same spirit as #10017, but replaces all `Object` usage in ddp-server.
I've tried to minimise the complexity of the changes.
Alternatively, I can only change `SessionCollectionView#documents` to a `Map`, but it seems like a missed opportunity.
---
nb: there's also a small change to `mongo-id` as it started showing up in cpu-profiles due to use of [`startsWith`](https://jsperf.com/charat-vs-startswith/2)
=> ddp-server: replace usage of Object with Map & Set

.circleci/config.yml
With the creation of a new package that has npm dependencies and self-tests, there was a gap in the CircleCI cache. I've added the path for the dependencies to the list, so they will be picked up in the future.
Since we've already run some tests with the current set of dependencies, there is an existing immutable cache for the combined shrinkwrap checksum. To generate a new cache for the same checksum, I've bumped the version numbers on the cache keys. And since I've added the new deps to cache group 2, I've only bumped the version numbers for that group.
=> Cache inter-process-messaging dependencies in CircleCI

.circleci/config.yml
Upon closer inspection of the CircleCI logs after last night's [armageddon](https://status.circleci.com/incidents/yj497xcsqxxf), I realized that in #10085 I missed a few other new packages in the codebase that have npm dependencies available for caching.
This PR adds those to npm deps cache group 2 and bumps the version numbers in the keys again. I think I got 'em all this time. 🤞
=> Cache fetch and mongo-decimal npm dependencies in CircleCI

packages/srp/package.js, packages/srp/srp.js
The `srp` (Secure Remote Password) package is required by the `accounts-password` package, so this change gets us one step closer to, if not completely, removing `underscore` from apps that have it solely due to use of the accounts packages.
=> Remove underscore from srp package

tools/isobuild/import-scanner.js
Small fix for typo that caused an error on build tool startup when we tested our app against 1.7.1-beta.19
=> Fix typo in import-scanner

packages/reactive-dict/migration.js, packages/reactive-dict/package.js, packages/reactive-dict/reactive-dict-tests.js, packages/reactive-dict/reactive-dict.js, packages/session/package.js
Targeting `release-1.7.1` branch because testing against `devel` is causing babel errors and I think our tests will fall over.
This is not a full modernization - just removing underscore, so there is less surface area for bugs.
=> Remove underscore from reactive-dict and session packages

tools/tests/mongo.js
This PR updates MongoDB to version 4.0 and the driver to version 3.1.
Fixes meteor/meteor-feature-requests#269.
=> Update MongoDB to 4.0

packages/facts-base/facts_base.tests.js, packages/facts-base/facts_base_server.js, packages/facts-base/package.js
Another small `underscore` removal. This one is server-only, so there is no client bundle impact.
I've also added a few unit tests to the `incrementServerFact` function.
=> Remove underscore from facts-base and add tests

packages/babel-compiler/babel-compiler.js, packages/babel-compiler/package.js
Currently we cannot us json5 in babel files which are used by meteor. That's a bit counter intuitive as babel itself supports json5 and we share babel files between jest and meteor. So atm we cannot e.g. add comments in babel files which are used by meteor.
This pr changes the parser the use json5 instead - which as i get should be fully backwards compatible and is already included via babel.
- fixes #10068 
-----
Not sure how to properly add a test for this, but I tested locally by adding a json5 .babelrc and running from checkout:
```
{
env: {
test: {
plugins: ['dynamic-import-node']
}
}
}
```
=> Allow json5 in babelrc

packages/webapp/webapp_server.js
The inline middleware that strips the ROOT_URL_PATH_PREFIX destroys req.url. If this happens before the query parameters are parsed by use(query()) the query parameters are always missing. This causes OAuth authentication to fail when ROOT_URL_PATH_PREFIX is set.
A better fix would be to fix the path stripping logic so that it preserves the URL parameters, since other things may try to rely on them later. But this works for now.
=> Parse URL query parameters before it's destroyed

packages/non-core/coffeescript-compiler/.npm/package/npm-shrinkwrap.json, packages/non-core/coffeescript-compiler/package.js, packages/non-core/coffeescript/package.js, packages/non-core/coffeescript/tests/bare_tests.js, packages/non-core/coffeescript/tests/coffeescript_strict_tests.coffee, packages/non-core/coffeescript/tests/coffeescript_test_setup.js, packages/non-core/coffeescript/tests/coffeescript_tests.coffee, packages/non-core/coffeescript/tests/coffeescript_tests.js, packages/non-core/coffeescript/tests/litcoffeescript_tests.coffee.md, packages/non-core/coffeescript/tests/litcoffeescript_tests.litcoffee, packages/non-core/coffeescript/tests/modern_browsers.coffee
@benjamn All I needed to do to add support for `setMinimumBrowserVersions`/the `modern-browsers` package was update the versions of the Meteor core packages that the `coffeescript` package was depending on. Once `coffeescript` was using the latest `ecmascript`, `caching-compiler` and so on, `setMinimumBrowserVersions` just started working.
While I was at it, I updated to the latest CoffeeScript and added some missing `import` statements and did some other general cleanup.
I can’t really find a good test for `setMinimumBrowserVersions` in the codebase; from what I can tell, my browser always gets the modern bundle when I load the tests app, whether or not I call `setMinimumBrowserVersions`. Please let me know if there’s some way to make this test more robust, or if I should take it out.
I …
=> CoffeeScript 2.3.1, support for setMinimumBrowserVersions

History.md
The `mongodb` package was updated in two PRs (#10058 and #10101) and both included a history entry (see the lines above the ones I removed).
=> Remove duplicate `mongodb` package update entry from history

tools/cordova/project.js, tools/isobuild/bundler.js
This strives to fix several issues with cordova integration plugins handling:
Fixes several cases causing cordova plugins reinstall on every build:
- proper handling of scoped npm cordova plugins (adding one would cause reinstall on every build)
- proper detection of plugin removal (previously a cordova plugin containing a dependency would make the algorithm think a package was removed from cordova-plugins)
- proper handling of plugins which have plugin.xml id different than the npm package name
Additionally:
- rechecks the build integrity verifying if packages were really installed and perform a retry if needed.
- allows to override a meteor package cordova dependency with scoped package i.e. @scope/cordova-dummy-plugin will now override a cordova-dummy-plugin dependency. (now in this …
=> Cordova plugin handling algorithm consistency improvements

History.md, packages/minimongo/cursor.js, packages/minimongo/minimongo_tests_client.js, packages/minimongo/sorter.js, packages/mongo/mongo_driver.js
Fixes https://github.com/meteor/meteor/issues/10212 . Note that while it is now compatible with Mongo 3.6+, it's incompatible with mongo < 3.6
=> Make array-field sorting compatible with mongo 3.6+ behavior

packages/babel-compiler/babel-compiler.js
When creating plugin it can be useful to have accessible info about target architecture of current transpilation. Plugin could therefore alter transformations of code. Based on architecture it would be possible to determine whether result will be run on server or client and therefore hide some critical logic or perform different operations. This allows for more isomorphic code which could be easier to write.
meteor/meteor-feature-requests#326
=> Exposing information about target architeture

packages/minifier-js/minifier.js, packages/minifier-js/package.js
Right after https://github.com/meteor/meteor/pull/10239 got merged, terser `3.9.2` got released with a fix for https://github.com/terser-js/terser/issues/117 . The previous pull request added the `ie8` option to workaround that specific safari bug.
However, since IE 8 hasn't been supported for a while ( https://github.com/meteor/meteor/issues/7761#issuecomment-247546074 ), it seems safer to only include the workarounds that are really necessary, to minimize the risk breaking compliant browsers.
=> Update terser to 3.9.2

packages/standard-minifier-css/package.js, packages/standard-minifier-css/plugin/minify-css.js
https://github.com/meteor/meteor/issues/10112#issuecomment-428646872
Further down in the `mergeCss` function, when we call `CssTools.stringifyCss`, we pass the following option:
```js
// don't try to read the referenced sourcemaps from the input
inputSourcemaps: false
```
Apparently this isn't enough to avoid reading inline source maps from the input file, so we should be a bit more aggressive about preventing `postcss` from picking up inline source maps.
This change mostly affects `.css` files imported from `node_modules`, and possibly raw `.css` files in the application that happen to have inline `sourceMappingURL=` comments. For CSS output from compiler plugins like LESS and SCSS, we have a totally different mechanism of handling source maps, namely `file.getSourceMap()`.
Should fix …
=> Ignore inline source maps when minifying CSS files.

packages/reactive-dict/reactive-dict.js
Adding documentation for `ReactiveDict` (meteor/docs#52) depends on generated data from JSDoc comments. This PR adds those JSDocs to accompany a future PR on meteor/docs
=> Add JSDoc comments to reactive-dict to fix meteor/docs#52

packages/autoupdate/autoupdate_client.js, packages/autoupdate/autoupdate_cordova.js, packages/autoupdate/autoupdate_server.js, packages/autoupdate/client_versions.js, packages/autoupdate/package.js, packages/ddp-server/package.js, packages/reactive-dict/package.js, tools/tests/apps/hot-code-push-test/hot-code-push-test.js, tools/tests/apps/standard-app/.meteor/packages, tools/tests/cordova-plugins.js, tools/tests/custom-minifier.js, tools/tests/hot-code-push.js, tools/tests/package-tests.js, tools/tests/stylus-cross-packages.js
The `autoupdate` package uses a local `Mongo.Collection` (i.e., not synchronized with MongoDB) to store hashes of current client resources, which are used to notify clients when new resources are available (in development and production). However, the collection is only used for storage and simple update operations for which a `Map` would be sufficient. If a Meteor app doesn't otherwise use MongoDB or Minimongo, this causes MongoDB to be started unnecessarily and a lot of unused code to be included in the client bundles.
This PR replaces the collection with a `Map`-based implementation, which reduces the bundle size (un-gzipped) by up to 63 kB.
To do:
=> Remove `mongo` dependency from `autoupdate` package

packages/ddp-client/client/client_convenience.js, packages/ddp-client/common/livedata_connection.js
- Fix return type of onMigrate callback, as it should be an array.
- Remove exception on retry, as onMigrate callback can be invoked repeatedly until all components are ready to migrate.
- Force ddp negotiation failures to cause an uninterruptible reload.
---
I've been using these changes in a fork for some time. As, I have a lib that prevents reload until a page change occurs.
very difficult to write unit tests for these, but let me know if it's super necessary and I'll give it a shot.
=> ddp-client: fix usage of reload

packages/caching-compiler/caching-compiler.js, packages/caching-compiler/multi-file-caching-compiler.js, packages/non-core/coffeescript-compiler/.npm/package/npm-shrinkwrap.json, packages/non-core/coffeescript-compiler/package.js, packages/non-core/coffeescript/.npm/plugin/compile-coffeescript/npm-shrinkwrap.json, packages/non-core/coffeescript/compile-coffeescript.js, packages/non-core/coffeescript/package.js, tools/isobuild/bundler.js, tools/project-context.js, tools/tests/compiler-plugins.js
Lazy compilation became possible in Meteor 1.8, thanks to #9983, but it's up to individual compiler plugin packages to take advantage of it.
Using lazy compilation in the `coffeescript` package should help with #10298.
=> Bump CoffeeScript to version 2.3.2 and enable lazy compilation.

packages/oauth/end_of_popup_response.js, packages/oauth/end_of_redirect_response.js, packages/oauth/package.js
Quick fix for #10305 by reverting https://github.com/meteor/meteor/commit/fcd650bd46511e3192098d06e0be2f2083ebc745 for `end_of_popup_response.js` and `end_of_redirect_response.js`.
=> Fix #10305

packages/autoupdate/autoupdate_client.js
This fixes an issue (c.f. https://github.com/Urigo/meteor-client-bundler/issues/87) where when the __meteor_runtime_config__ does not contain a proper autoupdate configuration object, the client would fail to load properly.
=> Fix uncaught TypeError in autoupdate_client.js

packages/accounts-base/accounts_server.js
Fixes a bug in `accounts-base` introduced by "modernization".  The check whether the email address matches the restriction pattern fails currently for external login services, since it treats `user.services` like an array rather than as an object.
=> user.services is not an array.

packages/caching-compiler/caching-compiler.js
While strictly speaking more characters are allowed, they are not usable in a shell except for uppercase / digits / underscore.
( https://stackoverflow.com/a/2821183 )
=> Sanitize compiler name for environment variables

History.md, packages/modern-browsers/modern.js, packages/modern-browsers/package.js, packages/webapp/.npm/package/npm-shrinkwrap.json, packages/webapp/package.js
This PR introduces changes to treat "Headless Chrome" and Chromium the same as Chrome in terms of identifying them as "modern" browsers (and thus serving them the modern, rather than legacy, bundles).
Best I can tell, the major version portion of Chromium versions has always tracked all the way through to Chrome Canary, Dev and Stable releases.  The [Chromium versioning documentation](https://www.chromium.org/developers/version-numbers) seems to back this up.
Furthermore, Headless Chrome isn't really a "different" Chrome — in fact, all recent versions of Chrome can be run with the `--headless` flag (yes, even the one on your — the reader's — local computer!) to be run without the visual element (and driven programmatically).  However, when run with the `--headless` flag, Chrome switches …
=> Identify Chromium and Headless Chrome as "modern" browsers.

History.md, tools/isobuild/package-source.js, tools/tests/apps/modules/imports/imported.tests.js, tools/tests/apps/modules/tests.js, tools/tests/test-modes.js
New Meteor apps have the following `meteor.testModule` in their `package.json` files by default:
```json
"meteor": {
"testModule": "tests/main.js"
}
```
When `meteor.testModule` is defined, it determines the test entry point when running the `meteor test` command, ignoring legacy file naming conventions like `*.tests.js` or `*.app-tests.js`.
The `package-source.js` code changed by this commit was incorrect because it ignored those specially-named test files even when running tests, which was a problem if the `meteor.testModule` tried to import them explicitly, because they would not be properly compiled.
If you're using `meteor.testModule`, the distinction between `meteor test` and `meteor test --full-app` matters a bit less, since the test entry point will be the same for both modes, …
=> Stop excluding test modules when meteor.testModule found in package.json.

packages/webapp/package.js, tools/cordova/project.js
Incomplete list of key improvements:
=> Cordova improvements for Meteor 1.8.1

History.md, tools/isobuild/compiler-plugin.js, tools/isobuild/compiler.js, tools/isobuild/package-source.js, tools/tests/apps/modules/packages/modules-test-package/client.js, tools/tests/apps/modules/packages/modules-test-package/client/where.js, tools/tests/apps/modules/packages/modules-test-package/common.js, tools/tests/apps/modules/packages/modules-test-package/server.js, tools/tests/apps/modules/packages/modules-test-package/server/where.js
The `client/` and `server/` directories should be meaningful only for organizing application code.
Before this commit, if a Meteor package contained a `client/` or `server/` directory, any modules inside it could be imported, but they would not be properly compiled, because the `PackageSource#_findSources` method would ignore them in its initial scan, which determines the set of modules that get passed into compiler plugins.
Fixes #10393.
=> Do not treat client and server directories specially in packages.

packages/webapp/webapp_server.js
Hello @benjamn,
this a PR to fix https://github.com/meteor/meteor/issues/10377
Currently Auto-compress forces gzip compression, that cannot be disabled and therefore interferes with the possibility to enable a different Content-Encoding on a frontend-proxy.
Adding an environment variable to disable Auto-compress will allow to use Brotli compression through a front-end proxy, such as nginx, and provide better compression ratio than gzip.
`METEOR_DISABLE_AUTO_COMPRESS=1`
For more details, please see:
https://github.com/meteor/meteor/issues/10377
Thanks, Georgy
=> Selectively disable compression based on the incoming request. Fixes #10377

packages/minifier-css/minifier.js
I saw this while using dynamic import on a css file that had an `@import` statement.
The previous error message has a grammar error, but also says that the rules are not taking effect. However, in my case the import seemed to work, despite the warning.
The explanatory comment above the warning seemed clearer to me and also doesn't claim that it is definitely an error, so I reused that text in the warning itself.
=> Adjust css import warning text

History.md, packages/webapp/package.js, packages/webapp/webapp_server.js, tools/cordova/builder.js, tools/cordova/index.js, tools/tests/cordova-builds.js
This PR updates the `cordova-android` and `cordova-ios` npm packages to their latest versions, updates `cordova-plugin-meteor-webapp` to version 1.6.4 to include https://github.com/meteor/cordova-plugin-meteor-webapp/pull/71 (which was necessary because of the `cordova-android` update), and hopefully fixes https://github.com/meteor/cordova-plugin-meteor-webapp/issues/69 by making the Cordova `program.json` client version consistent with the `manifest.json` client version served by the web server (cc @lorensr).
The last change is the most significant one. Details in the commit message: https://github.com/meteor/meteor/pull/10416/commits/a89b34c4c2d8335b337355eb61c382949ff762d9
=> More Cordova improvements for Meteor 1.8.1

tools/console/console.js, tools/fs/files.js, tools/fs/watch.js, tools/isobuild/builder.js, tools/isobuild/bundler.js, tools/isobuild/meteor-npm.js, tools/runners/run-app.js
The times are from the todos app. Rebuilds are for editing a file that is only used in the client, but not in a `client` folder, causing both the server and clients to be rebuilt.
resolveContraints: 2,149 2,261
prepareProjectForBuild: 10,299 11,230
build app: 20,656 18,792
App process started after: 36,902 35,839
Creating watchers finished: 12,383 13,462ms after app started
AppProcess onListen: 23,900 25,644ms after app started
Usuable after: 60,802 61,483
prepareProjectForBuild: 6,713 6,674 7,158
rebuildApp: 4,555 4,269 4,008
App process started after: 11,690 11,499 11,621
Creating watchers finished: 4,536 4,057 4,001ms after app started
AppProcess onListen: 8,746 8,090 8,015ms after app started
Delayed build: 9,469 8,484 8,406ms after app started
Usuable after: 20,436 19,589 19,636 …
=> Windows build performance

tools/isobuild/compiler.js
Meteor currently reads and hashes each asset during every build. The watcher then uses the optimistic functions to read and hash the file, which stores a copy of the contents in memory. During rebuilds it then reads the file again, causing multiple copies of the file to be in memory.
This changes it to always use optimistic functions with assets. Starting with the second rebuild, this saves 1.5 - 2 seconds of garbage collection during each rebuild in one app in addition to not having to read or hash the files.
An alternative is to use `fs.copyFile` and avoid storing a copy of the file in memory: https://github.com/zodern/meteor/commit/3696b30e11261ab0d681591e62cc17cf2998dfe4. It did reduce the tool's memory usage by 400mb for this app, but the initial build is several hundred milliseconds …
=> Use optimistic functions with assets

tools/isobuild/builder.js, tools/isobuild/bundler.js, tools/isobuild/compiler.js
**JS minify performance**
In development, most of the time spent minifying is from converting the content of the files to and from Buffers. This was done before minifying for dynamic files to rename the function, and afterwards for all files to restore the function name. These changes have it avoid converting the contents to and from buffers where possible, and only restores the function name for dynamic files. Saves ~400ms per rebuild in a larger app.
**Skip calculating SRI for assets**
The current SRI standard supports css and js files, and Meteor only uses it for the main css and js bundles. These changes disable calculating the SRI hash for assets since Meteor currently doesn't use it for assets. If some packages or apps want the SRI hash for js or css assets, then two alternatives …
=> Write performance

packages/fetch/.npm/package/npm-shrinkwrap.json, packages/fetch/package.js, packages/minifier-css/.npm/package/npm-shrinkwrap.json, packages/minifier-css/package.js, packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/package.js, packages/non-core/mongo-decimal/.npm/package/npm-shrinkwrap.json, packages/non-core/mongo-decimal/package.js, packages/standard-minifier-css/package.js, packages/standard-minifier-js/package.js
I wanted to see some bugfixes from terser in 1.8.1, but checked some other outdated dependencies in the same run.
node-fetch: https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md -> some bugfixes
postcss: https://github.com/postcss/postcss/releases -> some performance improvements and bug fixes
cssnano: https://github.com/cssnano/cssnano/releases -> some performance improvements
decimal.js: https://github.com/MikeMcl/decimal.js/blob/master/CHANGELOG.md -> seems non breaking
=> fix(deps): update terser, fetch, decimaljs, postcss, cssnano

scripts/dev-bundle-tool-package.js, tools/isobuild/linker.js
- Updates source-map to 0.5.7 which includes some performance improvements for source nodes. In one app it saves up to 1.2 seconds during full rebuilds  
- Caches the stringified output of dynamic files instead of a source node, which allows skipping stringifying the source node when the dynamic file didn't change since the last build.
- The main client bundle is not recreated when only dynamic files change. In one app this saves 2 - 3 seconds during rebuilds when a dynamic file is changed.  It only stores the latest bundle in the cache for each architecture instead of waiting until the cache has reached its max size to remove old entries.  That is to avoid increasing the tool's memory usage, though I am not sure if it is needed.
=> Linker performance

CONTRIBUTING.md
Adding @zodern as a collaborator with write access (including triage/review), based on contributions that demonstrate deep understanding of the meteor/meteor codebase: #9887, #10399, #10452, #10453, #10454
Also updated other parts of `CHANGELOG.md` to reflect 2019 realities.
=> Update CONTRIBUTING.md, adding @zodern as a collaborator.

packages/oauth/oauth_browser.js
This bugfix enables scrollbars in OAuth popup in Mozilla Firefox.
Related to #10473
=> typo fixed

tools/runners/run-all.js, tools/runners/run-app.js
This PR will add the environment variable `METEOR_AUTO_RESTART`. It's default value is set to `true` and will fall to `false` once the parameter `--once` is added when running `meteor`.
For [meteortesting/meteor-mocha](https://github.com/meteortesting/meteor-mocha) we were long looking for a way to determine if we should end after all tests are run, to support running the tests in a CI/CD environment, but also have an easy way to keep the process running for development.
Our solution until now was to add a custom environment variable (`TEST_WATCH`) which must be together with the `--once` argument for Meteor itself. Since many people were confused by setting it to the wrong value, I wondered if there would be an easier way - and the simplest I could think of was to let our extension know …
=> Added an environment variable to see if Meteor will restart automatically

tools/cli/example-repositories.js
Hello @benjamn,
this PR updates the example repositories with an Angular 7 boilerplate.
The repository URL has been updated to use the Angular-Meteor project (the old URL is just a redirect).
Meteor 1.8.0.1 with Angular 7.1.1 are supported.
(Based on already merged PRs in Angular-Meteor: https://github.com/Urigo/angular-meteor-base/pull/131 and https://github.com/Urigo/angular-meteor/pull/1927)
Thanks, Georgy
=> Updated example repositories with Angular 7 boilerplate.

packages/mongo/oplog_observe_driver.js
We need to have more information to understand where the error `The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query selector is` is happening.
I had to run Meteor locally with more logs to be able to discover where was the problem. That was necessary because the error message is using `EJSON.stringify` in the selector hiding the undefined fields and it's also not showing the `collectionName` and `options`.
This PR is pretty simple, it just adds a new `console.error` without using any stringify to preserve the objects.
We have open issues like #10205 that probably can benefit from this change.
Logs examples:
Before this PR:
```
The Mongo server and the Meteor query disagree on how many documents match your …
```
=> Add more information on logs when Mongo and Meteor query disagree

tools/runners/run-mongo.js
Using the `isMaster` command instead of checking the replica set member state is more reliable because a node can be a primary without being writable (see https://github.com/meteor/meteor/issues/10381#issuecomment-449572478 for details).
Fixes #10381 (and #9026).
=> Wait until primary node is writable

meteor, scripts/dev-bundle-tool-package.js, tools/isobuild/compiler-plugin.js, tools/isobuild/css-modules.ts, tools/isobuild/import-scanner.js, tools/isobuild/isopack.js, tools/tool-env/install-babel.js, tools/tsconfig.json
These changes pave the way for incrementally converting the implementation of Meteor's command-line tool to TypeScript, which should have profound benefits for self-documentation via types, as well as substantially improving navigability and approachability for community contributors.
Just imagine being able to auto-complete the fields of the various `File`-like classes currently floating around the codebase, instead of having to track down their implementations every time. TypeScript was designed with large projects like Meteor in mind, and it seems increasingly irresponsible to forgo the benefits of a type system by relying on the expertise of a few core contributors who know the codebase inside and out. I am one of those few people, and I am very excited to have the assistance of a …
=> Enable TypeScript compilation of .ts modules in meteor/tools.

packages/ejson/stringify.js
Currenlty the `v` variable is only visible in the `if` block but it is
also used in the outer scope. Move the declaration to the outer scope.
=> Fix variable scope

History.md, packages/modules-runtime/client.js, packages/modules-runtime/package.js, tools/fs/optimistic.js, tools/isobuild/linker.js, tools/isobuild/package-source.js, tools/isobuild/resolver.js, tools/tests/apps/modules/package-lock.json, tools/tests/apps/modules/package.json, tools/tests/apps/modules/tests.js
Like Node.js, Meteor's module system currently pays attention only to the `"main"` field of `package.json` files (and also `"browser"` on the client) when resolving package entry points. This behavior effectively limits Meteor to using the CommonJS version of any npm packages, even though many packages have both a CommonJS and an ECMAScript module (ESM) entry point.
This PR enables support for the `"module"` field for client code. The implementation required a few small adjustments: in particular, we now compile `.js` files within `node_modules` if they are contained by a package that has a `"module"` entry point (only if the `ImportScanner` decides the module is actually used), and our module resolution logic now prefers the `"module"` entry point both during build (`resover.js`) and at …
=> Support the "module" field of package.json for client code.

tools/console/console.js
Fixes a typo that caused ProgressDisplayFull to sometimes render after it was replaced with a different progress display.
=> Fix checking for a rerender timeout

tools/isobuild/compiler-plugin.js, tools/isobuild/compiler.js, tools/isobuild/import-scanner.js, tools/isobuild/package-source.js, tools/isobuild/unibuild.js, tools/tests/apps/modules/packages/modules-test-package/.npm/package/npm-shrinkwrap.json, tools/tests/apps/modules/packages/modules-test-package/common.js, tools/tests/apps/modules/packages/modules-test-package/package.js, tools/tests/apps/modules/packages/modules-test-plugin/.npm/plugin/compile-arson/npm-shrinkwrap.json, tools/tests/apps/modules/packages/modules-test-plugin/package.js, tools/tests/apps/modules/packages/modules-test-plugin/plugin.js
When I implemented support for the `"module"` entry point in `package.json` files for client code in #10541, I modified `PackageSource#_findSources` to include files found in `node_modules` that need to be compiled, but my implementation considered only "local" `node_modules` directories, like the one in the application root directory, while neglecting the private `.npm/package/node_modules` directories that many Meteor packages have.
This PR includes `.npm/**/node_modules` when `_findSources` is scanning a Meteor package, which should solve issues like #10544, where a Meteor package imports an npm package that was installed with `Npm.depends`, and that npm package has a `"module"` field in its `package.json` file, pointing to an ESM entry point module, but the ESM syntax was not …
=> Allow .npm/package/node_modules to be compiled in Meteor packages.

tools/fs/optimistic.js, tools/isobuild/bundler.js, tools/isobuild/compiler-plugin.js, tools/isobuild/import-scanner.js, tools/isobuild/package-source.js, tools/isobuild/unibuild.js
These commits partially revert my recent PR #10545, in favor of an implementation that uses the `ImportScanner` to compile any JS modules that were not already compiled by compiler plugins, including modules found in `.npm/package/node_modules` directories.
After much thought, I believe this implementation (#10545) would have caused severe compatibility problems when using packages published with earlier versions of Meteor in a Meteor 1.8.2 app, or when publishing packages with Meteor 1.8.2 for use with earlier Meteor versions.
Specifically, this implementation relied on writing the additional `.npm/package/node_modules` resources found by `_findSources` into the unibuild JSON file(s), and there just wasn't any good way to make sure the new JSON format could be safely consumed by previous …
=> Support module syntax in ImportScanner, rather than using PackageSource#_findSources.

packages/accounts-google/google.js
A dot went missing in a query parameter (in this commit: bb17d4d). Stumbled upon this by accident and have not seen any similar issues or pull requests.
=> Add missing dot in query parameter in accounts-google package

History.md, packages/ecmascript-runtime-client/.npm/package/npm-shrinkwrap.json, packages/ecmascript-runtime-client/legacy.js, packages/ecmascript-runtime-client/modern.js, packages/ecmascript-runtime-client/package.js, packages/ecmascript-runtime-server/.npm/package/npm-shrinkwrap.json, packages/ecmascript-runtime-server/package.js, packages/ecmascript-runtime-server/runtime.js, packages/ecmascript-runtime/package.js, packages/ecmascript-runtime/runtime-tests.js
Also added a polyfill for `Symbol.asyncIterator` to server, modern, and legacy bundles, which should fix #9897.
=> Update ecmascript-runtime-{client,server} to use core-js@3.1.4.

History.md, meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/babel-compiler.js, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/modules/.npm/package/npm-shrinkwrap.json, packages/modules/package.js, scripts/dev-bundle-tool-package.js, tools/isobuild/compiler-plugin.js, tools/isobuild/import-scanner.js, tools/tests/apps/modules/package-lock.json, tools/tests/apps/modules/package.json, tools/tests/apps/modules/tests.js
In Meteor 1.8.2, supporting legacy browsers increasingly requires recompiling npm packages that use slightly-too-modern JavaScript syntax like `const` and `class` and arrow functions.
In #10545 and #10550 I added support for ECMAScript module syntax in `node_modules` (`import`, `export`, and dynamic `import()`), but now I realize that's not enough, since many more npm packages use simpler features like `class` syntax and arrow functions than use module syntax, without even realizing they are excluding older browsers.
Instead, this PR uses the standard Meteor compiler plugins system to compile "unanticipated modules," which is the same machinery Meteor applications normally use to compile application code, including the same on-disk and in-memory caching logic. Unanticipated modules are …
=> Support full ECMAScript compilation of modules unexpectedly imported from node_modules.

tools/cordova/builder.js, tools/isobuild/bundler.js
Straight forward, we allow for overriding `gitCommitHash` in lieu of `findGitCommitHash`
Needed when build systems don't have access to `git` or `.git/`, but commit may be known.
This could also be used as a way to set custom version numbers, although something like `Meteor.appVersion` may be desired.
Cheers,
- Rob
=> Allow for METEOR_GIT_COMMIT_HASH in lieu of findGitCommitHash's execFile

packages/mongo/oplog_tailing.js, packages/mongo/package.js
This is my first pull request to meteor, so I am sorry if I forgot something.
The changes targets issue: https://github.com/meteor/meteor/issues/10602
Instead of throwing an error if there is an oplog entire from another db on the same mongo instance it is now simply ignored.
I also pushed the minor version of the package.js file, I am not sure if there are required any further changes.
=> Ignore oplog entries from other dbs instead of throwing an error.

packages/typescript/README.md, packages/typescript/package.js, packages/typescript/plugin.js, packages/typescript/tests.ts, tools/static-assets/skel-bare/.meteor/packages, tools/static-assets/skel-full/.meteor/packages, tools/static-assets/skel-minimal/.meteor/packages, tools/static-assets/skel-react/.meteor/packages, tools/static-assets/skel/.meteor/packages, tools/tests/apps/modules/.meteor/packages, tools/tests/apps/modules/tests.js, tools/tests/apps/modules/typescript.ts, tools/tool-testing/sandbox.js
As requested in https://github.com/meteor/meteor-feature-requests/issues/285.
This plugin package enables the use of [TypeScript](https://www.typescriptlang.org) modules with `.ts` or `.tsx` file extensions in Meteor applications and packages, alongside `.js` modules (or whatever other types of modules you might be using).
The `typescript` package registers a compiler plugin that transpiles TypeScript to plain ECMAScript, which is then compiled by Babel for multiple targets (server, modern browsers, legacy browsers, cordova). By default, the `typescript` package is included in the `.meteor/packages` file of all new Meteor applications.
To add the `typescript` package to an existing app, run the following command from your app directory:
```sh
meteor add typescript
```
To add the …
=> Implement an official TypeScript compiler plugin.

tools/cordova/run-targets.js, tools/runners/run-app.js, tools/shell-client.js, tools/utils/eachline.ts, tools/utils/utils.js
[no issue]
Hi @benjamn! Michael Newman here, no relation.
Wanted to give Meteor TypeScript conversion a shot after attending [your excellent Meteor Night talk](https://slides.com/benjamn/reimplementing-meteor-in-typescript#), so here's my shot at one of the easy files to start with you mentioned in your presentation.
I had a few questions about getting started, since the codebase/tooling of this repo is pretty unfamiliar to me:
1. Is the correct way to check for TS errors in this project just to open the project in VSCode and see if it gets angry? (That's what I did and it seemed to work... okay.)
2. For whatever reason, TypeScript lets me get away with code like `const pipe = require("multipipe");`	but not `import pipe from "multipipe";`, because for the latter version it wants me to …
=> Convert eachline.js to eachline.ts

packages/base64/base64.js, packages/base64/package.js
Fixes #10628
For strings we convert to Uint8Array, which does not support forEach on any version of IE, and is not polyfilled by default.
If a polyfill solution is preferable, we can close this and fix it that way.
=> Avoid use of forEach in Base64 encode method

scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js, tools/isobuild/meteor-npm.js
`@types/semver` is important because multiple files that should be transformed to TypeScript require it (e.g. `utils/utils.js`).
Regarding the versioning mismatch. There shouldn't be any problems since the only difference between 5.4.0 and 5.4.1 is the addition of a `try...catch` statement in commit [semver/7be83d15dcff73f6](https://github.com/npm/node-semver/commit/7be83d15dcff73f6df11b82507e0b9980e183bc2), so the interface wasn't changed.
=> Add @types/semver@5.4.0 to both dev-bundle-tools-package.js and dev-bundle-server-package.js

.eslintignore, tools/runners/run-mongo.js, tools/utils/mongo-exit-codes.ts
[no issue]
Another very very small TypeScript conversion along the lines of #10614. This time I just side-stepped the issue of "how do I install types for a package like underscore?" by removing underscore from this module, because it really doesn't seem to be necessary as far as I can tell.
Also exported a new (currently unused) type, `MongoExitCode`, that I think may be helpful when typing `tools/runners/run-mongo`, which I was experimenting with in another branch.
=> Convert tools/utils/mongo-exit-codes.js to TypeScript

.eslintignore, tools/fs/watch.ts, tools/index.d.ts, tools/utils/func-utils.ts
This is part of the ongoing transformation to typescript.
The pull should be accepted only after adding a `@types/underscore` to the node_modules, as mentioned [in pull request 10624](https://github.com/meteor/meteor/pull/10624#discussion_r302651681). Currently I've installed the types locally.
Also, I've added some ad-hoc types e.g. `EmptyFunction` and `AnyFunction`. After the transformation will mature we can use a library for stuff like this or have a centralised way where these type shuld be defined.
The global `Function` interface was ammended to include the `displayName` property.
=> Convert `func-utils.js` to typescript

.eslintignore, tools/console/README.md, tools/console/progress.ts, tools/utils/buildmessage.js
Converts the "progress" class to TypeScript! This conversion is a little bigger because I refactored the class to use `class` syntax and private members.
=> Convert tools/console/progress.js to TypeScript

tools/isobuild/import-scanner.ts
Hello, I have explained the details of the problem here https://github.com/meteor/meteor/issues/10643#issue-470986741 and the root cause with the solution here https://github.com/meteor/meteor/issues/10643#issuecomment-528295725
This PR fixes the mentioned problem without causing any regression to Meteor scanning system.
I would like to also point out that even if my solution is somehow wrong, what I know it is not, the only bad side effect would be to scan a module that was already scanned in the same status, this means, do unnecessary work but I know for sure that I got a missing case and for who understands Meteor scanning system is relatively easy to see that we really had a gap there.
We are already using this fix in my company and we have more than 120 Cypress tests and all are …
=> Fixes `cannot find module` error when using dynamic imports in massive projects

packages/accounts-base/accounts_client.js, packages/accounts-base/accounts_common.js, packages/accounts-base/package.js, packages/callback-hook/hook.js, packages/callback-hook/package.js
This repairs a timing issue. #10157 
Essentially, the user is logged in before any `onLogin` callbacks can be set up.  To remedy the problem:
I added a new internal function.
- `_startupCallback` is [called](https://github.com/brucejo75/meteor/blob/accounts_call_onLogin_callbacks_startup/packages/accounts-base/accounts_common.js#L198-L203) is called right after an `onLogin` callback is registered.
- On the client [`_startupCallback`](https://github.com/brucejo75/meteor/blob/accounts_call_onLogin_callbacks_startup/packages/accounts-base/accounts_client.js#L440-L455) checks if the user is logged in (non reactively), if true then the newly registered `callback` is scheduled to execute at the back of the event loop.  This makes sure that all necessary`Meteor.startup` callbacks complete before …
=> [fix #10157] Make sure onLogin callbacks are called during startup

tools/isobuild/bundler.js, tools/isobuild/compiler-plugin.js, tools/tests/apps/client-refresh/imports/node_modules/some-package/index.js, tools/tests/client-refresh.js
Fixes #10736 by never modifying existing `unibuild.watchSet` information, with additional tests to enforce this subtle behavior.
=> Simplify delayed watching of lazy modules.

tools/fs/files.ts, tools/isobuild/import-scanner.ts, tools/tool-testing/run.js, tools/tool-testing/sandbox.js
Windows tests have been timing out because the preparatory `meteor --get-ready` command stalls forever (using 0% CPU), so I'd like to gain some insight into how far it gets before it stalls.
=> Fix mysterious Windows AppVeyor test stalls.

packages/check/match_test.js
Since variables defined with **const** are not supposed to be reassigned, 'success = false' could cause errors. Changed declaration to **let** to avoid that.
=> change success variable declaration

packages/test-in-browser/.npm/package/.gitignore, packages/test-in-browser/.npm/package/README, packages/test-in-browser/.npm/package/npm-shrinkwrap.json, packages/test-in-browser/driver.css, packages/test-in-browser/driver.html, packages/test-in-browser/driver.js, packages/test-in-browser/package.js
Another step towards #10498
The direct jquery dependency was not necessary as far as I can tell. There was a second indirect dependency through the deprecated bootstrap package from which we only need the css.
So I replaced that one with bootstrap 4 css from npm
=> remove jquery and deprecated bootstrap dependency in test-in-browser

meteor, meteor.bat, scripts/dev-bundle-tool-package.js, tools/fs/files.ts, tools/index.d.ts, tools/isobuild/import-scanner.ts, tools/isobuild/linker.js, tools/tests/old.js
source-map 0.7.0+ has a much faster Rust WASM implementation.
Because this needs to be loaded, the constructor is now asynchronous.
The consumer should also be destroyed after it's no longer needed.
https://github.com/meteor/meteor/commit/1cf59867b2f74f5be1a3e6f1eb13ea4ae10540db paved the way for this.
Should hopefully help with: https://github.com/meteor/meteor/issues/9568 , but didn't ran any benchmarks yet.
=> Update source-map to 0.7.3

packages/accounts-password/package.js
Should be republished, since the published 1.5.1 is outdated and still contains underscore. https://github.com/meteor/meteor/issues/10788
=> Bump accounts-password version

tools/isobuild/resolver.ts
Between 1.3 and 1.3.1 the modules.js file got moved from modules to modules-runtime (and later on split for different archs)
=> Fix comment in resolver

ISSUE_TRIAGE.md, Roadmap.md
Roadmap update.
We are proposing a new format for the roadmap where community members are involved since the beginning.
This is a call for community leaders to step up and help in the future of Meteor.
=> Roadmap update

Roadmap.md
I noticed that the updated [roadmap](https://github.com/meteor/meteor/blob/devel/Roadmap.md) has a section titled **Ultra-thin Meteor**, but does not provide any information about the `meteor create --minimal` command introduced in Meteor 1.7.
I've expanded that section to describe the command and the opportunities for improvement that I think are worth exploring from that starting point.
Note to @filipenevola: since this PR is updating a single file with a single commit, let's be sure to squash-and-merge it to avoid adding a merge commit to `devel`.
=> Explain previous work on minimal Meteor applications.

packages/ddp-server/livedata_server.js
When an exception is thrown in a publication, it is very useful to see the entire stack trace rather than just the name of the error (#10782). #9678 refactored the debug messages and unfortunately made the server-side error messages less detailes. This PR tries to address the issue  by reverting some of the changes made by #9678,  specifically https://github.com/meteor/meteor/pull/9678/files#diff-7e48a19069e07781db2a50282a8bfdd7R1737
There is perhaps an opportinuty to print more details in other places, e.g. when exceptions are thrown in method calls, etc. #9678 added a todo that stack traces should be formatted nicely but that seems to have not been addressed. IMO it's better to print badly formatted stack traces than nothing at all. I'd be happy to do that if people are happy
=> Log error stack on exception in publication

packages/npm-bcrypt/wrapper.js
Adding native `bcrypt` to a project may require build tools be available on the system. This commit adds a note about that, and a link to the node-gyp documentation that best explains which tools to install. For more details, see this issue: https://github.com/meteor/meteor/issues/10113
=> Mention build tools in native bcrypt message

tools/tests/apps/client-refresh/.meteor/.finished-upgraders, tools/tests/apps/compiler-plugin-static-html-error/.meteor/.finished-upgraders, tools/tests/apps/compiler-plugin-static-html/.meteor/.finished-upgraders, tools/tests/apps/dynamic-import/.meteor/.finished-upgraders, tools/tests/apps/git-commit-hash/.meteor/.finished-upgraders, tools/tests/apps/linked-external-npm-package/.meteor/.finished-upgraders, tools/tests/apps/modules/.meteor/.finished-upgraders, tools/tests/apps/standard-app/.meteor/.finished-upgraders, tools/upgraders.js
While jquery is now a theoretical weak dependency of blaze, in reality everyone uses the jquery dombackend of blaze. So try to limit the complaints about apps being broken. (they will still need to have it as an NPM dependency, but at least the `jquery` package gives a clear error message if this isn't the case)
=> Add upgrader to add jquery dependency for blaze-users

History.md, tools/runners/run-app.js, tools/tests/run.js
Removes the logic that restarts a crashing Meteor server twice if there is a runtime error.
Fixes meteor/meteor-feature-requests#335.
=> Remove multiple restart feature

.circleci/config.yml, Roadmap.md, packages/launch-screen/package.js, packages/mobile-experience/package.js, packages/mobile-status-bar/package.js, packages/webapp/package.js, tools/cordova/index.js, tools/cordova/project.js
We want to update:
Related PRs (cordova-9 branch):
https://github.com/meteor/cordova-plugin-meteor-webapp/pull/88
Related issues #10809 #10626
Follow the list of known tasks:
Notes:
- To run on iOS the first time with `meteor run ios` I had to run this first `sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService` https://github.com/apache/cordova-ios/issues/652#issuecomment-514284852
Make sure the following is working after the update:
Known issues to fix:
=> Update Cordova to 9.0.1

Roadmap.md
I (and presumably others) often have code shared between client and server, with some blocked off by `if(Meteor.isServer)` and (more rarely) `if(!Meteor.isServer)`. It would be great if this constant is also handled in the tree shaking, and I imagine it's about as easy as `Meteor.isProduction` (but slightly different so worth mentioning).
=> Include Meteor.isSever constant in roadmap

packages/modern-browsers/modern.js
Capacitor (and possibly others) are identified as chromeMobileWebView. This is identical (also in numbering) to e.g. chromeMobile and can therefore be used as alias.
Fixes https://github.com/meteor/meteor/issues/10794
=> Add chromeMobileWebView alias

packages/mongo/oplog_observe_driver.js
_published is a max heap, not a min heap
=> Fix comment about the published data structure

.circleci/config.yml, History.md, packages/launch-screen/package.js, packages/mobile-experience/package.js, packages/mobile-status-bar/package.js, packages/webapp/package.js, tools/cordova/index.js, tools/cordova/project.js
Since #10810 was merged into `release-1.8.4`, which contains [a lot of extraneous changes](https://github.com/meteor/meteor/pull/10837), I wanted to try recreating just the Cordova-related parts, so that we can merge them cleanly into `devel`.
=> Rebase PR #10810 (Cordova 9) against current devel branch.

History.md, packages/appcache/appcache-server.js, packages/appcache/package.js, packages/webapp/package.js, packages/webapp/webapp_server.js, tools/cli/commands.js, tools/cli/help.txt
This commit implements an `--exclude-archs` arg to the run command which allows you to pass a comma-seperated list of architectures to exclude.
Motivation:
Improve rebuild speeds, by allowing to leave out certain web architectures during development.
Meteor rebuild speeds, although greatly improved in recent versions, is still a common point of frustration as seen in the issues (https://github.com/meteor/meteor/issues/10800) and on the forum (https://forums.meteor.com/t/2x-to-3x-longer-build-time-also-on-testing-since-1-8-2-update/51028/3)
One reason for slow rebuilds is high memory pressure (https://github.com/meteor/meteor/issues/9568).
The web.browser.legacy architecture is currently always being build while most of us will only test this every once in a while.
So while we don't need …
=> Allow to exclude web architectures in development mode

History.md, meteor, packages/mongo/mongo_driver.js, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js, scripts/build-dev-bundle-common.sh, scripts/generate-dev-bundle.ps1, scripts/generate-dev-bundle.sh, tools/runners/run-mongo.js
=> Update MongoDB to 4.2

History.md, meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/typescript/package.js, scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js, tools/static-assets/skel-bare/package.json, tools/static-assets/skel-full/package.json, tools/static-assets/skel-minimal/package.json, tools/static-assets/skel-react/package.json, tools/static-assets/skel-typescript/package.json, tools/static-assets/skel/package.json
Babel releases included in this update:
- https://github.com/babel/babel/releases/tag/v7.7.6
- https://github.com/babel/babel/releases/tag/v7.7.7
- https://github.com/babel/babel/releases/tag/v7.8.0
- https://github.com/babel/babel/releases/tag/v7.8.1
- https://github.com/babel/babel/releases/tag/v7.8.2
- https://github.com/babel/babel/releases/tag/v7.8.3
Although some of these changes won't take effect until the next Meteor release, I intend to publish the `babel-compiler`, `ecmascript`, and `typescript` changes using Meteor 1.9, so that applications can update without waiting for [Meteor 1.10](https://github.com/meteor/meteor/pull/10861).
=> Update meteor-babel and typescript to latest versions.

meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, scripts/dev-bundle-tool-package.js, tools/tool-env/install-babel.js
Modules that are evaluated before `meteor-babel/register` is configured should not be transformed by `meteor-babel`, even if they are imported again later, after `meteor-babel/register` has been configured.
If my analysis is correct, this change should prevent the dreaded
```
Error: [BABEL] /tools/index.js: Must export a default export when using ES6 modules. (While processing: "base$0$0")
```
error, as seen most recently in https://travis-ci.org/meteor/meteor/builds/638030190 and https://circleci.com/gh/meteor/meteor/40863.
=> Fix spurious Babel ES6 default export error, once and for all.

tools/isobuild/import-scanner.ts
[This line](https://github.com/meteor/meteor/pull/10798/files#diff-33c7061de8ece159a7cb510c847d2babR702) (added in #10798) causes a `TypeError: Cannot read property 'destroy' of null` if the file doesn't have a source map.
=> Make sure source map consumer exists before destroying it.

packages/shell-server/shell-server.js
If a shell connects to the Meteor server, `(STDERR) (node:12002) [DEP0124] DeprecationWarning: REPLServer.rli is deprecated` is logged to the console because the `REPLServer.rli` property is [deprecated since Node.js 12](https://github.com/nodejs/node/pull/26260).
=> Don't use deprecated `REPLServer.rli` property.

packages/ddp-server/stream_server.js
Defensive code to handle a scenario in which the sockjs `on('connection')` handler is passed `null` instead of a socket object.
This issue has popped up a couple of times in the past few years but doesn't look like it will be resolved in sockjs-node:
https://github.com/sockjs/sockjs-node/issues/121
And appears to be happening in recent versions of Meteor (1.8 and 1.9):
https://github.com/meteor/meteor/issues/10468
I couldn't really determine a way to write a test for this, apologies in advance.
=> Fixes bug #10468: ddp-server guards against null argument in sockjs connection handler

packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js
Versions 3.5.x of the MongoDB driver include some [bug fixes and features](https://github.com/mongodb/node-mongodb-native/blob/ffe92a9457d9eba94cd44e778a06ce4a49aab5f2/HISTORY.md#352-2020-01-20) that could be relevant for production deployments.
=> Update MongoDB driver to 3.5.2.

packages/mongo/mongo_driver.js
The `autoReconnect` and `reconnectTries` options are incompatible with the unified topology (http://bit.ly/2D8WfT6), which should reconnect automatically and without additional configuration.
=> Remove deprecated MongoDB connection options.

packages/non-core/bundle-visualizer/package.js, packages/non-core/bundle-visualizer/style.css
The updated babel-based minifiers must be more tight on some syntax. This trailing coma has been there for a while but it's now causing issue when minimizing to view the bundle size. Tests on a local app show a resolution just by deleting the coma.
=> fixes bug #10880 "[1.9] bundle-visualizer crashes app"

packages/socket-stream-client/browser.js, packages/socket-stream-client/package.js
Currently it's very difficult to remove `dynamic-import` from a Meteor app (#10704) because of strict dependencies from `ecmascript` and `socket-stream-client` (aka `ddp`).
This also means it's very difficult to disable `unsafe-eval` in CSP as `dynamic-import` sets `BrowserPolicy.allowEval()`.
Looking at `socket-stream-client`, the only dynamic import is rendered redundant by #9985 and so this PR cleans up the `import` call and dependency.
Maybe the optimization that #9985 reverts will come back, in which case it would be nice if SockJs could be conditionally bundled or `import()`ed based on whether the `dynamic-import` package is installed
=> Remove redundant dynamic-import from socket-stream-client

packages/github-oauth/github_server.js, packages/github-oauth/package.js
Update OAuth API calls for authentication due to deprecation:
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/
https://developer.github.com/v3/auth/#basic-authentication
=> Switch `google-oauth` to pass token in headers.

packages/boilerplate-generator/template-web.browser.js, packages/webapp/webapp_server.js
Although Meteor doesn't send cache headers to the runtime config file, a reverse proxy might still cache it.
Some reverse proxies will treat this case similar to cache-control: private.
So adding the hash can prevent reverse proxies from serving stale versions.
Furthermore, by adding the hash, it can actually be cached correctly by reverse proxies.
For more context: #10733
=> Add hash to runtime config file url

packages/appcache/appcache-server.js
Sometimes `browsers` is not enough when deciding to enable/disable the appcache feature.
This PR adds `enableCallback` as a more versatile option to control the appcache feature on a per-request basis.
```js
// Enable offline mode using a value from database
Meteor.AppCache.config({
enableCallback: () => {
return getSettingsFromDb("public.appcache_enabled");
},
});
```
```js
// Enable offline mode only when client sends a valid certificate
Meteor.AppCache.config({
enableCallback: req => {
const validation = validateClientCert({
clientCertPayload: req.headers["x-client-cert"],
url: req.url.href,
});
return validation.passed;
},
});
```
=> Add enableCallback option for appcache

packages/modules-runtime/server.js, tools/fs/optimistic.ts, tools/isobuild/import-scanner.ts, tools/isobuild/package-source.js
On the server, Meteor attempts to avoid bundling `node_modules` code by replacing entry point modules with a stub that calls [`module.useNode()`](https://github.com/meteor/meteor/blob/fca6c62d432eff1afd4a67280b7c90af23399511/packages/modules-runtime/server.js#L48). This trick allows evaluating server `node_modules` natively in Node.js, faithfully preserving all Node-specific behaviors, such as `module.id` being an absolute file system path, the `__dirname` and `__filename` variables, the ability to import binary `.node` modules, and so on. This bailout has been in place since Meteor 1.3 (when the module system was first introduced), and it has worked remarkably well.
However, starting in Node.js 12.16.0 (Meteor 1.9.1+), modules evaluated natively by Node are considered ECMAScript modules …
=> Avoid bailing out with module.useNode() for ESM modules.

History.md, meteor, scripts/admin/copy-dev-bundle-from-jenkins.sh, scripts/generate-dev-bundle.ps1, tools/cli/dev-bundle.js, tools/utils/archinfo.ts
Because MongoDB since 3.4 no longer supports 32-bit Windows, Meteor 1.10 has also dropped support for 32-bit Windows. In other words, Meteor 1.10 supports 64-bit Mac, Windows 64-bit, and Linux 64-bit.
=> Drops support for Win 32-bit

README.md
Adding a Slack invite link to the Meteor Slack community where new comers can interact with the rest of the community.
=> Add Slack invite link

.travis.yml
I think we should retry run test for Travis CI when failing by timeout or network, max times to retry is 3 times. Read more about `travis_retry` at [here](https://docs.travis-ci.com/user/common-build-problems/#travis_retry)
=> Should be retry run test for Travis CI when falling

packages/webapp/package.js, packages/webapp/webapp_server.js
Fixes https://github.com/meteor/meteor/issues/10756
=> Don't lose the query string when using a path prefix

packages/oauth/.npm/package/.gitignore, packages/oauth/.npm/package/README, packages/oauth/.npm/package/npm-shrinkwrap.json, packages/oauth/oauth_server.js, packages/oauth/package.js, packages/oauth1/oauth1_tests.js, packages/oauth1/package.js, packages/oauth2/oauth2_tests.js, packages/oauth2/package.js
This builds on work done by rooch84 in pull request #10501 and issue #10491 
That PR seems to have lost momentum and I am ready help with it as it's needed for sign in with apple oauth.
I have fixed the tests and made some small changes to take care of some bugs.
Tests are passing but i have some console warnings that I need help rectifying:
```
W20191029-15:10:41.469(1)? (STDERR) (node:79991) UnhandledPromiseRejectionWarning: TypeError: req.on is not a function
W20191029-15:10:41.537(1)? (STDERR)     at Promise (packages/oauth/oauth_server.js:146:8)
W20191029-15:10:41.538(1)? (STDERR)     at new Promise (<anonymous>)
W20191029-15:10:41.538(1)? (STDERR)     at parseRequestData (packages/oauth/oauth_server.js:142:33)
W20191029-15:10:41.538(1)? (STDERR)     at Promise.asyncApply …
```
=> Allows the oauth server package to parse post body data

History.md
Add migrations steps in case of `Unexpected mongo exit code 62.`
Based on discussion with @klaussner in #10861
=> Migrations steps for 1.10 MongoDB `Unexpected exit code 62`

History.md, packages/meteor-tool/package.js, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json
We have a few users having complicated issues with MongoDB Driver version 3.2.7 so we are doing this release just to upgrade MongoDB Driver to 3.5.4.
=> Release 1.9.3

tools/cli/dev-bundle-helpers.js, tools/isobuild/meteor-npm.js
This fixes the bug where commands like `meteor add-platform ios` would fail the first time with an error that `cordova-lib` could not be found, even though we successfully install the necessary packages if they have not already been installed.
To make a very long story short, calling `moduleDoesResolve` before installing dependencies like `cordova-lib` was causing Node.js to cache the _absence_ of `cordova-lib/package.json` permanently in the new [`packageJsonCache`](https://github.com/nodejs/node/blob/f8f20892e944a6c4b52e298528135161d85fcc7a/lib/internal/modules/cjs/loader.js#L245-L255), which cannot be invalidated or cleared by user code.
Although we could potentially propose a change to Node to allow the `packageJsonCache` to be invalidated, a more immediate solution is simply to avoid …
=> Stop calling moduleDoesResolve before installing Cordova npm deps.

packages/deprecated/markdown/package.js, packages/deprecated/markdown/showdown.js
I branched off of the latest devel branch commit
This issue was reported in #10904 and I was able to reproduce it. 
Testing this change allowed the page to load and the test snippet of markdown used in the issue to be shown in the screen
=> Markdown Bug Fix [Issue #10904]

History.md, meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/ecmascript/transpilation-tests.js, packages/typescript/package.js, scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js, tools/tsconfig.json
General Babel release info: https://babeljs.io/blog/2020/03/16/7.9.0
Relevant `babel-preset-meteor` commits: https://github.com/meteor/babel-preset-meteor/commit/d8576fad9625cb381e13ead89737749b6fbca6e9, https://github.com/meteor/babel-preset-meteor/commit/ddedc242e91b170a7078dee80007597e49c524bf
Relevant `meteor-babel` commits: https://github.com/meteor/babel/commit/25eab29826c88ed5e9dcc8a91b989917a0ec8907, https://github.com/meteor/babel/commit/45eb69ce876b9e21c150696e5a964ba3a20757fb
One potentially breaking change is that the `babel-preset-meteor` preset no longer includes support for stripping Flow type annotations by default, though you can still add
```
{
"plugins": [
"@babel/plugin-syntax-flow",
"@babel/plugin-transform-flow-strip-types"
]
}
```
to a custom `.babelrc` file, if you …
=> Update meteor-babel to version 7.9.0 and typescript to 3.8.3.

packages/mongo/mongo_driver.js
Adds support for the arrayFilters option for Collection.update (see https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/), as described in #10103 .
This option only works server-side, for client-side there is a PR: #9721
Fixes #10103
I'm not entirely sure how to write an automated test for it, but I have verified the fix by creating a toy project, and running the example given by @gustawdaniel in the original issue.
Note: This is my first contribution to Meteor or an open-source project in general. I'm still learning so I would love some feedback. If you need me to also update the tests or documentation, don't hesitate to let me know!
=> [FIX] The filtered positional operator $[<identifier>] (arrayFilters) does not work in Mongo update

History.md, packages/caching-compiler/caching-compiler.js, packages/caching-compiler/multi-file-caching-compiler.js
Starting in Meteor 1.8.2, Plugin.fs methods no longer accept a callback and are always the sync version. The caching compiler passed a callback that was never called and caused the cache files to never be renamed to their correct name.
=> Fix caching compiler file cache

packages/non-core/less/.npm/plugin/compileLessBatch/npm-shrinkwrap.json, packages/non-core/less/README.md, packages/non-core/less/package.js, packages/non-core/less/plugin/compile-less.js
This pull request updates less to the current version 3.11.1 from 2.5.0. Closing #10992.
I added the `javascriptEnabled` flag to less to maintain backwards compatbility, as this was the default behavior before 3.0.0 of less.
In addition I configured the file loader in a way that it loads files as less if they have no ending provided, accoriding to the documentation of less: http://lesscss.org/features/#import-atrules-feature-file-extensions
The main changes in the code were:
- Rewrite the `loadFile` function as this requires to return a promise.
- In addition I refactored the code to use template string syntax.
=> Updated less package

scripts/windows/download-dev-bundle.ps1
Fix for #10979 
I already described the issue, but just a quick summary: when running `meteor` from checkout from a directory which has a space in it, 7zip cannot find the dev_bundle tar to extract. This fixes this issue by surrounding the filepath with quotes.
Not sure I can provide any kind of automated test for this though, but for what it's worth, it works!
Note: I wasn't sure if I had to create an issue before opening a PR. Please let me know if this is the way to go in the future, or just a PR is good too!
=> Fix Windows dev_bundle extraction for running from checkout with spaces in path

packages/appcache/appcache-server.js, packages/appcache/package.js, packages/dynamic-import/package.js, packages/dynamic-import/server.js, packages/webapp/package.js, packages/webapp/webapp_server.js
Follow-up to #10824.
If the preferred arch is not available (most likely because it was deliberately excluded), it's better to use another client arch that is available than to guarantee the site won't work by returning an unknown arch.
For example, if `web.browser.legacy` is excluded using the `--exclude-archs` option (introduced by #10824), legacy clients are better served by receiving `web.browser` (which might actually work) than receiving an HTTP 404 response.
If none of the arches in `preferredArchOrder` are defined, only then should we send a 404.
I encountered this issue when `meteor npx wait-on http://localhost:3000` stopped working after I specified `--exclude-archs web.browser.legacy`, because the `wait-on` tool does not provide a `user-agent` header, so it gets classified as a …
=> Try other web.* arches if preferred arch was excluded.

tools/runners/run-proxy.js, tools/tests/run.js
Currently if the headers exceed Node's set limit, the client will see a blank page with the text "Unexpected error." and nothing will be logged on the server. This PR adds a server-side log informing the developer of the cause and suggests using a node CLI option to increase the maximum allowable header size.
One scenario which leads to this error is if a project with many CSP rules upgrades from an older version of Meteor, prior to Node's reduction of the maximum allowable size from 80 KB to 8 KB (discussed here https://github.com/nodejs/node/issues/24692).
This issue as it affects Meteor has been discussed here https://forums.meteor.com/t/meteor-1-8-1-unexpected-error-too-many-csp-rules/48447.
=> Add an error message warning developers of oversized headers.

.travis.yml, History.md, packages/meteor-tool/package.js, packages/mongo/mongo_driver.js, packages/mongo/package.js, scripts/admin/meteor-release-experimental.json, tools/static-assets/server/boot.js
In some MongoDB host providers like ScaleGrid and IBM Cloud some developers are getting this error because of certificate:
```
MongoNetworkError: failed to connect to server [sg-meteorappdb-32194.servers.mongodirector.com:27017] on first connect [Error: self signed certificate
```
We can fix the error passing additional options to the Mongo connection but right now Meteor only offers this ability via code in a package and also it's not easy to reference the certificate file inside the project.
This PR provides:
a) ability to set Mongo options using Meteor.settings.overrideMongoOptions;
b) simple way to reference files inside the `private` folder in the root.
Read the docs PR to see how this can be used https://github.com/meteor/docs/pull/662
More info:
- Issues about the limitation of …
=> Adds support to override mongo options via Meteor settings

packages/url/.npm/package/.gitignore, packages/url/.npm/package/README, packages/url/.npm/package/npm-shrinkwrap.json, packages/url/bc/url_client.js, packages/url/bc/url_common.js, packages/url/bc/url_server.js, packages/url/bc/url_tests.js, packages/url/legacy.js, packages/url/modern.js, packages/url/package.js, packages/url/server.js, packages/url/tests/main.js
Similar to the recent fetch package, this would add an isomorphic way to use the WHATWG URL api in legacy browsers (I needed this mainly for IE11).
Unfortunately there was already a url package exporting `URL`. So for BC reasons I have to add those old methods to the global URL function.
=> Add isomorphic URL api with BC

packages/minimongo/matcher.js, packages/minimongo/package.js
Minimongo now has no support for Decimal.js so there is issue when using is.
If we try to use meteor/mongo-decimal package it works normal on server side, but not on client, especially sorting cause it not implementing there.
=> add Decimal support to minimongo

tools/shell-client.ts
This is a proposed fix for issue #10803.
It has been observed that when the "shell-client.js" module got converted to TypeScript, producing the new "shell-client.ts" module, the callback passed to the "eachline()" function was modified to return the received data line. This, however, caused a side effect, which eventually made the meteor shell to hang.
This fix reverts that modification and eliminates that side effect.
=> Proposed fix for issue #10803

tools/meteor-services/deploy.js
Today when I transfer an app to our Galaxy organization, the message reads:
```
cool-app.meteorapp.com: transferred organization-name
```
I've corrected the grammar to:
```
cool-app.meteorapp.com: transferred to organization-name
```
With similar changes for `added` and `removed`.
=> Add prepositions to changeAuthorized verbs

tools/cordova/project.js
When we have plugins that use variables and Meteor integration tries to remove them it was not passing the variables and then the remove was failing.
In this PR I've changed the plugins remove command to remove the plugins one by one extracting the `cli_variables` for the plugin being removed currently.
For example, `cordova-plugin-facebook4` needs `APP_ID` and the removal was always failing because Meteor integration was not providing this variable.
=> Fixes error when removing cordova plugin that depends on cli variables

History.md
Only just noticed https://github.com/meteor/meteor/pull/10518 got merged. Think it's good to explain in the changelog.
=> Document changes to the URL package

packages/accounts-base/accounts_server.js, packages/accounts-base/accounts_tests.js, packages/accounts-base/package.js, packages/accounts-password/password_client.js
Add hook that allows to run check before user is created/logged via external service.
Draft PR so that we can discuss this and I still need to do testing on this.
Why this hook:
This hook fires after you get information from third-party on login and Meteor finds if there is a corresponding user. You will then get the service name, the data from the service and the corresponding user (if any) in the hook so that you can make determination if you want to allow the user to progress with login/user creation.
For example I plan to use this in an integration where I want to check that the user is logging in with the proper Google account.
Another example with Google includes that I want only people from certain domain(s) to be able to login, so I will use this hook to check that.
Yet another …
=> Add beforeExternalLoginHook

tools/cordova/project.js
After a change on `cordova-plugins` file `meteor run ios-device` was failing as explained here #11021
I was not able to reproduce without changing the `cordova-plugins` file but I hope this fix fixes all the cases.
Now I'm using remove force instead of just remove to uninstall Cordova plugins.
If the force mode causes other problems we could only force in the second try but as some users are experiencing this very often I prefer first to always use force mode.
=> Fixes Cordova build fails on the second time uninstalling plugins

History.md, packages/accounts-password/email_tests_setup.js, packages/email/.npm/package/npm-shrinkwrap.json, packages/email/email.js, packages/email/package.js
Updated dependencies of the `email` package and bumped the version to 1.3. The tests ran fine (though more testing is always encouraged). From the [changelog](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md) the biggest change is dropping support for Node bellow v6 (we had here a special version that supported Node v4) and various fixes and improvements.
TODO:
=> Update email dependencies

packages/url/bc/url_common.js
Fixes: TypeError: this._encodeParams is not a function #11092
I can't explain why behaviour changed, but this resolves the issue, I was able to reproduce it following @WayneUong comment (https://github.com/meteor/meteor/issues/11092#issuecomment-645814564) using a minimal app of:
```
meteor-base
http
ecmascript
standard-minifier-css
standard-minifier-js
```
=> Fixes: TypeError: this._encodeParams is not a function #11092

tools/fs/files.ts, tools/fs/safe-watcher.ts, tools/fs/watch.ts, tools/isobuild/compiler-plugin.js, tools/isobuild/import-scanner.ts
Since Meteor 1.8.2, it stats and watches most files and folders in the app and node_modules folders. It only does this to check which are folders. This PR changes it to use readdir's `withFileTypes` option, which removes the need to watch many of the files. This has very low overhead compared to `readdir` without the option.
Also, Meteor was using optimistic functions to read from the linker and reify file caches, which resulted in the files being watched, and the entries stored in two memory caches. This PR changes it to use a single memory cache, and not watch the files.
To work around a bug in Pathwatcher on Linux, Meteor would stat each file before watching it to deduplicate watchers by the file inode. Since Node can provide the same `ino` value for different files on Windows, and …
=> Reduce watchers and stats

tools/isobuild/package-source.js
For a medium sized app on Windows, these are some times from sorting files in 3 architectures during full rebuilds:
Before: 153ms, 140, 358, 391, 219, 177
After removing duplicate `files.pathBasename`: 84ms, 58, 73, 49, 114, 88
In the future, an additional optimization we could consider is using `path.posix.basename` instead of `files.pathBasename`. `files.pathBasename` converts paths to the os style path, then uses the `basename` function for the os. This conversion is probably unnecessary since all paths should be in posix format and are relative.
With posix basename: 57ms, 38, 25, 30, 40, 70, 43
=> Fix calling pathBasename twice during loadOrderSort

tools/isobuild/bundler.js, tools/runners/run-app.js
One optimization Meteor uses during builds is build in place. When enabled, Meteor re-uses files from the previous build and only updates the files that changed. On Windows, this was disabled since there could be issues if the meteor tool updates a file the server is accessing. I enabled it for building the server in #10399 since the server is always stopped before a full rebuild is started. Since there hasn't been any issues, this PR enables it for the client architectures during full rebuilds.
Before, writing the client target would take between 600 and 950ms during rebuilds of a medium sized app on Windows.
After, it is between 70 and 215ms.
Building in place is still disabled for client only builds. Meteor 1.8 added the ability for the webapp to be paused during delayed builds. It …
=> Build in place on Windows during full rebuilds

tools/fs/optimistic.ts, tools/isobuild/builder.js, tools/isobuild/bundler.js, tools/isobuild/package-source.js
With a smaller app on Windows, these changes reduces time spent by realpath from ~200 - 300 ms to 40ms on rebuilds, and saves ~750ms on the initial build. `realpath` works by using many lstat calls, which are slower on Windows than mac/linux.
When creating the list of files for each architecture, Meteor uses a symlink loop checker which would call `realpath` for each folder. It will now call `lstat` once for each folder and then call `realpath` for folders that are symlinks.
Meteor would also call realpath for each file in `node_modules/.bin` to check if it is a symlink. Since npm copies files into .bin instead of using symlinks on Windows, Meteor will now use lstat first, and then call `realpath` if it is a symlink. This does slightly increase the work done on linux/osx, but the …
=> Realpath performance

packages/ecmascript-runtime-client/package.js, packages/ecmascript-runtime-server/package.js
Updates the `core-js` library to the latest version `3.6.5` in `ecmascript-runtime-client` and `ecmascript-runtime-server`.
> #### Motivation
>
> During our tests with legacy browsers we noticed some issues with Svelte & older browsers, mainly IE11 and iOS {10,11}. I found some related closed issues in `core-js`.
>
>These problems were resolved by updating the `core-js` version .
=> Update core-js to version 3.6.5

packages/minifier-css/minifier-tests.js, packages/minifier-css/minifier.js
`minifier-css`'s check for imports to hoist unexpectedly stops on any comments and subsequent imports are not moved to the top of the merged css.
The `rulesPredicate(['import', 'comment'])` check for nodes to hoist is comparing to `node.name`, which is not present for PostCSS's Comment nodes. It should probably be looking for `type: 'comment'` instead.
Proposing a minimal fix to check `name` when present, i.e. for [AtRules](https://api.postcss.org/at-rule.es6.html#line39), and [`type`](https://api.postcss.org/node.es6.html#line423) otherwise for comments. Includes a basic test for import hoisting as there didn't appear to be one, as well as one for the broken case.
Possibly fixes #11096, as it resolved our issue that presented similarly, but need further info/confirmation that they are …
=> Fix moving css imports after comments to top of merged css

packages/deprecated/markdown/showdown.js
This corrects 'undefind' to 'undefined' in line 121 of packages/deprecated/markdown/showdown.js
=> Correct 'undefind' typo in deprecated markdown package

tools/static-assets/skel-apollo/imports/ui/App.jsx
Addressing and fixing issue #11145
Configured the client to use the InMemoryCache
=> Fixed: Apollo Skeleton - Apollo Client needs a cache to be setup

packages/boilerplate-generator/template-web.cordova.js
This fixes https://github.com/meteor/meteor/issues/8965, also discussed in the [forums](https://forums.meteor.com/t/correct-way-of-setting-content-security-policy-for-a-meteor-cordova-app/43985).
The issue was closed with a [workaround](https://github.com/meteor/meteor/issues/8965#issuecomment-370465644) which [turned out not to work](https://forums.meteor.com/t/correct-way-of-setting-content-security-policy-for-a-meteor-cordova-app/43985/7), forcing some people to maintain local versions of the `boilerplate-generator` package.
As the fix is simple and has no apparent drawbacks, I'd like to suggest we include it in Meteor by default.
=> Allow android-webview-video-poster (fixes #8965)

packages/standard-minifier-css/package.js
I did update minifier-css package to remove a warning about 'caniuse-lite'.
But standard-minifier-css uses minifier-css, so we should update the version of standard-minifier-css.
I tested it locally by cloning standard-minifier-css to project's packages folder and increase its version to 1.6.1. The warning disappeared.
=> Bump standard-minifier-css version to use the latest version of minifier-css package

History.md, meteor, scripts/build-dev-bundle-common.sh, scripts/dev-bundle-tool-package.js
* Node.js has been updated to version [12.18.4](https://nodejs.org/en/blog/release/v12.18.4/), this is a [security release](https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/)
* Updated npm to version 6.14.8
=> Update Node.js to 12.18.4 & npm to 6.14.8

packages/dynamic-import/client.js
Add the option for `dynamic-imports` to fetch from the current origin instead of the absolute URL.
=> Dynamic Imports: Dynamic Origin Option (CORS)

scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js, tools/console/console.js, tools/tests/apps/modules/package.json
Internal dependencies have not been updated for a while and in some cases there are promised performance improvements by some of the packages and some are required to work in Node 14 (or at least work better).
This is just a first shot of what I could do without much testing. If desired we can continue from here or I can split this thematically. @filipenevola
=> Initial internal dependencies update

.circleci/config.yml
Increasing Group 11 timeout in our self-test. This test group is frequently breaking and we have to manually go on Circle CI and execute it again. When we manually execute it the test succeeds. Hopefully, by increasing the timeout this problem will end.
=> -Increasing meteor self test timeout.

packages/standard-minifier-css/package.js, packages/standard-minifier-css/plugin/minify-css.js
This modernizes the standard-minifier-css package. 
It should also have a performance improvement on css heavy projects because of the updated source-map package which now works with the wasm-based sourcemap consumer.
=> Modernize standard-minifier-css and update dependencies

tools/cli/commands.js, tools/cli/help.txt, tools/meteor-services/deploy.js
Inserting a new flag that will allow the users to deploy their apps directly in the Galaxy's free mode.
=> #371 cold-start

tools/cli/commands.js, tools/cli/help.txt, tools/meteor-services/deploy.js
Adding a new flag that will allow Galaxy to create a database for apps, that do not have a MONGO_URL in their settings when deploying.
=> #459 MongoDB

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, DEVELOPMENT.md, ISSUE_TRIAGE.md, README.md
The idea of this change is to update the contributing docs and also organize the labels in a way that we can see better the current stage of each PR.
=> Review contributing docs and organizing labels

packages/minimongo/local_collection.js, packages/minimongo/minimongo_tests_client.js
This fixes a null reference exception, if an array contains null values while compiling a fields projection.
=> Fix bug in minimongo fields projection

tools/cli/commands-packages.js, tools/cli/help.txt, tools/tests/command-line.js
Implements [feature request #406](https://github.com/meteor/meteor-feature-requests/issues/406) by allowing to type a `--json` option and let the tree output be in JSON format. The entries consist of the package name as key and either String value (version number + top-level or expanded-above) or an Object with the following    properties:
- version (String) - always
- local (Boolean) - only if true when package is built from source
- weak (Boolean) - only if true
- newerVersion (String) - only if exists
- dependencies (Object) - only if > 0 and not all weak
In order to also support a more detailed output, there is a --details option. If it's active, the following properties are added, too:
- earliestCompatibleVersion (String) - always
- debugOnly (Boolean) - only if true
- prodOnly …
=> tool list command added json flag to output packages in json format

History.md, tools/cordova/project.js
=> When cordova add plugin fails using the id in the git URL we now retry using the plugin name

scripts/generate-dev-bundle.ps1
Resources where downloaded through insecure connection enabling an attacker to intercept communications and replacing with malicious data, downloaded files are intended for execution
Replace http url with https for downloading resources
Download is performed through insecure connection
After fix Secure conection is stablished for downloads
Resources can be downloaded normally
=> Avoid MiTM by downloading through https

meteor, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/standard-minifier-css/.npm/plugin/minifyStdCSS/npm-shrinkwrap.json, packages/typescript/package.js, scripts/dev-bundle-tool-package.js, tools/fs/files.ts, tools/tests/apps/modules/.meteor/packages
=> Update Typescript to 4.0.5

packages/accounts-base/accounts_server.js
> By default, the current user’s username, emails and profile are published to the client. You can publish additional fields for the current user with:
```JS
// Server
Meteor.publish('userData', function () {
if (this.userId) {
return Meteor.users.find({ _id: this.userId }, {
fields: { other: 1, things: 1 }
});
} else {
this.ready();
}
});
// Client
Meteor.subscribe('userData');
```
```JS
Accounts.setDefaultPublishFields({username: 1, profile: 1, emails: 1, 'foo.bar': 1});
// or
Accounts.setDefaultPublishFields({'do.not.publish.this': -1});
```
**Since this replaces the default projection the user has to add `profile`, `username`, and `profile` to the projection to keep the old behavior.**
I think that writing an additional subscription just for the sole purpose to fetch additional …
=> [Feature] Be able to define default user fields published on login

packages/browser-policy-content/browser-policy-content.js, packages/browser-policy/browser-policy-test.js
Fixes https://github.com/meteor/meteor/issues/11031
In short, this didn't work, now it works: 
```js
BrowserPolicy.content.allowScriptOrigin(`nonce-${nonce}`);`
```
To try it out, run this minimal example project: https://github.com/namenotrequired/meteor-csp-nonce-example - the page shows either `The nonce was set successfully` or `The nonce was NOT set`
Edit: I also added tests for both the new `nonce` and the pre-existing `sha` options
=> Allow setting nonce in browser-policy-content (fixes 11031)

packages/accounts-ui-unstyled/login_buttons_dropdown.js
In accounts-ui, when pressing Enter to submit,
- The login form would send the server two login requests (part of https://github.com/meteor/meteor/issues/10853; see the [reproduction repo](https://github.com/AndyCC25/meteor-login-bug))
- The "forgot password" form would not only send the email but also refresh the page
The first bug was because when we hit Enter on one of the form fields, the event handlers for both `click #login-buttons-password` and `keypress #login-password` run, and they both call `loginOrSignup();`. The `keypress` event listener wasn't needed, as the `login-buttons-password` is a `button`, and the [HTML spec](https://html.spec.whatwg.org/#implicit-submission) says:
> If the user agent supports letting the user submit a form implicitly ... then doing so ... must cause …
=> Fix form submit bugs in accounts-ui

packages/dynamic-import/client.js, packages/dynamic-import/dynamic-versions.js
Fix for #11157 
The fix contains two commits, the first fixes the problem that prefetching of dynamic imports only occurs when an import is executed during initial load of the page.
The second commit fixes a failed prefetch when dynamic imports from packages are used because of replacing : with _ in package names.
=> Fixing prefetching errors with dynamic-import #11157

tools/isobuild/bundler.js, tools/tests/bundle.js
Change isWithinProdPackage() in isobuild/bundler.js to check for broken symlinks and throw a useful error. Fixes #11241.
=> Catch broken symlinks in isobuild #11241

packages/dynamic-import/dynamic-versions.js
The problem as described in #11264 was that the new code used an arrow function which is incompatible with IE.
I have tested the fix locally by copying the entire package into my "packages" directory with meteor 1.12 and running our app with IE and then it worked fine.
=> Don't use ecmascript features - fixes #11264

packages/meteor-developer-oauth/meteor_developer_client.js, packages/meteor-developer-oauth/package.js
We need to have more control over what we send to our authentication system, so we are adding a new param for this.
=> Be able to provide extra info to Meteor Developer OAuth in the URL

tools/cordova/builder.js, tools/utils/utils.js
This has been an annoyance for nearly 3 years - as documented here: https://github.com/meteor/meteor/issues/8883 finally getting around to submitting a PR. If you have a non `/` ROOT_URL, the suffix is stripped off when building for cordova, so your app never connects. E.g., `https://mydomain.com/admin`. 
This package ensures that both the parseUrl function and the cordova `generateBootstrapPage` function respect the suffix of ROOT_URL. I've been making this fix to every version of meteor on every build machine for almost 3 years. Some of my projects use a `/suffix` url and some don't.
=> Ensure the pathname of the rootUrl is used in the mobile URL

tools/isobuild/package-source.js
I'm proposing this solution, adding the nodeModulesToRecompile to the cache key as suggested by @zodern instead of this #11247 to solve the issue #11215
=> Adds nodeModulesToRecompile to the cacheKey

GLOSSARY.md
The terms currently follow a loosely related order, but I believe alphabetizing the glossary is more sustainable long-term. It should ease determining "correct" placement of new terms where many relations exist, and it makes it more scannable for readers.
The diff may look a bit weird but I can assure that I've changed no headings, descriptions, or related terms*. 
*However, I did lower-case the anchor sources. In the "Preview Changes" tab of editing, anchors don't render correctly if the source isn't lower-cased and hyphenated; at the same time, it does render correctly when looking at the actual document in the repository, so this change just eases development.
=> Alphabetize GLOSSARY.md

package-lock.json, package.json, prettier.config.js, tools/cli/commands.js, tools/console/console.js, tools/runners/run-mongo.js, tools/tests/create.js, tools/tool-testing/README.md, tools/tool-testing/matcher.js, tools/tool-testing/run.js, tools/tool-testing/sandbox.js, tools/tool-testing/selftest.js, tools/utils/utils.js
`self-test` results are very hard to understand. 
In this PR we try to improve its readability making clear what each text represents.
For example, this was the log when a test is going to be executed:
`app-config: mainModule`
now it looks like this:
`app-config.js test:mainModule`
Also it's hard to debug adding new logs between tests as the tests can break as they are watching the logs in many cases. Using `METEOR_SIMPLE_DEBUG=1` and `Console.simpleDebug` we don't affect tests so we can add debug logs where we need.
I'm improving these tests and logs while I'm testing Node 14. I'll probably add more commits to this PR.
=> Improve readability of self-test results and new debug mode

tools/static-assets/server/mini-files.ts
=> Fix issue #11320.  WindowsLikeFilesystem true when release string includes case insensitive word microsoft

packages/launch-screen/package.js, packages/webapp/package.js, tools/cordova/index.js, tools/cordova/project.js
=> Update Cordova to 10.0.0

tools/static-assets/server/boot.js
This pull request will reorder the operations when attempting to get the absolute file path of an asset. I have reordered the operations in this pull request so we will convert the asset path before checking if it exists. Before when you passed a windows files path to `getAbsoluteFilePath` (e.g. getAbsoluteFilePath(`tests\test`)) the array that holds the assets would be storing the path with a linux like separator (e.g. `test/test`). Since the separator does not match, the asset was not found. The `convertToStandartPath` function takes care of this by changing the assetPath to use the proper separator. This function was being called after the existence check, which was too late causing the code to throw the error on line 365.
@filipenevola sorry about the delay for getting the pr up on …
=> Reorder code to fix absoluteFilePath on windows fixes #11312

History.md, appveyor.yml, packages/babel-compiler/.npm/package/npm-shrinkwrap.json, packages/mongo/mongo_driver.js, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js, tools/runners/run-mongo.js
MongoDB 4.4.4 has changed some messages.
Due to these changes Meteor apps were not starting with embedded MongoDB as the messages were not matching with the expected ones.
This PR updates these messages and also upgrades the MongoDB driver as it was not up-to-date.
=> Fix MongoDB startup checks

tools/static-assets/skel-blaze/.meteor/packages, tools/tool-testing/sandbox.js
Now, our Blaze skeleton by default will have [HMR](https://github.com/meteor/blaze/pull/313).
=> Adding the HMR to Blaze skeleton

History.md, packages/ddp-server/.npm/package/npm-shrinkwrap.json, packages/ddp-server/package.js, packages/socket-stream-client/.npm/package/npm-shrinkwrap.json, packages/socket-stream-client/package.js
Update `faye-websocket` and related dependencies. This will remove Node's HTTP parser deprecation message.
=> Update faye-websocket dependency

History.md, packages/ddp-client/common/livedata_connection.js, packages/ddp-client/package.js
This PR implements my suggestion made in https://github.com/meteor/meteor-feature-requests/issues/427:
> While there's a couple of excellent tools to debug the DDP communication, I still tend to rely on the browser's _Network_ tab. In this case, I can't see the whole DDP messages but a short prefix instead. It's fine for all but one message: `method`.
> 
> For example, if I'd like to check whether a subscription is ready, the `id` of a subscription is the second key both in the `sub` and `ready` messages ([source](https://github.com/meteor/meteor/blob/46e00a875726dff078c59eaf7fdc7b956cf0a996/packages/ddp-client/common/livedata_connection.js#L1745-L1750), [source](https://github.com/meteor/meteor/blob/46e00a875726dff078c59eaf7fdc7b956cf0a996/packages/ddp-server/livedata_server.js#L330)). …
=> Reordered fields in DDP method call.

tools/static-assets/skel-svelte/.meteor/packages, tools/static-assets/skel-svelte/imports/ui/App.svelte
In the new version of the Svelte tutorial (https://svelte-tutorial.meteor.com/), we made it visualizing that the programmer just needs to run the command to create a new app with Svelte and this app already has the HMR package installed.
=> Adding HMR to the Svelte skeleton

tools/cordova/project.js
Fix by first installing plugins, and then adding the Cordova platform android/ios, it will avoid errors due to plugins options declared in the config.xml.
=> Reverse order of adding plugins/adding platforms on cordova build

History.md, meteor, packages/babel-compiler/README.md, packages/babel-compiler/babel.js, packages/babel-compiler/package.js, scripts/dev-bundle-tool-package.js, tools/fs/files.ts, tools/isobuild/builder.js, tools/isobuild/js-analyze.js, tools/tool-env/install-babel.js, tools/tool-env/source-map-retriever-stack.js
`meteor-babel` has been update to v7.11.0 and renamed to `@meteorjs/babel`. This update includes a fix for Samsung Internet v6.2+ to be considered modern browser and addition of [logical assingment operators](https://github.com/tc39/proposal-logical-assignment) via `babel-presets-meteor`.
=> Meteor Babel 7.11.0

packages/react-fast-refresh/client-runtime.js, packages/react-fast-refresh/package.js
Fix #11418 by replacing arrow functions in `react-fast-refresh` by traditional anonymous functions.
A side note: shouldn't we move `react-fast-refresh` to react-pacakages repo?
=> Fix react-fast-refresh for IE11

meteor, packages/ecmascript/package.js, packages/typescript/package.js, scripts/dev-bundle-tool-package.js
The version of @meteorjs/babel was already updated in https://github.com/meteor/meteor/pull/11411
TS version in @meteorjs/babel also was updated in https://github.com/meteor/babel/commit/f23cb8dd5e44b6e84efc455e53504556532d6635
=> Update TypeScript to 4.2.4

tools/cli/commands.js, tools/cli/help.txt
This commit adds the "--platforms" flag to meteor build command. This allows the user to specify which platforms he want to build. For example, if we pass only android to it, we will build only android and web.cordova.
I think this is pretty useful when we want to build a specific mobile app. For example, I want to build only for android and not for iOS (but I may still build for iOS on another time, so removing and adding the platform is more work to do).
Usage example: `meteor build . --platforms=android`.
Note: if no platforms flag is used, it will do the build like it always did. 
Related to issue #63 (https://github.com/meteor/meteor-feature-requests/issues/63)
=> Add platforms options to meteor build:

packages/server-render/package.js, packages/server-render/server-register.js
Update server-render npm dependencies and small cleaning of the code. Supposedly this should help a bit with performance (when it comes to `magic-string` dependency: https://github.com/Rich-Harris/magic-string/blob/master/CHANGELOG.md).
=> Update server-render npm dependies

packages/deprecated/markdown/README.md, packages/deprecated/markdown/package.js, packages/deprecated/markdown/showdown.js, packages/deprecated/markdown/template-integration.js
this is breaking change but it saves 9kb in the initial bundle
markdown pacakge is using lazy imports and will not be added to the initial bundle.
to use `{{#markdown}}...{{/markdown}}` import it first with:
`import 'meteor/markdown';`
=> refactor: lazy import for markdown package

History.md, meteor, packages/babel-compiler/package.js, packages/ecmascript/package.js, packages/typescript/package.js, scripts/dev-bundle-tool-package.js
Blocked by https://github.com/meteor/babel/pull/44
- Announcing TypeScript 4.3 https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/
- Breaking changes https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#breaking-changes
=> Update TS to 4.3

packages/webapp/webapp_server.js
UNIX_SOCKET_PERMISSIONS takes an octal value. If an invalid value is specified, an exception is generated.
e.g. when the following env variables are set:
```
UNIX_SOCKET_FILE=/tmp/meteor.sock
UNIX_SOCKET_PERMISSIONS=660
```
After the Meteor app is started, the socket file `/tmp/meteor.sock` is created and will be given user & group read-write permissions.
When the Meteor app is running:
`ls -l /tmp/meteor.sock`
displays something like
`srw-rw---- 1 meteor meteor 0 May 24 09:25 /tmp/meteor.sock`
For us, the use case is to allow the Meteor app to run under a different user id to the Nginx web server. Instead, Nginx is made a member of the Meteor app's group and can now be given group permission to write to the Meteor app's socket file.
=> UNIX_SOCKET_PERMISSIONS sets permissions on UNIX_SOCKET_FILE

History.md
The cache is always enabled in development when (re)starting the server. The only part that isn't ready for general use is using it within the meteor tool to speed up loading build plugins.
=> Update description of reify cache changes

packages/accounts-base/accounts_server.js, packages/accounts-base/accounts_tests.js
When using an external service, there are times when a developer wants to merge the account instead of creating a new user. Various packages and workarounds have been created and suggested to handle this:
* [merge-accounts](https://atmospherejs.com/rkstar/accounts-merge) - Creates two users and decides which to use. Old package.
* [delete user in `Accounts.createUser` hook, and return identical user to be created](https://forums.meteor.com/t/accounts-password-merge-with-accounts-google-2017-way/35590) - Has bad side effect of an error being thrown in the `insertUserDoc` and now no user exists.
Provide another login hook, `selectCustomUserOnExternalLogin`, that takes a callback to allow the developer to decide how to determine if a user exists based on the `serviceData` provided by the …
=> add hook to allow custom user selection in Accounts.updateOrCreateUserFromExternalService

History.md
Checked the most recent changelog and noticed below was misspelled. Thanks!
=> Fixed spelling of "below" on History.md

packages/tinytest/README.md
Was reading into [`check`](https://github.com/meteor/meteor/blob/devel/packages/check/match_test.js#L347) package and wanted to know more about [`fail`](https://github.com/meteor/meteor/blob/devel/packages/tinytest/tinytest.js#L35) method but there wasn't any notes about it so I added one.
=> Add note about fail

History.md, packages/routepolicy/package.js
I have noticed that underscore was not used in `routepolicy` package so I have removed it from the dependencies.
=> Remove underscore from routepolicy

packages/minifier-css/.npm/package/npm-shrinkwrap.json, packages/minifier-css/package.js
Update to the latest `postcss` and latest `cssnano` in v4 branch. One tests fails if we go to `cssnano` v5 and that is due to the order of definitions beings switched, though the main point of the test passes. This will need further investigation.
#11486
=> Update css minifiers dependencies

packages/webapp/.npm/package/npm-shrinkwrap.json, packages/webapp/package.js, packages/webapp/webapp_server.js
Updates npm dependencies in the `webapp` package.
=> Update webapp dependencies

tools/isobuild/package-api.js
In [v1.7, 2018-05-28](https://docs.meteor.com/changelog.html#changes-24) there's a mentioning of `legacy` option that can be passed to `addFiles` but the official docs has no records of it.
>For the most part, the modern/legacy system will transparently determine how your code is compiled, bundled, and delivered—and yes, it works with every existing part of Meteor, including dynamic import() and even the old appcache package. However, if you're writing dynamic code that depends on modern features, you can use the boolean Meteor.isModern flag to detect the status of the current environment (Node 8 is modern, too, of course). If you're writing a Meteor package, you can call api.addFiles(files, "legacy") in your package.js configuration file to add extra files to the legacy bundle, or …
=> Add note about legacy bundle

packages/webapp/webapp_server.js
This fixes an issue in #11506 where the `WebApp.addRuntimeConfigHook` callback receives an `update` flag.
The `update` flag was only ever `true` for the first subscriber to the hook.
To fix the issue, I moved the reset of the updated flag out of the hook callback loop.
=> [Release-2.4] fix updated flag to be true for all hook subscribers

History.md, packages/deprecated/http/httpcall_client.js, packages/deprecated/http/httpcall_server.js
This updates the documentation and code to reflect the removal of the `npmRequestOptions` parameter to `HTTP.call`.
=> Reflect removal of npmRequestOptions in documentation and comments

meteor, packages/meteor/.npm/package/npm-shrinkwrap.json, packages/meteor/fiber_helpers.js, packages/meteor/package.js, packages/mongo/oplog_tailing.js
The original issue for which we have used our own `meteor-deque` npm package has been long resolved:
https://github.com/npm/read-installed/issues/40
So I have moved to used the target package directly.
=> Use double-ended-deque directly now that npm issue resolved

History.md, packages/logging/.npm/package/npm-shrinkwrap.json, packages/logging/README.md, packages/logging/logging.js, packages/logging/package.js, packages/meteor/debug.js, scripts/dev-bundle-tool-package.js, tools/console/console.js, tools/cordova/run-targets.js
The next version of Meteor logging.
=> Logging v1.3

History.md, packages/accounts-base/accounts_server.js, packages/accounts-oauth/oauth_common.js, packages/accounts-password/password_server.js, packages/mongo/collection.js, packages/mongo/mongo_driver.js, packages/mongo/oplog_tests.js, packages/mongo/package.js, packages/mongo/remote_collection_driver.js, packages/oauth/pending_credentials.js, packages/oauth1/oauth1_pending_request_tokens.js, packages/service-configuration/service_configuration_server.js
Add `_createIndex` as a collection function. This is a new name for `_ensureIndex` which MongoDB has deprecated and removed in MongoDB 5.0. This gives people the opportunity to start using the new MongoDB API, while we maintain backward compatibility.
=> createIndex for collections

History.md, packages/npm-mongo/package.js
While looking for stuff around #11568 I went ahead and updated `npm-mongo` with the latest `mongodb` in the 3.6 series.
=> Update mongodb to 3.6.10

tools/runners/run-app.js
Fix for #9907 cannot pass METEOR_SETTINGS to meteor run
Disregard `METEOR_SETTINGS` only in development (when you should use `--settings`).
=> Fix #9907 - Deleting METEOR_SETTINGS only in development

History.md, packages/facebook-oauth/package.js, packages/github-oauth/package.js, packages/google-oauth/package.js, packages/meetup-oauth/package.js, packages/meteor-developer-oauth/package.js, packages/oauth1/package.js, packages/weibo-oauth/package.js
Fix #11575 by allowing usage of both major versions of the deprecated `http` package until we can fully replace it with `fetch`.
=> Allow usage of http packages v1 and v2 in affected packages

tools/isobuild/bundler.js
This PR fixes issue https://github.com/meteor/meteor/issues/11583.
The ROOT_URL should NOT be added for base64 encoded source Mapping URLs
=> Fixes #11583 Do not add ROOT_URL to sourceMappingURL for base64 encoded urls

packages/callback-hook/hook.js, packages/callback-hook/hook_tests.js
Add `forEach` to the `callback-hook` so that it follows the naming standard for ES when it comes to looping. Retains `each` iterator for backward compatibility.
=> callback-hook add forEach iterator to follow the JS standard

packages/ddp-server/package.js, packages/ddp-server/stream_server.js
TEST_METADATA is by default `"{}"`, so the check if to send it is always true, even though it was intended to be false when the env var is not set.
Thanks to @zodern for pairing up on this one.
In regards to #11513 this fixes particular case that @zodern was seeing, it might not apply to other cases. Again, get the latest releases to stop seeing those messages or you can safely disregard them.
=> Fix/ sending test metadata

packages/ddp-client/common/livedata_connection.js, packages/ddp-server/stream_server.js
TEST_METADATA is by default `"{}"`, so the check if to send it is always true, even though it was intended to be false when the env var is not set.
Thanks to @zodern for pairing up on this one.
=> Fix sending test metadata

History.md, packages/accounts-password/package.js, packages/accounts-password/password_server.js, tools/tests/apps/custom-minifier/packages/custom-minifier/plugin/minify.js
Fix #11600 properly use `isEnroll` in accounts-password when determining reset password token location instead of the old way.
=> accounts-password use isEnroll

tools/cli/commands.js, tools/fs/safe-watcher.ts
This should fix Meteor getting stuck when creating the first app after it is installed on Windows. This is a temporary fix until we replace the library we use for using native file watchers.
=> Disable native file watching during meteor create

packages/webapp/webapp_server.js
Add another hook to the `webapp` package.
This function will add a hook to notify the caller whenever meteor has updated its code.  This hook would mostly be used in development to enable the caller to perform actions whenever meteor has updated itself.
@filipenevola, @StorytellerCZ,
This is a hook that I require to enable `autoupdate` when I am developing with a meteor server shared among multiple client applications.  Super useful during development.
Hoping we can sneak this into 2.4 while I was updating `webapp` anyway.
=> Add WebApp.addUpdatedNotifyHook

tools/cli/commands-packages.js
This should fix Meteor getting stuck when preparing to run the tests on Windows (AppVeyor). This is a temporary fix until we replace the library we use for using native file watchers.
=> Disable native file watching during meteor --get-ready

packages/facebook-oauth/facebook_server.js
Hello, I am using Meteor as a back-end for a **React Native App**. I have configured **OAuth** with **Facebook** and **Google** successfully (based on these articles for [Facebook](https://medium.com/differential/react-native-meteor-oauth-with-facebook-3d1346d7cdb7) and [Google](https://spencer-carli.medium.com/meteor-google-oauth-from-react-native-e30d146dfad6)).
Currently, the package of **accounts-google** already includes a **login handler** for Google, whereas **accounts-facebook** doesn't include it. So, I did this PR to add this login handler for the Facebook package to make **easier** the process about **Login with Facebook** using Meteor and React Native. Actually, this is part of a [feature](https://github.com/TheRealNate/meteor-react-native/issues/36) from …
=> Feature: Add login handler for Facebook

History.md, meteor, npm-packages/meteor-installer/README.md, npm-packages/meteor-installer/config.js, npm-packages/meteor-installer/package.json, packages/meteor-tool/package.js, scripts/admin/meteor-release-experimental.json, scripts/admin/meteor-release-official.json, scripts/build-dev-bundle-common.sh, scripts/dev-bundle-tool-package.js
Updated Node.js per [August 31st security release](https://nodejs.org/en/blog/vulnerability/aug-2021-security-releases2/).
You can test this release as usual:
```bash
meteor update --release 2.3.6-rc.0
```
=> Release 2.3.6

History.md, tools/runners/run-app.js
Do not delete `METEOR_SETTINGS`, but show a warning when used in development.
=> METEOR_SETTINGS always accepted

.travis.yml, packages/logging/.npm/package/.gitignore, packages/logging/.npm/package/README, packages/logging/chalk, packages/logging/package-lock.json, packages/logging/package.js, packages/logging/package.json
This commit creates a package.json for using the node_modules folder, and it does link the chalk dependency to the root of the package so meteor transpiles it.
The error was happening because IE11 doesn't support ecmascript 2019 features, and thus needs to be served a legacy bundle. Chalk wasn't being transpiled.
=> Use symbolic links for transpiling chalk and make it not throw parse errors with IE11

tools/cli/commands-packages.js, tools/cli/commands.js
Disables it for:
- `meteor update`
- `meteor add`
- `meteor remove`
- `meteor build`
=> Disable native file watcher for more commands

History.md, packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/minifier-tests.js, packages/minifier-js/minifier.js, packages/minifier-js/package.js, packages/standard-minifier-js/.npm/plugin/minifyStdJS/npm-shrinkwrap.json, packages/standard-minifier-js/package.js
Updates terser to the latest version, which in our case is one major version bump.
From breaking side it means this:
* BREAKING: minify() is now async and rejects a promise instead of returning an error.
* BREAKING: Internal AST is no longer exposed, so that it can be improved without releasing breaking changes.
* BREAKING: Lowest supported node version is 10
* BREAKING: There are no more warnings being emitted
Here are some highlights from new features:
* Optional chaining syntax is now supported.
* `source-map` library has been updated, bringing memory usage and CPU time improvements when reading input source maps (the SourceMapConsumer is now WASM based).
* Accept `{get = "default val"}` and `{set = "default val"}` in destructuring arguments.
* Performance improvements
* Many bug fixes …
=> Update terser to 5.8

History.md
While exploring the upgrade to the recently released v2.4 version, I noticed a small typo in the migration steps. Submitting a tiny fix (sorry if this isn't enough description; hoping it's okay for a one-word fix).
=> Fix typo in v2.4 notes: pacakges -> packages

History.md, packages/accounts-ui-unstyled/package.js, packages/accounts-ui/package.js
While working on mobile-packages I have noticed that accounts-ui is not updated to work with the latest `less` package. This PR fixes that by providing compatibility span from v3.0.2 to v4.0.0 of less.
=> Update accounts-ui less dependencies

packages/accounts-base/accounts_common.js, packages/accounts-base/package.js
Allow setting `Account.config` from Meteor settings. This works for all options unless function is specified. This is to make it quicker to setup accounts settings without the need to write code (and for most settings it is booleans or strings). This also allows to quickly change settings on Galaxy without the need to deploy a new version of the app as you have to now.
The old functionality is still working, but settings from Meteor settings will take precedent.
=> accounts-base set config from Meteor.settings

tools/packaging/catalog/catalog-local.js
This also fixes running Meteor from checkout on a different drive.
=> Fix finding local packages on Windows located on drives other than C

packages/ecmascript-runtime-client/package.js
=> Rollback to core-js@3.15.2

DEVELOPMENT.md
Changing `an Meteor` to `a Meteor` on line 98 in DEVELOPMENT.md
=> Fixing Typo in DEVELOPMENT.md

packages/minifier-js/minifier.js, packages/minifier-js/package.js
This is intended to fix #11756, by disabling the evaluation option in terser's compressor.
=> Work around terser bug.

npm-packages/meteor-installer/install.js
We are now checking the npm env var for making sure the user is not installing the meteor-installer package locally.
This env var is not officially documented(at least I couldn't find it!), but there are some mentions to it, like here: https://github.com/yarnpkg/yarn/issues/2472#issue-201139405
Pending tasks:
=> Improve meteor-installer - avoid local install of npm installer package

docs/source/packages/accounts-passwordless.md, packages/accounts-passwordless/package.js, packages/accounts-passwordless/passwordless_client.js
Fixes issue #11763.
This PR changes the passwordless `Meteor.loginWithToken` method name to `Meteor.passwordlessLoginWithToken`.
=> Change passwordless loginWithToken method name to passwordlessLoginWithToken

docs/source/api/tracker.md
Fixes #11747
Document the behavior in the [`Tracker.autorun`](https://docs.meteor.com/api/tracker.html#Tracker-autorun) section of [tracker.md](https://github.com/meteor/meteor/blob/devel/docs/source/api/tracker.md).
=> Document async callback behavior in autoruns

docs/source/packages/accounts-passwordless.md
Missed one 😄 
ref: https://forums.meteor.com/t/solved-passwordless-error-due-to-error-in-the-documentation/57056/11
and ref: #11780
=> Docs: accounts-passwordless - sendLoginTokenEmail should be imported from accounts-base

npm-packages/meteor-installer/README.md, npm-packages/meteor-installer/config.js, npm-packages/meteor-installer/package.json, packages/hot-module-replacement/client.js
The changes in Meteor 2.5 to support cordova broke the web arch's falling back to hot code push when some changes to js files could not be applied with HMR.
=> Fix falling back to hot code push on web archs

npm-packages/meteor-installer/README.md, npm-packages/meteor-installer/config.js, npm-packages/meteor-installer/package.json, packages/hot-module-replacement/hot-api.js
Currently, when both `module.hot.accept` and `module.hot.decline` are called for a module, the last one wins for if the module is updated with HMR.
There are several issues with this:
1. `module.hot.decline` is called when it is known the module can not be updated with HMR. Usually the code that calls`hot.accept` isn't completely accurate and it doesn't make sense for it to override `hot.decline`.
2. In most apps, `module.hot.accept` is only called by hmr integrations (`zodern:melte`, `react-fast-refresh`, `blaze-hot`, `vuejs:vue3`, etc.), after the module was run. If a developer simply adds `module.hot.decline()` to a module, it is likely to be overridden by the HMR integration, making it difficult to disable HMR for a module.
3. The HMR implementations in other bundlers that have a …
=> Prevent hot.accept from overriding hot.decline

.gitattributes
Hopefully this is the last step needed to fix #10930.
=> Fix type of tools/node_modules symlink on Windows

docs/source/api/accounts.md
The `loggingOut` data source is available and described equally as well as `loggingIn` in the [project file](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_client.js#L60-L66) but is not described in [Meteor's online API docs](https://docs.meteor.com/api/accounts.html#Meteor-loggingIn).
=> chore(docs): add `loggingOut` api to accounts page

tools/isobuild/package-source.js
Provides a better error message when we have invalid package.json files.
Also provides new env vars to change the default behavior.
As explained [here](https://forums.meteor.com/t/unable-to-run-after-update-to-2-5-2/57266/6?u=filipenevola) `resolve` is including invalid package.json file intentionally. So we add a specific code to ignore the error when parsing it.
In order to improve the diagnostic of errors like this in the future, we have added a new `console.error` to make clear from which directory this error is coming.
We have also added three new different env vars:
- `METEOR_WARN_ON_INVALID_EXPECTED_PACKAGE_JSON_ERRORS`: to produce warns even for expected invalid package.json;
- `METEOR_IGNORE_INVALID_PACKAGE_JSON_ERRORS`: to ignore any package.json error, could result in problems …
=> Fixes invalid package.json files breaking Meteor run

meteor, scripts/dev-bundle-tool-package.js, tools/fs/files.ts
This PR updates the tar library for faster extractions/compressions.
We are now using tar-fs and tar-streams, as they are 10x faster working with tar streams compared to the version we had of tar.
https://www.npmjs.com/package/tar-fs#performance
Testing locally, I've been able to see a reduction of 30% on deploy time(in the upload bundle step)
=> Update tar library for faster extractions/compressions

History.md, meteor, packages/meteor-tool/package.js, scripts/admin/meteor-release-official.json, scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js
Use fibers 5.0.1 version
Fix #11791 by reusing the same binaries shipped with 5.0.0, as our changes haven't touched the other distributed binary for now.
For any upcoming changes, we will generate new binaries.
=> Release 2.5.6

tools/fs/files.ts, tools/isobuild/resolver.ts
When building a local package for an app on Windows, if the package is on a different drive than the app, Meteor might resolve npm dependencies to a path that is not available when the app runs. This fixes it so the resolver works the same as when the app and package are on the same drive.
=> Fix resolving npm deps of local packages when on different drive

guide/source/testing.md
- Update test data and publications section with code examples on how to do things manually without the use of packages.
- Add a 'testing-methods` section.
- Replace Chimp references with Cypress.
- Update code examples by removing references to Meteor's underscore & jQuery.
- Replace faker reference with the new fork.
We might also need to un-archive the official todo example and update it but I guess that's for another day.
=> Update testing guide

docs/history.md, guide/source/2.6-migration.md, tools/runners/run-mongo.js
From mongoDB 5.0, w: majority is the default write concern for most MongoDB configurations
this causes writes to be acknowledged after the timeout on M1 macs
We are explicitly setting it to 1 when there is only 1 node, as we do simulate replica sets with only 1 node
when running locally or in test environments.
ref: https://docs.mongodb.com/manual/reference/write-concern/#mongodb-writeconcern-writeconcern.-majority-
=> Set explicitly write concern to w:1 on mongo v5 when running locally

docs/source/install.md, npm-packages/meteor-installer/README.md, npm-packages/meteor-installer/config.js, npm-packages/meteor-installer/install.js
The Meteor installer currently modifies the dotfiles of the user running it unconditionally. This makes sense as default behavior, but isn't always optimal. (For instance, I setup my dotfiles before installing meteor, and those dotfiles have the PATH modification already).
This change adds a flag to disable that behavior. I opted for an npm-managed argument, since that felt the most fluid of an interface to me. It's also accessible through a handful of means - you can use `npm install -g meteor --no-meteor-setup-exec-path`, but you can also pass it through the environment (`npm_config_meteor_setup_exec_path=false npm install -g meteor`). I used [this post](https://kgrz.io/how-npm-install-passes-cli-args.html) as a reference on how these arguments work, although the behavior of environment …
=> installer: Add a flag to skip modifying exec path

packages/mongo/oplog_v2_converter.js, packages/mongo/oplog_v2_converter_tests.js
Fix flatten object issue when the object is empty on oplog converter
Fix #11884
=> Fix flatten object issue when the object is empty on oplog converter

packages/mongo/oplog_v2_converter.js, packages/mongo/oplog_v2_converter_tests.js, packages/mongo/package.js
Fix flatten object issue when internal object value is an array - fix #11887
Preserve object.keys call for performance reasons
=> Fix flatten object issue when internal object value is an array on oplog converter

tools/tool-testing/clients/puppeteer/index.js
It was using an old version of puppeteer that didn't support m1.
=> Fix running self tests on m1

tools/isobuild/bundler.js, tools/tests/apps/custom-minifier/body.html, tools/tests/apps/custom-minifier/code.js, tools/tests/apps/custom-minifier/imports/imported.css, tools/tests/apps/custom-minifier/packages/custom-minifier/plugin/minify.js, tools/tests/custom-minifier.js
This makes it consistent with non-lazy resources. Lazy css resources are those in `imports` and any other css files that are not eagerly loaded.
This makes it possible for minifiers that run postcss plugins to do so with these files in development instead of only in production builds.
=> Pass lazy css resources to minifier in development

docs/history.md, packages/accounts-base/accounts_server.js, packages/accounts-base/accounts_tests.js
Fixes an issue where field defined in `Accounts.config.defaultFieldSelector` to be selected is not published to the client. Also added tests, but I'm not entirely certain about them.
The problem seem to have occurred that originally the `defaultFieldSelector` was to primarily prevent getting needless data retrieved, then there was a limitation of user data published to the client (and to ensure that people accidentally don't stop publishing fields that are needed for Meteor accounts to work), but it seems like this field was not taken into account and the functionality stayed only on client. The selection restrictions get applied both on client and server, but they don't make it to the publication till this PR.
This PR merges the required fields for publication and the desired fields. If …
=> Fix #11827 custom user fields not publishing

packages/mongo/oplog_observe_driver.js
Also support the new "projection" field inside the decision of using oplog for a published cursor or not
It was spawning errors as the decision was true for unsupported cursor fields
Fixes this comment: https://github.com/meteor/meteor/issues/11855#issuecomment-1035120781
=> Support the new "projection" field inside the decision of using oplog for a published cursor or not

docs/history.md, packages/email/email.js
Based on the issue [#11709](https://github.com/meteor/meteor/issues/11709), I could reproduce it by not setting a MAIL_URL and running my app with --production.
Now, an error will be thrown when the app runs in a production environment but doesn't have a mail URL set, as a reminder.
Also, making sure there are no [settings](https://github.com/meteor/meteor/compare/release-2.6.1...feature/check-if-mail-url-is-set?expand=1#diff-81b3d1c2cbdddcb39f637030fdb2c2fe5e3190c2b3e0b638c68199f793aa7e5aR66) when calling the function [knownHostsTransport](https://github.com/meteor/meteor/compare/release-2.6.1...feature/check-if-mail-url-is-set?expand=1#diff-81b3d1c2cbdddcb39f637030fdb2c2fe5e3190c2b3e0b638c68199f793aa7e5aR63). Before, this function was being called from …
=> Throwing error when no mail URL is set but the app is running in a 

docs/history.md, packages/facebook-oauth/facebook_client.js, packages/facebook-oauth/facebook_server.js, packages/facebook-oauth/package.js
Update Facebook API to v12. No changes to OAuth has been made, so just bumping the number is enough. Since this is also not anything that needs to be done and the v10 of the API will be supported till June 8th, 2023 I have put it as a feature upgrade to be included in the next feature release of Meteor.
* [v11 changelog](https://developers.facebook.com/docs/graph-api/changelog/version11.0)
* [v12 changelog](https://developers.facebook.com/docs/graph-api/changelog/version12.0)
=> [Facebook OAuth] Use Facebook API v12

packages/react-fast-refresh/client-runtime.js
When there are circular dependencies, the before require hook could be called several times for the same module before the after require hook is called, which caused `react-fast-refresh` to lose some of the state for the module.
=> Fix react fast refresh with circular dependencies

packages/mongo/oplog_v2_converter.js, packages/mongo/oplog_v2_converter_tests.js
The format for oplog v2 might include multiple array type operations. This PR fixes the bug that was caused by only going over the first one.
This PR also adds support for debug messages, which will help debug issues with the new format.
Fixes https://github.com/meteor/meteor/issues/11914
=> Fix multiple array operators bug and add support for debug messages

tools/fs/files.ts
Dependencies may have postinstall scripts which requires the executable permission to be set.
This PR fixes a regression introduced on 2.5.6, as node-fs is currently presenting the same behavior.
=> Revert missing binary permission bit when packing a meteor bundle on Windows

packages/hot-module-replacement/server.js, packages/webapp/webapp_server.js
1. Fixes crash when the app was built with the `--debug` option, and then run with NODE_ENV set to production. Some files are expected to be replaceable in this situation, so I removed the check that was causing the crash. Fixes https://forums.meteor.com/t/unexpected-replaceable-file-in-production/57534.
2. When running the app created from `meteor build --debug`, it would log `Restart Meteor to enable hot module replacement.`. Restarting the app wouldn't enable HMR since it isn't being run by the meteor tool, so it no longer shows the message.
=> Fix issues with HMR and meteor build --debug

guide/source/security.md
I think there is a small typo in guide related  to security
As you'll see, dev environment settings weren't consistent with helpmentOptions.
Let me know if I missed something.
=> docs: fix example code in security guide

docs/history.md, guide/source/2.6-migration.md
Based on the issue [#11921](https://github.com/meteor/meteor/issues/11921), we felt the necessity to make clear that the option applySkipLimit is no longer supported and present a solution in case someone is in the same situation.
=> Improving 2.6 migration guide

docs/source/api/packagejs.md, packages/standard-minifier-css/plugin/minify-css.js, tools/isobuild/bundler.js, tools/isobuild/compiler-plugin.js, tools/isobuild/minifier-plugin.js
Fixes  https://github.com/meteor/meteor/issues/11940.
Adds `file.getSourcePath()` to the minifier files to get the absolute path to the corresponding input file if there is one.
=> Allow minifiers to get source path of file

docs/history.md, packages/modules-runtime/package.js, packages/modules-runtime/server.js
The `install` npm package used to call `module.useNode` to check how to require a module, and then handle throwing an error itself if the module wasn't found. However, now Meteor does most of that work when building the app, and in some cases an error is never thrown if a module was found during the build, but not when running the app.
This PR updates `module.useNode` so it matches how it is now used.
Fixes https://github.com/meteor/meteor/issues/11900.
=> Fix some npm modules being imported as an empty object

npm-packages/meteor-node-stubs/index.js, tools/isobuild/resolver.ts
Adds support for [`node:`](https://nodejs.org/api/esm.html#node-imports) imports.
=> Support node: imports

tools/isobuild/import-scanner.ts
This makes the import scanner cache 4x larger.
With a small app that has:
```js
import * as a from '@mui/icons-material';
import * as b from '@mui/material';
```
the cache will be only 62% full.
=> Adjust import scanner cache size

docs/source/packages/accounts-2fa.md, packages/accounts-2fa/2fa-server.js
As I have stated in release 2.7 PR, returning the secret on 2FA creation is desired as it can be dysplayed as a backup to the QR code and allows the OTP to be used with clients such as KeePassXC which require manual imput of the secret.
=> 2FA return secret as well

packages/accounts-2fa/2fa-server.js, packages/accounts-2fa/package.js, packages/accounts-2fa/server_tests.js, packages/accounts-base/accounts_client_tests.js, packages/check/match.js
I have noticed that the 2FA implementation uses username as a the primary key to find user. That doesn't sound right as username is an optional parameter. As such I have switched it to use userId as the primary key and where feasible add backup of username.
I have also added `check` package to check for input and added a simple server side test for `_is2faEnabledForUser`. Nothing for client for now as I'm struggling with `has2faEnabled` which always returns undefined...
=> 2FA use userId instead of username

docs/history.md, packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/minifier-js/package.js
From this [issue](https://github.com/meteor/meteor/issues/11721) and [this](https://github.com/meteor/meteor/issues/11930) one, we find out a bug on terser (minify package) that was affecting some applications (more of that [here](https://github.com/terser/terser/issues/1155)). 
Terser team [fixed](https://github.com/terser/terser/blob/master/CHANGELOG.md#v5121) the bug on their package, hence this PR updating its version on our minifier package.
=> Updating terser version on minifier-js

packages/standard-minifier-css/plugin/minify-css.js
When setting up the new postcss support in standard-minifier-js along with tailwind, I was getting this error: `postcssInfo is not defined`. Eventually I figured out that it is an error in this file, where postcssInfo is undefined. This change passes along the *actual* error message, which is much more helpful – in my case I had neglected to `npm install -D tailwindcss`, which was an easy fix.
=> Pass on the real postcss error message if processing fails

packages/modern-browsers/modern.js
I have a need to access the `minimumBrowserVersions`.
I could not find an api that was able to read this information.
The PR is quite simple, just expose the `minimumBrowserVersions` with a new API `getMinimumBrowserVersions`.
Thanks!
=> New api getMinimumBrowserVersions

docs/source/api/accounts.md
Small fix to help understand better where the `ServiceConfiguration` settings should be imported
=> Improve accounts docs

docs/history.md, tools/static-assets/skel-apollo/package.json, tools/static-assets/skel-bare/package.json, tools/static-assets/skel-blaze/package.json, tools/static-assets/skel-full/package.json, tools/static-assets/skel-minimal/package.json, tools/static-assets/skel-react/package.json, tools/static-assets/skel-svelte/package.json, tools/static-assets/skel-typescript/package.json, tools/static-assets/skel-vue/package.json
Update skeleton dependencies to latest, with the exception of Vue and Svelte packages which I remember there are some restrictions.
=> Update skeleton dependencies

packages/hot-module-replacement/server.js, tools/fs/files.ts, tools/isobuild/unibuild.js, tools/packaging/tropohouse.js
This fixes a crash from #11474 when reading a package that was downloaded with a Meteor version before Meteor 1.2. Should fix #11959.
Also improves the error message in https://github.com/meteor/meteor/issues/11918.
=> Fix reading packages installed before Meteor 1.2

npm-packages/meteor-node-stubs/package-lock.json, npm-packages/meteor-node-stubs/package.json
Downgrades the buffer and punycode npm packages to a version that is compatible with IE.
=> Fix using meteor-node-stubs in IE

meteor
This allows users on multi-arch systems to explicitly indicate their execution architecture.
Overriding `ARCH` is necessary for systems which run without a `uname` binary extended to "lie" about the system's architecture in different contexts. For example on a multi-arch build system `meteor` may be running in an execution mode which differs from the host execution mode; currently you either have to modify `meteor` or patch `uname` to "lie" in order to get the desired `ARCH`.
This change allows users to run multi-arch without a patched `meteor` launcher or `uname` binary.
Ex:
```
PATH="/usr/local/opt/gnu-coreutils/bin${PATH+:$PATH}" ARCH=x86_64;
export PATH ARCH;
/usr/bin/arch -x86_64 ~/.meteor/packages/meteor-tool/2.5.6/mt-os.osx.x86_64/meteor ARGS...;
```
For context `gnu-coreutils`'s …
=> Permit users to set uname info

guide/source/cordova.md
Improving Cordova installation instructions.
This was an issue reported at: https://forums.meteor.com/t/unable-to-solve-android-target-error-in-meteor-add-platform-android/58069/2
=> Add Cordova M1 installation instructions

tools/project-context.js
Fixes Meteor not recompiling an npm package for the client when using these recompile settings:
```json
{
"meteor": {
"nodeModules": {
"recompile": {
"svelte": true,
"package-1": "web",
"package-2": "client",
"package-3": ["client"]
}
}
}
}
```
=> Fix recompiling npm packages for web arch

tools/isobuild/import-scanner.ts
Follow up to #11956 since it didn't increase the cache size enough for some apps.
=> Increase max size of IMPORT_SCANNER_CACHE

tools/fs/watch.ts, tools/isobuild/compiler-plugin.js
Watch sets should only have posix style paths, but on Windows there would be some that were not from build plugins calling `file.readAndWatchFileWithHash`.
=> Fix win style paths being added to watch sets

npm-packages/eslint-plugin-meteor/scripts/dev-bundle-server-package.js, npm-packages/eslint-plugin-meteor/scripts/dev-bundle-tool-package.js, packages/modules/package.js, scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js
This [PR](https://github.com/meteor/reify/pull/2) was open on the meteor/reify repository to fix this [issue](https://github.com/meteor/meteor/issues/12035), so we're upgrading the version on Meteor.
=> Upgrading reify version

packages/minifier-css/package.js
Update the `postcss` package from `8.3.5` to `8.4.16` from the `minifier-css` package.
This update will avoid issues with `Browserslist` and `caniuse-lite`.
https://github.com/postcss/postcss/releases
=> Update postcss from the minifier-css package

packages/minifier-js/package.js
Update the `terser` package from `5.12.1` to `5.14.2` from the `minifier-js` package.
This update is important due to security fixes and to take advantage of `terser` improvements.
https://github.com/terser/terser/blob/HEAD/CHANGELOG.md
=> Update terser from the minifier-js package

packages/mongo/mongo_driver.js, packages/mongo/oplog_tests.js, tools/tests/run.js
As reported by @denihs in #12118, the internal `topology` object is not always available, and as such, we can no longer rely on it. What is more, the current implementation relies on the `join` event of the aforementioned `topology`, and I couldn't find any documentation regarding it (I suspect it didn't work for a long time now).
Now, I thought that the solution will be to use the `topologyDescriptionChanged` instead, but it wasn't the case. The new implementation, proposed in this PR, uses the `serverDescriptionChanged` event, as it has all of the information we need.
It also allowed me to get rid of the `_primary` field on the `MongoConnection` object, but I'd need to check whether it won't be needed on a replica set with more nodes (~so far, I tested it on a set with one node~). …
=> Fixed `MongoConnection._onFailover` hook (fixes #12118).

packages/standard-minifier-css/package.js
Update the `standard-minifier-css` package dependencies.
This update will avoid issues with `Browserslist` and `caniuse-lite`.
=> Update standard-minifier-css dependencies

packages/standard-minifier-js/package.js
Update the `standard-minifier-js` package dependencies.
This update will avoid issues with `Browserslist` and `caniuse-lite`.
=> Update standard-minifier-js dependencies

packages/mongo/oplog_v2_converter.js, packages/mongo/oplog_v2_converter_tests.js
As I mentioned in #12107, I find the current implementation of the `oplogV2V1Converter` inefficient but also hard to understand. In this PR, I simplified it and made it more performant by skipping a lot of unnecessary object copies.
Additionally, I adjusted the tests, so it's easier to add more, as well as reduced logs to one per call to make it easier to debug. (The error message that was there before was no longer reachable.)
=> Improved `oplogV2V1Converter` implementation.

packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js
In this pull request, I updated the MongoDB driver to version [4.9](https://github.com/mongodb/node-mongodb-native/releases/tag/v4.9.0). As @fredmaiaarantes pointed out, it includes a fix for https://github.com/mongodb/node-mongodb-native/pull/3337, which may be important for some Meteor apps (most likely the ones which heavily rely on oplog and are not using `cultofcoders:redis-oplog`).
=> Updated MongoDB driver to 4.9

packages/minimongo/matcher.js, packages/minimongo/minimongo_tests_client.js
As reported in #12063, Minimongo doesn't handle the inequality operators (e.g., `$gt`) on invalid date objects (e.g., `new Date('')`) correctly, resulting in a broken connection. I couldn't figure out why the connection breaks (yet...?), but I implemented handling of the invalid date objects to fix it in the first place.
It's not stated in the MongoDB docs, but by checking the `explain` result, it looks like invalid dates are handled just like `new Date(0)`, and that's what I did. Here's how I checked it:
```ts
// db.example.find({createdAt: {$gt: new Date('')}}).explain().queryPlanner
{
"namespace" : "meteor.example",
"indexFilterSet" : false,
"parsedQuery" : {
"createdAt" : {
"$gt" : ISODate("1970-01-01T00:00:00.000Z")
}
},
"queryHash" : "77E9ED6B",
"planCacheKey" : "0CF3FA65", …
```
=> Handled invalid dates in Minimongo Matcher (fixes #12063).

docs/source/api/pubsub.md, packages/ddp-server/livedata_server.js
Rename setPublicationStrategy and getPublicationStrategy arguments.
Fix issue: [Bad naming for setPublicationStrategy variable (documentation fix probably) #12022](https://github.com/meteor/meteor/issues/12022)
=> fix: rename setPublicationStrategy and getPublicationStrategy arguments.

scripts/admin/update-semver/get-diff.sh, scripts/admin/update-semver/index.js, scripts/admin/update-semver/package-lock.json, scripts/admin/update-semver/package.json
Better dx for deploying and creating new versions
it can be used for auto-updating semver for meteor core packages
```bash
node index.js <package>.<major|minor|patch|beta|rc> # if does not include a version, it will default to patch. 
```
=> feat: auto semver updater

packages/ejson/ejson.d.ts, packages/ejson/package-types.json, packages/ejson/package.js, packages/fetch/fetch.d.ts, packages/fetch/package-types.json, packages/fetch/package.js
This is one of several PRs that move type definitions from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/meteor) into packages. It will enable using `zodern:types` for core packages' types.
It contains types for two packages: `ejson` and `fetch`. Types for other packages will be added later in different pull requests. There are two reasons for that:
1. To test the current solution of using `zodern:types` package on the production.
2. Several type definitions from DefinitelyTyped will go into different repositories for example [react-packages](https://github.com/meteor/react-packages) or [blaze](https://github.com/meteor/blaze). It will be easier to test this solution first and add other packages later than to make changes in several repositories. …
=> Type definitions for core packages

packages/mongo/collection_tests.js, packages/mongo/mongo_driver.js, packages/mongo/package.js
When implementing manual field level encryption with mongo, the decryption function expects a Binary data type with a `sub_type` of 6. Because meteor converts `Binary` to `Uint8Array` (and vice versa) we lose that. It isn't even possible to pass in a `Binary` - because mongo returns undefined.
This PR simple says to maintain the `Binary` type in most situations. The only situation it does not is when the `sub_type` is `0`. It does this for backwards compatibility (e.g., `sub_type` 0 is still returned as a `Uint8Array`)
=> Use true mongo binary types

packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/package.js
In this pull request, I updated the MongoDB driver to version [4.11](https://github.com/mongodb/node-mongodb-native/releases/tag/v4.11.0). There's nothing crucial there, just a couple of fixes and type improvements, but [4.10](https://github.com/mongodb/node-mongodb-native/releases/tag/v4.10.0) deprecates the callback-style API, it's a good moment to do this change - we're making sure to use promises everywhere.
=> Updated MongoDB driver to 4.11

docs/source/api/email.md
https://nodemailer.com/smtp/well-known/#supported-services seems to have moved to https://community.nodemailer.com/smtp/well-known/#supported-services
=> Fix dead link in docs

packages/ddp-client/common/livedata_connection.js
As suggested by @zodern [here](https://github.com/meteor/meteor/pull/12057/files#r996452189), we don't need to `await` if the stub is sync.
=> In the client, don't wait if the stub doesn't return a promise

packages/mongo-id/id.js
str.match() returns an array on success which is not coerced into boolean true. An explicit not null check is now performed instead.
=> MongoID._looksLikeObjectID bugfix

packages/accounts-base/accounts_client.js, packages/accounts-base/accounts_client_tests.js, packages/accounts-base/accounts_common.js, packages/accounts-base/accounts_tests.js, packages/accounts-password/password_client.js
We have an option of adding ``Meteor.userAsync()`` wich is not reactive ~yet~ because of tracker and keeping both. If you are using them in stateless calls things would look the same.
---
Also, made ``Meteor.loginWithPassword`` accept async values as callbacks
> There was nothing to decide, as since the userId is provided went instantiating that class.
for those who wants to know where it gets the userId field it does this trip:
[Meteor.userId](https://github.com/meteor/meteor/blob/222022ecf0dde1d5ad35aed1ce223aa02c6e4041/packages/accounts-base/accounts_client.js#L46) -> [method_invocation.js#constructor](https://github.com/meteor/meteor/blob/ef8796a44eaff508c285aa499ff7ce8f1dde2b05/packages/ddp-common/method_invocation.js#L48) -> …
=> Feat user accounts base async

npm-packages/eslint-config-meteor/README.md, npm-packages/eslint-config-meteor/index.js, npm-packages/eslint-config-meteor/package.json
- update links to actual code
- replace H1 in readme
- apply ESLint rules to index.js
We don't need to publish anything, just some cleanup.
Another strange thing that it has `1.0.4` in package.json version while npm shows `1.0.5`. Is it ok?
https://www.npmjs.com/package/@meteorjs/eslint-config-meteor
=> [@meteorjs/eslint-config-meteor] chore: update links

npm-packages/meteor-babel/options.js
This change will auto import React on jsx and tsx files by default.
You don't need to repeat yourself writing `import React from 'react'` in every React file.
You can read more about it on React documentation: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#manual-babel-setup
We already support it on `@babel/preset-react` since we are using v7.16.7 and this is added on v7.9
This was requested on forums and also part of our backlog. 
https://forums.meteor.com/t/solved-why-i-still-need-to-import-react-on-each-jsx-tsx-file/58358
TODO:
=> feat: Auto import React on jsx,tsx files

packages/mongo/oplog_v2_converter.js, packages/mongo/oplog_v2_converter_tests.js
This was my first glance at the oplog converter, _or oplog "under the hood" in general_, so I'm not a 100% sure I got it right. I'm still running this against a real app and trying to break it, and it probably will.
That being said, all Mongo tests ran succesfully and it fixes the test case I added + the known bug in our app.
**Explanation**: It seemed like the oplog converter wasn't handling array items updates, at all, such as:
```
sitems: {
u1: { name: 'Foo' }
}
```
which should have translated to 
```
$set: {
'items.1': { name: 'Foo' }
}
```
_Potentially_ fixes #12325
=> oplog-converter: Handle array item updates

meteor, npm-packages/meteor-babel/options.js, npm-packages/meteor-babel/package.json, npm-packages/meteor-babel/plugins/async-await.js, scripts/dev-bundle-tool-package.js
Updating dev bundle with ``@meteorjs/babel@7.18.0-beta.2``
=> chore: update dev bundle

packages/test-in-browser/driver.css, packages/test-in-browser/driver.html
While making the fibers-free tests pass, we made tinytest tests in the console into dark mode, in this PR I did an upgrade in the color palette to be more modern instead of just inverted CSS dark mode.
Here is a print screen of the final result
Also, I've placed a new font I'm still deciding if I continue with [Space Grotesk](https://fonts.google.com/specimen/Space+Grotesk?query=space), which is the same as we are using in Galaxy Cloud.
=> Update on tinytest UI

docs/history.md, packages/accounts-password/password_server.js, packages/accounts-passwordless/passwordless_server.js, packages/deprecated/http/httpcall_server.js, packages/email/email.d.ts, packages/email/email.js, packages/email/email_tests.js
The goal of this PR is to remove wrapAsync from `email` package and also update its usage.
=> Remove wrapAsync from email package

docs/history.md, docs/source/api/passwords.md, packages/accounts-password/package.js, packages/accounts-password/password_client.js, packages/accounts-password/password_server.js
Changing the methods `resetPassword()` and `verifyEmail()` to no longer sign in the user automatically if they have 2fa enabled.
By default these methods already work has the 2FA, sort of speaking, because you need to have access to the user's email in order to finish the operation.
This PR just adds one more layer to that.
=> chore: resetPassword and verifyEmail to no longer sign in the user automatically

docs/source/commandline.md
In 2.9 was added the ``--prototype`` flag was missing updating docs for this new feature.
for context: 
https://forums.meteor.com/t/noob-issue-hello-meteor-links-not-displaying/59240
=> docs: update docs about --prototype

docs/history.md, packages/boilerplate-generator/generator.js, packages/boilerplate-generator/package.js
Remove Fibers usage from the boilerplate-generator (actually just remove this method, since it was already deprecated). However, we can still keep the method there and throw an error if someone tries to use? Internally this is not used anymore, but someone may still use it.
=> Remove toHTML method from boilerplate-generator

tools/cli/commands.js
In the changes for 2.9.0, we added vue 3 as the default creation for app but for creating a vue2 app we had forgotten to add it to the listed apps skeleton variables
Thanks to [mlanning](https://github.com/mlanning) we have solved this one
Notes:
this closes #12395
=> Missing vue2 declaration

.github/workflows/docs.yml, .github/workflows/guide.yml, .github/workflows/labeler.yml, .github/workflows/npm-eslint-plugin-meteor.yml, .github/workflows/npm-meteor-babel.yml, .github/workflows/npm-meteor-promise.yml
- bump actions/checkout to v3
- bump actions/setup-node to v3
- bump actions/labeler to v4
- bump nwtgck/actions-netlify to v1.2.4
=> update actions used in GitHub workflows to newest versions

packages/minifier-js/minifier-tests.js, packages/minifier-js/minifier.js, packages/standard-minifier-js/plugin/minify-js.js
Upgrades minifier-js to expose an async function and use terser with pure async as well.
We didn't had to migrate tools as the minifier-css was already running with async since this [change](https://github.com/meteor/meteor/commit/d726f49a85a1d15662f1db0659fdf3707c45067d ) and this function is called with [Promise.await()](https://github.com/meteor/meteor/blob/088e52f38601d8a0fb40d463d031ec15d8d2eb4a/tools/isobuild/bundler.js#L1927).
=> async minifier js

docs/history.md, guide/source/2.9-migration.md
Add info to history and migration guide about `Accounts.createUserVerifyingEmail` as per #12398 
@Grubba27 I put created this very quickly so we might need to adjust wording.
=> Documentation addition about Accounts.createUserVerifyingEmail

docs/history.md, packages/oauth/oauth_server.js, packages/oauth/oauth_tests.js, packages/oauth/pending_credentials.js
In this PR I focus on making ``oauth`` async, making it possible to have a Fibers-free MeteorJS.
=> Making oauth async

docs/source/commandline.md, tools/isobuild/compiler-deprecated-compile-step.js, tools/utils/buildmessage.js
There are small typos in:
- docs/source/commandline.md
- tools/isobuild/compiler-deprecated-compile-step.js
- tools/utils/buildmessage.js
Fixes:
- Should read `libraries` rather than `libaries`.
- Should read `file name` rather than `filenanme`.
- Should read `compatibility` rather than `compitability`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

packages/mongo/mongo.d.ts
Now that mongodb has great typescript support, bring in filter, updatefilter and sort types from the driver types and remove the now unused old types.
Replica of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63759
=> Use mongodb driver types for Selector=>Filter, Modifier=>UpdateFilter, SortSpecifier=>Sort instead of homebuilt types

packages/mongo/mongo.d.ts
Both the synchronous and asynchronous iterators for Mongo.Cursor are defined to have a "next" argument type of never. However, TypeScript will reject using such an iterator in a for-of loop with:
> Cannot iterate value because the 'next' method of its iterator expects
> type 'never', but for-of will always send 'undefined'.ts(2763)
This changes back to the default (undefined), which is acceptable, since the iterators ignore any arguments passed into next() anyway.
It also correctly declares the return type of dropIndexAsync, which should return a Promise, not void.
(This is an analog to the PR I submitted to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63748)
=> Fix errors in Mongo types

docs/history.md, packages/oauth2/oauth2_server.js, packages/oauth2/oauth2_tests.js
In this PR I focus on making `oauth2` async, making it possible to have a Fibers-free MeteorJS.
=> Making oauth2 async 

packages/webapp/webapp_server.js
The forEach method on Hook will stop iterating unless the iterator function returns a truthy value. Previously, this meant that only the first registered runtime config hook would be called.
(I ran into this by accident when I tried to add a second hook to my application in a different area of functionality. I attempted to look for other places throughout the codebase that might have this bug and wasn't able to find any others.)
=> Allow multiple runtime config and updated runtime hooks

packages/react-fast-refresh/package.js, tools/static-assets/skel-apollo/client/main.jsx, tools/static-assets/skel-apollo/package.json, tools/static-assets/skel-react/client/main.jsx, tools/static-assets/skel-react/package.json, tools/static-assets/skel-typescript/client/main.tsx, tools/static-assets/skel-typescript/package.json
Updated the following skeletons to use React 18 and the new `createRoot` function:
* Apollo
* React
* Typescript
=> Update skeletons to use React 18

packages/meteor/fiber_helpers.js, packages/meteor/package.js
Replace https://github.com/petkaantonov/deque with https://github.com/invertase/denque a [faster](https://docs.page/invertase/denque/benchmarks) and much more maintained alternative
=> Replace double-ended-queue with denque

docs/history.md, packages/server-render/server-render-tests.js, packages/webapp/webapp_server.js, packages/webapp/webapp_tests.js
In this PR I focus on making `webapp` async, making it possible to have a Fibers-free MeteorJS.
=> Release 3.0 tests webapp

docs/history.md, packages/minifier-css/minifier-tests.js, packages/minifier-css/minifier.js
In this PR I focus on making `minifier-css` async, making it possible to have a Fibers-free MeteorJS.
=> Release 3.0 tests minifier css

packages/promise/promise-tests.js
In this PR I focus on making `promise` async, making it possible to have a Fibers-free MeteorJS.
=> [3.0] Solving meteor-promise tests

packages/minimongo/cursor.js, packages/mongo/collection.js, packages/mongo/mongo_driver.js
Previously, if an exception was thrown in an async method, it would not be caught, which is unusual in an async method. Instead, catch the exception and return it as a rejected promise.
=> mongo: In async wrappers, catch exceptions and reject

npm-packages/eslint-plugin-meteor/scripts/dev-bundle-tool-package.js, npm-packages/meteor-babel/package.json, packages/babel-compiler/package.js, packages/typescript/package.js, scripts/dev-bundle-tool-package.js, tools/static-assets/skel-typescript/package.json
Feature: Bump TS to 4.9.4
Done in accordance with the changes in https://github.com/meteor/meteor/pull/12393 and https://github.com/meteor/meteor/pull/12441
=> Bump Typescript to v4.9.4

packages/npm-mongo/.npm/package/npm-shrinkwrap.json, tools/cli/commands.js, tools/cli/help.txt, tools/console/console.js, tools/runners/run-mongo.js, tools/tests/mongo.js
In 2.11, we will update Meteor-embedded MongoDB to version 6.0.3, in which there will be no mongo shell. We needed to update the ``meteor mongo`` command. 
In this PR, I propose using the user ``mongosh`` but if it is unavailable, I show the downloads page and give him the URL so he can use it to connect.
Below there is a picture of how the result came to be:
I do not have mongosh on my machine, which is the error displayed.
If I run `meteor mongo -U` it displays this result
If all goes ok, this is the result that is shown
_Side note:_
For this PR, I also updated the console colors file to accept using template literals as well because it seems more of a natural way to describe which and what colors I want to paint in my console.
=> Updating meteor mongo command

docs/history.md, packages/tracker/package.js, packages/tracker/tracker.d.ts
With the addition of ``Tracker.withComputation`` in meteor 2.10, the type definitions of this new method were left missing.
In this PR I focus on adding it.
=> Updating tracker types 

tools/static-assets/skel-apollo/imports/ui/App.jsx, tools/static-assets/skel-apollo/package.json, tools/static-assets/skel-apollo/server/apollo.js
As title suggest, this PR upgrades the Apollo starter to use Apollo Server v4.
Another change is disabling http batching on client as it was disabled on the server:
https://www.apollographql.com/docs/apollo-server/migration/#http-batching-is-off-by-default
Thanks to @radekmie for consultation on this.
=> Upgrade Apollo starter to Apollo server v4

packages/accounts-base/accounts_server.js
=> Ensure the meteor.loginServiceConfiguration subscription always becomes ready

tools/static-assets/skel-vue-2/imports/ui/components/Info.vue, tools/static-assets/skel-vue-2/package.json
Since Meteor.js 2.9 in this https://github.com/meteor/meteor/pull/12220 we do not have insecure package by default anymore.
In this PR I focus on making links that are already available in the subscription appear in the UI
=> chore: updating vue2 skeleton app subscriptions

docs/source/packages/appcache.md, packages/appcache/CHANGELOG.md, packages/appcache/package.js
Deprecate the `appcache` package as its underlying technology is no longer supported on latest Chrome. #12445
=> Deprecate appcache package

packages/standard-minifier-css/package.js, packages/standard-minifier-css/plugin/minify-css.js, packages/standard-minifier-css/plugin/postcss.js
Thank you for contributing to Meteor. (My all-day every day stack since 2015)
Thank you for taking the time to review my PR!
Feedback and suggestions are welcome and appreciated.
Made minifyStdCSS aka standard-minifier-css debuggable.
* Either of the common debugging commandline arguments
* `--verbose`
* `--debug`
* Environment variable 
* `DEBUG_CSS`
I suffered terribly because if a postcss-plugin goes into an infinite loop, the whole build process gets stuck and there's zero indication from the meteor build tool
* Whether the build process has stalled or not
* What part of the build is having trouble
Etc, `--debug` and `--verbose` had zero effect on `standard-minifier-css` yet it's probably the most likely part of the build process to fail. And if it fails, there's no way to see which …
=> Made standard-minifier-css debuggable

tools/static-assets/skel-solid/imports/ui/Info.jsx, tools/static-assets/skel-solid/server/main.js
Since Meteor.js 2.9 in this [PR](https://github.com/meteor/meteor/pull/12220), we do not have insecure package by default anymore.
In this PR I focus on updating and adding publish and subscriptions to the solid.js skeleton
=> Updating solid skeleton

tools/cli/commands.js, tools/cli/main.js, tools/fs/safe-watcher.ts, tools/isobuild/bundler.js, tools/isobuild/compiler-plugin.js, tools/isobuild/compiler.js, tools/isobuild/isopack-cache.js, tools/isobuild/isopack.js, tools/isobuild/unibuild.js, tools/packaging/tropohouse.js, tools/project-context.js, tools/tool-env/isopackets.js, tools/tool-testing/sandbox.js, tools/utils/archinfo.ts, tools/utils/utils.js
There are some places where archinfo.host needs to be sync. With fibers this worked since it would be async the first time it was used, and then be sync rest of the times. That isn't as easy to do with promises, so this PR changes it to always be sync.
This also fixes a couple other bugs in #12471:
- When a cli command fails, the process will now correctly exit with an error code instead of logging a warning about an unhandled promise rejection and keep running.
- As a side effect of making some functions sync, it fixes a few places where it wasn't correctly awaiting the result when checking if an app or package used another package.
=> Make archinfo.host sync

tools/cli/commands.js, tools/meteor-services/deploy.js
In this PR I focus on making Lint and deploy command async, making it possible to have a Fibers-free MeteorJS.
_note_:
On the tools end did worked but on galaxy did not because of lack of commands(galaxy runs `meteor run`) but it should run meteor run with DISABLE_FIBERS flag
=> Solving lint and deploy

packages/meteor/meteor.d.ts
EventsMap and friends are already in the @types/Meteor blaze.d.ts (not imported to meteor/blaze repo yet though)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/meteor/blaze.d.ts
=> Remove Blaze dependency and types that live in blaze.d.ts

tools/static-assets/skel-typescript/package.json, tools/static-assets/skel-typescript/server/main.ts
Two straightforward issues with the TypeScript skeleton:
- Since tsconfig.json has `types: ['node' ...`, we need to include `@types/node`; not having those type definitions is an error:
```
error TS2688: Cannot find type definition file for 'node'.
The file is in the program because:
Entry point of type library 'node' specified in compilerOptions
tsconfig.json:37:15
37     "types": ["node", "mocha"],
~~~~~~
File is entry point of type library specified here.
```
- Since tsconfig has `noImplicitAny: true`, we need to not have parameters which are implicitly `any`:
```
server/main.ts:4:29 - error TS7031: Binding element 'title' implicitly has an 'any' type.
4 async function insertLink({ title, url }) {
~~~~~
server/main.ts:4:36 - error TS7031: Binding element 'url' implicitly has an 'any' …
```
=> TypeScript skeleton fixes

packages/accounts-password/password_client.js
Fixes #12454, by implementing the suggested change. The issue is indeed true. Look at the example below.
In the devtools I have created a variable `newPassword` which is clearly a number and not a String. However the clause `if (!newPassword instanceof String) {...}` fails to detect this. This happens because of operator precedence.
- `!` has a higher precedence than `instanceof` and thus `!` is always evaluted first. Hence `!newPassword` will always return false, and _false_ is not an instance of _String_, thus the if condition check never runs.
- The issue also mentioned about the infrequent use of String object. So as proposed in the issue itself, I made appropriate changes in the `changePassword` and `resetPassword`.
Please be kind enough to tell me if there is anything that I did …
=> Fixed changePassword and resetPassword functions type checking conditions

.gitignore, packages/accounts-2fa/.npm/package/.gitignore, packages/accounts-2fa/.npm/package/README, packages/accounts-2fa/.npm/package/npm-shrinkwrap.json, packages/accounts-password/.npm/package/.gitignore, packages/accounts-password/.npm/package/README, packages/accounts-password/.npm/package/npm-shrinkwrap.json, packages/logging/.npm/package/.gitignore, packages/logging/.npm/package/README, packages/logging/.npm/package/npm-shrinkwrap.json, packages/react-fast-refresh/.npm/package/.gitignore, packages/react-fast-refresh/.npm/package/README, packages/react-fast-refresh/.npm/package/npm-shrinkwrap.json
It sounds like these folders are supposed to be committed, so long as they aren't dumping additional junk beyond the npm-shrinkwrap file (which seems to be the case). So remove them from .gitignore and add the ones that are missing (presumably as a result of the gitignore).
This is based on @zodern's feedback from https://github.com/meteor/meteor/pull/12505#issuecomment-1424669385
=> Remove packages/*/.npm from gitignore and add missing .npm folders

packages/mongo/mongo.d.ts, packages/npm-mongo/index.d.ts, packages/npm-mongo/package.js, packages/underscore/package.js, packages/webapp/.npm/package/npm-shrinkwrap.json, packages/webapp/package.js
A newly created TypeScript Meteor project today will fail to type check. This is for a handful of reasons, although this PR only addresses a subset of them (stay tuned for more!).
In this PR, we deal with the fact that some of the type declarations for Meteor packages require type declarations for upstream NPM packages. If a Meteor package depends on an NPM package and that NPM package includes type declarations directly, then everything works fine. However, if the NPM package doesn't include type declarations, and instead type declarations have to come from a DefinitelyTyped `@types` package, then we have a problem.
Out of the box, a newly created TypeScript template project sees an assortment of errors caused by this:
```
evan@mathias meteor-types-test (main) % meteor npx tsc
[...] …
```
=> Fix TypeScript type dependencies for mongo, webapp, and underscore

packages/non-core/coffeescript-compiler/coffeescript-compiler.js, packages/non-core/coffeescript/package.js
This enables many new js features in coffeescript, and removes the workaround Meteor used to prevent coffeescript from overriding `Error.prepareStackTrace`.
Publishing a new version of the coffeescript package will also include the caching fix from Meteor 1.10.2.
=> Update coffeescript to 2.7.0

tools/isobuild/meteor-npm.js
The code for copying the node modules folders was converted to use for loops instead of forEach, but the returns were left which caused it to stop before it had copied all files.
This should fix #12530. The first time Meteor was run, it would save the isopacks to disk. The second time Meteor was run, it would try to rebuild any native deps, which involves copying part of the node_modules folder, rebuilding native deps, and then overwriting the original files with the copy. Due to the bug this PR fixes, the copy was missing files which would break the package.
I found it surprising that Meteor was rebuilding native deps here since it should have already ensured they were built correctly when writing the isopack. There might be another issue someplace here, or this something we can optimize …
=> [Meteor 3] Fix missing files when copying node modules to rebuild native deps

packages/babel-compiler/.npm/package/npm-shrinkwrap.json, tools/runners/run-hmr.js
To test it, you need to run using those flags: `DISABLE_FIBERS=1 IGNORE_ASYNC_PLUGIN=1 METEOR_ENABLE_CLIENT_TOP_LEVEL_AWAIT=true mymeteor` 
Note that `METEOR_ENABLE_CLIENT_TOP_LEVEL_AWAIT` is a new one, to enable TLA on Client
Fixes HMR compare - it was breaking due to not having async await
Also, I noticed that HMR is a bit slow compared to Meteor 2.X
=> [Meteor 3] Fix static files on client

guide/source/2.11-migration.md
Solving a few typos in migration guide for 2.11
=> Solving typos in migration guide for 2.11

docs/source/install.md
A small fix to recommend people use Node.js 14 in their Meteor.js apps.
=> docs: recommending Node.js 14 

packages/meteor/asl-helpers.js, tools/isobuild/linker.js
On the client, we can't use the runtime to handle eager requires for the app code since it would break files in `/client/compatibility`. This adds an alternative way to handle eager requires.
=> [Meteor 3] Fix app code not running on the client

.github/workflows/npm-eslint-plugin-meteor.yml, .github/workflows/npm-meteor-babel.yml, .github/workflows/npm-meteor-promise.yml
Update Node version on tests on NPM packages.
I've upped it to Node 14 and 16, but maybe for Meteor 3 we should up it for Node 16 and 18?
=> Update NPM packages Node versions

packages/oauth/oauth_server.js, packages/oauth1/oauth1_pending_request_tokens.js, packages/oauth1/oauth1_server.js, packages/oauth1/oauth1_tests.js, packages/oauth2/oauth2_tests.js, tools/static-assets/server/boot.js
In this PR we're fixing tests for packages:
- oauth
- oauth1
- oauth2
- webapp
The main problem here was that the function [loadServerBundles](https://github.com/meteor/meteor/blob/b4c6274108fa53a3f67900096f5b9e744f387387/tools/static-assets/server/boot.js#L224), inside boot.js, was using `var` in a loop, and that was causing an override the values from the previous time the loop ran.
The solution was to change all the `var` for `const` or `let`.
=> Release 3.0 fix tests oauth webapp

.eslintignore, package-lock.json, package.json, packages/mongo/collection.js, prettier.config.js
While working on fibers issues came across this awesome [eslint rule](https://eslint.org/docs/latest/rules/require-await) that may help us, and we were [discussing making](https://github.com/meteor/meteor/pull/12309) eslint better in general for meteor.
In this PR, I update the eslint deps with vazco ones, removed prettier.config( could not make it work with vazco eslint)
and commented a piece of code that is in the devel branch but is breaking in 3.0
=> Updating release 3.0 with eslint rules

packages/webapp/webapp.d.ts
I did not create any issue for that but if you need I can create one and link to it.
Since it's only missing type definition, I did not add a test ;)
=> fix: addHtmlAttributeHook missing type on WebApp

meteor
Bump devbundle to use our node fork with ESM
In 3.0 is already 14.21.3.2 so for this I needed to go to .2
=> bumped meteor bundle to 14.21.3.2

docs/source/api/accounts-multi.md, packages/accounts-base/accounts_common.js, packages/accounts-base/accounts_server.js, packages/accounts-base/accounts_tests.js
Add custom option to Accounts package:
`collection` {_String_|_Mongo.Collection_} - Instance of _Mongo.Collection_ or collection name as _String_
* [discussion](https://github.com/meteor/meteor/discussions/12544#discussioncomment-5240763) 
* [related issue](https://github.com/meteor/meteor-feature-requests/issues/20)
=> [Accounts] set custom collection

npm-packages/meteor-babel/package.json, packages/modules/package.js
Updates reify to include the changes in https://github.com/meteor/reify/pull/4/commits/cf61c57c6c4fefcbf164bf63d3c12fda1924b3d2. Fixes non-hoisted exports (`export let ...`, `export const ....`) sometimes missing when a module does not use TLA and imports an async module.
=> [Meteor 3] Fix missing non-hoisted exports

README.md
CI badges and links to CI results have been dead on https://github.com/meteor/meteor/blob/master/README.md
- `https://travis-ci.org/meteor/meteor` (dead) => https://app.travis-ci.com/github/meteor/meteor
- `https://circleci.com/gh/meteor/meteor/tree/devel` (to avoid an extra redirection) => https://app.circleci.com/pipelines/github/meteor/meteor?branch=devel
(https://github.com/meteor/meteor/blob/1d6983c0ecfb351400363f7eafb20d2686455704/README.md)
(`https://github.com/tnir/meteor/blob/289a46fdc6e9c1d131769c94761c6d134879058d/README.md`)
=> docs: update CI badges and links in the top README

guide/_config.yml
This is a fix for showing instead of the migration guide for 2.11, to show the migration guide for 2.12
=> Updating the _config.yml to show 2.12

guide/source/apollo.md, tools/static-assets/skel-apollo/package.json
It was pointed out to me on the [forums](https://forums.meteor.com/t/apollo-package-v5-suggestion/59889/3?u=storyteller&utm_source=storyteller&utm_medium=online&utm_campaign=Q2-2022-Ambassadors) that the Apollo server setup code in the Guide is outdated. This PR fixes that by including code from the Apollo skeleton.
While at it I have also updated the skeleton's NPM dependencies 📦 to their latest version.
=> Update guide code for GraphQL initialization

packages/mongo/mongo.d.ts, packages/mongo/oplog_tailing.js
Fields have been renamed to projection upstream and while in Meteor we can use both, it was not accounted for in the TS definitions.
=> Update mongo.d.ts with projection

packages/mongo/mongo.d.ts
As commented in [Slack](https://meteor-community.slack.com/archives/CS46CNDN0/p1683748449822519) by @zodern, it was wrong the .d.ts files.
As a future todo, I've added the addition of tests to be sure that this does not happen again.
Below there is a print showing that it works now, before, the options parameter was being treated as `any`:
=> Updating mongo types

packages/mongo/oplog_tailing.js, packages/mongo/oplog_tests.js
As I commented in https://github.com/meteor/meteor/issues/12627#issuecomment-1541489379, this oplog message can be safely ignored. I did that and added a test for it.
=> Handled implicit collection creation oplog message (fixes #12627).

packages/mongo/collection.js
Saw use of deprecated `Meteor.Collection` highlighted in my IDE, so I replaced it with the current one as indicated on the backward compatibility few lines above. Since this was deprecated in `v0.9.1` we should consider removing it. From the quick search I did `Meteor.Collection` is after this no longer used anywhere else in the code. Same for `Mongo.Collection.ObjectID` and `Mongo.Collection.Cursor`.
=> Replace deprecated reference with current one

packages/meteor/meteor.d.ts
Typescript typings for `Meteor.callAsync` were added a while ago, but `Meteor.applyAsync` was missing.
`Meteor.apply` has been refactored a bit to allow for sharing types across the two, and jsdoc has been copied from the implementation to make it available to intellisense.
=> fix: add `Meteor.applyAsync` typings

packages/mongo/collection_async_tests.js
Local collections can't be created with name. The test was failing because it was trying to save the client inserts on server side. Since there is no subscription for it, it can't count the documents back, so I believe it should not be sending the data to the server and only testing it locally.
=> fix: Collection Async tests not working

tools/isobuild/js-analyze.js
Meteor had been enabling every parser plugin, which makes parsing 3 - 4x slower compared to not enabling any plugins. js-analyze deals with files that have already been compiled, so it only needs to be able to parse code that Node and browsers are able to run and doesn't need as many plugins.
In a smaller app, this reduces the time spent parsing in `ImportScanner#findImportedModuleIdentifiers` from 18 - 23 seconds to less than 6 during the initial build. For some apps, that part of the initial build takes over a minute or two, so this should be a large improvement for those.
This change also makes finding globals in the linker ~2x faster. 
This optimization could be easily backported to Meteor 2.
=> Reduce parser plugins used in js-analyze in Meteor 3

docs/generators/changelog/versions/3.0.md, docs/source/commandline.md, tools/cli/commands.js, tools/cli/example-repositories.js, tools/cli/help.txt, tools/project-context.js, tools/tests/create.js
There are a few open topics I'm open to suggestions.
--- 
Today, when we use `meteor create <app>` we use a static asset that is within the tool itself. In my proposal, I want to change how this works, there are a few reasons:
- Ease of maintenance, if something is wrong with a starter it can be changed easily(now we will use git);
- Possibility of adding new examples and being open to more options because we will be using the network; 
Would instead of just list and show how to clone, it would clone it and make it ready for your development.
Creates from a based URL, clones from that repo, and then initiates the project with the current meteor.
- It will require the end user to have git installed to do a git clone. I guess it falls into our philosophy of being easy to use but I'm not …
=> [Meteor 3 - Feature]: Meteor create uses git instead of vendorized

guide/source/collections.md, guide/source/methods.md
closes https://github.com/meteor/meteor/issues/12689
Open it again because I deleted the meteor repo from my account 😅
This pull request updates the no longer supported regEx built-in expressions from SimpleSchema.
The purpose here is to define a regular expression and link the SimpleSchema doc. that explains why it no longer supports built-in expressions.
=> fix(skell): remove builtin regex expressions from simpleSchema

guide/source/structure.md
hey, just a small update on an outdated link. The current *private npm modules* link points to a 404 page
and I update it to this page:
To be honest I'm not sure if it's the appropriate page or not. I just found the outdated link when reading meteor guide and feels like updating it. So please review
=> Update private npm modules link in structure.md

docs/source/commandline.md
- Improve the description and example of each `meteor create` flag.
- Remove the unreadable table of packages as they are now described in each command.
- Add the `--release` option to the flags.
- Sort options by flag name.
=> Improve CLI / Flags documentation

npm-packages/babel-preset-meteor/babel-presets-meteor/modern.js
Meteor projects depending on Firebase (such as implementations of Push Notifications) do not run in Facebook in-app browser due to an error: "Uncaught TypeError: Y.values is not a function or its return value is not iterable."  Adding FB in-app browser to this default list fixes the issue.
=> Add Facebook in-app browser

packages/accounts-2fa/2fa-server.js, packages/accounts-password/email_tests.js, packages/accounts-password/email_tests_setup.js, packages/accounts-password/password_tests.js, packages/accounts-password/password_tests_setup.js, packages/minimongo/constants.js, packages/mongo/collection.js, packages/mongo/mongo_driver.js, packages/mongo/remote_collection_driver.js
Continuation of https://github.com/meteor/meteor/pull/12786
=> Making mongo errors clearer

packages/npm-mongo/package.js
Bumped MongoDB driver to 4.17.
We should be looking when Meteor v3 is released [to update our driver to the latest version(6.x) ](https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0)
=> bumped mongodb driver

packages/meteor/meteor.d.ts
Fixes the following error:
```
.meteor/local/types/node_modules/package-types/meteor/package/os/packages/meteor/meteor.d.ts:173:20 - error TS2304: Cannot find name 'Result'.
173           result?: Result
~~~~~~
```
=> Fix type declaration for MethodApplyOptions

packages/modern-browsers/modern-tests.js, packages/modern-browsers/modern.js
We noticed that on iPads Meteor serves the legacy bundle (`Meteor.isModern === false`). We determined this is because the user agent is reported as 'Apple Mail' (for example `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)`). This PR adds an alias for this user agent so (modern) iPads also receive the modern bundle.
=> Fix iPad user agent

packages/accounts-base/accounts_server.js, packages/accounts-oauth/oauth_common.js, packages/accounts-password/password_server.js, packages/accounts-passwordless/passwordless_server.js, packages/oauth/pending_credentials.js, packages/service-configuration/service_configuration_server.js
Cherry-pick user index async creations from #12647 
This is to scale down #12647 and get things in faster in more manageable chunks.
=> User index async

packages/accounts-password/password_client.js
Relates to #12300.
This brings createUserAsync to client-side
Maybe this pr should contain all the missing in client-side accounts methods.
We should backport this to 2.x ASAP.
=> [ Meteor 3.0 ] - added createUserAsync in the client

npm-packages/babel-preset-meteor/babel-presets-meteor/package.json, npm-packages/cordova-plugin-meteor-webapp/package.json, npm-packages/eslint-config-meteor/package.json, npm-packages/eslint-plugin-meteor/package.json, npm-packages/meteor-babel/package.json, npm-packages/meteor-installer/package.json, npm-packages/meteor-node-stubs/package.json, npm-packages/meteor-promise/package.json
Future proof NPM packages by adding `"type": "commonjs"` to `package.json`.
See latest Node release notes: https://github.com/nodejs/node/releases/tag/v21.1.0
With that I also suggest publishing `@meteorjs/babel` without the beta tag.
@Grubba27 if you want I can update it in the bundle as well and it to this PR, so then we merge this PR in first, release NPM packages and then we can build the new bundle.
=> Future proof NPM packages

packages/mongo/oplog_v2_converter.js, packages/mongo/oplog_v2_converter_tests.js
Attempts to fix #12855: When setting a Mongo.ObjectID in a document, the ObjectID gets transformed into a plain object in Minimongo, until the page is refreshed / the document is refetched.
Includes the fix and a matching test.
Thanks for any feedback.
=> Don't flatten ObjectIDs in oplogV2V1Converter (fixes #12855)

scripts/dev-bundle-tool-package.js, tools/cli/commands.js
Cloese #12791 
If either or both of application name and skeleton flag is missed in the create command, there will be prompts for choosing them.
=> Feature: interactive meteor create command

packages/modules/.npm/package/npm-shrinkwrap.json, packages/webapp/.npm/package/npm-shrinkwrap.json, tools/isobuild/compiler-plugin.js, tools/isobuild/import-scanner.ts
This PR [fixes](https://github.com/orgs/meteor/projects/10?pane=issue&itemId=41843545).
A missing `await` for `file.reportPendingErrors` was causing an error to be thrown wrongly.
=> [Meteor 3.0] Unhandled Rejection when fails to bundle the app

packages/oauth/pending_credentials.js
Address #12641 by moving remove calls to async. I think they can be just moved to async without any issue, but we'll see what the tests say. There are other DB calls that are not async, so that might still be a problem, but those will probably be a bit more involved and are beyond the scope of this simple PR.
=> OAuth async remove

docs/package-lock.json, docs/source/index.md, guide/_config.yml, guide/source/3.0-migration.md, guide/source/index.md
A proposal to create a 3.0 migration guide page as a placeholder is suggested, which for now, will centralize the main links related to Meteor 3.0. It also adds a warning to the Docs and Guide to inform about Meteor 3.0.
Meteor 2.x warning:
3.0 Placeholder Migration Page
=> New 3.0 migration page placeholder and warnings about Meteor 2.x

tools/cli/commands-packages.js
See below:
```
Newer versions of the following indirect dependencies are available:
* accounts-base 3.0.0-alpha300.18 ([object Promise] is available)
```
This PR fixes this log message.
=> Fixes latestVersion as [object Promise] on package upgrade command

meteor, npm-packages/meteor-babel/package-lock.json, npm-packages/meteor-babel/package.json, packages/babel-compiler/package.js, packages/modules/package.js, packages/package-version-parser/package-version-parser.js, packages/package-version-parser/package.js, scripts/dev-bundle-server-package.js, scripts/dev-bundle-tool-package.js
This comes from: https://security.snyk.io/package/npm/semver
Todo: 
It was already published the `npm meteor/babel`
=> Update semver to 7.5.4

docs/generators/changelog/versions/3.0.md, packages/babel-compiler/babel.js, packages/ecmascript/ecmascript.js, packages/ecmascript/package.js, packages/shell-server/package.js, packages/shell-server/shell-server.js
The babel-compiler package is 86mb. Since it is a runtime dependency of `ecmascript`, a copy of it is included in every app, build plugin, or meteor-tool version that uses `ecmascript`. A few years ago, I found that about half of the 10gb of disk space on my computer in ~/.meteor/packages was just copies of `babel-compiler`, and the multiple copies of it in each release contributed to the slow install times on Windows.
We've been needing to fix it for a while, and it seems Meteor 3 is a good time to do it.
The only reason babel-compiler is a runtime dependency of ecmascript is for `Ecmascript.compileForShell`, used by packages that implement the Meteor shell. This PR moves `compileForShell` to the `babel-compiler` package. This is a breaking change. It should only affect the small number …
=> Move compileForShell from ecmascript to babel-compiler

packages/meteor/asl-helpers.js, packages/meteor/async_helpers.js, packages/meteor/dynamics_nodejs.js, packages/meteor/emitter-promise.js, scripts/admin/check-legacy-syntax/check-syntax.js
Some of the new code in the `meteor` package uses newer syntax that breaks the legacy client and breaks build plugins that want to run in both Meteor 2 and 3.
This PR re-enables the check-syntax script for more of the files in the `meteor` package and fixes the issues it found.
I increased the ecmascript version for server files to es2017 which allows us to use async/await. There are some es2017 features not supported in Node 8, but we currently don't use those features so this still verifies that these core packages can be used in build plugins compatible back to Meteor 1.6.
There are some remaining issues with the `async_helpers.js` file. I fixed enough so it works in build plugins in older Meteor releases, but not enough for it to run in legacy clients.
I tested these changes with …
=> Fix syntax issues with meteor package

packages/ddp-server/livedata_server.js, packages/ddp-server/livedata_server_tests.js
Hello!
Found this issue while seeing metrics on Monti APM with Meteor 3.
When we have an async publication handler, Meteor livedata server is not waiting for the promise resolution(either success/error) to unblock the processMessage handler.
The current behavior is like all publications are being unblocked.
This PR fixes it.
=> Meteor 3.0 - FIX - publication handler is not being waited on

.gitmodules, npm-packages/cordova-plugin-meteor-webapp/package-lock.json, npm-packages/cordova-plugin-meteor-webapp/package.json, packages/webapp/package.js
Report: https://github.com/meteor/meteor/issues/12946
It seems that when we migrated the `cordova-plugin-meteor-webapp` from its [own repository](https://github.com/meteor/cordova-plugin-meteor-webapp/tree/master) to the meteor monorepo, we missed to set up the git submodule included in the other repository.
=> GCDWebServer missing in cordova-plugin-meteor-webapp

tools/cordova/builder.js
Use correct method to check if used key exists or not. This was throwing the warning even when the right keys where being used because `validDevices` is an `array` and not an `object`.
=> Fix `cordova` launch screen warnings on `2.14`

docs/source/api/tracker.md
I was talking to a client and found out this example with the temporary API and not the final one.
=> updates findAsync to fetchAsync on Tracker's docs

tools/static-assets/skel-apollo/package.json, tools/static-assets/skel-apollo/server/apollo.js
NOTE: Related GraphQL packages will require an update as well. These are `apollo` (just needs version bump and Meteor 3 in `versionsFrom`) and `swydo:graphql` requires an update, but looks like it is no longer maintained.
Apollo package PR: https://github.com/meteor/apollo/pull/4
`swydo:graphql` PR: https://github.com/Swydo/meteor-graphql/pull/54
=> [Meteor 3] Apollo skeleton upgrade

packages/accounts-base/accounts_common.js, packages/accounts-base/accounts_server.js, packages/accounts-password/password_tests.js
Set `ambiguousErrorMessages` to true if in production. This increases default security.
=> [Meteor 3] Accounts Ambiguous error messages in production set to true by default

packages/deprecated/appcache/README.md, packages/deprecated/code-prettify/README.md, packages/deprecated/deps/README.md, packages/deprecated/facebook/README.md, packages/deprecated/facts/README.md, packages/deprecated/fastclick/README.md, packages/deprecated/github/README.md, packages/deprecated/google/README.md, packages/deprecated/handlebars/README.md, packages/deprecated/jquery-waypoints/README.md, packages/deprecated/jshint/README.md, packages/deprecated/jsparse/README.md, packages/deprecated/livedata/README.md, packages/deprecated/meetup/README.md, packages/deprecated/meteor-developer/README.md, packages/deprecated/meteor-platform/README.md, packages/deprecated/meyerweb-reset/README.md, packages/deprecated/npm-bcrypt/README.md, packages/deprecated/preserve-inputs/README.md, packages/deprecated/showdown/README.md, packages/deprecated/spiderable/README.md, packages/deprecated/srp/README.md, packages/deprecated/standard-app-packages/README.md, packages/deprecated/startup/README.md, packages/deprecated/stylus/README.md, packages/deprecated/twitter/README.md, packages/deprecated/weibo/README.md
Fixes for: https://forums.meteor.com/t/wrong-repo-links-in-atmosphere/61244?u=storyteller
I think the metadata update should be enough, but not sure.
=> Update readme links on deprecated packages

packages/accounts-base/accounts-base.d.ts, packages/accounts-password/password_server.js, packages/caching-compiler/caching-compiler.js, packages/caching-compiler/multi-file-caching-compiler.js, packages/email/.npm/package/npm-shrinkwrap.json, packages/oauth1/oauth1_binding.js, tools/isobuild/bundler.js, tools/isobuild/compiler-plugin.js
Removing methods that use Promise.await to be sync. These won't work on version 3.
- `_checkPassword`: Now `_checkPasswordAsync`
- `setPassword`: Now `setPasswordAsync`
- `OAuth1Binding.call`: Now `OAuth1Binding.callAsync`
- `Assets.getText`: Now `Assets.getTextAsync`
- `Assets.getBinary`: Now `Assets.getBinaryAsync`
=> [Meteor 3] Removing broken methods in version 3

tools/cli/commands-packages.js, tools/tests/update-tests.js
Fixes [this](https://github.com/meteor/meteor/discussions/12865#:~:text=Fix%20springboarding%20and%20warehouse).
Springboarding was already moved to async. Just rechecked tests and fixed what was needed.
=> [Meteor 3] - Fix springboarding 

tools/isobuild/linker.js
Fixes [this](https://github.com/meteor/meteor/discussions/12865#:~:text=test%20to%20fail.-,Fix%20Linker%20bug,-In%20this%20commit). 
There was an issue where we had a file linked twice. Previously we created a [workaround](https://github.com/meteor/meteor/pull/12580/commits/eb63a1b6643805590d3bf70ff9611e837aede1e9#diff-0972e87d5bf49b0ff289a29dee4ae83bb04b83d2e057976f7a7680e0e1ee2e0aR170-R177). This PR removes that workaround and fixes the issue.
=> [Meteor 3] Fix linker bug

packages/minifier-js/.npm/package/npm-shrinkwrap.json, packages/npm-mongo/.npm/package/npm-shrinkwrap.json, packages/webapp/.npm/package/npm-shrinkwrap.json, tools/static-assets/skel-chakra-ui/.meteor/packages, tools/static-assets/skel-react/.meteor/packages, tools/static-assets/skel-tailwind/.meteor/packages, tools/static-assets/skel-typescript/.meteor/packages
We had to pin this version because, as react-meteor-data is not a core package, it'll always get the latest version (v2 right now) when creating a new app. Otherwise, we need to do things like [this](https://dev.to/meteor/meteor-v3-uses-express-under-the-hood-how-to-use-and-deploy-it-5c2n#:~:text=beta%2Dapp.-,Temporary%20issue,-Before%20starting%20our).
We also [created a task](https://github.com/meteor/meteor/discussions/12865#:~:text=Remove%20%403.0.0%2Dbeta300.1,a%20new%20app) to remove this once we have an official version.
=> [Meteor 3] Pin react-meteor-data for v3 skels

packages/minimongo/cursor.js, v3-docs/docs/api/collections.md
`observeChangesAsync` and `observeAsync` are new recommendations on docs for Meteor 3.x, while sync version remain useful to handle easily on some clients.
=> Docs: observeChangesAsync and observeAsync

packages/ddp-client/client/queueStubsHelpers.js, packages/ddp-client/test/async_stubs/client.js, packages/ddp-client/test/async_stubs/server_setup.js, packages/ddp-client/test/livedata_tests.js
OSS-352
Context: https://github.com/meteor/meteor/pull/13054#discussion_r1514578297
Describe the next methods in the server.
``` javascript
let events = [];
Meteor.methods({
async 'unblockedMethod'({ delay }) {
events.push('unblock start');
this.unblock();
await Meteor._sleepForMs(delay);
events.push('unblock end');
},
'blockingMethod'() {
events.push('blockingMethod');
},
});
```
Run on the client:
``` javascript
Meteor.callAsync("unblockedMethod", { delay: 200 }); // unblock + sleep for 20 milliseconds
Meteor.callAsync("blockingMethod"); // run straight + block
// assert 1: `events` should have `["unblock start", "blockingMethod"]` at this point as two methods are executed in parallel and the first one is unblocked. 
// assert 2: `events` should have added `["unblock end"]` at some …
```
=> Fix an issue with methods interacting with unblocking mechanisms

docs/generators/changelog/versions/3.0.md, packages/ddp-client/client/queueStubsHelpers.js, packages/meteor/debug.js
OSS-347
This PR spreads the debug mode used on the server via `--inspect*`/`-brk` to the client. Therefore you can ignore certain code execution on the client in a normal execution (`meteor run`), like ignoring log messages.
Specifically, we have introduced the following variables to handle debug-only flows in Meteor code or your app code:
- `__meteor_runtime_config__.debug`
- `Meteor.isDebug`
Besides, and as a practical example, we have ignored in normal app execution the `Method stub took too long` warning message.
=> [3.0] Debug mode

packages/mongo/mongo_driver.js, packages/mongo/oplog_tailing.js, packages/mongo/package.js
Oplog has its specific startup, but it was missing a condition for `minPoolSize` which made it impossible to set `minPoolSize` for normal connection as setting it in the `mongo` settings would set it as well for oplog connection which would result in error as `maxPoolSize` for oplog is `1`. So setting `minPoolSize` to 30 would result in failed startup on Galaxy when the oplog was started as `minPoolSize` for oplog could not be more than `maxPoolSize` (which is 1). So by setting `minPoolSize` for oplog to 1 and adding a copy of if function in startup for oplog connection for `minPoolSize` as well should avoid that error.
I think this should be released asap as a bug fix as Atlas has recommended me to work on the connection pool sizes in my connection, so more people are likely to work on …
=> Set minPoolSize for oplog

packages/minimongo/local_collection.js, packages/minimongo/minimongo_tests_client.js
Issue:
During the migration to Meteor 3 , for some reason, our UI was not working anymore.
Collections were returning empty arrays for some reason. After changing `upsert` to `upsertAsync`, everything seemed to start working as expected again.
I reviewed the documentation, and it explicitly states that Minimongo will continue to provide synchronous functions. Investigating the code, I realized that both functions are practically identical, except for the part that deals with the case where no record has been modified, where it is assumed that an insertion should be performed. Adding this code to the application made it return to normal, and it now honors what is written in the documentation.
=> fix(minimongo): sync upsert doesn't create new documents

guide/source/3.0-migration.md, npm-packages/meteor-installer/cli.js, npm-packages/meteor-installer/install.js, npm-packages/meteor-installer/package-lock.json, npm-packages/meteor-installer/package.json, v3-docs/docs/about/install.md
OSS-357
More details in this [comment](https://github.com/meteor/meteor/pull/13059#issuecomment-2007063599)
Two commands are now operational:
`npx meteor@alpha install`/`npx meteor@alpha uninstall`: New recommended method that provides full output during Meteor installation or uninstallation. Installation simplified with `npx meteor@alpha`/`npx meteor`.
`npm install -g meteor`: Installs Meteor silently unless --foreground-scripts is specified.
There are several issues on various environments reported by devs when you execute `npm i -g meteor@beta`.
So this PR is about to review each OS environment and check that the installation command is still working fine. Try also to reproduct the reported issues and fix them.
My main suspicion is when using a new node version (`20.x`) for the …
=> [3.0] Fix Meteor installer

packages/mongo/mongo_driver.js, packages/mongo/oplog_tailing.js, packages/mongo/package.js
This PR aims to add test cases to track the behaviors around data persistence resulted on run collection operations in 2.x to help to understand and match 3.x later.
These tests will be added in this https://github.com/meteor/meteor/pull/13052 3.x branch to also ensure the same exact API is perserved on the next version.
As mentioned on 3.x PR, data is temporary persisted when using collection operations, and the only way to persist them is through using local collection operations (or publications which actually use these). As part of this PR I also added aync versions of local collection operations, since these are enabled in 3.x and facilitates the same test form for the two versions, and allow any migration in 2.x.
=> [2.x] Report and extend test cases for the old async behaviors

tools/static-assets/skel-svelte/tsconfig.json
Add `exclude` rule `"!./.meteor/local/types"`. Prior to this, intellisense for my package's types wasn't working.
From `zodern:types`:
"If your tsconfig has exclude configured, make sure the exclude rules do not exclude `.meteor/local/types`"
=> Update tsconfig.json for svelte skeleton

packages/test-in-console/puppeteerRunner.js, packages/tinytest/tinytest.js
In this PR, I address the issue of the Travis CI not being so good to read when tests are running(currently only shows a `testNumber` variable). This PR will solve that(kind of). 
We will add the current test that is running if we do not have that in the context, we will still print the `testNumber` variable, but  for the most part, our ci will start to look like this:
If it ever gets stuck somewhere, we will know it
=> [Meteor 3.0] Making our CI more easy to understand

packages/ddp-server/livedata_server_tests.js
OSS-383
[These last changes on tinytest](https://github.com/meteor/meteor/pull/13079) to output test names have introduced a failure on an existing test.
The issue is that a test that we expect `Meteor.onMessage` callback to retrieve the DDP message of one method we run as part of the test. But as the new tinytest setup to get current test name on the output adds and runs a new Meteor method, the test won't be get the first DDP message from the method run. I changed the test to actually check properly that we get the proper DDP message at some point to fix the test,
=> [2.x] Fix tests after tinytest setup improvement

.github/workflows/npm-meteor-promise.yml, npm-packages/meteor-promise/promise_server.js
OSS-384
Release 3.0 has still a pending [check suddently failing.](https://github.com/meteor/meteor/assets/2581993/d2bacf6a-5bdd-4fca-8fc2-7badefd89661)
Changing only `meteor-promise` package triggers the GitHub action check. Other PRs from `release-3.0` don't trigger this check. However, the check relies on fibers, expecting node version 14.x, not 20.x, as updated [here](https://github.com/meteor/meteor/pull/12925). Yet, the node upgrade PR didn't trigger the `meteor-promise` check to confirm the node upgrade keeps the check green.
Use node 14.x as part of meteor-promise check.
=> [3.x] Fix checks

packages/meteor/dynamics_nodejs.js, packages/meteor/dynamics_test.js
Context: https://forums.meteor.com/t/meteor-3-0-beta-7-is-out/61417/27
Following https://github.com/meteor/meteor/pull/13063, we encountered an issue where `audit-argument-checks` didn't validate correctly. This problem remained hidden until the inclusion of the `matb33:collection-hooks` package, which brought it to light through the error message: `Error: Did not check() all arguments during publisher`.
The code snippet for reproduction is as follows:
``` javascript
if (Meteor.isServer) {
Meteor.publish('namedPub', function (testValue, testStr) {
check(arguments, [Match.Any])
console.log('testStr', testStr);
return [];
});
}
if (Meteor.isClient) {
Meteor.subscribe('namedPub', 1, 'test');
}
```
Ensure proper validation of nullish values when preparing the context on …
=> Fix issue with `audit-argument-checks` after changes on env contexts

docs/source/api/accounts.md, packages/accounts-base/client_main.js, packages/accounts-base/server_main.js
**Description**
Currently, the _accounts-base_ package begins before your own project does it. If you want to use a custom configuration, you must wait for the package to start and then pass the configuration you need. This can cause problems when, for example, you want to use a different DDP connection, such as login attempts to the wrong server on the first login attempt.
At this time, the _accounts-base_ package is ready to receive different configuration parameters, however, you will have to wait for the package to start, and then, when your application starts, you can change the configuration.
To solve this problem, I modified the _accounts-base_ **client_main.js** file to allow custom configuration when initializing **AccountsClient**. In my version, the **AccountsClient** …
=> Get default options from meteor settings

docs/source/api/collections.md, packages/mongo/collection_tests.js, packages/mongo/mongo_driver.js, packages/mongo/oplog_tailing.js, packages/mongo/oplog_tests.js, packages/mongo/package.js
Hello all,
Following several conversations on the drawbacks of Meteor's oplog implementation and its limitations when it comes to scaling (see: [my forums post](https://forums.meteor.com/t/cpu-spikes-due-to-oplog-updates-without-subscriptions/60028), [a slightly older blog post](https://blog.meteor.com/tuning-meteor-mongo-livedata-for-scalability-13fe9deb8908) and a [2 year old github discussion](https://github.com/meteor/meteor/discussions/11842)), I investigated in the core a bit and propose an easy solution which, I hope, should work for many users who have issues with this.
Please consider our situation at Orderlion: We have several collections, where huge amounts of data are being updated on a daily basis. On all of these collections we have not a single publication, for these we …
=> New mongo package options to optimize Oplog tailing performance to include/exclude certain collections

tools/cordova/run-targets.js
OSS-391
----
Critical issues on Cordova experience on Meteor 3.x.
Two issues reported and described on Meteor Discord, https://discord.com/channels/679410334292901888/1225337436784037919
Published on forums as well.
https://forums.meteor.com/t/meteor-3-typeerror-cannot-read-properties-of-undefined-reading-format/61390
=> [3.x] Fix Cordova

packages/mongo/collection.js
I just found what I think is a small typo in the documentation of `Mongo.ObjectID`. Just a missing word.
This PR adds that missing word :)
=> Fix small typo in Mongo.ObjectID documentation

packages/core-runtime/load-js-image.js, tools/isobuild/compiler-plugin.js
As recommended in https://github.com/meteor/meteor/pull/13095#discussion_r1571327249, I added additional check in `waitUntilAllLoaded` in case it gets called while the last module is still being loaded. I was not able to prepare a test for that (the queue is never empty in my tests), I didn't add any.
=> [Meteor 3] Added `waitUntilAllLoaded` safety check.

packages/minifier-js/package.js
We spent 3 hours to find that the terser version used in Meteor (5.14.2) has a bug that make minifying React generates a bug in "finally" part.
Upgrading to the latest version 5.31.0 of terser fix the problem.
We cloned the minify-js package locally so it's ok for us but please include this bump version in rc3
Here is the only diff (version bump)
https://github.com/acemtp/meteor/commit/63630ef40d52eaf69806e16d110d39cd4e6d784c
=> update to the latest version of terser

packages/facebook-oauth/facebook-oauth_tests.js, packages/facebook-oauth/facebook_server.js, packages/facebook-oauth/package.js, packages/github-oauth/github-oauth_tests.js, packages/github-oauth/github_server.js, packages/github-oauth/package.js, packages/google-oauth/google-oauth_tests.js, packages/google-oauth/google_server.js, packages/google-oauth/package.js, packages/meetup-oauth/meetup-oauth_tests.js, packages/meetup-oauth/meetup_server.js, packages/meetup-oauth/package.js, packages/meteor-developer-oauth/meteor-developer-oauth_tests.js, packages/meteor-developer-oauth/package.js, packages/mongo/mongo_livedata_tests.js, packages/oauth/oauth_server.js, packages/test-helpers/async_multi.js, packages/test-helpers/mock.js, packages/test-helpers/package.js, packages/test-helpers/wait.js, packages/weibo-oauth/package.js, packages/weibo-oauth/weibo-oauth_tests.js, packages/weibo-oauth/weibo_server.js
OSS-411
Context: https://forums.meteor.com/t/meteor-3-0-rc-0-is-out/61515/28
In some parts of the code, `findOne` is still being utilized sync on Meteor 3.x, resulting in errors asking for migration, such as: `Error: findOne + is not available on the server. Please use findOneAsync() instead`.
Review all occurrences of `findOne` and other operations needing asynchronous migration on Meteor 3.x packages. Additionally, I'll supply a few regression tests to ensure coverage of the affected flow, enabling us to detect any missing adaptions in the future through test failures.
The regression test triggering properly the requirement of this migration as showed in the next example:
I've added two new test helpers:
- `mockBehaviours`: This acts as a mock to halt the run on an entire module. Useful …
=> [3.x] Fix async OP behaviors on server (oauth packages)

packages/test-helpers/wait.js, tools/cli/commands.js
OSS-409
Context: https://github.com/meteor/meteor/issues/13106
Several developers reported issues with failures when using Meteor create. I followed further research into the issue.
Initially, I thought it was caused by the new machinery [introduced in this PR](https://github.com/meteor/meteor/pull/12697) to prepare the template projects fetching from github using `git clone` command.
The reported errors, such as "Will use cached version of skeletons" and "Something has happened while creating your app using git clone", [correspond to a specific part of the code](https://github.com/meteor/meteor/blob/release-3.0/tools/cli/commands.js#L1134-L1156).. However, it turns out that these errors occur consistently when the --release option is used, with the message "Error message: Using release …
=> [3.x] Fix error log create cmd

packages/oauth/oauth_server.js, packages/reload-safetybelt/reload-safety-belt-tests.js, packages/reload-safetybelt/reload-safety-belt.js, tools/static-assets/server/boot.js, tools/tests/apps/compiler-plugin-add-asset/use-asset.js, tools/tests/apps/compiler-plugin-asset-and-source/packages/asset-and-source/asset-and-source.js, tools/tests/apps/unicode-asset-app/index.js
In the [docs](https://v3-docs.meteor.com/api/assets.html#assets) we mentioned that now, `getText` is called `getTextAsync`, and `getBinary` is `getBinaryAsync`.
But that was true only for the [build plugin assets methods](https://github.com/meteor/meteor/blob/31d1f28eef82720c3649bc1bab3b7cb8f2e58090/tools/isobuild/bundler.js#L2245-L2258). The ones in for the app files were not updated.
This PR now creates these methods to be concise with the docs as well.
This issue was reported in our [Forums](https://forums.meteor.com/t/assets-gettextasync-is-not-a-function/61622).
=> Fix assets method names

packages/github-oauth/github_server.js, packages/google-oauth/google_server.js
This PR fixes the invocation of the OAuth._fetch() method on the `github_server` and `google_server` of their oauth.
This fix is explained in more details on the Additional Notes of the Issue #13152.
I've set the base of the Pull Request as `release-3.0` since the `devel` branch seems to not be fully updated with the code on `release-3.0` (on the `devel` branch, this implementation was still using Fetch API and `findOne` invocations.)
=> fix: oauth_.fetch invocation on github_server and google_server

.gitmodules, packages/allow-deny/allow-deny.js, packages/mongo/allow_tests.js, packages/mongo/collection.js, packages/static-html/package.js
This PR reviews the allow-deny package to make it async-compliant.
Two issues have been reported by the community. Feel free to report any other issues in the comments for the next RC.
Context: https://github.com/meteor/meteor/issues/13143
Client-side collection operations trigger server failures. The server uses the `_validate<OP>` sync method, causing the error `Error: findOne + is not available on the server. Please use findOneAsync() instead`.
We now enforce async validation with proper test coverage.
Context: https://forums.meteor.com/t/meteor-3-0-rc-1-is-out/61580/9
Async definitions on allow/deny rules don't work.
=> [3.0] AllowDeny async compatibility

packages/webapp/webapp_server.js, packages/webapp/webapp_tests.js
This issue was reported and reproduced https://github.com/meteor/meteor/issues/13101 and https://github.com/meteor/meteor/issues/12939.
The provided fix is to make `WebApp.addRuntimeConfigHook` async compatible.
The callbacks provided to this function [describe hooks](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L357) and [these wraps async by default](https://github.com/meteor/meteor/blob/devel/packages/callback-hook/hook.js#L82). This is a behavior we must to keep to offer flexibility on use configurable async flows.
I served from [this doc](https://v3-docs.meteor.com/packages/webapp.html#dynamic-runtime-configuration) to understand how to use  `addRuntimeConfigHook` and provide the missing test scenario.
=> Fix WebApp.addRuntimeConfigHook

guide/source/3.0-migration.md, tools/cli/commands.js, tools/cli/help.txt, tools/fs/files.ts, tools/tests/mongo.js, tools/tests/reset.js, tools/tool-testing/sandbox.js, v3-docs/docs/cli/index.md, v3-docs/v3-migration-docs/breaking-changes/index.md, v3-docs/v3-migration-docs/index.md
Context: https://forums.meteor.com/t/post-your-tips-for-updating-to-meteor-v3/61625/16 and https://github.com/meteor/meteor/issues/7789
There are two ways to implement this to ensure by default the db is not removed.
1) Fetch beforehand all the folders and files within `~/.meteor/local` and trigger a promise in parallel per subfolder that is not the `~/.meteor/local/db` path
2) Upgrade `rimraf` to latest as they offer a way to filter the files to remove within a specific folder, and use it directly. The [dev_bundle is stuck into an old version](https://github.com/meteor/meteor/blob/devel/scripts/dev-bundle-tool-package.js#L52) of `rimraf@2.6.2` that [doesn't support a way to filter](https://github.com/isaacs/rimraf/tree/79b933fb362b2c51bedfa448be848e1d7ed32d7e).
I decided to go with 1), …
=> Implement reset db option and default without cleaning db

docs/source/api/passwords.md, packages/accounts-password/password_server.js, packages/accounts-password/password_tests.js, v3-docs/docs/api/accounts.md, v3-docs/v3-migration-docs/api/renamed-functions.md
We already did this for version 2 https://github.com/meteor/meteor/pull/13164, but for version 3, even though `Accounts.addEmail` is async now, we still didn't have added the `Async` suffix to it. So, in this PR, we:
- rename `Accounts.addEmail` to `Accounts.addEmailAsync`.
- updated the Migration Guide and Docs about this change.
=> [Meteor 3] Add Accounts.addEmailAsync alias

tools/cli/commands.js
For some reason, we had [this](https://github.com/meteor/meteor/pull/13217/files#diff-a65d7a89d948df5e2e7122e62391d58d20521d447c7ebbf2c4f22faf0d12f048L947-L978) code [duplicated](https://github.com/meteor/meteor/blob/3c3a1345aa67db06503f782819cefc2fb824b910/tools/cli/commands.js#L1132-L1170). And what it does is copy the skeleton folder to the user's machine. The problem was that we were doing this before the `git clone` [command](https://github.com/meteor/meteor/blob/3c3a1345aa67db06503f782819cefc2fb824b910/tools/cli/commands.js#L1062) ran, thus the error:
Now:
I've also added the env `GIT_TERMINAL_PROMPT=0` to avoid getting stuck in the clone command while waiting for credentials.
=> [Meteor 3] Fix git clone error when running `meteor create`

tools/cli/commands.js
Context: https://github.com/meteor/meteor/issues/12932
Refer to this comment for extra information about this problem: https://github.com/meteor/meteor/issues/12932#issuecomment-2214665318
After the meteor build process [ensure the `npm-shrinkwrap.json` file has the proper write permission](https://github.com/meteor/meteor/assets/2581993/0d1883a9-a24b-47ee-9d03-a7857af75305), so that the server app can be installed properly later on.
=> OSS-462 Tweak npm-shrinkwrap.json permissions on newer npm versions to proper app server bundle setup

tools/cli/commands.js
On my testing with the RC previous to the official version, I was able to run into the issue tweaked here, https://github.com/meteor/meteor/pull/13217.
When an error cloning actually happens the meteor process crashes. This happened consistently on my Windows machine. But I believe the error happens all time a git clone error happens, which in common env may not be easy to reproduce.
=> Fix crashing on clone example error flow

tools/cli/commands.js
This PR is a continuation of https://github.com/meteor/meteor/pull/13217 and https://github.com/meteor/meteor/pull/13227.
- 	In Windows could have been by using `$env:GIT_TERMINAL_PROMPT=0;
git clone --progress "..." "..."` and then ```exec(`powershell.exe -Command "${command.replace(/\n/g, '; ')}"`)```, but I decided to make it simpler with `process.env`
=> Review and fix git clone meteor examples issues

packages/underscore-tests/common_test.js, packages/underscore-tests/package.js, packages/underscore/package.js, packages/underscore/underscore.js
Context: https://github.com/meteor/meteor/issues/13049
This PR reviews the recent underscore functionality changes that result in breaking changes. I also added tests for the updated helpers [in this PR](https://github.com/meteor/meteor/pull/12912) to identify any failures. In the future, we should expand this test coverage if we modify or add any helpers.
I will publish meteor/underscore 1.6.2 as soon as these changes are approved and spread to 3.0.
=> Fix underscore functionality changed recently and provide tests
